### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by ehneilson** [mzmine/mzmine2#119]
Two small and hopefully easy requests: 
1. I would like to normalise my data to an individual tissue weight for each sample. 
2. I have many smaller ions (less than m/z 200) with a high intensity. I suspect that some of my larger compounds are being fragmented as they come off the source, and what I am seeing are daughter ions. The parent ions, or at least many of my larger compounds (larger than m/z 500) do not have a high intensity. As such, it is very difficult for me to set my noise limit. It is possible to set a m/z size filter, similar to the RT one you have in raw data methods -> peak detection -> mass detection -> set filters? In this way, I would be able to analyse my data in two sets ie less/greater than m/z 200

**Comment by chrisbarlow79** [comment]
Hi ehneilson,
With respect to your second point I think you might just be looking for:
Raw Data > Filtering > Crop filter
You can then set the m/z range you require.

Cheers,

Chris

**Comment by tomas-pluskal** [comment]
Hi ehneilson,

Honestly, we don't have the capacity to work on features that people request. Feel free to ask/hire a software developer to implement the feature you want, and we will be happy to include it in MZmine. 
As for your request 2, as Chris already suggested, you can use the crop filter.

Cheers,

Tomas
