### ISSUE TITLE
NIST MS Search problem

### ISSUE THREAD

**Issue by chrisbarlow79** [mzmine/mzmine2#120]
Hi,
I'm trying to use Mz Mine 2.16 to process some data from a DDA type experiment.  I'm trying to use the NIST MS Search option to compare my MS/MS spectra against the Lipid Blast library.  Unfortunately I'm finding that when I use the NIST MS Search option MzMine 2.16 is not passing the MS/MS spectra to NIST but rather is passing a spectra which typically only contains the parent ion.  I'm unsure if this is a bug in MzMine or if I've failed to understand the intended function of this feature.

Many thanks for your great work on MzMine and consideration of my problem.

Cheers,

Chris

**Comment by tomas-pluskal** [comment]
Hi Chris,

The functionality of the NIST search module is quite well described in the help file :)
I agree having MS/MS search option would be useful. Feel free to contribute.

Cheers,

Tomas

**Comment by chrisbarlow79** [comment]
Hi Tomas,
Thanks for your reply.  Sorry, I was expecting this to export MS/MS spectra and so got a bit confused reading the help file.

Cheers,

Chris
