### ISSUE TITLE
Peak Integration

### ISSUE THREAD

**Issue by JanElschen** [mzmine/mzmine2#122]
Dear Developers, 

I have encountered a problem with the integration of peaks in MZmine 2.15. 
After the steps “peak extending” and “duplicate filtering” I receive a list of peaks. The subject of my concern is a peak which baseline shows a drift so the automated integration calculates too much area. I know I can solve this by increasing the peak height level. This would be my last option as I would like to keep my peak height low so I can analyze small peaks just above noise level. 
I would like to know if there is a tool for setting some kind of retention time window in which the integration will happen or if I can integrate the peak manually (if yes, how is it done). 

Please give me some advice. Thank you very much. 

Best regards, 
Jan

**Comment by tomas-pluskal** [comment]
Hi Jan,

You can integrate the peaks manually by opening the peak list (table view), right mouse click on a row, select "Manually define peak".

If you need further assistance, please provide more details about your workflow (see the How to report problems section of the manual).

Tomas
