### ISSUE TITLE
MZmine viral infection

### ISSUE THREAD

**Issue by benlh** [mzmine/mzmine2#129]
Hi,

I am really disappointed about MZmine 2 because it appears that the software is infected by a virus.
Indeed, I downloaded the last version of MZmine 2.17 last Friday and install it as usual as the previous versions (2.9.1 and 2.12). The soft worked well by itself but in the beginning of this week, the informatics team of my enterprise found a viral attack on our network with irreversible damages. After time-consuming analyses performed by our network team, MZmine 2.17 has been identified as the source for the attack and anti-virus analysis confirmed the infection of MZMine 2.17 downloaded archive by “Gen:Varian.Kazy.739801” virus. For information the archive was downloaded directly on your website (http://mzmine.github.io/).

Firstly, you should immediately disable the download of the file from your website until the problem is checked and solved.

Secondly, you have to give us explanations on how that it could happen. We are entitled to have answers and you have to check your source codes and files to stem the problem. As mentioned, due to the attack we suffered irreversible damages, lost important data and among all a lot of time. 

For information, as a member of the French metabolomics network, I will broadcast the information that Mzmine 2.17 is a threat for my French colleague and will also spread the information on the net in order to protect all the users.

I look forward to hearing from you as soon as possible.

Yours faithfully,

**Comment by tomas-pluskal** [comment]
Hi,

First of all, please stop threatening and let's take a look at the issue together.

I take your report seriously, but I have some doubt about its factual accuracy. MZmine is a Java application that is distributed as a ZIP archive and does not contain any Windows executables apart from the small Thermo and Waters converters. It is unlikely that Java application can carry such virus. I quickly searched the MZmine 2.17 ZIP archive that is published on GitHub and did not find any sign of a virus.

Please talk to your network team, and let me know the following information:
- which file in the MZmine archive (specifically) is infected by your virus?
- how exactly did you identify that MZmine is a source of the virus?

Thanks a lot,

Tomas

**Comment by benlh** [comment]
Hi Tomas,

 

Thank you for you quick reply.

 

I am really interested in understand what happened and working together in order to solve the issue.

 

Concerning the viral infection, my network team found the source of the attack in the “WatersRawDump.exe” file created MZmine 2.17 archive was uncompressed a few days ago.

 

Several points where checked to validate this diagnosis. First, the threat was detect using Endpoint Security by BitDefender on my computer as mentioned. Then, we scanned the downloaded uncompressed file and BitdeFender found the virus in the archive et finally, today we re-downloaded the MZmine 2.17 archive from your website (http://mzmine.github.io/download.html) and re-analyzed it with BitDefender which confirmed the detection and archive infection for “Gen:Variant.Kazy.739801” virus.

 

I hope it helps in order to solve the problem.

 

Regards,

 

Benoit

De : Tomáš Pluskal [mailto:notifications@github.com] 
Envoyé : mercredi 14 octobre 2015 15:23
À : mzmine/mzmine2
Cc : benlh
Objet : Re: [mzmine2] MZmine viral infection (#129)

 

Hi,

First of all, please stop threatening and let's take a look at the issue together.

I take your report seriously, but I have some doubt about its factual accuracy. MZmine is a Java application that is distributed as a ZIP archive and does not contain any Windows executables apart from the small Thermo and Waters converters. It is unlikely that Java application can carry such virus. I quickly searched the MZmine 2.17 ZIP archive that is published on GitHub and did not find any sign of a virus.

Please talk to your network team, and let me know the following information:

*	which file in the MZmine archive (specifically) is infected by your virus?
*	how exactly did you identify that MZmine is a source of the virus?

Thanks a lot,

Tomas

**Comment by tomas-pluskal** [comment]
Thomas @dyrlund, can you take a look at this issue? I built the last version of the Waters reader (WatersRawDump.exe) on your (Steno's) workstation when I was visiting your lab.

**Comment by dyrlund** [comment]
I did a virus scan on the **MZmine-2.17.zip** file and the **WatersRawDump.exe** using **McAfee VirusScan Enterprise+ v. 8.8** with DAT version 7952.0000 (12-10-2015) and I don't find any viruses.

![virus](https://cloud.githubusercontent.com/assets/10582167/10485857/99665b50-728c-11e5-9495-cb6f53d72c13.png)

**Comment by tomas-pluskal** [comment]
Thomas, can you check the BitDefender software on WatersRawDump.exe? Unfortunately, I don't have any Windows machine around at the moment.

**Comment by benlh** [comment]
I am redownloading the archive and will re-perform BitDefender analysis.

**Comment by benlh** [comment]
![mzminescan](https://cloud.githubusercontent.com/assets/15122908/10486213/31f8cd5c-728e-11e5-9831-53024cce259a.jpg)

**Comment by benlh** [comment]
My network team manager will give me soon the first anti-virus analysis report that found the threat with all the details. I will publish it on this thread as soon as possible wishing it will help.

**Comment by dyrlund** [comment]
On my system, **BitDefender AntiVirus Plus 2016** (20.0.19.1099 with engine v. 7.62880) also detects the mentioned thread in **WatersRawDump.exe**.

However, testing the file on [virustotal.com](https://www.virustotal.com/en/file/50b35c9fbf1b1b7b3035957970ec6f7b75b3ba68d196d3d15e05190a42c59835/analysis/1444833410/) shows that only 2 out of 56 AntiVirus software report the file as a thread. I have contacted BitDefender to clarify if this is a false positive detection by their software.

**Please note, you can safely delete the WatersRawDump.exe from the MZmine folder and still use the software. The file is only needed to load RAW Waters data into MZmine.**

![bitdefender](https://cloud.githubusercontent.com/assets/10582167/10486682/59837848-7290-11e5-9635-f5eb470ea20d.png)

**Comment by dyrlund** [comment]
Here is the reply I recieved from BitDefender:


Dear Thomas, 

Thank you for the data provided. We have sent it to our laboratories for specialized analysis. If a false positive is found, detection will be removed in the next 72 business hours. Should you need further assistance in the future, please do not hesitate to contact us.

Thank you,
Bitdefender Customer Care Team

**Comment by benlh** [comment]
Thank you for these last informations and your reactivity.

For our point of view the problem in my lab is that, as previously mentioned, we underwent an attack and lost a lot of important files. Maybe these two facts are not linked but for now the only viral infection we detected is the one we are talking about.

I hope we will have further informations to clarify the situation.

**Comment by tomas-pluskal** [comment]
Benoit, 
to rule out the possibility of a false alarm, do you have any additional evidence that your computer was infected by the Gen.Variant.Kazy virus?
For example, according to this website http://www.enigmasoftware.com/genvariantkazy-removal the virus creates a number of files:

1	%Program Files%\Gen.Variant.Kazy\Gen.Variant.Kazy.exe
2	%UserProfile%\Desktop\Gen.Variant.Kazy.lnk
3	%UserProfile%\Start Menu\Gen.Variant.Kazy\Registration.lnk
4	%UserProfile%\Application Data\Microsoft\Internet Explorer\Quick Launch\Gen.Variant.Kazy.lnk
5	%UserProfile%\Start Menu\Gen.Variant.Kazy\Help.lnk
6	%UserProfile%\Start Menu\Gen.Variant.Kazy\Gen.Variant.Kazy.lnk

Do you see such files in your computer?

**Comment by benlh** [comment]
I have to ask my network team to check this.

Otherwise, here is the original report concerning the first detection of the virus:
"Nom du code malveillant,Type de menace,Nettoyé,Ignoré,Quarantaine,Supprimé,Bloqué,Dernière détection,Nom de l'endpoint,Nom de l'entreprise
Gen:Variant.Kazy.739801,"virus","0","0","0","1","0","14 Oct 2015 12:04:45","BLOUP-HP","LCH"

Gen:Variant.Kazy.739801,"C:\Users\bloup\Downloads\MZmine-2.17.zip=>MZmine-2.17/lib/vendor_lib/waters/WatersRawDump.exe","BLOUP-HP","Résolu(s)","14 Oct 2015 12:04:45","1","LCH"
"

**Comment by DrewG** [comment]
In case a crowd-sourced anti-virus scan could be useful here, I have scanned my instance of 2.17 on my windows laptop with Microsoft Windows Essentials and MalwareBytes Anti-Malware (both up to date) and found no issues.

**Comment by tomas-pluskal** [comment]
Thanks, Drew!

**Comment by DrewG** [comment]
Just wondering, but is WatersRawDump compiled with an Embarcadero compiler ?  Written in Delphi ?  It's unfortunate but this happens from time to time in Delphi executables.

**Comment by tomas-pluskal** [comment]
WatersRawDump was compiled using Microsoft Visual C++. The C++ source code is included with MZmine distribution in lib/vendor_lib/waters/WatersRawDump.cpp

**Comment by dyrlund** [comment]
Bitdefender has now confirmed that the file is clean and they have corrected so that it is no longer detected by Bitdefender. I have also confirmed that the  MZmine-2.17.zip file and the WatersRawDump.exe does not report a thread in Bitdefender engine v. 7.62922.

![bitdefender](https://cloud.githubusercontent.com/assets/10582167/10542589/7fbaa240-7419-11e5-83dc-6f047ac24d4f.png)

**Comment by tomas-pluskal** [comment]
Thanks a lot Thomas!!
I am now closing this issue as it was a false alarm.

**Comment by benlh** [comment]
Thanks to all for your help and I am glad that MZmine is clearly harmless.
