### ISSUE TITLE
How to extract XIC areas in batch mode

### ISSUE THREAD

**Issue by aserramaq** [mzmine/mzmine2#130]
Dear MZmine team,

I'm new using MZmine and I think I will need your help. I need to extract XIC areas for multiple peptides if possible setting the ppms. The file that I need to analyze is a raw file from a Thermo instrument. Just now I'm trying with other raw files because the file I have to analyze is around 5gb and it takes very long to be loaded. 

I have the list of peptides from mascot database search, my idea is create a peptide list (but I don't know also which format in should have that peptide list) and my idea is doing it in batch. But I don't know which steps I should include in the batch and which parameters I should set to get the XIC areas because I cannot find that option in the batch mode wizard. I've tried to do it in a batch mode using Targeted peak detection but after many failed trials I think that's is not the way. Manually I get XIC areas just loading the raw file and by the Visualization\TIC/XIC visualizer , going to the TIC\XIC visualizer and using the m/z from mascot results. 

FYI, I'm using MZmine2 in a windows system 32 bits.

Thank you in advance!!!

aida

**Comment by tomas-pluskal** [comment]
Hi Aida,

Try using the targeted detection module. That will generate a peak list that you can export to CSV file including the peak areas.

Tomas

**Comment by aserramaq** [comment]
Hi Tomas, I just edited my message to include that I was trying the Targeted detection in batch mode. But it give me errors. Do I should just load the raw file and do the targeted detection? or I should include other steps?

Thanks!

**Comment by tomas-pluskal** [comment]
"it give me errors" is not very useful information.

**Comment by aserramaq** [comment]
You are right, let me give you more details, sorry.

I loaded the raw file manually.

then in batch mode I included Targeted peak detection\Configure\ and here I selected:
Raw files: as selected in main window
Name suffix:detectedPeak
peak list file: I loaded here a csv file containing a single column, that is the list of m/z from mascot
field separator: ,
Ignore first line: empty (my file doesn't have headers)
Intensity tolerance: 20%
Noise level: 500
m/z tolerance: 0.001 or 5 ppm
Retention time tolerance: 60 min (my chromatogram is a 60 min-chromatogram)

Once I try to run this it tells me that Target peak detection  XXXX.raw: Could not read file or the file is empty.

Hope now it's clearer.

Best,

Aida

**Comment by dyrlund** [comment]
Hi Aida

Your targeted peak list file has to be in the following format:
m/z,RT,Name

Please try to update your csv file and try to run the targeted peak detection module again.

Best,

Thomas

**Comment by aserramaq** [comment]
Hi Thomas,

I've tried again following your recommendation. I loaded the raw file manually and I selected it. Using the same parameters I described in one of my previous messages I changed only the peak list file. 
For the peak list file I've tried two versions:

File 1: (in three different columns in excel, and saved as csv)
m/z	RT	NAME
722.8124	2763	K.YICDNQ#DTISSK.L
722.8126	2459	K.YICDNQ#DTISSK.L
722.8128	2128	K.YICDNQ#DTISSK.L
722.8135	2155	K.YICDNQ#DTISSK.L
722.8144	2384	K.YICDNQ#DTISSK.L
820.9685	975	R.KVPQ#VSTPTLVEVSR.S
547.6502	3341	R.KVPQ#VSTPTLVEVSR.S
874.8406	3018	K.YNGVFQ#ECCQAEDK.G
1082.5231	2383	R.LGEDNINVVEGNEQ#FISASK.S

File 2: (single column in excel saved as csv)

722.8124,2763,K.YICDNQ#DTISSK.L
722.8126,2459,K.YICDNQ#DTISSK.L
722.8128,2128,K.YICDNQ#DTISSK.L
722.8135,2155,K.YICDNQ#DTISSK.L
722.8144,2384,K.YICDNQ#DTISSK.L
820.9685,975,R.KVPQ#VSTPTLVEVSR.S
547.6502,3341,R.KVPQ#VSTPTLVEVSR.S
874.8406,3018,K.YNGVFQ#ECCQAEDK.G
1082.5231,2383,R.LGEDNINVVEGNEQ#FISASK.S

Using the first kind of peak list file the software analyzed the raw file and they generated a peak list, located at the right window. But that peak list shows:

#0 0.0000 m/z @0.0 NAMEOFPEPTIDE
#1 0.0000 m/z @0.0 NAMEOFPEPTIDE
....

using the second kind of file it shows me an error when I'm trying to load the batch mode, telling that Targeted peak detection XXXXX.RAW: Could not read file or the file is empty.

:( I'm sure i'm doing something wrong...

Aida

**Comment by dyrlund** [comment]
Your retention times should be in minutes not seconds. Also, please note that you are setting your retention time tolerance to 60 min. You should set this to something small since this value tell the algorithm how much off individual RT values are allowed to be for accepting and ID. Try with something like 0.05 (= 3 seconds).

If this is not working, then please upload your RAW and CSV file to dropbox (or other storage system) and provide us with the download link so we can reproduce your steps

**Comment by aserramaq** [comment]
Dear Thomas,

Still doesn't work, the list of peaks is empty.
I share the files by dropbox, here there is the link.

https://www.dropbox.com/s/oct1ucujmvtmt7c/doubt_mzmine.rar?dl=0

Inside you can find:
the raw file
Deam_list_loaded.csv --> is the file I loaded as peak list
modified_peptides.txt --> is the raw list of peptides filtered from mascot results. RT is in the last column combined with other info, so I took the RT from here and I converted to min as you recommended.
Printscreen.docx --> contains printscreen showing the values I used 

Many thanks for you patients,

Aida

**Comment by aserramaq** [comment]
Dear Thomas,

I opened the csv file in notepad, and I detected that the file was full of " that were not shown in excel. I delete all of them and now MZmine is able to detect the peak list and it is able to give me a chromatogram for each row of the peak list. 

Now I'm playing around with the parameters, as sometimes RT doesn't match with mine.In my final experiment I'm trying to look for multiple elutions of a single mass, then I should play with the retention time tolerance I think.

Many thanks for your help! and sorry for so many question.

Aida ^.^

**Comment by dyrlund** [comment]
Great that you solved it. With regards to detecting multiple elutions of a single mass then you should add multiple entries in you CSV file with the same mass but different retention times. Expanding the RT tolerance will only give you the most intense peak.

**Comment by aserramaq** [comment]
Dear Thomas,

A few months you was helping me to solve some technical problems about how extract XIC area in batch using MZmine and with your help I successfully extracted my XIC areas. I’ve been working on my data and I would like to know if there is any way to export and save all the XIC area images, like the one pasted below, but also in batch because I need to include in a manuscript all the XIC areas for an specific kind of peptides which I extracted using the targeted peak detection in batch mode.

[cid:image001.png@01D18B6D.EBAC9FB0]

Thank you in advance,

Aida Serra Maqueda
Research Fellow
School of Biological Sciences
Structural Biology and Biochemistry Division
Nanyang Technological University
60 Nanyang Drive, Singapore 637551
SBS-03n-S1
Tel: (65) 9660 2806
Email: aserramaq@ntu.edu.sg<mailto:aserramaq@ntu.edu.sg>

**Comment by dyrlund** [comment]
There is currently no way to automatically export all the XIC areas as images. You will have to do this manually for each peak through the software by opening the XIC chromatogram and then saving this as an image using the right click menu.

**Comment by aserramaq** [comment]
Dear Thomas,

First of all, thanks for your answer, a bit difficult for me to find it but anyway thanks. Can you please delete my personal details from the message you posted? 

About my question,
I have coelution of peptides in different retention times and I need to compare areas of these peaks from the XIC graphics. is there any way to integrate these areas?

I saw that with right click on the XIC graphic I can export chromatogram and it generates a CSV file with intensity and time. 

Then is there any way to do both things in batch, integrate areas and export areas and export the CSV file for each XIC?

Thanks.

Aida

**Comment by dyrlund** [comment]
I have removed your personal details. Please be aware that if you reply to GitHubs emails then they are automatically posted under the issue – this is not something I have done.

You can select two or more entries in a peak list and then use the “Show XIC” in the right click menu to show them in the same plot.

And no, there is no way to export plots to CSV files from the batch mode. You are more than welcome to write a module for this yourself and contribute to the project.

**Comment by aserramaq** [comment]
Dear dyrlund,

thanks for your help, then I will do it manually and unfortunately I'm not able to write a module to export the plots to CSV.

Thanks for the good job done with MZmine,

Aida
