### ISSUE TITLE
Batch stepping broken on MassDetectionTask + "Those created by previous batch steps"

### ISSUE THREAD

**Issue by golgauth** [mzmine/mzmine2#132]
Hi all,

I noticed that the "BatchTask" clears created Data Files and Peak Lists on every step. Which is OK in most of the cases, but when a task does not produces any Data File or Peak List, the entry point (data file or peak list) for the next step is cleared were we would like it to keep the state of the batch intact and able to keep going:

**Example:**

* Step 1: Baseline Correction => Input: "df0", _CLEAR_, Ouput: "df1".
* Step 2: Mass Detection => Input: "df1", _CLEAR_, Ouput nothing.
* Step 3: Chromatogram Builder => Input: nothing => **FAILURE**.

In Step 3, the expected behavior would be to keep going with "df1" (the output of Step 1) as input, since Step 2 is an "unproductive" task.

 _CLEAR_:
https://github.com/mzmine/mzmine2/blob/master/src/main/java/net/sf/mzmine/modules/batchmode/BatchTask.java#L139

This is a quick fix, just to illustrate the problem and the type of solution that could/should be applied. _(Since I haven't been working on MZmine for a while now, I wouldn't pollute the repository too much by providing too easy or inappropriate solutions)_.

```java

        //        // Clear the saved data files and peak lists
        //        createdDataFiles.clear();
        //        createdPeakLists.clear();
        
        // Check if the parameter settings are valid
        ArrayList<String> messages = new ArrayList<String>();
        
        ...
        
        boolean allTasksFinished = false;

        // Clear the saved data files and peak lists only if the 
        // current task is not a task that does not produces any
        // (allows to get next step to keep going with the last
        // created DF and PL from steps older than the previous one)
        if (!(currentStepTasks.get(0) instanceof MassDetectionTask)) {
            createdDataFiles.clear();
            createdPeakLists.clear();
        }

        // Submit the tasks to the task controller for processing
        MZmineCore.getTaskController().addTasks(
                currentStepTasks.toArray(new Task[0]));
```

T(h)omas: Could you help me with providing a proper code/answer to this issue. Is `MassDetectionTask` the only one task to generate this particular issue (I suppose so, but not one hundred percent sure)?

**Comment by tomas-pluskal** [comment]
Hi Gauthier,
I added a workaround for this problem in pull request #135. Basically if the last task did not produce any new data files or peak lists, it will use the ones from the previous step. Could you please give it a try and check if it really fixes the problem?

**Comment by golgauth** [comment]
Hi Tomas,
Cool stuff, seems perfect. Works nicely with my above use case as well.
Thanks very much.
