### ISSUE TITLE
Wrong amount of memory being displayed in bottom right-hand corner!

### ISSUE THREAD

**Issue by Leperkhan** [mzmine/mzmine2#138]
Windows 7 (64-bit)
32GB RAM

MZmine 2.17

C:\Users\Admin>java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)

When I run MZmine 2.17 everything starts up fast and the amount of memory allocated as indicated in the bottom right-hand corner is "1024MB".

I managed to fix this by replacing this line in the startup script...

set JAVA_PARAMETERS=-showversion -classpath lib\* -Djava.ext.dirs= -XX:+UseG1GC -Djava.io.tmpdir=%TMP_FILE_DIRECTORY% -Xms1024m -Xmx%HEAP_SIZE%m

with this line...

set JAVA_PARAMETERS=-showversion -classpath lib\* -Djava.ext.dirs= -XX:+UseParallelGC -Djava.io.tmpdir=%TMP_FILE_DIRECTORY% -Xms%HEAP_SIZE%m -Xmx%HEAP_SIZE%m

or more specifically I replaced...

-Xms1024m

with...

-Xms%HEAP_SIZE%m

Once I changed this line the amount of memory displayed correctly in the bottom righthand corner. I'm not a programmer, so I'd like to know if my fix matters at all. In other words...

Did I do good?

**Comment by tomas-pluskal** [comment]
Hi,
Actually, this is not a bug. See this explanation of the -Xms and -Xmx parameters: http://stackoverflow.com/questions/14763079/what-are-the-xms-and-xmx-parameters-when-starting-jvms

We initially allocate 1024 MB for the java heap, but the JVM can increase the size of the heap as necessary, up to the %HEAP_SIZE% setting.
