### ISSUE TITLE
Error in XCMS preview

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#141]
Gauthier @golgauth ,

I see some issues when running the Chromatogram deconvolution - XCMS module (via Rserve) in MZmine 2.18. If I run the module once, it works fine. But running it the second time results in the following error:

![screen shot 2015-12-13 at 16 21 33](https://cloud.githubusercontent.com/assets/1796692/11769470/15dd41aa-a1b6-11e5-8d9d-18fa688b49fb.png)

Could you please take a look at it?

**Comment by golgauth** [comment]
Hi Tomas,

Yep, I'll look at it ASAP. First need to check if this is a regression, or if the problem exists from the beginning, when we switched to Rserve.

**Comment by tomas-pluskal** [comment]
The CAMERA module is also affected by this

**Comment by tomas-pluskal** [comment]
![screen shot 2015-12-14 at 10 36 47](https://cloud.githubusercontent.com/assets/1796692/11785208/aae87f60-a24e-11e5-9839-7ee162483155.png)

**Comment by tomas-pluskal** [comment]
Note: these modules work fine in MZmine 2.17, so I don't think it is caused by RServe.

**Comment by tomas-pluskal** [comment]
OK, I tracked this issue down to this line in Rsession.java:

boolean SINK_OUTPUT = false;

Since the XCMS and CAMERA modules are unusable at the moment, I am going to revert your last commit to Rsession and release version 2.18.1 immediately. You can then analyze the issue more carefully.

**Comment by golgauth** [comment]
OK, thanks for the tracking. I am quite sure that just keeping the changes and passing 

    boolean SINK_OUTPUT = true;

back to true would have done the job (and kept the fix for the commit valuable). I'll commit it again once I am a hundred percent sure. That is in a few minutes...

**Comment by golgauth** [comment]
Hi Tomas @tomas-pluskal,

Could you please try with your own above use case to check if everything is working fine again with those XCMS and CAMERA modules: Commit 96f5a5e, Pull request #145.

_Note: I went a bit fast in trying to fix issue #128  and optimizing R feature at the same time._

Since you revert my changes, this latest #145 pull request limits its scope to fixing the issue (without the optimization part. I'll try the latter in a separated commit later, after deeper testings).

Thanks

**Comment by tomas-pluskal** [comment]
Hi Gauthier, 
it seems to work fine after merging #145

**Comment by golgauth** [comment]
Hi Tomas,

I hope so. As far as I tested, it's OK. I've been a bit too quick and should stick to one change at a time in the future...

Cheers
