### ISSUE TITLE
total number of different m/z fragmented

### ISSUE THREAD

**Issue by giorgiasapienza** [mzmine/mzmine2#154]
Dear all,

I've just started to work on untargeted metabolomics and I need to understand whether a mass-spectrometric method is better than another for the identification of the metabolites of interest. Due to the impossibility to identify all metabolites each time I change a mass-spectrometric parameter, I need a rapid method to compare the different methods applied.

I've seen in literature that people usually compare the number of features detected (chromatographic peaks associated to a specific m/z) in different conditions. This could be a good information to indicatively understand the best method. But my samples are full of isomers and so it's necessary to collect their pattern of fragmentation (I work in data dependent).

Taking into account the relevance of the fragmentation for my analysis, I think that the best way to understand if a spectrometric method is better than another is counting the number of different features that have been fragmented.

Which is the way to have this information with MZMine? MZ Mine gives all the features detected in a chromatogram, and,selecting each m/z, it shows the relative MS/MS spectrum. But how can I have the total number of m/z features that have been fragmented? It would take a lot of time checking manually if an ion has been fragmented or not!!

Please help me! Thank you!!!!!  :) 

Giorgia

**Comment by tomas-pluskal** [comment]
Hi Giorgia,
Try the MS/MS peaklist builder under Raw data methods -> Peak detection. 
Read the Help, too.

**Comment by dyrlund** [comment]
It might also be interesting for you to check out the MS/MS visualizer to get an overview of your MS/MS runs.

**Comment by giorgiasapienza** [comment]
Hi Tomas-Pluskal, Hi Dyrlund, thank you for the answers!!!

During the last two days I worked on my data using the MS/MS peaklist builder as Tomas suggested me. But I have some concerns:
I've seen that is possible to build the MS/MS peaklist only starting from the original raw data.
Instead, before using the MS/MS peaklist builder, I'd do these operations: mass detection, FTMS shoulder peak filter, chromatogram builder, chromatogram deconvolution and chromatogram deisotoping, to have a feature list that makes sense.
Is there a way to do the MS/MS peaklist builder after all these operations? 

Thank you very much :)

**Comment by tomas-pluskal** [comment]
You can do both ways, you will just end up with two different peak lists.

**Comment by giorgiasapienza** [comment]
![mzmine](https://cloud.githubusercontent.com/assets/16669648/12387949/30500e6a-bdd0-11e5-8e00-73987febdc70.png)

I tryed to build the MS/MS peaklist after the deisotoping but it doesn't work. I send to you a picture of the window to show you the problem!

**Comment by tomas-pluskal** [comment]
Why did you select "Those created by previous batch step" for Raw data files? You are not running a batch sequence, if I understand correctly.

**Comment by giorgiasapienza** [comment]
I selected "those created by previous batch step" because I thought it was the only suitable option for my purpose. 
I'm sorry, maybe I didn't explain the problem in the right way: 
I want to create the MS/MS peaklist starting from the deisotoping step. In this way, I will have an MS/MS peak list that: 1) keeps all the parameters set in the previous steps (for example minimum intensity to consider a peak= 1E6, FTMS shoulder peak filter etc.);   2)  deconvoluted;  3) deisotoped.
The information that I want is: how much features (obtained by the previous steps) have a fragmentation spectrum?

I hope there's a solution :))

**Comment by tomas-pluskal** [comment]
Hmm, I am afraid there is no function in MZmine for that. 
Feel free to contribute.

**Comment by giorgiasapienza** [comment]
mmh ok, however I thank you very much for your help!

The last question and then I promise I'll stop:
In building the MS/MS peaklist I have to set the m/z window and the time window.

To which window does it refer?

To the whole range of m/z and of minutes in which it will look for MS/MS spectra or to something else? (for example if I put 1000 m/z and 30 minutes it will look for features between 0 and 1000 m/z, and from 0 to 30 minutes that have been fragmented?) 

I did some attempts but I don't understand...  :/

**Comment by tomas-pluskal** [comment]
Sorry, it is not well explained in the help. The m/z window corresponds to a tolerance window around the precursor mass. The time window corresponds to a tolerance window around the retention time of the MS2 scan. MZmine will search for the parent (MS1) peak in all MS1 scans within these windows.

**Comment by dyrlund** [comment]
Hi Giorgia,

Although you can’t automatically filter your features by which have an associated MS/MS spectra, you can visualize which features have an associated MS/MS spectrum. Here is an example of how this looks in MZmine:

![msms](https://cloud.githubusercontent.com/assets/10582167/12413072/548b4346-be8c-11e5-8da7-625796e75535.png)

The green lines are the features from a specific peak list, and the grey/black dots represent MS/MS spectra. When they overlap, you know that you have a MS/MS spectra for a particular peak.

To generate this plot, first generate a peak list like you would normally do. Then open a MS/MS visualizer plot for your raw data file. Once loaded, you can select to show e.g. all peaks from a specific peak list at the bottom of the plot. These will then be added as the green lines to the plot.

Another option - although very manual - is to right click on a peak in a peak lists and open the show menu. If the "MS/MS" is not grayed out then there is a MS/MS spectrum for the peak. You can use this to remove features with no associated MS/MS spectra.

![msms2](https://cloud.githubusercontent.com/assets/10582167/12413131/e4e64ac6-be8c-11e5-8a98-ed24b5a363f1.png)

**Comment by giorgiasapienza** [comment]
Hi Dyrlund,
I've tried with the graphical method, but my data set are too large. I see all green lines so that I can't have a real comparation among different samples. Thank you however. :)

**Comment by giorgiasapienza** [comment]
Hi Thomas,
thank you for the explanations. From what I understood, if i set 0.001 m/z and 2 minutes, those precursor ions whom m/z and time difference is comprised in those windows should be shown as a single line in the MS/MS peak list, right?
But I have these results:
![ms ms 1](https://cloud.githubusercontent.com/assets/16669648/12423901/f64e5bb4-becd-11e5-8f92-4e0da5d3b8d6.png)
![ms ms 2](https://cloud.githubusercontent.com/assets/16669648/12423900/f64c4798-becd-11e5-8b92-4612eca825ce.png)

**Comment by tomas-pluskal** [comment]
There is always a single line, because only a single scan is selected to form the peak using this module. You can use the Peak extender module to expand the single line into a full peak over retention time.

**Comment by giorgiasapienza** [comment]
What I meant was that for example the 160.1332 ion shouldn't be repeated four times ( as in the first pictures). In fact, when I extend the single lines into full peaks with the peak extender module, I obtain 4 different chromatographic peaks for the 160.1332. But it's obvious that's a unique compound.
![ms extender](https://cloud.githubusercontent.com/assets/16669648/12444121/234f659c-bf5d-11e5-8fdc-0852d1551b0d.png)

**Comment by dyrlund** [comment]
You can fix this by running the Duplicate peak filter (Peak list methods -> Filtering) on your peak list.

FYI. In [MZmine 3](https://github.com/mzmine/mzmine3) we have updated the MS/MS feature list builder to make everything more simple so you don't need to run the Peak extender and filtering afterwards on your features. You can read more about how it works [here] (https://github.com/msdk/msdk/issues/31).

**Comment by giorgiasapienza** [comment]
Oook! 
Thank you Thomas and Dyrlund for the assistence, you've been very helpful!

Giorgia
