### ISSUE TITLE
Error appears when running

### ISSUE THREAD

**Issue by LeonLiang92** [mzmine/mzmine2#157]
Hello,

After I downloaded MZmine2 from the website, I couldn't run it successfully. The following is the codes that came out in the screen. My computer is 64 bit, 8GB ram, Windows 10.

It shows:
Checking physical memory size...
Found 8094 MB memory, 64-bit system
Java version is 1.7.0_06 (64-Bit)
Java maximum heap size set to 6046 MB

java version "1.7.0_06"
Java(TM) SE Runtime Environment (build 1.7.0_06-b24)
Java HotSpot(TM) 64-Bit Server VM (build 23.2-b09, mixed mode)

Error: Could not find or load main class lib\avalon-framework-api-4.3.1.jar
Press any key to continue . . .

Could anyone help explain this issue? Thanks!

Leon

**Comment by dyrlund** [comment]
You are running an old version of Java 7 on your system. Please try to update to the latest 64-bit version of [Java 8](https://www.java.com/en/download/manual.jsp) and see if this solves your issues.

**Comment by LeonLiang92** [comment]
I updated to Java 8 and it works well! Thank you very much!
