### ISSUE TITLE
startMZmine on Windows

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#161]
Apparently, the startMZmine.bat script fails on Windows when executed from a different folder than the MZmine folder.

**Comment by dyrlund** [comment]
Here are two easy workarounds for this:
1. Create a shortcut to the startMZmine.bat script instead of moving the script, or
2. Change the classpath in the script to account for the full path of the lib folder.

    set JAVA_PARAMETERS=-showversion -classpath C:\MZmine\MZmine-2.18.2\lib\* -Djava.ext.dirs= -XX:+UseG1GC -Djava.io.tmpdir=%TMP_FILE_DIRECTORY% -Xms1024m -Xmx%HEAP_SIZE%m

**Comment by tomas-pluskal** [comment]
Both of the workaround require the user to perform some action. Isn't there any way to fix this universally on our side?

In the Linux/Mac scripts, this issue is already handled by the following code:
```
# Make sure we are in the correct directory
SCRIPTDIR=`dirname "$0"`
cd "$SCRIPTDIR"
```

**Comment by dyrlund** [comment]
So on a Mac you can place the startMZmine_MacOSX.command file in a random folder and then start MZmine without an issue?

I cannot see how this should be possible on Windows since the .bat file will only be able to get the directory path to where it is located (using **%~dp0**), not where the MZmine lib folder is located. You could solve this by scanning for the MZmine folder on the computers drives but I don’t think this makes sense.

**Comment by golgauth** [comment]
Well, Hi Thomas,

I don't think so: `dirname "$0"` does not give the location of the MZmine folder. It gives the full path of the script being executed (just like `%~dp0` does).
What Tomas meant, I believe, is: From a command prompt, how do I run the startup script without the current working directory being the MZmine one (the startup script remains in the MZmine script in anyways)?

I think `cd %~dp0` should be the correct equivalent.

**Comment by dyrlund** [comment]
Ahh, I see. Well then yes, the above lines of code should solve it :)

**Comment by dyrlund** [comment]
Gauthier, will you make a commit?

**Comment by golgauth** [comment]
Well, I could do so. Let me switch under Windows and test the code first.

**Comment by golgauth** [comment]
Done: #168. Cheers

**Comment by tomas-pluskal** [comment]
Great. Thanks guys.
