### ISSUE TITLE
MZmine2 parameter settings for peptide maps

### ISSUE THREAD

**Issue by annezeck** [mzmine/mzmine2#163]
I'm looking for a standard workflow or a procedure on how to extract the analysis parameters from the raw data for a comparative analysis of two peptide maps aquired on a QExactive instrument.
It is almost impossible for us to try different parameters due to very long processing time on the computer.

With many thanks in advance,

Anne

**Comment by tomas-pluskal** [comment]
Hi. There is no general answer to this, it will depend on what "analysis parameters" are you talking about.
Some ways how to optimize the parameter values are described in each module's help.

**Comment by annezeck** [comment]
Hi Tomáš,

is there some information in the module’s help on how to compare non-metabolite (=peptide map) data? Somehow we could not find it.
Currently we are using SIEVE (Thermo) for differential analysis of our peptide map data. Although we can detect differences in samples that are well separated chromatographically and by mass, it is not possible to detect e.g. deamidation. The deamidation of a peptide is often not well separated from the non-deamidated peptide and has a mass difference of only 1 Da (interfering isotope peaks).
Do you think we could analyze such modifications with MZMine 2 and what would be the best procedure? Is somebody using MZMIne for differential analysis of peptide maps?

With many thanks in advance,

Anne





Von: Tomáš Pluskal [mailto:notifications@github.com]
Gesendet: Tuesday, January 19, 2016 6:43 PM
An: mzmine/mzmine2
Cc: Anne Zeck
Betreff: Re: [mzmine2] MZmine2 parameter settings for peptide maps (#163)


Hi. There is no general answer to this, it will depend on what "analysis parameters" are you talking about.
Some ways how to optimize the parameter values are described in each module's help.

**Comment by tomas-pluskal** [comment]
> is there some information in the module’s help on how to compare non-metabolite (=peptide map) data? 

I don't think we have any specific help for such use case.
From MZmine's perspective, it's all about peaks. It doesn't matter if the peaks come from metabolites or peptides.

> Do you think we could analyze such modifications with MZMine 2 and what would be the best procedure? 

The adduct search module can annotate peaks with a pre-defined mass difference, that could help you. If you require more sophisticated approach, you can develop (or ask someone to develop) your own module for your purpose.

> Is somebody using MZMIne for differential analysis of peptide maps?

No idea, sorry.
