### ISSUE TITLE
mzTab peaklist export - Newlines inconsistent

### ISSUE THREAD

**Issue by photocyte** [mzmine/mzmine2#164]
When exporting peaklist into mzTab, the resulting metadata section has windows style newline (0x0D0A), whereas the data portion has unix style newline (0x0A), which confuses text editors.  
[blank_GB2_20uL.mzTab.txt](https://github.com/mzmine/mzmine2/files/96111/blank_GB2_20uL.mzTab.txt)

**Comment by tomas-pluskal** [comment]
The export was done on Windows?

**Comment by photocyte** [comment]
Windows using batch mode.

**Comment by photocyte** [comment]
On mac it is all 0x0A
[test_mzTab_export_mac.mzTab.txt](https://github.com/mzmine/mzmine2/files/96152/test_mzTab_export_mac.mzTab.txt)

**Comment by dyrlund** [comment]
I updated the code (#167) to use System.lineSeparator(); for new lines instead of \n. This should fix the issue.

**Comment by photocyte** [comment]
dyrlund's change fixes the issue on my end.  Thanks!
