### ISSUE TITLE
mzTab import - raw data import

### ISSUE THREAD

**Issue by photocyte** [mzmine/mzmine2#165]
When importing mzTab there is a checkbox to also import the raw data.  In my case, on windows, when the .raw and .mzTab are in the same directory, MZmine seems to not find the appropriate .raw file & uses produces a placeholder raw data file in the GUI instead of the appropriate raw data.  In the mzTab the .raw file path is specified relatively, perhaps this could be the cause?

**Comment by dyrlund** [comment]
This is an issue with the data structure in MZmine 2. You will have to manually specify the absolute path in your mzTab files to allow the raw data files to be imported also.

We have developed a new and more improved data structure in [MZmine 3](https://github.com/mzmine/mzmine3) which has solved this issue.

**Comment by tomas-pluskal** [comment]
Thomas, I think @photocyte is talking about .mzTab files that were exported from MZmine, and then imported again back to MZmine. It seems the full path to the raw data file is not added to the .mzTab file when it is exported, and that is why it fails.

**Comment by dyrlund** [comment]
I know, but the original path to the raw data files is not stored in the data model for MZmine 2 and is therefore not available. I listed it as a [to do task in the code](https://github.com/mzmine/mzmine2/blob/master/src/main/java/net/sf/mzmine/modules/peaklistmethods/io/mztabexport/MzTabExportTask.java#L122) but decided to not spent time on it with the development of MZmine 3.

**Comment by tomas-pluskal** [comment]
Ok, I understand :)

**Comment by tomas-pluskal** [comment]
In PR #170 I added the function that it looks for the raw data file in the same folder as the mzTab file (which might be sometimes the case, although not always)

**Comment by dyrlund** [comment]
That's a nice workaround - I like it!

**Comment by photocyte** [comment]
Changes fixes the issue! (Tested on Mac w/ loading .mzML & mzTab from the same directory over the network)
