### ISSUE TITLE
mzTab peaklist import - File import GUI only allows 1 file at a time

### ISSUE THREAD

**Issue by photocyte** [mzmine/mzmine2#166]
mzTab peaklist import only allows 1 file to be imported at a time (e.g. shift clicking doesn't select multiple files).  Ideally multiple files should be able to be selected & imported through the import dialog simultaneously

**Comment by dyrlund** [comment]
This has already been implemented in [MZmine 3] (https://github.com/mzmine/mzmine3). You are welcome to contribute with the change to MZmine 2.

**Comment by tomas-pluskal** [comment]
I'll backport this back to MZmine 2. It is actually quite simple.

**Comment by tomas-pluskal** [comment]
Added in PR #169
