### ISSUE TITLE
.mzML.gz GZIP import - fails on windows batch mode.

### ISSUE THREAD

**Issue by photocyte** [mzmine/mzmine2#179]
Hi there,

Working with revision #178 created "pre-release" (created using Maven build through Eclipse).  I have successfully imported .mzML.gz files on Mac & Windows through the GUI (over a network by SMB, relatively quickly so issue 148 https://github.com/mzmine/mzmine2/issues/148 doesn't seem to apply, presumably as the .mzML loading is done on a cached decompressed .mzML file)  However, on windows batch mode, the .mzML.gz file is successfully decompressed as reported in the log, but afterwards the batch mode fails with "File not found.".  See attached for logs & .xml batch configuration file (all from Windows)

[successful_gzip_import_GUI.txt](https://github.com/mzmine/mzmine2/files/102105/successful_gzip_import_GUI.txt)
[failed_gzip_import_batch.txt](https://github.com/mzmine/mzmine2/files/102106/failed_gzip_import_batch.txt)
[temp_MZmine2batch.xml.txt](https://github.com/mzmine/mzmine2/files/102107/temp_MZmine2batch.xml.txt)

**Comment by photocyte** [comment]
Little bit more information: In running the same batch configuration file (provided in previous comment) under the GUI the issue becomes more clear.  Seems like it might be a timing issue of sorts.  E.g., the first batch step executes, and once the GZIP decompressing task ends (and the mzML import task then starts), the batch then tries to execute the second step (mass detector), but since there is no .mzML file it fails with the error message: "Invalid parameter settings for module Mass detection: [At least 1 raw data file must be selected"]

**Comment by tomas-pluskal** [comment]
Right.. 
I didn't think about that. 
Will fix.

**Comment by tomas-pluskal** [comment]
Should be fixed in PR #180

**Comment by photocyte** [comment]
Thanks! With #180 .mzML.gz import is observed to now be implemented as a single task. Issue tested & solved on Windows batch mode.  

Closing comment: I wonder if the HD caching of the decompressed .mzML file as a temporary file could be problematic. If not cleaned up appropriately (not explicitly deleted by MZmine2 after import, OS never reboots etc.) could cause issues due to files building up.  Likely fixed in MZmine3 with option to import into Ram vs HD temporary file.

**Comment by tomas-pluskal** [comment]
The tmp file is now deleted after import and also marked to be deleted by JVM on shutdown, so it should only remain on disk in very rare cases (like JVM crash).
