### ISSUE TITLE
Not getting areas for Thermo raw data peak detection (but it claims to find peaks)

### ISSUE THREAD

**Issue by MrDarkHorse** [mzmine/mzmine2#184]
I'm using one of the example files that comes with Thermo Xcalibur.  (drugx_01.raw)

I've been trying to trace through the code to see where I'm going wrong, but even when I run the mzMine app itself, I can't seem to get areas for my peaks.

Here is the file in Xcalibur:
![drugx01inxcalibur](https://cloud.githubusercontent.com/assets/9271182/12536877/840e6af0-c277-11e5-8d04-873478034314.png)

My mass settings:
![drugx01masssettings](https://cloud.githubusercontent.com/assets/9271182/12536879/90897d56-c277-11e5-864e-5d537d3a2c12.png)

Chromatogram settings:
![drug01chromatograms](https://cloud.githubusercontent.com/assets/9271182/12536881/9f19acd8-c277-11e5-9037-9f1ce9ca0c98.png)

But here's what my peak list shows:
![drugx01notraceorareas](https://cloud.githubusercontent.com/assets/9271182/12536886/a5826ab0-c277-11e5-9da4-8368cf411bce.png)

I know Thermo/Waters are the weird ones because they have their own formats, but I'm trying to get peak detection working using all of the different supported file types.

**Comment by tomas-pluskal** [comment]
The Chromatogram builder module is generally used with MS1 (full scans).
It will probably require some tweaking to use it on SRM data as you are trying to do. 
Can you send the .raw file, e.g. using Dropbox?

**Comment by MrDarkHorse** [comment]
Sure... where do you want me to send it?

**Comment by tomas-pluskal** [comment]
You can post it here, or send it to my email (plusik@gmail.com)

**Comment by MrDarkHorse** [comment]
https://www.dropbox.com/s/aeyb5xnhsd4ny0z/drugx_01.raw?dl=0

**Comment by tomas-pluskal** [comment]
The problem here is that you have alternating types of scans (fragmenting 465 mz and 469 mz), so chromatogram builder cannot find a continuous signal to build the peak. You can trick it by selecting only those scans that have the same precursor, but that will only build a single peak:

![sshot](https://cloud.githubusercontent.com/assets/1796692/12553314/c158372e-c344-11e5-918b-823b34435d90.png)

The conclusion is that the Chromatogram builder is not really a good algorithm to process this kind of SRM data. We currently don't have a module for that.

**Comment by MrDarkHorse** [comment]
So, I'm really glad you clarified that Scan Definition could be used to isolate precursors.  I didn't catch that.  I was able to isolate the scans that match the precursor I'm interested in, and it was simple enough to filter by Retention Time, but unfortunately the chromatogram builder is still unable to pick up these scans and put them together.  Do you think it's a limitation of the chromatogram builder itself?  (in which case I might be interested in trying to help fix that, assuming that change would be desirable for everyone)

Or perhaps I'm just not setting up the parameters correctly.  I tried not specifying any Scan Definition in the chromatogram builder, in which case it complains that my first scan doesn't contain a mass in the mass list.  I also tried specifying *465*, which yielded no results.

Sorry for the continued questions, but this is a new tool for me and I'm trying to understand all the nuances to see if it will be sufficient for my needs.


![drugxmassselectedbyprecursor](https://cloud.githubusercontent.com/assets/9271182/12569836/195ba50c-c398-11e5-97dd-b881365c7185.png)

**Comment by tomas-pluskal** [comment]
First, run mass detection on all scans. Then run the chromatogram builder using the parameters I showed above. That will give you a peak list for a single precursor. However, MZmine is generally made for MS1 (full scan) data. You probably won't have much use for it, unless you want to add new modules by yourself.

**Comment by MrDarkHorse** [comment]
Hmmm... I still get no results using the method you just described. 

![drugxmassallscans](https://cloud.githubusercontent.com/assets/9271182/12572105/6bbd7e14-c3ad-11e5-8eff-3942aca47786.png)

![drugxmassnochro](https://cloud.githubusercontent.com/assets/9271182/12572106/6bc1e698-c3ad-11e5-978a-2b39bc96e61c.png)


It may not be outside the realm of possibility that I could write a module to do this.  I may be oversimplifying, but it doesn't seem ridiculous to do so if it's just a matter of picking what scans to use.  I'm just not sure if I'm doing something wrong.  Getting back a single peak would be fine for what I'm doing.

**Comment by tomas-pluskal** [comment]
How did you set the noise level in the centroid mass detector?

**Comment by MrDarkHorse** [comment]
Ah!  That was it... my noise was too high.

Now i'm finding a peak and gettting an area.

Still not seeing a trace, but maybe that's expected since this is SRM data and confusing the system?

![drugxpeaknochro](https://cloud.githubusercontent.com/assets/9271182/12572275/a8cfd53e-c3af-11e5-8751-b772dff60116.png)

**Comment by tomas-pluskal** [comment]
Yes, that's because the traces are constructed from MS1 signals.

**Comment by MrDarkHorse** [comment]
Okay cool that explains it I guess.

**Comment by MrDarkHorse** [comment]
Thanks this was very helpful

**Comment by MrDarkHorse** [comment]
Created a pull request that addresses this issue:

https://github.com/mzmine/mzmine2/pull/200
