### ISSUE TITLE
Allow MZmine to export data in mzXML file format?

### ISSUE THREAD

**Issue by brittoner** [mzmine/mzmine2#187]
Hi, I am trying to fix chromatograms using MZmine before inputting into GNPS which requires mzXML format.  Is this possible?  I do not see mzXML and an export option.  I also need the fragmentation data to remain in my final chromatograms.  Please let me know, as it would really benefit my work!  

Best, 
Emily Britton
erbritto@uncg.edu

**Comment by tomas-pluskal** [comment]
Hi Emily. 
MZmine does not currently have such module.
Contributions are welcome.

**Comment by brittoner** [comment]
I think the development of this would be wonderful, but I am not by any means a computer scientist!  I'm more of an analytical biochemist.  What would your advice be? Would anyone else be able to develop it, or would I need to teach myself how to do this?

**Comment by tomas-pluskal** [comment]
My advice: try to find an interested student in a computer science department.

**Comment by brittoner** [comment]
Will do, thank you so much!
