### ISSUE TITLE
About Custom database search

### ISSUE THREAD

**Issue by tnlatnlagho** [mzmine/mzmine2#188]
Thank you for presenting this good software. But I have a problem with it.

I want to search all of peaks in the given range(I choose). I used other database search in MZmine, and they did as I wanted. Namely, they search all the peaks that are in the given ranges. Is it possible to search all of  peaks in custom database search, other than just searching nearest peak??

**Comment by tomas-pluskal** [comment]
Hi,

Please follow the "How to report problems with MZmine" section of the manual.

**Comment by tnlatnlagho** [comment]
1. Your MZmine version.
MZmine 2.18.3 
2. Your OS and its version (32­bit or 64­bit?). 
Windows 10, 32bit
3. The exact output of the following two commands:  java ­version   R ­­version  
I don't know well about this.
4. Let us know if you changed any settings in your startMZmine script file. 
No, I didn't changed anything. I just used R to activate kinds of baseline correction.
5. The exact steps you took until you encountered the problem. 

File open-Filtering(baseline correction)-Mass detection(mass detector-exact mass)-

chromatogram builder-chromatogram deconvolution- custombased database search
  
6. Screenshots of all error messages or unexpected output. 

Custom database is made by me very roughly. I just wanted to know MZmine can search the 

database with right range. But as I mentioned, MZmine just searched only nearlest peak.
[MZmine custom database2.zip](https://github.com/mzmine/mzmine2/files/105997/MZmine.custom.database2.zip)

for example I want to all peaks near 306.3720 (m/z), so the number of peaks can be 1 or 2 or 3 or ~~.

But it can only give only one output regardless of the range.

**Comment by tomas-pluskal** [comment]
Based on your report, the closest answer I can give you is: maybe.

**Comment by tnlatnlagho** [comment]
Could you inform me of the method to search every peaks in the range? I don't understand what you answered.

**Comment by tomas-pluskal** [comment]
What "range"?
Please describe **exactly** what you did, including parameter values.

**Comment by tomas-pluskal** [comment]
Since no details were provided, should I close this issue?

**Comment by dyrlund** [comment]
@tnlatnlagho If I understand your question correctly, then you want to use the custom database search to find all possible ion annoations of your features. This is not possible in the current implementation of the module in MZmine 2. We have however made this possible in MZmine 3 – please see the following [issue](https://github.com/mzmine/mzmine3/issues/52).
