### ISSUE TITLE
chromatographic profile after deconvoluting

### ISSUE THREAD

**Issue by giorgiasapienza** [mzmine/mzmine2#189]
Hi!
I've a problem with the XIC visualization: After applying the chromatogram builder, the peaklist shows the right peak shape and the right parameters relative to an m/z ion. 

![chromatogram builder](https://cloud.githubusercontent.com/assets/16669648/12582478/b73c064a-c43d-11e5-92d7-b383a2ce2865.png)

After deconvoluting I see inconstistent results among the parameters (for example the number of data point), the peak shape and the xic. Is it possible to solve it?

![chromatogram deconvolution](https://cloud.githubusercontent.com/assets/16669648/12582518/eceedb50-c43d-11e5-921a-7939115d4bbf.png)

Thank you!

Giorgia
Giorgia

**Comment by tomas-pluskal** [comment]
Hi Giorgia,

The answer is: maybe.

[hint: check the "How to report problems with MZmine" section of the manual]

**Comment by giorgiasapienza** [comment]
​
 60%_38min.mzmine
<https://drive.google.com/a/uniroma1.it/file/d/0B_ZTVvGID9ugRVNBbEJoYUY2ODQ/view?usp=drive_web>
​1) MZmine version: 2.18.3
2) windows 7, 64 bit
3) java 1.8.0_60
4) Didn't change any settings to  my startMZmine script file
5) see the attached files


2016-01-26 15:39 GMT+01:00 Tomáš Pluskal <notifications@github.com>:

**Comment by tomas-pluskal** [comment]
Can you please also explain what did you mean by "inconstistent results among the parameters".

**Comment by giorgiasapienza** [comment]
for sure! let's show an example.
This picture is after the chromatogram building:
![chromatogram builder 1](https://cloud.githubusercontent.com/assets/16669648/12587223/b9ad885c-c453-11e5-9752-59c28a71545f.png)
I set to consider signal over 5E5. So the only signal that I should see highligthed are the 401.2538 (RT 9.5) and 401.2514 (RT 10.02). Instead, a lot of other signals are highlighted, but it's not a problem.

This picture is after deconvoluting:
![chromatogram deconvolution1](https://cloud.githubusercontent.com/assets/16669648/12587611/6bec02e0-c455-11e5-90e8-9125bee402a1.png)
Considering the peaks mentioned above, we can se that:
-the ion 401.2538 (RT 9.5) in the peak list appears as 401.2532 and in XIC visualizer as 401.2538. Its area is colored  pink and its profile highlighted in blue (even if the blue line follows all the chromatographic profile).
-the ion 401.2514 (RT10.02), instead, in the peaklist appears as 401.2530. It is NOT higlighted in pink and NOT with the blue line. There's another peak instead that is highlighted in blue, the 401.2527 ion.

So the problems are that: 
-sometimes the m/z values changes a little before and after these operations (which is the right one?)
-sometimes the m/z values are different in the peaklist and in the XIC visualizer (Which is the right one?)
-in the XIC visualizer the m/z ions are highlighted in pink, but sometimes in blue. So I don't know if i can trust to parameters such as tailing factor, asimmetry factor, number of data point. (Do they refer to the "pink peak"? Or to the "blue peak"?)

I hope everything was clear!!

**Comment by tomas-pluskal** [comment]
> I set to consider signal over 5E5. So the only signal that I should see highligthed are the 401.2538 (RT 9.5) and 401.2514 (RT 10.02). Instead, a lot of other signals are highlighted, but it's not a problem.

Not sure where you set this "consider" level. Please describe which parameter exactly you are referring to.

> sometimes the m/z values changes a little before and after these operations (which is the right one?)

The m/z value of each detected peak is calculated as a median of the m/z values across the chromatographic profile, which themselves are calculated for each scan using the Mass Detection module (the method of calculation depends on the selected algorithm).

> -sometimes the m/z values are different in the peaklist and in the XIC visualizer (Which is the right one?)

When you open the TIC visualizer, the peak profile (that was recognized by the deconvolution process) is shown in pink. The blue color indicates the XIC from the raw data, and the shape of that XIC depends on the exact m/z range that you are plotting. Try right mouse click in the peak list table -> show TIC (dialog) option and adjust the m/z range. You will see how the blue line changes, while the pink profile will stay the same. So, to summarize the answer: pink are your peaks, blue is the raw data.
It's important to realize that in the XIC, each data point will have a different m/z value.

> -in the XIC visualizer the m/z ions are highlighted in pink, but sometimes in blue. So I don't know if i can trust to parameters such as tailing factor, asimmetry factor, number of data point. (Do they refer to the "pink peak"? Or to the "blue peak"?)

tailing factor, asymmetry factor, number of data points all refer to the detected (pink) peaks.

**Comment by giorgiasapienza** [comment]
Thank you for the explanations

I set the level 5E5 here:
![untitled](https://cloud.githubusercontent.com/assets/16669648/12615922/b9e2235e-c508-11e5-986a-4f4885b51c47.png)

**Comment by tomas-pluskal** [comment]
"Min height" means you only detect peaks that are higher (at their top data point) than 5E5. Which is the case for both of your detected (pink) peaks - one is 8E5, the other one is 1.1E6. Seems like everything is working as expected.

**Comment by giorgiasapienza** [comment]
Yes, those are the only detected (pink) peaks after deconvolution, but not before the deconvolution. 
Before the deconvolution there are others peaks highlithed in pink. Apart from that I understood everything!

**Comment by tomas-pluskal** [comment]
The other peaks you showed in the plot are all lower than 5E5 - that's why they were discarded during the deconvolution.

![Uploading b9ad885c-c453-11e5-9752-59c28a71545f.png…]()

**Comment by tomas-pluskal** [comment]
Can I close this issue?

**Comment by giorgiasapienza** [comment]
Yes, Thank you!
