### ISSUE TITLE
Batch stepping broken on CSVExportTask + "Those created by previous batch steps"

### ISSUE THREAD

**Issue by golgauth** [mzmine/mzmine2#199]
Hi all,

We get an error when running a batch on several files:

![selection_088](https://cloud.githubusercontent.com/assets/5875064/12824180/4c18666c-cb70-11e5-9f1e-d32518e80c33.png)

> Error: Maximum 1 peak lists may be selected

The problem is: We should be able to give a pattern as a `Filename`, or by default, use the peaklist's name as a prefix. Otherwise, if we allow _"Those created by previous batch steps"_ or any other way of having more than one peak list as input of the Exporter, we'll have the exact same issue.

![selection_089](https://cloud.githubusercontent.com/assets/5875064/12824361/1f22c5c0-cb71-11e5-897d-a4c97788998b.png)

_Use case here (see first and last step of this batch file): 
[CL_batch_ok2.xml.zip](https://github.com/mzmine/mzmine2/files/117948/CL_batch_ok2.xml.zip)_

Note: I guess all the exporters have the same issue. If you can fix that one I'll try to fix the others the same way.

Thanks.

**Comment by tomas-pluskal** [comment]
Hi Gauthier,

The question is, what do you think is the best way to fix this?
It is not possible to export multiple peaklists into a single CSV file. We can export the first peaklist that is selected, and ignore the others, but that is not so intuitive either.

**Comment by golgauth** [comment]
Hi Tomas,

Well, I did not mean to have a unique output CSV file. I was more trying to figure out a way to generate 1 CSV output file per peak list, which induces to not ask for a unique `Filename`, but more something like using the peaklist name as the CSV prefix (1), or a more advanced "pattern oriented" approach (2):

1) (default = Pattern: "{PL name}")
PL1 => PL1.csv
PL2 => PL2.csv

2) Pattern: "{PL name}_glg.csv"
PL1 => PL1_glg.csv
PL2 => PL2_glg.csv

etc.

BUT, I am aware that this can be a little bit complicated to have something intuitive and compatible with the actual design and `UserParameter`s (in term of code). This can also generate problems like: What happens if two PL have the same name, etc.

I don't know if I made myself clear. If yes, do you see a nice way of doing this?

**Comment by tomas-pluskal** [comment]
I see your point. What you propose is actually very easy to implement. And since the change will not break current behavior, I have no issues with adding this kind of function. Would you like to submit a pull request? :)

I'd say we can substitute {} for the peaklist name, that is a similar pattern to the unix _find_ command. If two peak lists have the same name, the second one will overwrite the first one, but I don't think that is a big problem.

**Comment by golgauth** [comment]
OK, let's go then ;). I'll do that ASAP.
I'll keep the current `Filename` field (but suggest in the tooltip, to use `{}`, if applicable for the user) and search for the pattern `{}`. If the pattern is not found, the behavior would remain the old one, otherwise one CSV file per PL is exported. Does that suit you and did I understand you properly?

**Comment by tomas-pluskal** [comment]
Sounds good to me.

**Comment by golgauth** [comment]
Proposal: Pull Request #203.

**Comment by golgauth** [comment]
Made changes as promised. Pull Request #236.
