### ISSUE TITLE
Newly opened windows are not always shown in front of other windows

### ISSUE THREAD

**Issue by dyrlund** [mzmine/mzmine2#20]
XIC plots, peak list tables and parameter dialogs  (and possibly also other windows) are often hidden behind the main MZmine window - this seems to happen randomly.

If the call to **window.setVisible(true)** is postponed using a timer like the below then the window is shown correctly in front of the main window:
```java
Timer timer = new Timer();
timer.schedule(new TimerTask() { public void run() {window.setVisible(true); } }, 300);
```
The issue has been seen on Windows 7 (32-bit) running java 1.7.0.75 (32-bit) and Windows 2008 R2 (64-bit) running java 1.8.0.31 (64-bit).

The issue occurs both when opening a new window using double click or the right click menu.

**Comment by tomas-pluskal** [comment]
Thomas, have you tried calling
window.toFront() 
after window.setVisible(true)?

https://docs.oracle.com/javase/7/docs/api/java/awt/Window.html#toFront()

**Comment by dyrlund** [comment]
Yes, I tried that and also the window.repaint(); but the window is still displayed behind the main window.

**Comment by dyrlund** [comment]
The following hack works - but I think it would be nice to find a better solution:

// Hack to bring window to front
window.setAlwaysOnTop(true);
Timer timer = new Timer();
timer.schedule(new TimerTask() { public void run() { window.setAlwaysOnTop(false); } }, 500); //msecs

**Comment by tomas-pluskal** [comment]
The hack may work for you now, but it's hard to guess what it's going to do in all possible situations - keep in mind there is a multitude of versions of JVM on Windows, Mac OS X, and Linux/Unix (that itself comes with a multitude of X server implementations and window managers), plus various multi-display configurations, remote desktop access methods (e.g., VNC), virtual machines (e.g., VMware Fusion integrated into Mac desktop), etc etc. The hack may bring undesired side effects to some users. 
We need to find the true cause of the bug..

**Comment by dyrlund** [comment]
I agree. I haven't had much time lately to work on the issue.

**Comment by dyrlund** [comment]
Here are some other things I have tried.

This dosen't work:
```java
	window.setVisible(true);
	window.toFront();
	window.requestFocus();
	window.repaint();
```

Neither does this:
```java
	java.awt.EventQueue.invokeLater(new Runnable() {
	    @Override
	    public void run() {
		window.setVisible(true);
		window.toFront();
		window.repaint();
	    }
	});
```

However, this works:
```java
	Timer timer = new Timer();
	timer.schedule(new TimerTask() { public void run() {window.setVisible(true); window.setVisible(true); } }, 150); //msecs
```

**Comment by tomas-pluskal** [comment]
I have not seen this bug myself, but I suspect that in your case the new window actually gets the focus, but then the main window gets focused again shortly after. That would explain why the 3 above-mentioned workarounds didn't help.

If my assumption is true, then what remains is to find out why the main window gets activated (by what event). I think in any case you will need to monitor the Swing event queue to find the cause. See for example here: http://stackoverflow.com/questions/6178944/eclipse-java-is-there-an-event-monitoring-feature

```
Toolkit.getDefaultToolkit().addAWTEventListener(new AWTEventListener() {
    public void eventDispatched(AWTEvent event) {
        System.out.println(event);
    }
}, -1);
```

**Comment by dyrlund** [comment]
The bug was solved by replacing:
```public void mousePressed(MouseEvent e)```

With:
```public void mouseClicked(MouseEvent e)```

Thanks to Tomas for finding the solution!
