### ISSUE TITLE
Unable to correct baseline

### ISSUE THREAD

**Issue by jlparkI** [mzmine/mzmine2#206]
Hi all,

The baseline correction feature in the most recent version of MZmine gives me the error message shown below every time I try to run it, no matter which algorithm I use. I downloaded an older version of MZmine (version 2.18.2) just in case this was a problem with the new version but I still get the same error message.

"Error of task Correcting baseline for Background.mzXML
'R computing error' during baseline correction.
Rserve error: couldn't collect result for R expression 'baseline' (instance '24112')."

I have R(64-bit) installed on my 64-bit Windows operating system (Windows 8), and I have installed all of the R packages needed for baseline correction (baseline, ptw, hyperSpec, gplot, rJava, Rserve, etc.) I am using R version 3.2.3 and Java version 1.8.0_73 (64 bit). I get this error message whenever I try to use the "Baseline Correction" command under "Filtering" under the Raw Data Methods menu. I've reprinted the log messages from the MZmine console window below (this is for MZmine 2.18.2 -- the most recent version of MZmine however does the same thing.)

Looking at your message boards I see someone had a similar problem previously but in their case it was fixed as soon as they downloaded version 2.18.2 (which at that time was the most current version). I'm using 2.18.2 and more recent versions -- and yet I still have this problem.

Any idea what might be wrong?

![image](https://cloud.githubusercontent.com/assets/17245205/13041867/0e55c57e-d370-11e5-9bc9-2b4be5b8ac5a.png)

**Comment by jlparkI** [comment]
I think that last image was a little small...here's an expanded copy...

![image](https://cloud.githubusercontent.com/assets/17245205/13041879/35c75f32-d370-11e5-93db-807dfd992167.png)

**Comment by golgauth** [comment]
Hi,

Usually, I would not recommand using version of R later than R 3.2.2, because some features we use (mainly xcms R package) are not yet compatible with this version. But since the one you use (ptw) does not depend on xcms, my guess would be that your input data (chromatogram) are not satisfaying for R asysm in some ways. Anyway, could you join a sample such that I can reproduce the issue and see what is going on. 

Thanks

**Comment by jlparkI** [comment]
One of the files I have tried is attached as a zipped netCDF file. If you have trouble opening it please let me know. Also in case it's worth mentioning...I tried cropping the file based on retention time to
[Background.zip](https://github.com/mzmine/mzmine2/files/130857/Background.zip)
 RT 2.00, 21, in case the empty regions before/after the divert valve opened were affecting the baseline correction function, and that didn't help either. I've tried loading the file either as mzXML or as netCDF and either way seems to make no difference.

Thanks.

**Comment by tomas-pluskal** [comment]
Gauthier @golgauth ,

There is now a native java version of the ptw package through the Renjin project:
http://packages.renjin.org/package/org.renjin.cran/ptw

How about trying that?

**Comment by golgauth** [comment]
Yep, why not, but @jlparkI mentions in his very first message that the program fails, no matter which algorithm is chosen for the baseline module, so the issue has theoretically to intervene before that. I'll give a try with the provided sample in the evening.

**Comment by jlparkI** [comment]
BTW, I don't know if this helps, but...I tried deleting R from my system and reinstalling R3.2.2 in case that was the problem, and -- no change, doesn't seem to have helped...

**Comment by golgauth** [comment]
Well, I corrected baseline successfully by cropping (3.0 < RT < 21.0), then applying asymmetric corrector (no use of m/z  bins, params: smoothing=10, asymmetry=0.001). I also tried with no preliminary crop + m/z bins of size 1.0, same params. It worked fine. Have you, by any chance, the possibility to test this on another machine?

**Comment by golgauth** [comment]
Tomas @tomas-pluskal ,

You may be right. May be we could add kind of a fallback system that would compute a baseline (using Java only) when R or Rserve fails. I don't know. You've been monitoring the user's feedback all along: Would you say that the baseline R based features are reliable, or not so much? Do we often have issues with this?

**Comment by golgauth** [comment]
One last remark: you error backtrace mentions a Background**.mzXML** file and the file you provided in attachment is a **.cdf**. Why that? Did you do any conversion? With which app?

Conversion algorithm can , sometimes, introduce small differences. Could you provide the real original .mzXML with which the error was generated and/or confirm that you get the same error with the .cdf? Thanks.

**Comment by dyrlund** [comment]
I also have no problem running the baseline correction module on the **Background.cdf** file on a Windows 10 64-bit system with MZmine 2.19, R 3.2.3 and Java 1.8.0_66 (64-bit).

**Comment by jlparkI** [comment]
I tried with both netcdf and mzxml files and both gave me the same error; I uploaded the netcdf file since it was smaller, so I thought it would be easier to download. I tried both in case it was a problem with a specific file type. I use ProteoWizard for file conversions.

Since this works on your computer, however, I'm starting to wonder whether this could be a machine-specific issue. I have a Mac I may be able to try this on -- let me try this later and see if it runs ok there.

**Comment by golgauth** [comment]
Some of my users noticed some issues with baseline correction. Like you some samples were properly processed on certain machine and not on some other. In our case this was a very restricted case: a few samples, and only while using the `RubberBand Algorithm`. So I am not sure this has to do with the issue you are experiencing. And I don't know if this is OS related or processor related, or else. Anyway, I'm on it, but this can take some time...

**Comment by dyrlund** [comment]
@jlparkI Have you had a chance to try the baseline filtering on the above file as suggested by Gauthier?

**Comment by MarcosAlvarez** [comment]
Hello   Was this problem ever resolved?  I am observing the exact same symptoms  and could not make the test file work.  Please advise.
