### ISSUE TITLE
Proposal for new feature: "Round Resampling filter"...

### ISSUE THREAD

**Issue by golgauth** [mzmine/mzmine2#207]
I recently had an issue with building chromatogram with data which were very unpredicatable in their m/z dimension (ions where not at all dispatched properly every unit ion value): 

![selection_096](https://cloud.githubusercontent.com/assets/5875064/13053453/da383b06-d404-11e5-8862-e71becc23183.png)

Here we see that two DataPoint are competing for the same ion... Leading to very complicated and very eavy Chromatograms (chromatogram builder taking for ever, and result we can't anything with).

Since in GC/MS we like to have datapoints/ions on exact unit, I wrote a resampler that does it:

![selection_098](https://cloud.githubusercontent.com/assets/5875064/13053601/a249e9dc-d405-11e5-9498-b673c08cf170.png)

How it works: 

* If two DataPoint are competing for the same ion, we try to shift one of them to previous or to the next unit, in case  there is not a Datapoint at this place already.
* If shifting is not an option, the user parameter "Sum duplicates intensities" is used to merge (or not if unchecked) or sum the datapoint intesity at this point, leading to:

![selection_099](https://cloud.githubusercontent.com/assets/5875064/13053696/1dc238bc-d406-11e5-9da8-f84ff8aa0ec7.png)

Anyway, this is something very useful to my biologist colleagues, would you like to have it MZmine master trunk? Do I create a Pull Request?

Feel free to ask for more information on how this works.

Best
Gauthier

**Comment by tomas-pluskal** [comment]
Hi Gauthier, 

I think this is a useful feature for the master branch, please submit it. Please make sure it comes with a help file where the algorithm is explained. 

Does it take centroid or profile spectra as input, or both?

**Comment by golgauth** [comment]
The `profile spectra` case is not yet covered. Is this a problem?

**Comment by tomas-pluskal** [comment]
The plot you showed above shows a profile spectrum (continuous line), or not?

If the method works only for centroid spectra, please specify that clearly in the help file.

**Comment by golgauth** [comment]
Well, the continuous line is a weird behavior of the viewer. It is displayed as a discrete signal when opening the TIC visualizer, then clicking the right arrow button to shift the scan number turns to a line... But this is definitely centroid. Frankly I do not know what a profile spectra would imply, I never worked with that kind of spectrum. Applied on a profile spectrum, the algorithm results in a centroid spectrum with values every unit, but I don't know if this gives a correct answer to the subject. We should probably be converting from profile to centroid or something. Is there any MZmine feature that already does this? May be the best approach would be that I submit my centroid version proposal first, then you comment on it, we discuss about that and I add what is missing to have it properly implemented for both profile and centroid.

**Comment by tomas-pluskal** [comment]
Sounds good.

**Comment by golgauth** [comment]
OK. I guess the "Sum duplicates intensities", is not applicable to non-centroid spectrum as-is. I also suppose converting from profile to centroid requires `local minima` search, or equivalent. Well, let's see it together soon.

**Comment by golgauth** [comment]
Hi all,

First attempt here: #214 
Thanks for testing.
