### ISSUE TITLE
Peaklist row "RT start" & "RT end" parameters not preserved w/ project saving

### ISSUE THREAD

**Issue by photocyte** [mzmine/mzmine2#210]
Hi there,

If a peaklist is saved in a MZmine project, and then reopened (from the saved project), it appears that the "RT start" & "RT end" variables of a given peaklist row are set to the minimum & maximum possible RT times (presumably from the raw file), instead of to their original values before project saving.

MZMine2: 2.1.9
Mac OS X 10.11.3

**Comment by tomas-pluskal** [comment]
Should be fixed now
