### ISSUE TITLE
MainWindow repaint & Healess mode

### ISSUE THREAD

**Issue by golgauth** [mzmine/mzmine2#220]
Hi T(h)omas(es)

Shouldn't we have:

    // Repaint the window to reflect the change in the peak list
    // (Only if not in "headless" mode)
    Desktop desktop = MZmineCore.getDesktop();
    if (!(desktop instanceof HeadLessDesktop))
        desktop.getMainWindow().repaint();

instead of:

    // Repaint the window to reflect the change in the peak list.
    MZmineCore.getDesktop().getMainWindow().repaint();

in most of the identification search tasks:

* https://github.com/mzmine/mzmine2/blob/master/src/main/java/net/sf/mzmine/modules/peaklistmethods/identification/adductsearch/AdductSearchTask.java#L115
* https://github.com/mzmine/mzmine2/blob/master/src/main/java/net/sf/mzmine/modules/peaklistmethods/identification/camera/CameraSearchTask.java#L167
* ...

I can pull a request, if you agree.
Can you confirm that those tasks will fail in headless mode. I am unsure because I would be surprised that no one reported this before, but since `getMainWindow()` returns `null` in headless mode, I would be also surprised if we do not get a `NullPointerException` while running those tasks.

Thanks
Gauthier

**Comment by tomas-pluskal** [comment]
Hi Gauthier,

I think you are right. Can you submit the pull request?

Thanks!

Tomas

**Comment by golgauth** [comment]
Right away, Sir! ;)
