### ISSUE TITLE
Typo in documentation 

### ISSUE THREAD

**Issue by Tebatu** [mzmine/mzmine2#222]
In Chromatogram Deconvolution Wavelet:
*Tatenhahn* instead of *Tautenhahn* in the first paragraph

**Comment by tomas-pluskal** [comment]
Would you like to fix this via a pull request?

**Comment by Tebatu** [comment]
Hi Tomas,
I will love to contribute to this cool project, but I am very fresh to Github and still need to build up my skills. 
I will study for a couple of days and do it.

Greetings

**Comment by tomas-pluskal** [comment]
Hi,
Github has a nice tutorial for its workflow: https://guides.github.com/introduction/flow/
Tomas
