### ISSUE TITLE
integration in inspector

### ISSUE THREAD

**Issue by ypriverol** [mzmine/mzmine2#228]
@tomas-pluskal Would be possible to reuse some of your components for 2D and 3D visualization into PRIDE Inspector. What would be the license implications?

**Comment by tomas-pluskal** [comment]
In principle, I have no problem with that. MZmine is GPL. What is the license of PRIDE inspector?

**Comment by ypriverol** [comment]
Inspector is Apache 2. I guess if you use some of the components your license will **Override** our liecense?

**Comment by tomas-pluskal** [comment]
Yeah, well, who cares, it's open source anyway.
If you tell me which classes you need, I can give those classes to you under Apache license, since I am the author. If there are other authors, we can ask them, but should be no problem.

**Comment by ypriverol** [comment]
Fantastic @tomas-pluskal . Would you maybe interested to do the integration? We can write a paper around after that or open some kind collaboration? I guess would be more easy that if I go through your classes. I aim something like the attachement. 

<img width="1202" alt="screen shot 2016-03-17 at 14 13 56" src="https://cloud.githubusercontent.com/assets/52113/13860338/af8100b2-ec7f-11e5-97c6-ad5fa364c0b8.png">

**Comment by tomas-pluskal** [comment]
Nice try, but no thank you.. I am already swamped with my own projects, and in my free time I want to work on getting MZmine 3 ready.

By the way, MZmine 3 will be JavaFX-based. Not sure what your plans are with PRIDE Inspector, but I am very happy about the design of JavaFX in comparison to Swing.

**Comment by ypriverol** [comment]
We don't want to do a big refactoring with inspector right now. In contrast we would like to add new simple functionalities that our users are looking for it. I know JavaFX is really good compare with Swing. I have used for other projects. 

About this functionality to show the 2D and 3D maps. Can you point me to the classes and panels in mzmine 2 that will allow me to implement this in Inspector.

**Comment by tomas-pluskal** [comment]
Sure, you can find all the code here:
https://github.com/mzmine/mzmine2/tree/master/src/main/java/net/sf/mzmine/modules/visualization/twod
https://github.com/mzmine/mzmine2/tree/master/src/main/java/net/sf/mzmine/modules/visualization/threed
