### ISSUE TITLE
Related Peak Finder (A Mathematical Approach) (Suggestion not an issue)

### ISSUE THREAD

**Issue by Leperkhan** [mzmine/mzmine2#232]
It'd be great if MZmine incorporated a tool that would be able group peaks (tag them) simply by their similarity in shape and retention time (RT). My research involves doing large-scale untargeted metabolomics and there are lot of unknown peaks that have several related peaks (i.e. complexes, adducts and fragments). Using just the M/Z value to identify the related peaks is too reliant on knowing how the compound fragments. However, if a peak could be related to other peaks by just using intensity and RT and grouped (tagged in the comment) then one peak of a given target m/z could be used to represent the compound and be tracked in multiple samples. Or better yet--all the peaks of the group could be summed and be used to represent the compound. I'll be working on making a simple program that will do this, but it'll take me awhile because I'm a novice programmer.

**Comment by dyrlund** [comment]
Isn't this similar to what the CAMERA algorithm does?

**Comment by Leperkhan** [comment]
I think you may be right, I haven't used CAMERA before. I know exactly what I would like it to do, so I'll try it out and get back to you. Thanks!

**Comment by dyrlund** [comment]
@Leperkhan Have you had a chance to look at the CAMERA algorithm?
