### ISSUE TITLE
MZmine 2.20 not starting

### ISSUE THREAD

**Issue by naa93** [mzmine/mzmine2#234]
I keep getting this error message when I try to start MZmine, I have downloaded the latest version of Java and I'm not sure what could be wrong. 

<img width="564" alt="screen shot 2016-04-14 at 10 21 41 am" src="https://cloud.githubusercontent.com/assets/18468610/14537349/730cc85c-022b-11e6-8f49-980d087f7475.png">

**Comment by tomas-pluskal** [comment]
Try installing the latest JDK (not JRE). It usually helps.
