### ISSUE TITLE
Mac start-up script doesn't work if only a JRE is installed

### ISSUE THREAD

**Issue by TDI-tenderholt** [mzmine/mzmine2#235]
As reported to me by a user of the PeakInvestigator fork of MZmine, the Mac launch script does not work if there aren't any JDKs installed.

The problem seems to be related to ```/usr/libexec/java_home``` only finding JDKs. Once a JDK has been installed, MZmine does correctly launch.

**Comment by tomas-pluskal** [comment]
You are right. It seems the JRE installs to 
````/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java```` 
and is completely ignored by ````/usr/libexec/java_home````. How stupid.
I will update the startMZmine command to try the default JRE location if the java_home command fails.

**Comment by TDI-tenderholt** [comment]
FYI, this is the solution I came up with: https://github.com/Veritomyx/mzmine2/commit/6fc389a423903774c7a1be3cd338ed72b1918b3d

**Comment by tomas-pluskal** [comment]
Added in PR #239.
