### ISSUE TITLE
Feature Request: Peak zoom in Peak Shape window

### ISSUE THREAD

**Issue by chemnerd1** [mzmine/mzmine2#237]
For all our LCMS runs I double check the peak quality for aligned features by browsing the peak shape window; however, this is difficult for longer runs since the peaks are zoomed out. It would be very helpful if there was an option to be able to adjust the Peak Shape window zoom to be something like  +/- 1 minute of the retention time for the row. That way I can see detail in the peak without needing to do an XIC for the row.

Thanks!

**Comment by tomas-pluskal** [comment]
Hi. Honestly, it is quite meaningless to post feature requests here. If you want to have the feature, please implement it (or ask/hire someone to do it for you) and send us the code.
