### ISSUE TITLE
I can't run mzmine on  my mac

### ISSUE THREAD

**Issue by marylos** [mzmine/mzmine2#241]
Your MZmine version: 2.20
Your OS version: 64-bit
I don't know how to reach the "log page" after opening the OS X command with .txt

Thanks!

**Comment by tomas-pluskal** [comment]
Try installing the latest Java JDK (not JRE) and see if it helps.
If it does not, you will need to provide more information.

**Comment by marylos** [comment]
Thank you very much! It worked! Once I installed java I had also to restart the macbook to make it operative.
