### ISSUE TITLE
Masslynx import

### ISSUE THREAD

**Issue by sargelavoie** [mzmine/mzmine2#242]
I tried to import a raw masslynx datafile acquired with a Waters QDa mass detector. The file contain three function, an ESI+, an ESI-, and a UV pda. At about half the import process, the following error message is displayed:

Error of task Opening file D:\ [...] \SL08135I.raw: java.io.IOException: Generic Error (NativeFileReadTask.java:208)

Maybe it is related to the fact that a UV trace is present. If this is the case, MZMine should have the capability to detect this type of trace and simply reject it.

_**MZMine version**: 2.20
**OS version**: Windows 10 64-bit
**java -version output**: java version "1.8.0_91"
            Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
            Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
**R**: not installed_

**Comment by tomas-pluskal** [comment]
Hi, 
This bug was reported before in the MZmine Google Group. I will fix it, just need to find some time.
It would be great if you could generate a minimal raw file (size below 1 MB) with only a few scans, that still shows this error. We could add that file to our test set.

**Comment by tomas-pluskal** [comment]
Hi,
I believe I have a fix for this bug. Could you test it for me?

**Comment by sargelavoie** [comment]
Yes, no problem! Is it already compiled?

**Comment by tomas-pluskal** [comment]
Try using this build: https://www.dropbox.com/s/g4qr09atltdxzie/MZmine-2.21.zip?dl=0

**Comment by Jinjun-Hou** [comment]
I have tried the new software, it could open the raw data of waters ,but it could't distinguish different functions, all the signal would be appear on the TIC.

**Comment by tomas-pluskal** [comment]
You can use the scan selector in the TIC dialog to select only scans of a particular function

**Comment by Jinjun-Hou** [comment]
Thank you , it works ,but if it could distinguish different functions, i could use the neutrol loss analysis.
