### ISSUE TITLE
mzmine 2-RANSAC aligner has a bug?

### ISSUE THREAD

**Issue by KSNIOO** [mzmine/mzmine2#245]
Dear mzmine programmer and users,
I am using mzmine to analyze GC-MS data. For the alignment of the deconvoluted peaks per sample I am using the RANSAC aligner at the end as I read it should be more precise as the Join aligner. However, when I repeat the aligning with RANSAC with same settings and same samples I always obtain always different results in terms of different final numbers of row of aligned peaks. That of course also affect the statistical analysis afterwards. Therefore, I was wondering why this problem appears and how it can be prevented. The join aligner always gives out consistent results in terms of number of rows with aligned peaks regardless how often I repeat the aligning.

I hope that you can help me with this issue. Thus, I am looking forward to getting feedback soon.

Kind regards,
Kristin

**Comment by tomas-pluskal** [comment]
Hi Kristin,

The RANSAC algorithm is by definition non-deterministic, because it runs in iterations, starting from a random alignment. Sandra @SandraCastilloPriego, who wrote the method, can provide more details if you need.

Tomas

**Comment by KSNIOO** [comment]
Dear Tomas,
Thank you for your response regarding my question to the RANSAC alignment. I will contact then Sandra to get further information about the RANSAC aligner.

Have nice week!

Cheers,
Kristin


*******************************************


PhD student
Microbial Ecology Department
Netherlands Institute of Ecology (NIOO-KNAW)
Droevendaalsesteeg 10
6708 PB Wageningen

k.schulz@nioo.knaw.nl<mailto:k.schulz@nioo.knaw.nl>
Tel: 0031-317-473-505

****************************************************************
