### ISSUE TITLE
Very slow chromatogram building on Mzmine using Masshunter Mzxml files

### ISSUE THREAD

**Issue by kebbasabally** [mzmine/mzmine2#247]
I am a new user of mzmine for metabolomics analysis of digested colored
potato varieties. The LC-MS data (40min run) was acquired using Agilent
 Masshunter software which was converted into MzxmL files for processing on
 Mzmine.
 I started processing five files, however the chromatography builder stage is
 very slow and was not completed in 24hrs only 6% completion
[Screen shot slides.pptx](https://github.com/mzmine/mzmine2/files/305711/Screen.shot.slides.pptx)
. I aborted the process and started
to process one sample. Chromatogram builder stage was even slower with one
 sample.
 My computer is new with 16GB and 1 Terabite.

Any suggestions on how to process my data better or fast
Tools Used.
1.	Mzmine 2.20
2.	OS version 64 bits
3.	Java version 1.8.0_91
4.	R version 3.3.0 (2016-05-03)
5.	No settings were change

**Comment by tomas-pluskal** [comment]
Hi,

Everything depends on how you set the parameters. If the chromatogram builder is running too slow, you probably set the noise level too low during mass detection. Use the previews and read the help files to optimize the parameter values.

If you want a better advice, you'll have to send your mzXML file and list the exact parameter values you used in each step.

Tomas

**Comment by kebbasabally** [comment]
Hi Tomas,

Thanks very much, appreciated.  I will send you my data files and settings
tomorrow from my desktop.

Regards,

Kebba
