### ISSUE TITLE
Error of task Detecting chromatograms

### ISSUE THREAD

**Issue by UMG-Metabolomics** [mzmine/mzmine2#252]
mzMINE Version: 2.21
OS: 64 bit Windows

Hello,
i am a beginner using mzMine 2. 
I imported some .raw Files that where saved from Waters Masslynx 4.1. I used a XEVO G2S-QTof in negative Mode, MS/MS.
After importing raw Files i detected masses and if i want to build chromatogramms the following error ocurrs.
"Retention time of scan #2563 is smaller then the retention time of the previous scan. Please make sure you only use scans with increasing retention times. You can restrict the scan numbers in the parameters, or you can use the Crop filter module"

I just tried to change the parameter MS-level to 2. Now i dont get the error anymore. But the peaklist is empty.
It would be great if you can help me. Thank you.

[16:25:29|FINEST|MainMenu]: Setting parameters for module Chromatogram builder
[16:25:32|FINEST|MainMenu]: Starting module Chromatogram builder with parameters
 Raw data files: 20160627_ZWS_neg-keine-Pl-1.raw, Scans: net.sf.mzmine.parameter
s.parametertypes.selectors.ScanSelection@6812f5b4, Mass list: massdetection, Min
 time span (min): 0.01, Min height: 100.0, m/z tolerance: 0.005 m/z or 5.0 ppm,
Suffix: chromatograms
[16:25:32|FINEST|TaskQueue]: Adding task "Detecting chromatograms in 20160627_ZW
S_neg-keine-Pl-1.raw" to the task controller queue
[16:25:32|INFO|WorkerThread]: Starting processing of task Detecting chromatogram
s in 20160627_ZWS_neg-keine-Pl-1.raw
[16:25:32|INFO|ChromatogramBuilderTask]: Started chromatogram builder on 2016062
7_ZWS_neg-keine-Pl-1.raw
[16:25:32|SEVERE|WorkerThread]: Error of task Detecting chromatograms in 2016062
7_ZWS_neg-keine-Pl-1.raw: Retention time of scan #2563 is smaller then the reten
tion time of the previous scan. Please make sure you only use scans with increas
ing retention times. You can restrict the scan numbers in the parameters, or you
 can use the Crop filter module
[16:33:46|FINEST|MainMenu]: Setting parameters for module Chromatogram builder
[16:33:50|FINEST|MainMenu]: Starting module Chromatogram builder with parameters
 Raw data files: 20160627_ZWS_neg-keine-Pl-1.raw, Scans: net.sf.mzmine.parameter
s.parametertypes.selectors.ScanSelection@1bfdf7a5, Mass list: massdetection, Min
 time span (min): 0.01, Min height: 100.0, m/z tolerance: 0.005 m/z or 5.0 ppm,
Suffix: chromatograms
[16:33:50|FINEST|TaskQueue]: Adding task "Detecting chromatograms in 20160627_ZW
S_neg-keine-Pl-1.raw" to the task controller queue
[16:33:50|INFO|WorkerThread]: Starting processing of task Detecting chromatogram
s in 20160627_ZWS_neg-keine-Pl-1.raw
[16:33:50|INFO|ChromatogramBuilderTask]: Started chromatogram builder on 2016062
7_ZWS_neg-keine-Pl-1.raw
[16:33:50|INFO|ChromatogramBuilderTask]: Finished chromatogram builder on 201606
27_ZWS_neg-keine-Pl-1.raw
[16:33:50|INFO|WorkerThread]: Processing of task Detecting chromatograms in 2016
0627_ZWS_neg-keine-Pl-1.raw done, status FINISHED

**Comment by tomas-pluskal** [comment]
Hi,
Waters files typically contain several MS functions, and when you open the file in MZmine, the scans will be ordered as all scans of function 1, followed by all scans of function 2, followed by all scans of function 3, etc. Note that "lock mass" is one of the ms functions.
You can unroll the file in the tree to see all scans

![screen shot 2016-07-07 at 19 20 39](https://cloud.githubusercontent.com/assets/1796692/16672971/ef5b20be-4477-11e6-8b87-3cfa75a7651c.png)

Then you can use the crop filter to select only the scans of a single function - use the "Scan definition" field of the "Scans" filter. By cropping only the scans you want, you will be able to run the Chromatogram builder. 

You can also select the scans in the setup of the Chromatogram builder, but cropping is probably better.

**Comment by UMG-Metabolomics** [comment]
Thank you. You helped me a lot ! 
So i actually have #1-2562 MS1 c- and #2563-5180 MS1 c-. Is it a good idea to crop first the spectrums of 1-2562 then 2563-5180 and generate seperated chromatograms although they came from the same raw file ?

P.S.: Thank you for offering your Software mzmine for free. It is a very good alternative to expansive Softwares for me. You done a great job !

**Comment by tomas-pluskal** [comment]
If the name is same, I guess you can use the scan number to distinguish them.
MZmine cannot do it automatically. Feel free to write a new module for MZmine to do that :)
