### ISSUE TITLE
Minor window display inconvenience

### ISSUE THREAD

**Issue by Leperkhan** [mzmine/mzmine2#254]
MZmine 2.21
Windows 7 64-bit
Java version "1.8.0_91"
R version "3.2.4"

Decided that I'll mention this just in case someone has a quick fix. 
From a Peak list I right-click on a row, and do an operation, the resulting new window (i.e. XIC (base peak) (quick)) always displays quickly and goes behind the Peak list that I have open. When you do this a few thousand times it gets pretty annoying always clicking the taskbar and selecting the newly created window. Since I have multiple monitors, I can drag the newly created window to a separate monitor from the Peak list, and from then on the new windows will display on the new monitor. However, when I'm working on my laptop with a single monitor this can be quite annoying. Any suggestions or fixes?

**Comment by tomas-pluskal** [comment]
Please check if it still happens with MZmine 2.22.
Also, I would recommend updating Java to the latest version first.
