### ISSUE TITLE
Setting up eclipse to run GitHub

### ISSUE THREAD

**Issue by Leperkhan** [mzmine/mzmine2#255]
So I have been trying to import my Git Repository to MZmine into Eclipse, but once I have it loaded as a Java project it has a lot of errors. 

![image](https://cloud.githubusercontent.com/assets/16259557/17383487/ff3f2354-598a-11e6-9519-c2573a64f6bd.png)

Is there any easy way to fix this so I can run it with the IDE? I'm not much of a programmer, but I'm really interested in seeing if there's a way to add an easy manual integration that you can select from the peak lists. 

Thanks,

Nate Sullivan

**Comment by dyrlund** [comment]
Did you follow the following guide?
https://mzmine.github.io/eclipse_tutorial.html

**Comment by Leperkhan** [comment]
No, I did not. Thanks Thomas! You and Tomas are always on top of everything.
