### ISSUE TITLE
Heap size memory

### ISSUE THREAD

**Issue by Titan100** [mzmine/mzmine2#256]
Hello,
I was running mzMine 2.0 to process my data. During filtering step (SG method), I got error message that says "heap size space error". Is that the memory issue? Shall I increase the memory size on the sofware? My file size is 10GB. Please suggest me to get the things done smoothly. I thing my heap size space is 1024 or something around that.

Thank you

**Comment by tomas-pluskal** [comment]
Please follow the "How to report problems" section of the manual.

Tomas
