### ISSUE TITLE
MZmine startup error

### ISSUE THREAD

**Issue by grfxmunkey** [mzmine/mzmine2#258]
I've downloaded MZmine v2.21 and 2.20.  I have a 64-bit system and was running 32-bit Java, so I've used the uninstall tool to replace with the corrected Java but now I'm getting this error when I try to start MZmine.  I'm on Windows 10.

![image](https://cloud.githubusercontent.com/assets/21205573/17907674/f4c3b19a-694a-11e6-8150-7478eaab329b.png)

**Comment by tomas-pluskal** [comment]
Hi,
My guess is you didn't decompress the downloaded ZIP file and are attempting to start the application from within the ZIP.

**Comment by grfxmunkey** [comment]
I actually did extract the .zip file.  I'm starting MZmine from the
executable that is located in my extracted folder.

**Comment by tomas-pluskal** [comment]
Ok, that is strange.
Could you post screenshots of the contents of your extracted MZmine folder and its subfolders?

**Comment by grfxmunkey** [comment]
[image: Inline image 1]

Your question prompted me to download the zip file again and extract
again.  It works now.  I'm not sure how my subfolders and other information
got wiped out.

Thanks!
