### ISSUE TITLE
How to enlarge the avaliable memory??

### ISSUE THREAD

**Issue by Jiaqc** [mzmine/mzmine2#261]
Hi Friend,

I met a problem in extracting metabolomics data by MZMine. The avaliable memory for MZMine is only about 200M, but the computer's memory is actually 3G. When handling multiple files, the software always corrupts. What can I do to enlarge the avaliable memory?
Thank you for your attention to this problem.

All the best,
Jiaq, Chen

**Comment by tomas-pluskal** [comment]
Make sure you are running a 64-bit OS and 64-bit Java runtime.
Check the messages in the console when MZmine is starting.
