### ISSUE TITLE
Output Bug with Export to CSV File

### ISSUE THREAD

**Issue by jcanderan** [mzmine/mzmine2#263]
I noticed a problem with the .csv output after exporting a csv file of an gap filled aligned peak list.

I run a custom database search on the gap filled aligned peak list. My custom database contains "identity" and "formula" with data containing the field separator used in the csv export (comma), so mzmine attempts to place that data in quotes during the .csv export.

For example, this custom database might have an identity of YYYY-YYY, YYYY_YYYYY and a formula of TASVVCLLNNFYPR#mod(1, 3) for one of the rows. As you can see, they contain commas, which is used as the field separator for the .csv export. 

This works in general, but whenever I have peaks with multiple identifications, it does not quote properly, so Excel does not interpret the columns from the csv export correctly for those rows.

Here is an example line from the .csv file that is outputted:

`28802,1130.0736994062152,69.67789895833332,,7,;,2+#7; 83#0.140600#94.392643;2+#211; 212#6.449514#18.567146,XXXX.csv;XXXX.csv,TPSDKPVAHVVANPQAEGQLQ#mod(5);"NTKVDKKVEPKSCDKTHT#mod(3, 7)","YYYY-YYY, YYYY_YYYYY";"YYYY-YY, YYYY-YY",1.1369752188842744E7,5573012.42727437,1.0901196113238941E8,1.1843432135501438E8,8.873141410748288E7,1163836.9898568874,9.66278138400916E7,7.040880743330976E7,`

The problem lies with the quoting when there are multiple identifications. In this case, the first line below is the "Molecular formula" column and the second line is the "Name" column:

TPSDKPVAHVVANPQAEGQLQ#mod(5);"NTKVDKKVEPKSCDKTHT#mod(3, 7)"
"YYYY-YYY, YYYY_YYYYY";"YYYY-YY, YYYY-YY"

In order for those columns to be interpreted correctly when opening in Excel, the entire section needs to be quoted, as in:

"TPSDKPVAHVVANPQAEGQLQ#mod(5);NTKVDKKVEPKSCDKTHT#mod(3, 7)"
"YYYY-YYY, YYYY_YYYYY;YYYY-YY, YYYY-YY"

mzmine 2.21
Windows 64 bit
java 1.8.0_112

If you need any other information, let me know.

Thank you for your efforts.

**Comment by tomas-pluskal** [comment]
Thanks for reporting. 
I fixed this (I believe) in this commit:
https://github.com/mzmine/mzmine2/commit/ee772c18dffd82ffeac7b03896372e0aa90cdacf

**Comment by tomas-pluskal** [comment]
I'm going to release MZmine 2.22, so please test if it fixed the problem for you.

**Comment by jcanderan** [comment]
Looks good. Thanks a lot for your work!
