### ISSUE TITLE
Batch export of MS2 as .mgf files (file)

### ISSUE THREAD

**Issue by oolonek** [mzmine/mzmine2#265]
The possibility to batch export MS/MS data associated to peaks in the peaklist would be amazing !
Ideally, desired additional fields (Molecular formula, Identification) could be selected and added to the mgf header.

Thank you for the attention,

PM

**Comment by tomas-pluskal** [comment]
Hi,

Feel free to contribute - the beauty of open source :)

Tomas

**Comment by oolonek** [comment]
Yep. Just let the suggestion here (since it's linked from the "Suggestions and feature requests" section of the Mzmine website) for people with abilities to code for mzMine (not my case ...)

Best.

PM
