### ISSUE TITLE
Problem when connecting to a SSL postgresql server

### ISSUE THREAD

**Issue by lcguida** [mzmine/mzmine2#266]
Hello, 

When trying to export tables to a PostgreSQL server that uses SSL, I'm facing this error:

```
SSL error java.lang. runtimeexception: could not generate DH repair
```

Reading on the internet, I found that Java has a problem with SSL keys when they have more than 2048 bits. 

Any tips on how I could make this work? Maybe re-compile Mzmine with a newer version of Java (Im currently using JRE 1.8) ?

**Comment by tomas-pluskal** [comment]
I don't think you need to recompile MZmine. 
Try installing the newest JDK (8u112) from http://www.oracle.com/technetwork/java/javase/downloads/index.html and it might fix the problem.

**Comment by lcguida** [comment]
Updated Java. Seems to work. Thanks.
