### ISSUE TITLE
Visualization in batch mode?

### ISSUE THREAD

**Issue by ndpendant** [mzmine/mzmine2#267]
Hello, 

I was wondering if there was a way to export any of the visualization and data analysis modules via batch mode? I noticed that they are imported via .xml and some have similar parameters to other batch export modules.   

i.e XML export
batchstep method="net.sf.mzmine.modules.peaklistmethods.io.xmlexport.XMLExportModule"
parameter name="Peak lists" type="BATCH_LAST_PEAKLISTS"
parameter name="Filename"  blah   parameter
parameter name="Compressed file"  false    parameter
 /batchstep

your assistance is greatly appreciated

**Comment by tomas-pluskal** [comment]
Hi,

The plots are interactive, you can export them into image files manually but not via the batch mode.
