### ISSUE TITLE
Error of task Detecting chromatograms

### ISSUE THREAD

**Issue by 442953882** [mzmine/mzmine2#268]
Work environment:
Window 7 professional
32-bit operating system
4GB installed memory
Java: version 8 Update 91
R version 3.3.2

I have tried to perform Chromatogram builder but gave me the error:Scan…… does not have a mass list masses MS1.But I have performed Mass detection.Please let me know if anything I have missed.

Thanks.
![img_20161221_235554](https://cloud.githubusercontent.com/assets/24649335/21396891/b4c4fcde-c7dc-11e6-9b12-3b88cd5a5968.jpg)
![img_20161222_001735](https://cloud.githubusercontent.com/assets/24649335/21396892/b4c6f4bc-c7dc-11e6-915e-8dc3f963b98b.jpg)

**Comment by tomas-pluskal** [comment]
Hi,

The error message says scan number 99 does not have the mass list. In your second screenshot I can see that scans 1, 2, and 3 do have it, but what if you unroll scan number 99?
Perhaps you performed mass detection only on a subset of scans?
