### ISSUE TITLE
Formula prediction

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#269]
The Identification>Formula prediction method assigns the formulas in the order as they are generated (which is quite unpredictable). It would be better to sort them first and then select the one with the lowest mass error or best isotope pattern match.

**Comment by tomas-pluskal** [comment]
Hi Anja,
Use both the relative (ppm) and absolute (Da) tolerances. For example, if you set the window to "4ppm or 0.001 Da", the maximum of each value will always be used. That means for larger masses, the 4ppm will be used, while for small masses (where 4 ppm becomes too narrow), the 0.001 Da tolerance will be used. I think that will solve your issue.

**Comment by anja-lauer** [comment]
It worked! Thank you so much :D

**Comment by bruggemann-tropos** [comment]
Hello Tomas,

coming back to the initial idea of this thread:

> The Identification>Formula prediction method assigns the formulas in the order as they are generated (which is quite unpredictable). It would be better to sort them first and then select the one with the lowest mass error or best isotope pattern match.

Is the current version of MZmine still following this procedure? This would explain some strange assignments in my dataset.

Best wishes,
Martin

**Comment by tomas-pluskal** [comment]
Hi Martin,
Yes, MZmine still follows the same procedure.,

**Comment by tomas-pluskal** [comment]
Now fixed!
