### ISSUE TITLE
HPC Issue

### ISSUE THREAD

**Issue by kb238** [mzmine/mzmine2#272]
I have installed MZmine on a high performance computing system, but upon opening the software I received this error:

$ module load mzmine/2.23
$ startMZmine_Linux.sh 
Checking physical memory size...
Found 128725 MB memory
Java maximum heap size set to 126677 MB
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Error: Could not find or load main class net.sf.mzmine.main.MZmineCore

The software is installed to /opt/apps/mzmine/2.23.

**Comment by tomas-pluskal** [comment]
are really **all** the files in /opt/apps/mzmine/2.23?
have you tried starting it from /opt/apps/mzmine/2.23?

**Comment by kb238** [comment]
Yes, the software is there:

$ ls -l /opt/apps/mzmine/2.23/
total 720
-rw-r--r-- 1 root root    496 Dec 12 14:01 DEVELOPMENT.txt
-rw-r--r-- 1 root root  15148 Dec 12 14:01 LICENSE.txt
-rw-r--r-- 1 root root 652525 Dec 12 14:01 manual.pdf
-rw-r--r-- 1 root root  31260 Dec 12 14:01 mzmine-eclipse-code-formater.xml
-rw-r--r-- 1 root root  10955 Dec 12 14:01 pom.xml
-rw-r--r-- 1 root root   2006 Dec 12 14:01 README.md
drwxr-xr-x 4 root root   4096 Dec 12 14:01 src

Running the software from that directory gives the same error (same for going into the src directory) and wouldn't be much of a fix anyway. I mentioned CLASSPATH because what environment modules do is simply change environment variables which you load or unload the module. Right now this module only adds /opt/apps/mzmine/2.23/src/main/scripts to PATH. Since the software is saying it can't find its main class, I'm guessing we need to set CLASSPATH to wherever that is.

**Comment by tomas-pluskal** [comment]
Apparently, you downloaded the source codes, not the compiled software.

**Comment by kb238** [comment]
Okay, I downloaded the correct files. Everything is working now. Thanks!
