### ISSUE TITLE
Rserve download

### ISSUE THREAD

**Issue by acetogen1** [mzmine/mzmine2#273]
Hi,
I can't get the baseline algorithm to work at all.  The command window shows that MZmine 2.23 is looking for a website in France (http://cran.irsn.fr/...) and not finding the program.  I downloaded version 2.15 from a mirror site in the US but MZmine cannot find it. BTW, MZmine can find the location of the version of R (R-3.2.2) but not Rserve.  Without the baseline correction the package is not very useful.  Do you know what the issue could be?

**Comment by tomas-pluskal** [comment]
Did you install the required R packages as described in the manual?

**Comment by acetogen1** [comment]
The issue appears to be solved.  I re-installed R3.2.2 and then used an R command window (win7 x64) to add the packages using the install.packages command.  However I have not installed the other ones such as XCMS, Camera and PROcess.  Would I need those too?  I used the USA(CA) mirror site.  Thanks.
