### ISSUE TITLE
Centroid scans within profile data

### ISSUE THREAD

**Issue by acetogen1** [mzmine/mzmine2#274]
Hi,
I am working with ABSciex data files (*.wiff).  When I convert them with MSConvert into mzXML or mzML I do get a strange result in MZmine2 (ver 3.23).  Most of the scans look identical to what the Analyst software (ver 1.6) shows for that file, but a few, in an apparent random pattern, show being Centroidal.  More strange is that using SeeMS all three versions of the experiment file (wiff, mzXML and mzML) show all the scans as Profile (the experiment was acquired in profile mode), so I have to conclude that is something with either the installation or the version of mzmine2.  I also tried the MS Data Converter from AB Sciex and got the same outcome.  I am attaching the original wiff file for your perusal.  I am eager to hear whether it worked on your end.  Best regards. 
[Sigma-250-1.zip](https://github.com/mzmine/mzmine2/files/758959/Sigma-250-1.zip)

**Comment by tomas-pluskal** [comment]
Hi.
MZmine uses its own auto-detection to determine whether each scan is centroided or profile. The auto-detection is not perfect, though. That is not a big problem, though - data processing methods do not take this into account, and in the spectrum visualizer you can always switch the profile/centroid mode using the upper right corner toolbar button.

Could you send me your file in mzML format? I can add it to our set of tests.

**Comment by acetogen1** [comment]
Thanks for the prompt response,
What is interesting is that it is always the same scans that display the centroidal display.  Please see the attached mzML generated from the ABSciex Converter.  if I recall the scans in question are 4,5,108,117,124 and so one.  Also since these data were acquired in low resolution mode (~0.7 Da using a triple quad) what is the best method for mass selection, chromatogram construction and deconvolution that you would recommend?
Best regards, 
[Sigma-250-1-ABSCIEX.zip](https://github.com/mzmine/mzmine2/files/759490/Sigma-250-1-ABSCIEX.zip)

**Comment by tomas-pluskal** [comment]
Thanks for sending the file. 
Sorry but I do not have the capacity at the moment to give advice on parameter settings.. Try using the embedded previews to determine optimal parameters.
