### ISSUE TITLE
Exporting MS/MS Pattern to SQL database

### ISSUE THREAD

**Issue by Gxwen** [mzmine/mzmine2#276]
Hi everyone,
I am trying to export data to a MySQL database using a local server (Wamp 3.0.6) in order to process MS/MS paterns later on. 
To do so I use the export method : PeakListMethods/Export/ExportToMySQLDatabase. 
I use this jdbc connection string : jdbc:mysql://localhost/dbname?user=root
I try to export 3 columns including the ID (INT), m/z (DOUBLE) and MS/MS pattern (BLOB) and I get this error : 
"Error running SQL query:
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Le champ 'column3' ne peut être vide (null)" (translation : the field 'columns3' cannot be empty (null))
So I was wondering if it was really possible to export MS/MS patterns in an MySQL database.
Thanks in advance =)
Gxwen

**Comment by tomas-pluskal** [comment]
Hi. Not all peaks will have MS/MS patterns. I suppose you created your table with a NOT NULL constraint and that's why you are seeing this error. Try to modify the structure of the mysql table to allow NULL values in column3.

**Comment by Gxwen** [comment]
Hi again. So I tried to allow Null values for the MS/MS column and it worked ! When I export the peak list, the error is no longer here but every entry in the column3 (MS/MS) is NULL witch is now the default value.
And I know the majority of them should have a MS/MS pattern !
Any idea ?

**Comment by tomas-pluskal** [comment]
I cannot give you any answer unless I see the project file.

Check if you can open the MS/MS spectra from the peak list view in MZmine (right mouse click -> Show -> MS/MS spectrum)

**Comment by Gxwen** [comment]
Yes I can do that, I am able to see them all.

**Comment by tomas-pluskal** [comment]
https://github.com/mzmine/mzmine2/blob/master/src/main/java/net/sf/mzmine/modules/peaklistmethods/io/sqlexport/SQLExportTask.java#L303

**Comment by tomas-pluskal** [comment]
The method assumes you have a mass list on the MS/MS scans. It does not export the complete scan, but it exports the mass list instead. This is because the MS/MS scans might be in profile mode, which is typically not what you want to export. Try running the raw data methods -> peak detection -> mass detection on your MS/MS scans first.

**Comment by Gxwen** [comment]
Ok I know for sure that the MS/MS scan are not in profile mode but in centroid mode.
After running the peak detection first the result is the same.

**Comment by tomas-pluskal** [comment]
Hmm, now that I look at the code, it seems it takes the mass list name from the configuration dialog column "Export value", but that value is hardcoded to BLOB when you select the MS/MS column.

That is obviously a bug. But I think it should still work if you run the mass detector again and set the Mass list name to BLOB. 

After running the mass detector, you should be able to open (unroll) the individual scans in the project tree and see the mass list there, as shown below:

<img width="328" alt="screen shot 2017-02-13 at 12 31 58" src="https://cloud.githubusercontent.com/assets/1796692/22894864/8704319e-f1e8-11e6-8241-9d6eba679f35.png">

**Comment by Gxwen** [comment]
Ok, this works just fine ! I am able to see BLOBs when there is one.
![capture](https://cloud.githubusercontent.com/assets/25747076/22920465/77ead53e-f295-11e6-829c-91084b6bdc70.PNG)

I can't realy read Java code but I guess the BLOB is containing a list, do you know by any chance how to access it ? Or should I be looking for this in MySQL forums ?

Anyway, thanks a lot for your answer =)
And nice job with your program !

**Comment by tomas-pluskal** [comment]
The BLOB contains binary data (m/z and intensity pairs). You cannot view it directly from the database.

**Comment by Gxwen** [comment]
Hi Tomas, I'm comming back to you because I've been trying to read the .bin files but I can't manage to find a way of getting the data out of it. I'm not familiar with binary language but I manage to read theses files as binary files using python but I can only get access to the different bytes. I couldn't find a way of converting thess bytes into the m/z and intensity pairs.
Is there a specific way of doing it ?
Thanks, 
Gwendal

**Comment by tomas-pluskal** [comment]
Hi,

Take a look at the export code: https://github.com/mzmine/mzmine2/blob/master/src/main/java/net/sf/mzmine/util/ScanUtils.java#L562

The data points are encoded from the java 'double' type into bytes. The double type in Java is a 64-bit IEEE 754 floating point number (https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html), so each m/z value will take 8 bytes followed by 8 bytes intensity value. 
Java uses Big-endian byte order (https://en.wikipedia.org/wiki/Endianness#Big).

I guess this will help you in Python: https://docs.python.org/3.4/library/struct.html

**Comment by Gxwen** [comment]
Ok that's the information I was missing !
Thanks a lot for your help, I think I can close the subject.
