### ISSUE TITLE
PUBchem issues

### ISSUE THREAD

**Issue by bidaw262626** [mzmine/mzmine2#277]
Your MZmine version : Mzmine 2.23
Your OS version - 64-bit
The exact output of the following two commands:
java -version : 1.8.0_66_b36, hotspot 25.66-b36
R --version: 3.3.2
![image](https://cloud.githubusercontent.com/assets/26263557/23684773/c4d08904-036e-11e7-82c1-b431c57b973d.png)

The exact steps you took until you encountered the problem. When searching peaks using Pubchem, KEGG and other librairies work fine

Thank you

**Comment by tomas-pluskal** [comment]
Thanks for reporting. 
I fixed this in commit https://github.com/mzmine/mzmine2/commit/47f002dc89a7165c6a3f9ad0e4ecbfb9387f6614

It will be fixed in next version of MZmine.

**Comment by bidaw262626** [comment]
Thanks Tomás 

Pascal
