### ISSUE TITLE
Getting Information Raw files

### ISSUE THREAD

**Issue by Fiona-dym** [mzmine/mzmine2#279]
Hi Tomas,
Could MZmine 2 directly export the instrument detected charge information in Xcalibur raw files? Just like Xcalibur labels. If yes, which method implements this function? Does it rely on the .dll document of MSFileReader? 
If I want to use MZmine 2 for my software, how could I get the .jar file for MZmine 2? 

Best regards!
Aimee

**Comment by tomas-pluskal** [comment]
Hi Aimee,

MZmine has its own charge detection method, so we don't use the information provided by Xcalibur.

MZmine jar file is of course included in each MZmine release, just download the ZIP distribution.

Best,

Tomas
