### ISSUE TITLE
Keep or remove rows parameter in peak list rows filter not correctly recognised when read from a batch file

### ISSUE THREAD

**Issue by chrisbarlow79** [mzmine/mzmine2#285]
If a batch file contains a "Peak list rows filter" step (such as in the attached file) when loaded in MZmine and run it will throw an error saying that "Keep or remove rows is not set properly".  If the batch is immediately saved as new file the Keep or remove rows parameter is indeed blank, eg:  
`        <parameter name="Keep or remove rows"/>`

So it looks like MZmine is failing to read the Keep or remove rows paramter.

[Peak list rows filter example.txt](https://github.com/mzmine/mzmine2/files/895284/Peak.list.rows.filter.example.txt)
`

**Comment by tomas-pluskal** [comment]
Thanks for reporting. I just committed a fix.

**Comment by chrisbarlow79** [comment]
Thanks Tomas,
Much appreciated.
