### ISSUE TITLE
Export to CSV drops identity elements

### ISSUE THREAD

**Issue by benbowen** [mzmine/mzmine2#289]
When I load and run a batch list of tasks, the parameters "Identification method" and "Name" are dropped.

![image](https://cloud.githubusercontent.com/assets/810953/24961446/a1c876a6-1f4d-11e7-952b-cb86564deec9.png)

If an aligned peak list in in the workspace that has those attributes then the options are available.

![image](https://cloud.githubusercontent.com/assets/810953/24961339/58966d26-1f4d-11e7-934f-422191f0f43f.png)

**Comment by tomas-pluskal** [comment]
Hi,
that is because the list is populated using the data that you have currently in the project. If you start with an empty project, the only option that is available is "All identity elements". It's not really a bug, although I agree it could be designed better. I won't have time to redesign this in near future (contributions are welcome).

**Comment by benbowen** [comment]
I understand, but "All identity elements" doesn't contain anything but
delimiters.

**Comment by tomas-pluskal** [comment]
Really? Ok, I'll take a look at it :)

**Comment by benbowen** [comment]
Thanks, I'm doing isotope, cluster, adduct identification on per-file peak
lists prior to joining.

**Comment by tomas-pluskal** [comment]
I fixed this issue by removing the parameter completely (https://github.com/mzmine/mzmine2/commit/eac53f945c5fd7adab4a231f8497c7eb3850b451).

Try downloading the latest build from here and let me know if it works for you:
https://www.dropbox.com/s/24wd2a2ff2ew2di/MZmine-2.24.zip?dl=0

**Comment by benbowen** [comment]
Very nice.  

To the "Export common elements" block, I added:

```
    <item>Export row identity</item>
```

I removed the "Export identity elements" block completely:

```
    <parameter name="Export identity elements">
      <item>All identity elements</item>
      <item>Identification method</item>
      <item>Name</item>
    </parameter>
```

and it looks good to me.  

Many thanks,@tomas-pluskal , for you hard work!
