### ISSUE TITLE
HOW TO SPECIFY INTERNAL STANDARD

### ISSUE THREAD

**Issue by Algoric** [mzmine/mzmine2#291]
Dear MZmine,

Please advise on procedure for carrying out normalisation by ratio to standard compound area
I followed steps as per below but unable to specify the standard peak satisfactorily – ERROR no internal standards peaks selected

MZ v 2.23MP1
OS win7 32bit
Java 8.0.910.14
R 3.1.0

Select aligned peak list
Select peak list methods\normalisation\standard compound normaliser
Nearest standard
m/z vs RT balance 1
add

Yours sincerely, Algoric

![image](https://cloud.githubusercontent.com/assets/19595262/25012675/282fc624-2069-11e7-903d-c75f58f5db0d.png)

**Comment by tomas-pluskal** [comment]
Are you sure your peak list contains a peak within the parameters you defined (ID7..67 etc)?
This peak must be detected (or gap-filled) in all samples, otherwise it cannot be used for normalization.

**Comment by Algoric** [comment]
Many thanks for reply and advice, normalisation by IS now achieved.

Algoric
