### ISSUE TITLE
Adding modules for MGF export of LC-MS/MS data for GNPS and Sirius, and a new filter to keep only features with MS/MS

### ISSUE THREAD

**Issue by lfnothias** [mzmine/mzmine2#300]
Hi Tomas,
Just to let you know that the DorresteinLab "bioinformatic squad" has been working on preparing MZmine modules to export LC-MS/MS features as MGF that can be processed with GNPS (http://gnps.ucsd.edu), and with Sirius (https://bio.informatik.uni-jena.de/software/sirius/).
In addition, we created a new filter that keep only features with MS/MS spectrum associated.
The branch is currently being consolidated on our side and we will submit the pull request within couple of days. 
Louis-Felix

**Comment by tomas-pluskal** [comment]
Hi Louis-Felix,

I'm glad to hear that! Actually, I was planning to release a new MZmine version later this week. Should I wait for your additions, so they can be included in MZmine 2.25?

Best,

Tomas

**Comment by lfnothias** [comment]
Sure. We just pulled a request. [here](https://github.com/mzmine/mzmine2/pull/301)
Please modify as the request as suitable, and let us know if there is any changes needed.

**Comment by tomas-pluskal** [comment]
FYI, I just release v. 2.25 that includes your modules. Please let me know if you find any problem.

**Comment by lfnothias** [comment]
Thanks a lot Tomas !
