### ISSUE TITLE
Problems when opening a project with Mzmin 2.26

### ISSUE THREAD

**Issue by leonie74** [mzmine/mzmine2#304]
Hey,

I am running Mzmine on a 64bits processor with 8Go VM, and the latest version of Java 8 131. I did all the steps till gap filling with no problem, unfortunately, when I try to open a previously saved project, it is bugging at 33%. 
I also had a message saying that java platform SE binary stopped running. 

I tried many times to install java again and tried with mzmine 2.24, but it is still not opening . 

Any body aready had this problem ? 

Thanks

**Comment by tomas-pluskal** [comment]
For start, please follow the instructions here: http://mzmine.github.io/support.html

**Comment by leonie74** [comment]
Thanks, I already followed thoses instructions ....

**Comment by tomas-pluskal** [comment]
Really? The "How to report issues" paragraph clearly gives 6 points that you should include. In your message I can only see MZmine version (point 2), nothing else.

**Comment by leonie74** [comment]
1. MZ mine version 2.24, 2.25, 2.26 
2. 64 bits ( 8Go VM)
3. Java 8 131 
R x64 3.4.0
4. 
![image](https://cloud.githubusercontent.com/assets/28785814/26316977/4f074c06-3f16-11e7-9127-af6555655d47.png)
5 . ![image](https://cloud.githubusercontent.com/assets/28785814/26316984/56bb119e-3f16-11e7-80bb-b9c87130f60a.png)

6. After opening my mzXML data, I just did a Grid mass putting the following parameters and it is bugging after about 30 % processing 

![image](https://cloud.githubusercontent.com/assets/28785814/26317131/c0056460-3f16-11e7-982f-03d28b96433d.png)

Thanks ! 
Leonie

**Comment by tomas-pluskal** [comment]
Hi Leonie,

Could you please clarify what OS you are running - I am not familiar with anything called "8Go VM".
Also, I would like to have the complete log output, not just the last few lines.

How much RAM does your system have?
