### ISSUE TITLE
MZMINE2 EOC Identification

### ISSUE THREAD

**Issue by Livoirien** [mzmine/mzmine2#305]
Hello 

I’m a PhD student working on the occurrence of emerging organic contaminants (pharmaceuticals, pesticides ad residues) in ground water samples collected from an alluvial aquifer used for water supply. The contaminants are planned to be extracted from the samples using solid-phase extraction, and a LC-ESI-MS/MS QTRAP 3200 will be used for screening.
However, our library contains only 30 compounds which results in a poor identification capacity.  I discovered your tool and wonder if libraries implemennted, as massbank, could be help me ? 

Thanks

**Comment by tomas-pluskal** [comment]
Sorry, this question is too general, you'll have to try and see for yourself.
