### ISSUE TITLE
Error when running minimal batch files

### ISSUE THREAD

**Issue by rrawle** [mzmine/mzmine2#308]
Hello,

I am trying to run a batch mode that opens a previously saved project and performs another step. For example: 

Open project (project has raw files imported and masses detected)
Chromatogram builder
Save project as

When I do it this way, it will not complete and errors saying that I need a file selected. No matter which option I choose ('As selected in main window', 'All raw files', etc.) I can never get the operation to follow through, including the save as at the end. Is there a way to do a step at a time, or must they always be run together? I have run an entire batch file with no problems, but when I try to separate the steps I have issues. 

Thank you!

**Comment by tomas-pluskal** [comment]
Hi,
Can you send the batch xml file?
Are you running the batch from the GUI or from command line?
What MZmine version?

**Comment by rrawle** [comment]
Thank you for your quick response. 

I am using MZmine version 2.25, and I've tried running the batch from both the GUI and from command line.

Here is my batch file that does not work. 
[chromatograms_batch_file.txt](https://github.com/mzmine/mzmine2/files/1043055/chromatograms_batch_file.txt)

This one, on the other hand, does work. It works when the batch includes opening the raw files, but just not work from opening a project (even though the raw files are in it). 
[mass-detect_batch_file.txt](https://github.com/mzmine/mzmine2/files/1043056/mass-detect_batch_file.txt)

**Comment by tomas-pluskal** [comment]
OK, I think I found the problem... It should be fixed in next release
