### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by hale94** [mzmine/mzmine2#315]
The new version (2.26) no longer has the "export identity elements" options in the export to CSV file function.  Can you add these options back?  Is there a way to export these elements to a CSV file?

Thanks,

John

**Comment by tomas-pluskal** [comment]
Hi,
I removed the selection list because virtually no one was using it and it created issues in batch mode etc. You can still export the peak identity by selecting the "Export row identity" option in "Export common elements"

**Comment by hale94** [comment]
Is there a way to export the ID column from the custom db search?  I include several parameters in this column (ie RT, ppm error) that I can extract after export.  The current export to CSV function does not have an option to export this column.

 

Thanks,

 

John

**Comment by tomas-pluskal** [comment]
You're right, there is no way to export that currently.

Tomas
