### ISSUE TITLE
V2.26 peaklist not visible in 2D visualizer 

### ISSUE THREAD

**Issue by Gregor90** [mzmine/mzmine2#318]
Hello,

I updated my MZmine2 version from 2.23 to 2.26 and encountered a bug. 
When I create a (targeted) peaklist, I cannot visualize them (as green lines) in the 2D visualizer as I've done in the versions before. I made sure that the peaklist is not empty, and also the button "Toggle displaying of data points in continous mode" didn't change anything. 

Kind regards,

Gregor

**Comment by tomas-pluskal** [comment]
Hi Gregor,

Can you send your project file?

Tomas

**Comment by Gregor90** [comment]
Hi Tomas,

The mzML file itself has 360MB. Where should I upload it?

Gregor

2017-06-20 13:39 GMT+02:00 Tomáš Pluskal <notifications@github.com>:

> Hi Gregor,
>
> Can you send your project file?
>
> Tomas
>
>

**Comment by tomas-pluskal** [comment]
Whereever you like.

Tomas

**Comment by Gregor90** [comment]
Hi Tomas,

Here is the Dropbox Link:
https://www.dropbox.com/sh/ltq7fd8urc3upv7/AACzqXWYE65RnOiTASL2SJ5Aa?dl=0

If I use the V2.23, everything works fine with this sample, in the V2.26
however, I can't visualize the peaks as green lines in the 2D plot.

Gregor

2017-06-20 13:50 GMT+02:00 Tomáš Pluskal <notifications@github.com>:

> Whereever you like.
>
> Tomas
>
>

**Comment by tomas-pluskal** [comment]
Hi Gregor,

I would like you to upload the MZmine project file, not the raw data.

Best,

Tomas

**Comment by Gregor90** [comment]
Hi Tomas,

I'm sorry. I never save my files as projects and didn't exactely knew what
you meant. I hope I uploaded the correct file now.

Gregor

2017-06-20 14:29 GMT+02:00 Tomáš Pluskal <notifications@github.com>:

**Comment by tomas-pluskal** [comment]
Hi Gregor,

I fixed the bug, it should work fine in the next MZmine release.

Tomas
