### ISSUE TITLE
Parsing Thermo raw file

### ISSUE THREAD

**Issue by AimeeD90** [mzmine/mzmine2#324]
Hello there,
I am wondering whether mzmine2 could directly be used as an API to parse Thermo's raw file. As we all know, this work can only be done by means of Xcalibur  of MSFileReader. If avaliable, which class or method in mzmine2 could I use to parse this type of file. It will be pretty good if you could give me some sample codes.

Best regards,
Aimee Deng

**Comment by tomas-pluskal** [comment]
Hi Aimee,
You can use the corresponding MSDK (http://msdk.github.io) module: http://msdk.github.io/api/io/github/msdk/io/nativeformats/ThermoRawImportMethod.html
