### ISSUE TITLE
MZmine: After Smoothing Peak Area is Less Than Peak Height

### ISSUE THREAD

**Issue by jeremykoelmel** [mzmine/mzmine2#328]
MZmine version: 2.26
OS version - 64 bit
Java: 1.8.0_101

Error: Values for peak areas are less than those for peak heights after smoothing (smoothing: 15).
Procedure: Take any MZmine workflow and you final aligned peak list. Apply smoothing level 15. Look at peak heights versus peak areas. 
![aftersmoothing](https://user-images.githubusercontent.com/30200700/28241412-dcf0b0dc-6961-11e7-9fff-9d322c3a6bf8.PNG)

Here are the values before smoothing the aligned peak list:
![beforesmoothing](https://user-images.githubusercontent.com/30200700/28241433-351e2226-6962-11e7-91ac-1b5dc0389a51.PNG)

Here is an EIC showing the first row in the previous 2 images:
![eic](https://user-images.githubusercontent.com/30200700/28241522-0d2fab2a-6964-11e7-9ff0-33802ebbe987.PNG)

I think this is a problem with any aligned peak list with smoothing after as I have tried multiple MZmine workflows and obtained the same strange result. Unless you would expect peak area to ever be lower than peak height?

Here is my batch file for one workflow where I saw this problem:

<?xml version="1.0" encoding="UTF-8"?>
<batch>
    <batchstep method="net.sf.mzmine.modules.rawdatamethods.peakpicking.massdetection.MassDetectionModule">
        <parameter name="Raw data files" type="GUI_SELECTED_FILES"/>
        <parameter name="Scans">
            <ms_level>1</ms_level>
        </parameter>
        <parameter name="Mass detector" selected="Centroid">
            <module name="Centroid">
                <parameter name="Noise level">5000.0</parameter>
            </module>
            <module name="Exact mass">
                <parameter name="Noise level">10000.0</parameter>
            </module>
            <module name="Local maxima">
                <parameter name="Noise level"/>
            </module>
            <module name="Recursive threshold">
                <parameter name="Noise level"/>
                <parameter name="Min m/z peak width"/>
                <parameter name="Max m/z peak width"/>
            </module>
            <module name="Wavelet transform">
                <parameter name="Noise level"/>
                <parameter name="Scale level"/>
                <parameter name="Wavelet window size (%)"/>
            </module>
        </parameter>
        <parameter name="Mass list name">masses</parameter>
        <parameter name="CDF Filename (optional)" selected="false"/>
    </batchstep>
    <batchstep method="net.sf.mzmine.modules.rawdatamethods.peakpicking.targetedpeakdetection.TargetedPeakDetectionModule">
        <parameter name="Raw data files" type="GUI_SELECTED_FILES"/>
        <parameter name="Name suffix">detectedPeak</parameter>
        <parameter name="Peak list file">C:\Users\Sieve\Documents\JeremyKoelmel\MZmineSRM1950\Input\1950_Pos_Targeted.csv</parameter>
        <parameter name="Field separator">,</parameter>
        <parameter name="Ignore first line">false</parameter>
        <parameter name="Intensity tolerance">1.0</parameter>
        <parameter name="Noise level">10000.0</parameter>
        <parameter name="m/z tolerance">
            <absolutetolerance>0.005</absolutetolerance>
            <ppmtolerance>10.0</ppmtolerance>
        </parameter>
        <parameter name="Retention time tolerance" type="absolute">0.1</parameter>
    </batchstep>
    <batchstep method="net.sf.mzmine.modules.peaklistmethods.peakpicking.deconvolution.DeconvolutionModule">
        <parameter name="Peak lists" type="BATCH_LAST_PEAKLISTS"/>
        <parameter name="Suffix">deconvoluted</parameter>
        <parameter name="Algorithm" selected="Local minimum search">
            <module name="Baseline cut-off">
                <parameter name="Min peak height"/>
                <parameter name="Peak duration range (min)">
                    <min>0.0</min>
                    <max>10.0</max>
                </parameter>
                <parameter name="Baseline level"/>
            </module>
            <module name="Noise amplitude">
                <parameter name="Min peak height"/>
                <parameter name="Peak duration range (min)">
                    <min>0.0</min>
                    <max>10.0</max>
                </parameter>
                <parameter name="Amplitude of noise"/>
            </module>
            <module name="Savitzky-Golay">
                <parameter name="Min peak height"/>
                <parameter name="Peak duration range (min)">
                    <min>0.0</min>
                    <max>10.0</max>
                </parameter>
                <parameter name="Derivative threshold level"/>
            </module>
            <module name="Local minimum search">
                <parameter name="Chromatographic threshold">0.2</parameter>
                <parameter name="Search minimum in RT range (min)">0.1</parameter>
                <parameter name="Minimum relative height">0.2</parameter>
                <parameter name="Minimum absolute height">10000.0</parameter>
                <parameter name="Min ratio of peak top/edge">1.3</parameter>
                <parameter name="Peak duration range (min)">
                    <min>0.05</min>
                    <max>1.2</max>
                </parameter>
            </module>
            <module name="Wavelets (XCMS)">
                <parameter name="S/N threshold">10.0</parameter>
                <parameter name="Wavelet scales">
                    <min>0.25</min>
                    <max>5.0</max>
                </parameter>
                <parameter name="Peak duration range">
                    <min>0.0</min>
                    <max>10.0</max>
                </parameter>
                <parameter name="Peak integration method">Use smoothed data</parameter>
            </module>
            <module name="Wavelets (ADAP)">
                <parameter name="S/N threshold">10.0</parameter>
                <parameter name="S/N estimator">
                    <module name="Intensity window SN"/>
                    <module name="Wavelet Coeff. SN">
                        <parameter name="Peak width mult.">3.0</parameter>
                        <parameter name="abs(wavelet coeffs.)">true</parameter>
                    </module>
                </parameter>
                <parameter name="min feature height">10.0</parameter>
                <parameter name="coefficient/area threshold">110.0</parameter>
                <parameter name="Peak duration range">
                    <min>0.0</min>
                    <max>10.0</max>
                </parameter>
                <parameter name="RT wavelet range">
                    <min>0.01</min>
                    <max>0.1</max>
                </parameter>
            </module>
        </parameter>
        <parameter name="Remove original peak list">false</parameter>
    </batchstep>
    <batchstep method="net.sf.mzmine.modules.peaklistmethods.alignment.join.JoinAlignerModule">
        <parameter name="Peak lists" type="BATCH_LAST_PEAKLISTS"/>
        <parameter name="Peak list name">Aligned peak list</parameter>
        <parameter name="m/z tolerance">
            <absolutetolerance>0.005</absolutetolerance>
            <ppmtolerance>10.0</ppmtolerance>
        </parameter>
        <parameter name="Weight for m/z">20.0</parameter>
        <parameter name="Retention time tolerance" type="absolute">0.1</parameter>
        <parameter name="Weight for RT">20.0</parameter>
        <parameter name="Require same charge state">false</parameter>
        <parameter name="Require same ID">false</parameter>
        <parameter name="Compare isotope pattern" selected="false">
            <parameter name="Isotope m/z tolerance">
                <absolutetolerance>0.001</absolutetolerance>
                <ppmtolerance>5.0</ppmtolerance>
            </parameter>
            <parameter name="Minimum absolute intensity"/>
            <parameter name="Minimum score"/>
        </parameter>
    </batchstep>
    <batchstep method="net.sf.mzmine.modules.peaklistmethods.filtering.rowsfilter.RowsFilterModule">
        <parameter name="Peak lists" type="BATCH_LAST_PEAKLISTS"/>
        <parameter name="Name suffix">filtered</parameter>
        <parameter name="Minimum peaks in a row" selected="false">30.0</parameter>
        <parameter name="Minimum peaks in an isotope pattern" selected="false"/>
        <parameter name="m/z" selected="true">
            <min>0.0</min>
            <max>80.0</max>
        </parameter>
        <parameter name="Retention time" selected="false">
            <min>0.7</min>
            <max>17.0</max>
        </parameter>
        <parameter name="Peak duration range" selected="false">
            <min>0.0</min>
            <max>10.0</max>
        </parameter>
        <parameter name="Parameter">No parameters defined</parameter>
        <parameter name="Only identified?">false</parameter>
        <parameter name="Text in identity" selected="false"/>
        <parameter name="Text in comment" selected="false"/>
        <parameter name="Keep or remove rows">Remove rows that match all criteria</parameter>
        <parameter name="Keep only peaks with MS2 scan (GNPS)"/>
        <parameter name="Reset the peak number ID"/>
        <parameter name="Remove source peak list after filtering">false</parameter>
    </batchstep>
    <batchstep method="net.sf.mzmine.modules.peaklistmethods.filtering.duplicatefilter.DuplicateFilterModule">
        <parameter name="Peak lists" type="BATCH_LAST_PEAKLISTS"/>
        <parameter name="Name suffix">filtered</parameter>
        <parameter name="m/z tolerance">
            <absolutetolerance>0.005</absolutetolerance>
            <ppmtolerance>15.0</ppmtolerance>
        </parameter>
        <parameter name="RT tolerance" type="absolute">0.12</parameter>
        <parameter name="Require same identification">false</parameter>
        <parameter name="Remove original peaklist">true</parameter>
    </batchstep>
    <batchstep method="net.sf.mzmine.modules.peaklistmethods.gapfilling.samerange.SameRangeGapFillerModule">
        <parameter name="Peak lists" type="BATCH_LAST_PEAKLISTS"/>
        <parameter name="Name suffix">gap-filled</parameter>
        <parameter name="m/z tolerance">
            <absolutetolerance>0.005</absolutetolerance>
            <ppmtolerance>15.0</ppmtolerance>
        </parameter>
        <parameter name="Remove original peak list">true</parameter>
    </batchstep>
    <batchstep method="net.sf.mzmine.modules.peaklistmethods.gapfilling.peakfinder.PeakFinderModule">
        <parameter name="Peak lists" type="BATCH_LAST_PEAKLISTS"/>
        <parameter name="Name suffix">gap-filled</parameter>
        <parameter name="Intensity tolerance">1.0</parameter>
        <parameter name="m/z tolerance">
            <absolutetolerance>0.005</absolutetolerance>
            <ppmtolerance>15.0</ppmtolerance>
        </parameter>
        <parameter name="Retention time tolerance" type="absolute">0.1</parameter>
        <parameter name="RT correction">false</parameter>
        <parameter name="Remove original peak list">true</parameter>
    </batchstep>
    <batchstep method="net.sf.mzmine.modules.peaklistmethods.filtering.duplicatefilter.DuplicateFilterModule">
        <parameter name="Peak lists" type="BATCH_LAST_PEAKLISTS"/>
        <parameter name="Name suffix">filtered</parameter>
        <parameter name="m/z tolerance">
            <absolutetolerance>0.005</absolutetolerance>
            <ppmtolerance>15.0</ppmtolerance>
        </parameter>
        <parameter name="RT tolerance" type="absolute">0.12</parameter>
        <parameter name="Require same identification">false</parameter>
        <parameter name="Remove original peaklist">true</parameter>
    </batchstep>
    <batchstep method="net.sf.mzmine.modules.peaklistmethods.peakpicking.smoothing.SmoothingModule">
        <parameter name="Peak lists" type="BATCH_LAST_PEAKLISTS"/>
        <parameter name="Filename suffix">smoothed</parameter>
        <parameter name="Filter width">15</parameter>
        <parameter name="Remove original peak list">false</parameter>
    </batchstep>
</batch>

**Comment by tomas-pluskal** [comment]
Hi,
Could you send your .mzmine project file?

**Comment by jeremykoelmel** [comment]
do you have an email I can send via gmail?

**Comment by tomas-pluskal** [comment]
Best if you upload to dropbox or google drive and paste a download link here

**Comment by jeremykoelmel** [comment]
https://drive.google.com/file/d/0Bw-cmkF0JBBONEJfcDBod0JQVlE/view

Also here are two EICs, one with and one without smoothing, the peak areas were calculated at over a magnitude less after smoothing. Not sure why.
![758_smoothed](https://user-images.githubusercontent.com/30200700/28241682-1a8968b2-6967-11e7-8009-4dd9a2c4fea1.PNG)
![758_notsmoothed](https://user-images.githubusercontent.com/30200700/28241681-1a85d83c-6967-11e7-9cbe-a43b4f39b627.PNG)

**Comment by tomas-pluskal** [comment]
Congratulations, you found a bug!
The fix will be included in MZmine 2.28, which should be released in a few days.

**Comment by jeremykoelmel** [comment]
Thank you Tomas,
I very much appreciate your dedication and enthusiasm to supporting MZmine 2!

**Comment by jeremykoelmel** [comment]
I checked and the issue is resolved. But a new issue occurs where the row ID is reset after smoothing a feature table (you can upload the project file above, smooth the final feature table and see).
Before smoothing:
![image](https://user-images.githubusercontent.com/30200700/28597331-535391de-716b-11e7-8812-f2b1c3a450c0.png)
After Smoothing:
![image](https://user-images.githubusercontent.com/30200700/28597360-6898dcde-716b-11e7-8e40-b4befe2fe969.png)

**Comment by tomas-pluskal** [comment]
Yes, well that is easy to fix.
