### ISSUE TITLE
Can't open raw data

### ISSUE THREAD

**Issue by dani-AR** [mzmine/mzmine2#331]
MZmine version: 2.28
OS: 64 bit

I'm sorry if this isn't clear, I'm not familiar with any of this, so please let me know what other information you need (and how to get there). I was trying to import one of my raw files (from a Waters instrument) and got the following error (see screenshots). I've included a screenshot of the contents of the raw folder, in case that helps. I've consistently gotten this same error for any raw folder I've tried to open, so I'm not sure what's going on. Any help will be appreciated!

![screen shot 2017-07-27 at 9 35 41 am](https://user-images.githubusercontent.com/30500330/28673236-10372b2c-72b0-11e7-94ef-d544d1cf8aec.png)
![screen shot 2017-07-27 at 9 36 03 am](https://user-images.githubusercontent.com/30500330/28673237-1039a32a-72b0-11e7-8f87-54bd08648fbf.png)
![screen shot 2017-07-27 at 9 43 16 am](https://user-images.githubusercontent.com/30500330/28673238-103deebc-72b0-11e7-9539-e43c94ad9f63.png)

**Comment by tomas-pluskal** [comment]
The raw file import only works on Windows. Try converting your files to mzML first.
