### ISSUE TITLE
"Online database searching" errors

### ISSUE THREAD

**Issue by MuyMal** [mzmine/mzmine2#333]
1. When attempting to search PubChem I get the following error: "Could not search PubChem Compound Database: java.io.IOException: javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair (PubChemGateway.java:88)". Has anyone seen this before or know how to remedy it?

2. In the help documentation it says METLIN is one of the online databases available to search, but it is not listed as an option when I hit the dropdown menu to select a database (see screenshot). Do I have to add it somehow? If so, how can I do that?
![screenshot](https://user-images.githubusercontent.com/29641179/28728954-9fa192fa-7398-11e7-8be5-e54a42068b4a.PNG)

System: Windows 7, 64 bit, 4 CPUs; mzmine (2.27), R (3.4.0) and java (7.0.720.14)

Thanks in advance.

**Comment by tomas-pluskal** [comment]
1. See https://github.com/mzmine/mzmine2/issues/297
2. The METLIN database does not support remote access anymore. Feel free to contact them about it.
