### ISSUE TITLE
How to trigger the MS2 scan event for a new mzmine2 user?

### ISSUE THREAD

**Issue by ouyangluman** [mzmine/mzmine2#335]
Hi Tomas,
My MZmine version is 2.28，and my OS is Windows 10 (64-bit),the exact output of the following two commands is java-version. I have imported Waters .raw files then the data is continuous. The parameters of the first Mass detection was set like Fig.1 and Fig.2. The parameters of the first Mass detection was set like Fig.1 and Fig.3.
My question are: 
1. Must I use the batch mode to pre-process my LC-MS data? 
2. Can you tell me where and how to download the following batch method (.XML format)?
**3. How to set an intensity threshold at value corresponding to the triggering of the MS2 scan event？ (I have tried many times. Unfortunately, I still can’t trigger the MS2 scan event and I can’t continue the following steps.)** 
4. What MS level in the set filters should I set after the second mass detection step in the batch queue (like chromatogram builder, Chromatogram deconvolution, isotopic peaks grouper, join aligner and peak finder in the Fig.1). 
Thanks and Thanks all for your works on MZmine.

Best wishes
Olivia
 
tips: Fig.1-3 are shown in the attachment 20170730-help.
[20170730-help.docx](https://github.com/mzmine/mzmine2/files/1185612/20170730-help.docx)

**Comment by lfnothias** [comment]
Hello Olivia, 
I noticed that you referred to the MZmine-GNPS documentation. https://bix-lab.ucsd.edu/display/Public/GNPS+data+analysis+workflow+2.0
1 and 2. It's up to you to use a batch, or indeed simply perform manually the sequence of steps needed. The second option is actually better to optimise parameters if you are not familiar with the workflow. Batch file can be generated in MZmine by going into menu / batch mode, and save the batch.
3. It really depends of your instruments theoretical/real performances and and the method used. 

LF

**Comment by ouyangluman** [comment]
@lfnothias ， thanks for answer.
and now I have two new questions: 
1. how to edit  the startup script (startMZmine_Windows.bat​ script )to use more RAM for MZmine2 ?
2. how to delete the data to release my physical RAM?

**Comment by lfnothias** [comment]
1. Just open the startMZmine_Windows.bat​  and replace the 
HEAP_SIZE=AUTO by HEAP_SIZE=8000MB or the amount needed. 
2. That's good question, and I dont know the answer. @tomas-pluskal should know.

**Comment by tomas-pluskal** [comment]
2. If you remove the raw data files and peak lists from your project in MZmine, the memory will be reclaimed by the Java runtime garbage collector
