### ISSUE TITLE
Little discrepancy when reprocessing the same data with the same batch method

### ISSUE THREAD

**Issue by lfnothias** [mzmine/mzmine2#336]
Hello @tomas-pluskal, 

On Windows 10, with MZmine 2.28.
Following a report from Hendrick Wolff (thanks a lot !) indicating that there is a little discrepancy when reprocessing the same files with the same batch method.
I tried by taking five random files on my computer and processed data with classic alignment batch.

I processed five files with a batch method, four times, and got 846 / 845 / 846 / 845 aligned peaks. The first peak and last are the same for each processing. So, one peak got skipped somewhere for the second and fourth processing.
When applying the MS/MS filter on the aligned table, then number of features differ also, but with no apparent correlation (551 / 549 / 548 / 549 aligned peaks).

So I am wondering if you have an idea where to look to tackle that ?

**Comment by tomas-pluskal** [comment]
It might be just ordering issue - try ordering the peak lists alphabetically before running alignment. 
I assume you are not using the RANSAC aligner (which is non-deterministic by nature).

**Comment by lfnothias** [comment]
Yes no RANSAC aligner. Well, I just tried after sorting the peaklist prior to alignement and it is consistent now 👍 Same number of aligned peaks. True also after the MS/MS filtering.

Is there an easy to control this sorting of peaklists automatically in order to keep data reproducibility in batch mode ? A suggestion could be to implement an option in the alignement step, that can do peaklist sorting prior to alignement processing ?

**Comment by tomas-pluskal** [comment]
There is a batch step for that.

**Comment by lfnothias** [comment]
Nice. Issue solved then. This step is important to add to the batch :)
 Thanks a lot @tomas-pluskal
