### ISSUE TITLE
Alignment of substances with the same mass 

### ISSUE THREAD

**Issue by ptebb** [mzmine/mzmine2#337]
Hello,

i want to use MzMine for LC-MS-Data. In my case we have analyzed ingredients of beer in two different batches. The retention time of the analytes changes between these two batches. Now i want to align the samples. Using the JOIN Aligner and the RANSAC aligner i get good results for most of the analytes. 
But i have some analytes which have exactly the same mass and a similar retention time. 
These analytes are correctly aligned when there where not deconvoluted. But after deconvolution the alignment ist not possible. 
I will put a screenshot of one substance from the first and the second batch as an example for that problem. 
![bp-361](https://user-images.githubusercontent.com/30626987/28867193-85bb36c6-7775-11e7-8d39-fd945433f796.JPG)

Do you have an idea to solve this problem to align the peaks correctly.

Thank you very much and best regards
Peter

Im working with MzMine 2.28, 64-bit System, java version 1.8.0_141-b15.

**Comment by tomas-pluskal** [comment]
Hi Peter. Try using the RT normalization module before performing alignment (after deconvolution). That should adjust the retention times of detected peaks (it won't change the raw data). More details in the module Help.
