### ISSUE TITLE
Exporting detailed CAMERA annotation

### ISSUE THREAD

**Issue by lfnothias** [mzmine/mzmine2#338]
Hello,
I need some help about the CAMERA module. It seems to perform a really good job with isotopic pattern deconvolution and adducts. However, I am not able to export the adducts informations  (which is displayed when putting the mouse on the peak in the peaklist) as .CSV (with all options activated).
Am I looking at the wrong place ?

Thank you for you help

**Comment by tomas-pluskal** [comment]
Can you send your mzmine project so I can take a look?

**Comment by lfnothias** [comment]
Here it is. 
https://drive.google.com/file/d/0B0AWoOmYeeeDV28xUU5Rcy1QMkE/view?usp=sharing

**Comment by tomas-pluskal** [comment]
I see.
Any idea how these should be exported to CSV?

**Comment by lfnothias** [comment]
You mean the export format in the table ?

**Comment by tomas-pluskal** [comment]
Yes. I mean how should the final CSV look like.

**Comment by lfnothias** [comment]
Just an additional column named adducts or camera annotation, and the camera adduct in the row.

**Comment by lfnothias** [comment]
You right. It’s actually fine if the adducts is showing up in the identification column.

**Comment by lfnothias** [comment]
Just to make it clear. It's currently not the case. Actually, the row "identity" and " row comment" shows the name of pseudo-spectrum only.

**Comment by tomas-pluskal** [comment]
So, I updated the CSV export with a selection to export 
- main ID result
- all ID results
- main ID result including all details, in the form of semicolon-separated key:value pairs
I think this should be sufficient to address this issue.

**Comment by lfnothias** [comment]
That's great ! Thanks a lot

**Comment by tomas-pluskal** [comment]
Fixed in version 2.29
