### ISSUE TITLE
MSMS patterns vanish into thin air

### ISSUE THREAD

**Issue by pedrotango** [mzmine/mzmine2#339]
Hi everyone,

I noted that in the latest versions of MZmine 2 (since v25 I guess) I loose a bunch of MSMS patterns associated to my features especially during the Gap filling step. I tested both "Peak Finder" and "Same RT and mz range gap filter" varying all parameters available but it still the same...
So I was wondering if it was possible to afford some kind of "MSMS pattern filling" that could be used at the end of the peak picking process instead of paring the MS2 info at the begenning (during deconvolution).

Many thanks for your help and this amazing tool !

**Comment by tomas-pluskal** [comment]
Hi,
Can you send your .mzmine project file that demonstrates the issue?

**Comment by lfnothias** [comment]
Thank you for the feedback/suggestion.
Before v2.25, MS/MS features were associated to a peak without any retention window (across the all rt range of the sample). As a result, many peaks were showing MS/MS scan that were not corresponding to that molecule, but an other an isomer/isobar (You can check that by looking at the Rt of the MS/MS scan associated to a peak).
I would say that as long as the mass detection step is performed at the correct noise level for (both MS1 and MS2), and the parameters for the MS1/MS2 feature pairing at the deconvolution step are set properly, you will recover all the true paired features.

**Comment by tomas-pluskal** [comment]
@lfnothias What you said is actually not true, the MS/MS spectra were always associated with features within their RT window, even before v. 2.25. Of course, you needed to run the deconvolution mode in order to see it.

**Comment by lfnothias** [comment]
@tomas-pluskal. Ok, my misunderstood. I am glad to know that it was already the case. 
So there is something else at stake in the current issue.
@pedrotango, the best I can tell you is to make sure your noise level at the mass detection steps are low enough. We saw that it was significant. Are you using the MS/MS peaklist row filter in addition ?

**Comment by pedrotango** [comment]
I confirm, the RT were taken into account (except for Gridmass).
Ok, I think I got it! The MS/MS peaklist row filter is not working well on my (all?) gap-filled peak list.

Here is an exemple, MZmine project: https://drive.google.com/open?id=0Bw0KjAbh0eyJYjVHWnZmYTF0dTA
Batch steps: https://drive.google.com/open?id=0Bw0KjAbh0eyJZEVsdXZSdkQ0Z28

My final gap-filled peak list contains only 86 rows after the MSMS peaklist row filter, but if I extract the mgf file for the gapfilled peak list **before** the MSMS peaklist row filter, this file contains actually nearly 600 MS2 spectra!

**Comment by lfnothias** [comment]
That's correct. The bug has been recently addressed by @zhz077, just after 2.28 release.
In the meantime, I would simply suggest not to use that particular filter, or have a look at the GNPS module documentation.

**Comment by pedrotango** [comment]
Ok I'll wait until the next release then!
Many thanks
