### ISSUE TITLE
Unpredictable memory allocation problem and High Performance test and settings.

### ISSUE THREAD

**Issue by dorvan** [mzmine/mzmine2#341]
Hello on a i7-7700K with 64gb ram and nvme + ssd disk,
after process tuning following java virtual machine specification and documentation, 
On a 102 mzxml files elaboration, mzmime after 3 days generates a 48Gb mzmine file.

The elaboration of the generated 48gb mzmine file, to elaborate and interpolate peak lists need to allocate all available assigned system RAM 60gb (HIPE 61440) due not stop process (if the HIPE it's set to 32Gb the process freeze at 32Gb, 20% of total) + 42Gb of swap (on nvme disk at 1.3Gbyte/s)

most of time CPU have a low workload,
at 60+42 Gbyte of computational memory allocatd, slowdown around the 37%

There are some relation/ratio to consider for define resource size looking the input data? 

Thanks.

![isb01](https://user-images.githubusercontent.com/848817/29042567-b34b9c3e-7bb7-11e7-9309-ff75e82a3f95.JPG)
![isb02](https://user-images.githubusercontent.com/848817/29042571-bbb7ed78-7bb7-11e7-8e7b-c76aee2ee5c3.JPG)
![isb03](https://user-images.githubusercontent.com/848817/29042565-b327d88a-7bb7-11e7-88df-0e2f38a3c4e7.JPG)
![isb05](https://user-images.githubusercontent.com/848817/29042597-dd8a5e4a-7bb7-11e7-94ce-2e8df464763a.JPG)

**Comment by dorvan** [comment]
The End.
![isb06](https://user-images.githubusercontent.com/848817/29042746-7cbe3c8e-7bb8-11e7-8bd6-1f2faf39f90c.JPG)

**Comment by tomas-pluskal** [comment]
Hi,
You're likely generating too many features, try increasing the noise level in the mass detection step to reduce the amount of data.

**Comment by dorvan** [comment]
in this 102 files test-case the analysis it's made by 1.0E3 on mzXML sources, and calculation takes 3days and complete successfully, and data it's manageable, but after saving of the project the file resultant it's 48Gb, and anytime we reopen the project file, program stop run at file 37 in alfabethical (not numerical) order. tuning system and java settings crash percentage it's between 22 and 37% always on the same file. (seems a limit), on a full recalculation you can complete analysis. 

I'm an IT man, not a scientific figure, I've recommended, to change approach of analysis if are needed more then 4000-5000 signals, and not around 1000-2000, to make 1.0E3 on a smaller set of data and interpolate smaller sets to obtain the results. But on scientific side seem this is not possible, so... Is this possible? in which way i can recommend to proceed with mzmine? There is something related in the documentation, to operate with a low discretionality on a big set of data, partitioning data sources and results?

il the problem it's like "see the indoor floor atoms of a house from a satellite" and obviously the approach to see atoms directly from satellite it's "wrong" how I can proceed in slicing analysis steps into smaller ones and with different operations, algorithms and interpolate them partially to obtain a single (valid) result in the end?

Thanks in advice.

**Comment by tomas-pluskal** [comment]
Hi, please understand this is open source software, there is no perfect way to do what you want. My advice is to increase the noise level to keep the memory consumption in reasonable limits. Or you can consider contributing to the project and improving the data model.

**Comment by dorvan** [comment]
@tomas-pluskal I know well open software and community principles, and I'm ready to share, like my post, alla use cases and the behaviour I can see using MZmine2 with the systems we use. But 

1. I'm not a Developer, I'm a System Engineer;
2. "Well known performance" settings are not present in documentation, I'm trying myself; 
3. I'm trying to undestand and approach an open source software, new for me, because I need to interact with MZmine.
4. I can provide data and statisctics and what change on settings modifications but I need also some answers, to use data in right way and find (and I hope fix problems)
5. first thing, I see 3 different behaviour of the software on load in 3 calculation steps, and 3 ways to manage the file queue/spooler.

At moment the best settings I have tried are to scale up correctly to a 100 of Load Average without freeze the machine or processes:
(on a 4 core, 8 thread cpu machine, with 64gb ram and nvme disk).

test environment and report about MZmine behaviour.

1. change HIPE to 60gb (61440)

2. set 16 processes in MZmine preferences

3. JAVA_PARAMETERS:
3.1. Original DOES NOT SCALE UP: `"-showversion -classpath lib/\* -Djava.ext.dirs= -XX:+UseG1GC -Djava.io.tmpdir=$TMP_FILE_DIRECTORY -Xms256m -Xmx${HEAP_SIZE}m" `
3.2. Overload: "-showversion -classpath lib/\* -Djava.ext.dirs= -XX:+UseG1GC -Djava.io.tmpdir=$TMP_FILE_DIRECTORY -Xms${HEAP_SIZE}m -Xmx${HEAP_SIZE}m"
3.3 Best Tune for big calculation and scaling: "-showversion -classpath lib/\* -Djava.ext.dirs= -XX:+UseLargePages -XX:+UseParallelOldGC -XX:+UseCompressedOops -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:+UseBiasedLocking -XX:+EliminateLocks -XX:NewSize=16384m -XX:MaxNewSize=16384m -XX:SurvivorRatio=8 -Djava.io.tmpdir=$TMP_FILE_DIRECTORY -Xms${HEAP_SIZE}m -Xmx${HEAP_SIZE}m"

4. Temp Directory: with a 102 file analysis Temp raise up to 7,8 - 10 Gb with a lot of writes. So in our installation Temp it's on SSD (450-650mbyte/s) or NVMe disk (1.3Gbyte/s)

5. Swap: with the test done, on 102 files analysis Swap IT'S NECESSARY, because java forking and MZmine algorithms scale up-to 200% of assigned, this can differ on different operations and calculation steps.
with 64gb ram machine, 3-45gb result used + system ram.

6. MZmine Task Queue Priority. (Damn! only 1:1 change after 1:1 selection!!!) HIGH priority make java processes more reactive and permit memory and CPU to scale up and scale down correctly. This is a more evidence about a problem on task queue elaboration, on change priorities, Task starts in parallel ignoring the maximum number of processes set up in MZmine preferences THIS IS GOOD, because solve the problem about the slow down on single processes when a process end and does not reassign freed CPU and memory to the next process.

7. this setup permit us to move from a 7 days of elaboration to 3 days of elaboration time in a 1.0E3 
then to 3 days to a 5 hours of elaboration time with 1.0E4, 40 minutes with 1.0E5.

8. there are problems about memory allocation and management around the 40% on the Task Queue on a list of 100+ files. there are some errors around 36-38... where 22%-37% (change between operations) it's equal to the 70%-80% of memory workload. A Big (all free almost same Ram size) and Fast (nvme) swap partition and priority change in MZmine Task Queue seems minimize the problem without stopping operations.
