### ISSUE TITLE
backwards compatibility with xml file in batch mode

### ISSUE THREAD

**Issue by ndpendant** [mzmine/mzmine2#342]
Good morning,

I currently have MZmine 2.23 on a linux based platform. In batch mode we are able to save and load the xml file created from each of the different modules. I am working with others that have a later version (2.26). Are the xml files created from the different versions consistent (meaning is there backwards compatibility to use them one on the different versions, of course if modules are available)?

I ask because I noticed changes in modules like the Export to CSV (removal of identification elements).

Thank you for your assistance.

**Comment by tomas-pluskal** [comment]
In general, it should be compatible. If you see any specific issue, please point to it.
