### ISSUE TITLE
No more file in the .conf folder ?

### ISSUE THREAD

**Issue by lfnothias** [mzmine/mzmine2#345]
I noticed that there no more file in the .conf folder !?
And also, I observed that the queue behavior is kind of weird regarding normal and status priority.

**Comment by tomas-pluskal** [comment]
https://sifterapp.com/blog/2012/08/tips-for-effectively-reporting-bugs-and-issues/

**Comment by lfnothias** [comment]
With MZmine2.29. I think, it summarizes pretty well the problem: there are no more conf.xml in the .conf folder. With MZmine2.29. I think some unusual behavior of the queue manager might be related to that.

**Comment by tomas-pluskal** [comment]
Please. Slow down. Describe step by step what you did (after downloading version 2.28) and what you observed.

**Comment by lfnothias** [comment]
I downloaded MZmine2.28. 
I opened the /conf folder.
There, I cannot see the conf.xml file that was previously there.
I am wondering if it is critical. That's why I am acting a bit fast.

**Comment by lfnothias** [comment]
Ok. Problem solved. The conf file got created after starting the software.

**Comment by tomas-pluskal** [comment]
The config.xml file was never part of the downloads (well at least not in the last few years).

**Comment by lfnothias** [comment]
Sorry the disturbance ^^

**Comment by tomas-pluskal** [comment]
No problem :)
