### ISSUE TITLE
MZmine 2.29 (beta) Filtering Peak List Rows Compilation Issues

### ISSUE THREAD

**Issue by abisarvepalli** [mzmine/mzmine2#348]
When attempting to run the "Peak list rows filter", I am confronted with this error:

![screen shot 2017-08-10 at 2 18 23 pm](https://user-images.githubusercontent.com/7587923/29192629-f052f8cc-7dd6-11e7-821a-e345ed2d44b0.png)

**Comment by tomas-pluskal** [comment]
Compilation problems? That's strange. Did you pull the latest sources and could you build the whole source tree from scratch?

**Comment by abisarvepalli** [comment]
I pulled from the latest source as I recently reforked the mzmine2/ master branch. I am running it through eclipse.

**Comment by tomas-pluskal** [comment]
If you run a clean build from eclipse, you get no errors?

**Comment by tomas-pluskal** [comment]
Can I close this issue?
