### ISSUE TITLE
MZmine2 version 2.28 Installation Issue

### ISSUE THREAD

**Issue by yannaa** [mzmine/mzmine2#350]
Hi I am a new user, and  I cannot even open MZmine now...

Here is what I have done: installed java, and R, then downloaded MZmine 2 version 2.28 and unfolded it. Then restarted my laptop, and clicked the "startMZmine_Windows.bat", and a new window popped up, but in a few minutes the window will disappear automatically....In the screenshot, I have laptop OS info., and the  screenshot of the window just moments before it disappeared.... looks like there is no memory or OS system info. These info. is really Greek to me, and hope you guys can help me to fix this. Thank you very much!
![system](https://user-images.githubusercontent.com/30941587/29235810-bde73bac-7ebf-11e7-91d8-6779c907c20b.JPG)
![mzmine issue](https://user-images.githubusercontent.com/30941587/29235811-c0135f46-7ebf-11e7-8170-c199d55af6d3.jpg)

**Comment by yannaa** [comment]
sorry, will disappear in a few seconds, not minutes...lol

**Comment by tomas-pluskal** [comment]
This is not MZmine problem. It seems like something is screwed up with your Windows installation. Try looking here: https://katyscode.wordpress.com/2007/02/03/tutorial-how-to-fix-wmi-corruption/
Or you can edit the startMZmine script and remove the memory detection code and instead set the HEAP_SIZE variable manually
