### ISSUE TITLE
Cannot open .RAW file on linux 64 bit using Wine (windows emulator)

### ISSUE THREAD

**Issue by magnetic111** [mzmine/mzmine2#356]
I installed MZmine 2.28 on Ubuntu (Linux) 16.04.

I am a first time user. I am unable to import the . RAW file using the windows emulator for linux called Wine? Is there anyway around this or will it simply not be possible to do?

Thanks
Chris

**Comment by tomas-pluskal** [comment]
Why don't you convert your files to mzML.

**Comment by ndpendant** [comment]
I tomas, I have a similar issue opening .RAW files on the linux platform.

I am using Ubuntu 14.04, and have attempted to do so on MZmine 2.23-2.28. After installing wine and trying to import i receive the following message:

![raw file error](https://user-images.githubusercontent.com/19844446/29613130-92d2f43a-87d2-11e7-81c8-cbc7a5644238.png)

Is there a specific configuration needed for wine?

Also, it seems like most conversion software doesn't seem so compatible with native files on the linux platform (i.e. msconvert only does so with windows platform).

**Comment by magnetic111** [comment]
Hi guys, so do you think wine needs a specific configuration for
msconverter to work?

**Comment by tomas-pluskal** [comment]
I remember I made it work on linux a while ago, but it took a bit of experimenting with wine.

Try running the ```wine lib/vendor_libs/ThermoRawDump.exe filename``` from the MZmine folder first.

**Comment by magnetic111** [comment]
When I try to import my .RAW Waters folder (containing .STS, .DAT, .IDX,
.SIG, .INF. and .TXT files)  i get the following error.

[image: Inline image 2]​

**Comment by tomas-pluskal** [comment]
The image didn't go through.

**Comment by magnetic111** [comment]
Ok, Ill attach the image here.

**Comment by ndpendant** [comment]
After attempting the command:
wine lib/vendor_libs/thermo/ThermoRawDump.exe filename

I received the following output:

![image](https://user-images.githubusercontent.com/19844446/29775779-7c836650-8bd4-11e7-821a-dcc9d3328b62.png)

**Comment by tomas-pluskal** [comment]
ThermoRawDump.exe is a 32-bit app, so I would try running it using wine instead of wine64

**Comment by tomas-pluskal** [comment]
also try running something like "wine cmd.exe" to check if wine is actually working

**Comment by magnetic111** [comment]
Thanks,

Ive changed it to wine32 in the terminal, do you know how I can maybe try
to run MZmine in the terminal via the wine32?

**Comment by tomas-pluskal** [comment]
MZmine calls "wine" by default, not wine32 or wine64. It is hard-coded in the code.

**Comment by magnetic111** [comment]
Ok :)
