### ISSUE TITLE
Cannot open raw file

### ISSUE THREAD

**Issue by jamilshilpi** [mzmine/mzmine2#359]
I have just installed MZmine 2.28. I failed to load raw file and got the following message:

![screenshot 2017-09-12 12 30 08](https://user-images.githubusercontent.com/31878853/30311372-ba9b0914-97b6-11e7-8bc0-ded5816f69ac.png)

**Comment by tomas-pluskal** [comment]
How about following the instructions here? https://mzmine.github.io/support.html#Issues

**Comment by tomas-pluskal** [comment]
Also you could tell us something about the raw file.

**Comment by jamilshilpi** [comment]
Many thanks for your kind reply. Here are the information:

MZmine-2.28
Windows 10, 64bit
R x64, 3.3.2
jre 8

What I have done is
double click startMZmine_Windows file found in the MZmine-2.28 folder
which opens a windows command prompt and then a new window with the title MZmine-2.28: New project (screen shot attached)
Now if I select raw data import, it gives error message (screen shot attached)
If I go for project, batch mode, then selecting the file also not helping and I guess that is not the way to go.
Probably I am entering through the wrong way.
![1](https://user-images.githubusercontent.com/31878853/30519675-b9abbcaa-9bbd-11e7-9b62-eb0de17a79a7.png)
![2](https://user-images.githubusercontent.com/31878853/30519676-c984d1f2-9bbd-11e7-9d9a-179fc143df6d.png)
![3](https://user-images.githubusercontent.com/31878853/30519679-d00539ea-9bbd-11e7-8906-6a5e416aa8cb.png)
![4](https://user-images.githubusercontent.com/31878853/30519680-d55ff948-9bbd-11e7-8135-e92c3b85be1f.png)

**Comment by jamilshilpi** [comment]
Forgot to mention that the raw file comes from Waters XEVO triple quadrupole MS instrument
https://www.dropbox.com/s/5lzpqf4rzjcv523/crude%20sonneratia%20sample.raw.zip?dl=0

**Comment by tomas-pluskal** [comment]
This error happens because you are trying to open the ZIP file directly. If you decompress the zip file first, it will work fine. MZmine can open most data formats in a zipped form, but not the Waters raw format (because their format is actually a folder). It could be implemented, of course, if you find someone who has the time to do that (I don't, sorry).
