### ISSUE TITLE
Online Database Search: HMDB

### ISSUE THREAD

**Issue by wezel4u4** [mzmine/mzmine2#360]
Hi,
We can no longer search the online Human Metabolome Database (HMDB). We could before.

The error given now: 
Could not search Human Metabolome Database (HMDB): java.io.IOException: java.io.FileNotFoundException: http://www.hmdb.ca/metabolites/HMDB00297.xml (HMDBGateway.java:131).

(the hmdb number changes from search to search)

Has there maybe been an update at the HMDB website? Is there anything I can do?
We are researching metabolites in humans so this feature is very important to us.

I thank you in advance.

**Comment by tomas-pluskal** [comment]
This is likely going to be related to this issue: http://chem-bla-ics.blogspot.com/2017/08/updated-hmdb-identifier-scheme.html

I will take a look at it and hopefully fix it for next MZmine version.

**Comment by wezel4u4** [comment]
Hi,
Yes I've noticed that as well. 
Thank you for your quick reply, and I will be looking forward to the new update.

Wesley.

**Comment by tomas-pluskal** [comment]
Fixed in version 2.29
