### ISSUE TITLE
Combining multiple MS scans into one spectra

### ISSUE THREAD

**Issue by StevenVds** [mzmine/mzmine2#364]
Hey, 

I'm totally new into the world of MassSpec and the various software packages there are available. I know that you can combine multiple MS scans into one spectra in MassLynx by dragging the right mouse button over the area you want the software combine them. I wonder whether this is possible with mzmine. If it is... then I can't figure how, could someone help me with this please?

Thanks in advance!

Greetings
Steven Vds

**Comment by tomas-pluskal** [comment]
Hi Steven,
MZmine does not have such function.
