### ISSUE TITLE
ADAP Chromatogram Builder underestimates its progress

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#365]
The ADAP Chromatogram Builder seems to report progress below 100% even after finishing. Not a major issue, but should be fixed.

<img width="997" alt="screen shot 2017-09-26 at 10 55 36" src="https://user-images.githubusercontent.com/1796692/30867250-75220092-a2a9-11e7-95a5-047476e9fcfe.png">

**Comment by asmirn1** [comment]
Sure, I'll take a look.
