### ISSUE TITLE
Gas chromatography files

### ISSUE THREAD

**Issue by LiLouzki** [mzmine/mzmine2#367]
Hi MZmine community!

I am currently working with gcd files, which are raw data files of gas chromatography (by Shimadzu).
Can I use MZmine to analyse these files or is their a converter function to convert them into MS format?

Best wishes,
Lisa

**Comment by tomas-pluskal** [comment]
Hi Lisa,
MZmine cannot import gcd files. Check msconvert from ProteoWizard if it can convert gcd to mzML.
Tomas

**Comment by LiLouzki** [comment]
Thanks for the quick answer.
No, I don't think that works. I might have to look for another converter.
Lisa
