### ISSUE TITLE
Can't import .raw files / Mac OS X

### ISSUE THREAD

**Issue by chandlerjd** [mzmine/mzmine2#368]
MZmine version 2.29
OS X 10.12.6 (64-bit)
java -version: 1.8.0_144
R --version: 3.3.3
No script changes
Exact steps: Start up GUI; Raw data import; Select 6 Thermo .raw files, profile mode Orbitrap data; press "Choose"

<img width="711" alt="screen shot 2017-10-05 at 5 54 53 pm" src="https://user-images.githubusercontent.com/32556064/31254461-c38046be-a9f6-11e7-8744-69086b51b186.png">
<img width="1084" alt="screen shot 2017-10-05 at 5 54 56 pm" src="https://user-images.githubusercontent.com/32556064/31254462-c382379e-a9f6-11e7-8eb3-e6e4f4ea7c37.png">

**Comment by tomas-pluskal** [comment]
Thermo .raw import only works on Windows. 
(well, it is possible to make it work on other platforms through wine, but it is very tricky)

**Comment by chandlerjd** [comment]
Thanks. Is it possible to convert to another file type that is workable on OS X MZmine?

**Comment by tomas-pluskal** [comment]
Yes, use msconvert from ProteoWizard to convert your files to mzML.

**Comment by tomas-pluskal** [comment]
Or you can run MZmine on Windows to import the raw files, then save the MZmine project, and reopen the project on your Mac.

**Comment by chandlerjd** [comment]
Thanks. Can you recommend msconvert settings?

**Comment by tomas-pluskal** [comment]
I cannot, since I don't know anything about your data or what you are
trying to accomplish.
Tomas

**Comment by chandlerjd** [comment]
I’m trying to analyze positive mode Orbitrap LC-MS data (profile mode) for high mass accuracy m/z feature extraction. 

On October 6, 2017 at 6:02:47 PM, Tomáš Pluskal (notifications@github.com) wrote:

I cannot, since I don't know anything about your data or what you are
trying to accomplish.
Tomas

**Comment by tomas-pluskal** [comment]
In that case I'd stick to mzML format, 64-bit precision, zlib-compressed. No other parameters necessary.

<img width="670" alt="screen shot 2017-10-09 at 15 55 33" src="https://user-images.githubusercontent.com/1796692/31355986-56e26520-ad0a-11e7-83e8-552d9433afe1.png">

**Comment by chandlerjd** [comment]
Thank you!
