### ISSUE TITLE
Targeted Peak Detection Error

### ISSUE THREAD

**Issue by Gregor90** [mzmine/mzmine2#369]
Hello,
 In the current Version 2.29, I get an error when trying to use the "Targeted peak detection" function. It works fine in the Version 2.27, however. 
The error I get is: 
Unhandled exception in task Targeted peak detection filexy.mzML: java.lang.IndexOutOfBoundsException: Index: 340, Size: 340 (null:-1) 

What could be the problem for this error?

My .csv peaklist has 340 lines. I'm using the current Java Version 8 Update 144 and Windows 10 x64 and R 3.4.1. 

Regards,

Gregor

**Comment by tomas-pluskal** [comment]
Hi Gregor,
Could you please send the CSV file that you're using?

**Comment by Gregor90** [comment]
Hi Tomas,

I attached the file.


Am 06.10.2017 4:18 nachm. schrieb "Tomáš Pluskal" <notifications@github.com
>:

Hi Gregor,
Could you please send the CSV file that you're using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mzmine/mzmine2/issues/369#issuecomment-334768131>, or mute
the thread

**Comment by tomas-pluskal** [comment]
The attachment didn't go through. Please upload it to the github issue, or send it to me directly: plusik@gmail.com

**Comment by tomas-pluskal** [comment]
Found the problem and fixed it. It will be fixed in the next release.
