### ISSUE TITLE
SIRIUS single feature export

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#379]
I loaded the sample project (https://github.com/mzmine/sample_data/releases/download/v2.3/sample-2.3.mzmine) and exported single feature ID 8 (HEPES) to SIRIUS MGF. The MGF file is attached. 

[sir.mgf.zip](https://github.com/mzmine/mzmine2/files/1458899/sir.mgf.zip)

When I try to import the file into SIRIUS 3.5.1, it appears as a bunch of MS2 spectra - shouldn't it appear as a single feature?
<img width="947" alt="screen shot 2017-11-09 at 14 18 37" src="https://user-images.githubusercontent.com/1796692/32625007-0ac863e4-c559-11e7-895b-c4aa7a0ab2cb.png">

**Comment by tomas-pluskal** [comment]
@kaibioinfo

**Comment by TDEVIJLD** [comment]
Hi all,
I'm new to MZmine.  Is the SIRIUS export currently the best/only way to export single feature (i.e. selected MS/MS) data or are there other procedures that you can recommend?
Thanks
