### ISSUE TITLE
Is it possible to batch export baseline corrected TICs?

### ISSUE THREAD

**Issue by stefanjhill** [mzmine/mzmine2#380]
Hi,

I was wondering if we wished to do PCA etc on the baseline corrected "Raw data file" TICs (i.e. like NMR spectra) is there a way to export these as CSV files as a batch? I am currently I need to view them individually and then export as a CSV. 

Kindest regards,
   Stefan.

**Comment by tomas-pluskal** [comment]
Hi Stefan,
There is no such function in MZmine currently.
Feel free to contribute.

**Comment by stefanjhill** [comment]
Thanks for the quick reply, saved me hunting for hours!

I would love to contribute but my Code-Fu isn't up to the task. I unfortunately sit squarely in the impressed user camp. 

Any suggestions on active members I might interact with to see what could be done?

Cheers!
