### ISSUE TITLE
How to use chromatogram deconvolution algorithm 'XCMS'?

### ISSUE THREAD

**Issue by taekyupark** [mzmine/mzmine2#381]
Hi, I'm a student studying mzmine2 with the manual(Mzmine tutorial).

1.I'm trying to get used to the algorithm 'XCMS' which is one of the 'chromatogram deconvolution' algorithms. 

But it's so hard for me to input the parameter values of XCMS(S/N threshold, Wavelet scales). 
Do you have any tips when you input the parameter values of XCMS? I really want to know how to use that algorithm. really 
I already read the explanation about each parameter in the Mzmine2(clicking 'help') but I don't know
if i'm putting right value to each parameter.

     2. When I use XCMS algorithm for the chromatogram deconvolution, is it okay to use 'centroid' MS data? I saw another option 'wavelet transform' and there is word 'wavelet' next to the XCMS

Thank you for reading

**Comment by tomas-pluskal** [comment]
Have you read the original paper about the centWave algorithm? 
That might be a good start.
Tautenhahn, R., Bottcher, C. & Neumann, S. Highly sensitive feature detection for high resolution LC/MS. BMC Bioinformatics 9, 504 (2008)

**Comment by taekyupark** [comment]
Thank you so much!!
