### ISSUE TITLE
Visualization via API / documentation of API

### ISSUE THREAD

**Issue by Stortebecker** [mzmine/mzmine2#386]
Hi, 

I wondered if there is a way to visualize MS data using MZmine via API. I found some documentation of the "batch mode", but none about actual commandline usage.
A well-documented API (and some help) would probably enable us to integrate MZmine (or parts of it) into the Galaxy data analysis framework. So far, we feature MS data analysis via OpenMS and other tools, but lack proper visualization features. Your great visualizations would come in handy to fill that gap.

Thanks, Florian

**Comment by tomas-pluskal** [comment]
Hi Florian,

MZmine does not really have any API for the visualization tools, apart from what you can find in the source codes. The batch mode is for running the data processing methods, not for visualization. 

I am not quite sure how interactive, Java-based MZmine visualization modules could be added to Galaxy, which is based on web interface if I am not mistaken.

Tomas

**Comment by Stortebecker** [comment]
Hi Tomas,
that's a pity. Interactive programs are really hard to integrate into Galaxy, if they were not designed for API usage. I guess I have to keep searching.
Thanks, Florian
