### ISSUE TITLE
Is this Mzmine2 problem or MS scanning problem?

### ISSUE THREAD

**Issue by taekyupark** [mzmine/mzmine2#387]
Hi, I have been working with mzmine2 to make molecularnetwork.
To get MS data, I use UPLC-qTOF-ESI-MS
(Fast DDA, 
 MS scan time:0.15s(centroid),
 MS/MS scan time: 0.1s(centroid),
 condition: stop the MS/MS scan when 0.35seconds has elapsed,
 Maximum numberof ions which can be selected for MS/MS from a single MS survey scan: 3  )

After acquisition of the 'raw MS data' , I use 'ProteoWizard-Msconvert' to make 'raw MS data' to be 'mzXML' file.

And then I import mzXML data to Mzmine2. ->mass detection(MS1)->mass detection(MS2)
->chromatogram builder

but several problem observed when I compare the 'chromatogram in Mzmine' and the 'chromatogram in Masslynx'
![1](https://user-images.githubusercontent.com/33615318/32943081-5a67c6a8-cbce-11e7-9dd9-ec7edc260eb0.jpg)

In the picture upper side represents 'chromatogram in Mzmine during chromatogram deconvolutionXCMS'
and down side represents 'chromatogram in Masslynx.

If you focus on the retention time 9min in mzmine2, you can see the split of the peak(two peaks with 'same' m/z value) (see the blue line)
But, in the Masslynx which represent MS1 data of my sample, there is 'a' sharp peak at retention time 9min

Similar phenomenon is observed at another retention time(5,89min),
![2](https://user-images.githubusercontent.com/33615318/32943709-59db8510-cbd0-11e7-93e3-2a0d03130e9e.PNG)

I think it usually happens when the peak width is wide.

I wonder if my MS Scan condition is wrong or not.
Does anyone know how to solve this problem? 

If you want to get my mzXML file, you can get it at this link
https://www.dropbox.com/s/lq25x1ii4px5w60/171114_dangG_MN2.zip?dl=0

**Comment by asmirn1** [comment]
Hi. It seems to me that the chromatogram built by MZmine is missing a data point. So you might want to check parameters of Chromatogram Builder. Did you try to increase m/z tolerance there?

**Comment by tomas-pluskal** [comment]
This is not sufficient information to debug anything:
````
And then I import mzXML data to Mzmine2. ->mass detection(MS1)->mass detection(MS2)
->chromatogram builder
```` 
The key is in the parameter values that you used. If you want help with that, the best would be to send your mzmine project file.

**Comment by taekyupark** [comment]
Hi, asmirn1 and Tomas. I really thank you for your help.

I will show you how I made that project and also I will send my project in here.
https://www.dropbox.com/s/68oxqa1qfmj5mjg/171114_dangG_MN2.mzmine?dl=0
If you click this link. you can download my project.

And this is how I made that project
First I import my mzXML data to mzmine2.
And then I used 'crop filter' to get 'negative' and 'centroid' data
![a](https://user-images.githubusercontent.com/33615318/32976988-3081b1de-cc67-11e7-8e3e-6af3a2367d56.PNG)

After 'crop filter',  I used 'mass detection' for MS1 
![b](https://user-images.githubusercontent.com/33615318/32976997-6134ec10-cc67-11e7-8de7-3ece47fc4e67.PNG)

and then I used 'mass detection for MS2
![c](https://user-images.githubusercontent.com/33615318/32977002-6f007d8c-cc67-11e7-90a9-d98d0c97166c.PNG)

after 'mass detection', I used 'chromatogram builder'
![d](https://user-images.githubusercontent.com/33615318/32977004-8159af26-cc67-11e7-9933-ff935dac0bbd.PNG)

+I also increased m/z tolerance from 0.06 to 0.10 but same problem still exists..

**Comment by tomas-pluskal** [comment]
Just take a look at the raw data in your file (disregarding all peak detection, just open the TIC plot).
Clearly, the peak around 9 min looks ok in your positive mode scans:
![positive](https://user-images.githubusercontent.com/1796692/32983418-4168a818-cc62-11e7-9368-dc5c2a16bec0.png)

The same peak is split in negative mode scans:
![negative](https://user-images.githubusercontent.com/1796692/32983421-436a844c-cc62-11e7-81a3-ecb37ab3e1bb.png)

So this is not an issue of peak detection in MZmine, but one of your negative scans somehow dropped intensity.
My guess is that you were looking at positive mode scans in masslynx and that's why the peak showed as a full peak in masslynx.

**Comment by taekyupark** [comment]
Tomas, I really appreciate your effort to check my data. It' so nice of you to help me.

In our lab, when we use UPLC-qTOF-MS, we select only one mode(negative mode or positive mode).
We don't use negative and positive mode at the same time... So I used 'crop filter' in mzmine2 to select only negative mode data.

In the masslynx picture, you can recognize the m/z value '371.1495' which corresponds with the m/z value in your picture(negative mode scan)
![aa](https://user-images.githubusercontent.com/33615318/32988201-79284df4-cd42-11e7-8d44-fa732b448475.PNG)

Just in case, I upload my raw MS data in here.
https://www.dropbox.com/s/lq25x1ii4px5w60/171114_dangG_MN2.zip?dl=0

I wonder why peak shape(intact in the masslynx) is changed(dropped intensity) in the mzmine2.
I used 'pick extender' to fill in the gap between two splitted peaks, but I'm not sure this is right choice.
Do I have to change my MS condition?

 I rechecked my MS conditions.
**1.Fast DDA,
1-1. Acquisition Mode
Polarity: Negative,                   Analyser Mode: Resolution 
1-2. MS survey
MS scan time: 0.15 second (centroid), 
MS survey Switching Threshold: switch to MS/MS acquisition when 'TIC rises above'

1-3 MS/MS
Scan rate for MS/MS: scan Time(0.1sec, centroid),
Maximum number of ions which can be selected for MS/MS from a single MS survey scan: 3 MS/MS ions )
condition: stop the MS/MS scan when 0.35seconds has elapsed(After MS/MS acquisition, the Acquisition switches back to MS survey)**

**Comment by tomas-pluskal** [comment]
In your mzXML file, scan number 13964 (9.013 min) has a peak of 371.1495 m/z with 9.3E4 intensity, but the next scan number 13970 (9.017 min) does not have the peak and has intensity of only 3E3. I don't know if this is a problem of your instrument or a problem of your conversion to mzXML, but I don't think MZmine has anything to do with it.

![9_013min](https://user-images.githubusercontent.com/1796692/32991648-4a537dd0-cd0d-11e7-9887-e2b5f98065cb.png)
![9_017min](https://user-images.githubusercontent.com/1796692/32991650-4ce6a860-cd0d-11e7-9aa8-a27b8c9d8783.png)

**Comment by taekyupark** [comment]
Thank you Tomas.
I guess the problem is came from converting process because when I import raw data file, the peak(9min) doesn't split.
Maybe using proteowizard to convert Waters MS raw data is not perfect.
Any thanks a lot.
I will search another program to convert my Waters MS raw data.
