### ISSUE TITLE
The PlantCYC databse shows no results

### ISSUE THREAD

**Issue by SripadJ** [mzmine/mzmine2#390]

**Comment by tomas-pluskal** [comment]
I removed the outdated PlantCyc search and replaced it with MetaCyc, which actually has a usable API.

**Comment by SripadJ** [comment]
But the current version 2.30 shows PlantCyc in the database list and not MetaCYC

**Comment by tomas-pluskal** [comment]
Indeed. The change will appear in the next version.

**Comment by paul-abraham** [comment]
Hello,

I tried to perform an online database search against MetaCyc and I get the following error:

"Could not search MetaCyc Database (javax.net.ssl.SSLKeyException: RSA premaster secret error@sun.security.ssl.RSAClientKeyExchange.<init>(Unknown Source)) 

I am using version 2.31 and Java version 1.8.0_161.

**Comment by tomas-pluskal** [comment]
Try installing Java JDK 9. This looks like a Java problem, not MZmine problem.
