### ISSUE TITLE
identification function error

### ISSUE THREAD

**Issue by jeep3** [mzmine/mzmine2#392]
Hi, I encountered a issue when I performed a identification function to search the database of massbank. 
Could your give me some advise to combat this error?  The error as follow:
![error](https://user-images.githubusercontent.com/28469054/33523287-bcc6b518-d83d-11e7-8bb4-f01e8c24332a.PNG)

**Comment by jeep3** [comment]
Win 10 system, 64bit, Mzmine 2.30, Installed java as follow:
![java](https://user-images.githubusercontent.com/28469054/33523320-8b41552e-d83e-11e7-8240-b39803816a05.PNG)

**Comment by tomas-pluskal** [comment]
There seems to be a problem at the Japanese MassBank with retrieving certain entries. 
E.g., see
- http://www.massbank.jp/jsp/FwdRecord.jsp?id=JP003932 (works)
- http://www.massbank.jp/jsp/FwdRecord.jsp?id=SM801701 (fails)

**Comment by tomas-pluskal** [comment]
I added a fix, will be included in next release.

**Comment by jeep3** [comment]
ok, thank you a lot.
