### ISSUE TITLE
Trouble running mzmine2 on BioLinux OS

### ISSUE THREAD

**Issue by kchavarr** [mzmine/mzmine2#396]
Hello,

I'm trying to run startMZmine_Linux.sh on my machine running BioLinux and am constantly running into one particular error: 

MZmine2 version 2.30
Java version:
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
R version:  3.4.0 (2017-04-21)

-------------------------------------------------------------------------------------------------
[mycomputer] ./startMZmine_Linux.sh                       
Checking physical memory size...
Found 24104 MB memory
Java maximum heap size set to 22056 MB
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Error: Could not find or load main class net.sf.mzmine.main.MZmineCore
--------------------------------------------------------------------------------------------------

In the directory src/main/java/net/sf/mzmine/main/,  MZmineCore.java  exists. I tried to change the startMZmine_Linux.sh file to append the .java extension to see if that was the issue but nothing changed. I read a previous issue where a user had a similar error but the resolution was not clear. Any help would be greatly appreciated. 

Thank you

**Comment by tomas-pluskal** [comment]
If you downloaded the official release from this website, there would be no src/ directory. So you probably downloaded something else?

**Comment by kchavarr** [comment]
My apologies, instead of just downloading the zip, I downloaded the source tarball. The zip is now downloaded and it is running fine.
