### ISSUE TITLE
Issues exporting more than 1 deconvoluted chromatogram as a .csv file

### ISSUE THREAD

**Issue by kchavarr** [mzmine/mzmine2#397]
Hello,

I am trying to export 100+ deconvoluted chromatograms as .csv files. I highlight the files, go to 'Peak list methods' -> Export/Import -> Export to CSV file. I see under 'Peak lists' the number of files selected and the pull down tab says "As selected in main window". Under filename I choose the directory and a name, check the appropriate elements I want and press OK. 

I expect that because 1 filename is written, it would output all my files to a single .csv file. However, only the first file in the list is output. 

I have also tried "All peak lists" under the pull down menu. Still only the first file is exported. (The exported files are all ~30kb no matter how many I choose).

I am not sure what the issue is, but I have three questions. Where am I going wrong?  Is it possible to export multiple files as a single .csv file? And is it possible to export a list of files as individual .csv files with files named how they are identified in the Peak lists window automatically?

Thank you for your time

_______________________________________________________________________

MZmine2 version 2.30
Java version:
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
R version: 3.4.0 (2017-04-21)

**Comment by asmirn1** [comment]
Hello,

It's definitely possible to export a list of files as individual .csv files. What name do you choose for individual .csv files? You need to use symbol "{}" in their filename and it will be replaced by the name of an exported peak list. For instance, if you select peak lists **list1**, **list2**, **list3** in MZmine2, choose Export to CSV file and specify filename "export.{}.csv", then you should get three files **export.list1.csv**, **export.list2.csv**, **export.list3.csv**. Does it work for you?

**Comment by kchavarr** [comment]
It does work! Thank you!
