### ISSUE TITLE
Error: Could not find or load main class

### ISSUE THREAD

**Issue by pbalegro** [mzmine/mzmine2#399]
Hi!

I was using MZmine 2.29 without any troubles before. But then, I had an update for Windows 10 (64-bit) last Dec. 23, 2017. After that update, whenever I run _startMZmine_Windows_ startup script, I get _Error: Could not find or load main class..._

![image](https://user-images.githubusercontent.com/26851384/34456926-bf2d53b0-eddd-11e7-926b-db3c28c83360.png)

The line following the error message (i.e. Alegro.LAPTOP-G2UFO3BH\AppData\Local\Temp) is a location address in my local drive C:

![image](https://user-images.githubusercontent.com/26851384/34456947-4e50232e-edde-11e7-9edd-6282da800b37.png)

The user folder "Patrick Alegro" is similar to a newly installed Windows (my previous files were not present); whereas, the user folder "Patrick Alegro.LAPTOP-G2UFO3BH" contains all the files that I had prior to the update.

I have tried reinstalling Java and downloading the latest MZmine version (MZmine 2.30), but I still encounter the same error. I also don't have a background in Java programming so I don't know how to edit the startup script (if that would fix the error).

I am really hoping that you could help me with this problem. Thank you.

**Comment by tomas-pluskal** [comment]
Not sure why this happens. Try editing the startup script and setting the TMP_FILE_DIRECTORY, e.g. like this:

set TMP_FILE_DIRECTORY=C:\

See if that helps.

**Comment by pbalegro** [comment]
Hi! Setting the TMP_FILE_DIRECTORY to C:\ did help, I was able to open the MZmine GUI. However, the problem now is with exiting the program. Whenever I close the GUI, I get these in the command prompt window:

![image](https://user-images.githubusercontent.com/26851384/34459720-3a3ab7d2-ee33-11e7-99ac-cbe43195d315.png)

![image](https://user-images.githubusercontent.com/26851384/34459673-99c5b956-ee31-11e7-844d-7782401a3e16.png)

![image](https://user-images.githubusercontent.com/26851384/34459750-5e03de4a-ee34-11e7-9337-d50bca054353.png)

![image](https://user-images.githubusercontent.com/26851384/34459759-7f01a8d4-ee34-11e7-8dea-3e99b69dc6ad.png)

![image](https://user-images.githubusercontent.com/26851384/34459762-98229184-ee34-11e7-82bd-5df143e7b7fb.png)

Unlike in normal exiting process, the command prompt window does not automatically terminates.
Also, the _MZmine 2.29_ folder containing the script I ran becomes empty.

**Comment by pbalegro** [comment]
I also tried setting TMP_FILE_DIRECTORY to the address where my MZmine is located. The result is that it opens and exits the GUI and command prompt properly. But the _MZmine 2.29_ folder containing the script I ran still becomes empty.

**Comment by tomas-pluskal** [comment]
You can create a new folder like C:\TEMP and set TMP_FILE_DIRECTORY to that folder. That should work for you.

Meanwhile, could you run this command in the Windows command line?
````
echo %TEMP%
````

**Comment by pbalegro** [comment]
Creating a new folder and setting TMP_FILE_DIRECTORY to that folder did fix the problem. Thank you for that. MZmine GUI is now starting and exiting as before.

On the other hand, executing
`echo %TEMP%`
on the Windows command line returned the following;
![image](https://user-images.githubusercontent.com/26851384/34472083-15f86ef2-ef94-11e7-87c4-477c33359f82.png)

which is the same destination referred in the error message. Just curious; is it the case that Java does not recognize destinations/path that has a space in the folder's name (i.e. it should be named PatrickAlegro and not Patrick Alegro)?

**Comment by tomas-pluskal** [comment]
This is probably something that we should take into account in the script. 
What if you change
````
set JAVA_PARAMETERS=-showversion -classpath lib\* -Djava.ext.dirs= -XX:+UseG1GC -Djava.io.tmpdir=%TMP_FILE_DIRECTORY% -Xms256m -Xmx%HEAP_SIZE%m -XX:+IgnoreUnrecognizedVMOptions --add-modules=java.se.ee
````
to
````
set JAVA_PARAMETERS=-showversion -classpath lib\* -Djava.ext.dirs= -XX:+UseG1GC -Djava.io.tmpdir="%TMP_FILE_DIRECTORY%" -Xms256m -Xmx%HEAP_SIZE%m -XX:+IgnoreUnrecognizedVMOptions --add-modules=java.se.ee
````
Does that work?

**Comment by pbalegro** [comment]
Yes, it did work, even when TMP_FILE_DIRECTORY is set back to %TEMP%. It works as well even with the new folder I created in drive C.

By the way, when I exit the MZmine GUI, a line appears in the command window before closing that says

`Warning: Could not get charToByteConverterClass`

Should I be concerned with this warning message?

**Comment by tomas-pluskal** [comment]
You don't need to worry about the warning.

**Comment by pbalegro** [comment]
Well, I think that solves it. Thank you very much for your help.
