### ISSUE TITLE
Tiny but important typo in the RANSAC peak list aligner module

### ISSUE THREAD

**Issue by Althalis** [mzmine/mzmine2#401]
HI there!

I spotted a discrepancy of unit for the threshold value for the RANSAC peak list aligner.
In the Help button description, it says (seconds), while the yellow message displayed with the mouse over the field says (minutes).
I am new in metabolomics, that's why I double check everything. :)

Thanks!
best
Julie

**Comment by tomas-pluskal** [comment]
Thanks, Julia, it will be fixed in next release.
