### ISSUE TITLE
Wildcards for Raw data import in XML file

### ISSUE THREAD

**Issue by stickenstein** [mzmine/mzmine2#409]
Is there any way to support wild cards in the batch xml files?

For example, a line like:

` <file>*.raw</file>`

would load all the raw files in the current directory (or another directory if it was specified). 

This would be a great help since it's desirable not to have to edit either the XML or in the GUI every time.

Thanks!

**Comment by tomas-pluskal** [comment]
Not possible at the moment. Feel free to contribute!

**Comment by asmirn1** [comment]
One workaround that I'm using on Mac is a bash script:
```shell
for filename in *.raw
do 
     ln -s $filename data.raw
     startMZmine_MacOSX.command batch_script.xml
done
```
The line `ln -s` creates a symbolic link with a name `data.raw` to a file. Then, batch_script.xml uses name `data.raw` to import that file. 

It should work on Linux also. For Windows, it might be possible to write a similar script file.

**Comment by tomas-pluskal** [comment]
Can also put a placeholder string (like HERE_BE_FILENAMES) into the batch XML file and then write a simple text substitution script that will replace the string with a list of filenames, similarly to @asmirn1 's example above.

**Comment by stickenstein** [comment]
Thanks for the suggestions! I was hoping there was already a built in method but I'll be able to find something that works.
