### ISSUE TITLE
GNPS-MZmine-annotation

### ISSUE THREAD

**Issue by djawedb** [mzmine/mzmine2#410]
Hi everyone,
So i just started using GNPS and I would like to know more so that I could use it properly and explore every option it offers. So I’ve been using it so far just to make the annotation or make the correlations between the unknowns and hope to find one of them to figure out the others. For that I’m using a top 20 MSMS file (of my sample) and after following all the workflow I can get some small networks of mass parents and also some identification using GNPS databases (there are not so many identified unfortunately may be because of my parameters). So my first question is related to the network visualized in cytoscape; so I would like to know if there is an option to export every cluster in the network we observe on an excel table so that I can match it with my MS1 data used for statistical analysis (even if the purpose is not clear it’s the easiest way for me to identify the impacted molecules that I selected from the PLS-DA model) , since the GNPS doesn’t make the peakpicking, filtering and alignement and use it later on for statistical analysis (PLS-DA …). Now, according to the answers I’ve received in another topic (annotation Mzmine) it is possible to create a mass list (MS1 and MS2) from MZmine that we could visualize using GNPS and what I understood is that this file contains all the masses (MS1) that would be used for the statistical analysis also (since we performed the peak picking, alignement …etc). I’ve tried to follow the workflow to create this list from MZmine to export it to GNPS and it doesn’t work (I’m still trying to figure it out and hope to get some answers in the future) so I was wondering if there is a way to use the MSMS file as I said in the beginning just for creating networks between parent masses according to their fragmentation pattern and then merge another list of variables (MS1) let’s say created with MZmine or XCMS and selected from the statistical analysis in order to highlight it in the network created by GNPS and visualized in cytoscape
Cheers 
Djawed

**Comment by lfnothias** [comment]
Hi @djawedb 
Yes. After using the following GNPS-MZmine workflow ([see step-by-step documentation](https://bix-lab.ucsd.edu/display/Public/GNPS+data+analysis+workflow+2.0#GNPSdataanalysisworkflow2.0-SequenceofstepstoperforminMZmine2%28v2.30%29)), you can then export the merged table from Cytoscape, that would contain both MZmine information and network informations. If you have any issues with it, please let me know about it. 
For more details on GNPS please [use the following forum](https://groups.google.com/forum/#!forum/molecular_networking_bug_reports
).
LF

**Comment by djawedb** [comment]
Thank you so much for your answer !
Djawed

**Comment by lfnothias** [comment]
I would recommend to close that thread.
