### ISSUE TITLE
SIRIUS export

### ISSUE THREAD

**Issue by sayuichimi** [mzmine/mzmine2#413]
Hi, I'm using MZmine 2.30 and or 2.31.
I have a trouble for the SIRIUS export module does not progress correctly with a "java.langNullPointerException (SiriusExportTask.java:315)".
I have same data on pos/neg mode. The pos mode data have been done succesfully. However the neg data was failed. I can not understand. How can I do?

**Comment by tomas-pluskal** [comment]
Hi,
The SIRIUS export module is not in a very good condition, needs some more work.
