### ISSUE TITLE
MetaCyc not working

### ISSUE THREAD

**Issue by paul-abraham** [mzmine/mzmine2#418]
Hello,

I have run into an issue where MetaCyc is not working.

- MZmine version = 2.31
- OS version = 64-bit
- java version = 9.0.4
- R version = 3.4.3
- Screenshot of the error message =
![image](https://user-images.githubusercontent.com/31446382/37301787-fe25c610-25ff-11e8-8b81-fd2575ac9702.png)

- The log messages reported in the MZmine console window =[14:11:51|WARNING|PeakListIdentificationTask]: Could not search MetaCyc Database(java.lang.ArrayIndexOutOfBoundsException: 4@net.sf.mzmine.modules.peaklistmethods.identification.onlinedbsearch.databases.MetaCycGateway.findCompounds(MetaCycGateway.java:75))
[14:11:51|SEVERE|WorkerThread]: Error of task Identification of peaks in easy_nlc_Udaya_1x_1uL_c18_ac30cm_01.raw chromatograms (140.1068 m/z) using MetaCyc Database: Could not search MetaCyc Database: java.lang.ArrayIndexOutOfBoundsException: 4 (MetaCycGateway.java:75)

- The exact steps you took until you encountered the problem = 1)import raw file, 2) mass detection, 3) ADAP chromatogram builder, and 3) online database with MetaCyc.

I should note that other online databases do work.

**Comment by tomas-pluskal** [comment]
I added a fix for this issue, although I am not sure which MetaCyc record produced the error.

**Comment by tomas-pluskal** [comment]
Should be fixed in version 2.32
