### ISSUE TITLE
33 mzML data file takes several days to extract chromatogram - Is that normal?

### ISSUE THREAD

**Issue by Angelahoerdum** [mzmine/mzmine2#420]
I am stil new at this, sorry about that!

I have 33 samples in .d format from agilent that i have converted into .mzML format using MSconvertGUI 

My issue is that these data take a long time to handle and i would love to know if this is just how it is? did I do something wrong in the setup? Or can I fix this issue?

I am currently running on two computers:

Computer 1:
Processor: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHZ 2.81 GHZ
RAM: 8.00 GB
System type: 64-bit 

R is set up (64 bit) and all packages are installed.
Java is updated to the newest version (64bit)
I have edited the HEAP_SIZE to 4000

Chromatogram extraction take approximately 8 days.

Computer 2:
Processor: Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz 3.50GHz
RAM: 32, GB
System Type: 64-bit

R is set up (64 bit) and all packages are installed.
Java is updated to the newest version (64bit)
I have edited the HEAP_SIZE to 10000

Chromatogram extraction take approximately 3 days.

I hope you have some ideas of how to reduced the processing time. And please let me know if this is just how it is suppose to be.

**Comment by robinschmid** [comment]
Hey,

- Is your mzML data already centroided or which Mass detection do you apply? 
You should specify a noise level that excludes most of the noise while retaining as much information as possible. As a first test, set the noise level for Mass detection well above your actual noise. Later, you should try to lower this value.

- The noise level might change with a gradient which is usually applied in GC or HPLC (see Fig 24). Facing this issue, you can run multiple mass detections on each mzML with different retention time ranges. However, you have to use the same mass list name for later chromatogram building.

- If your mzML files contain MS1 and MS2 spectra or if you have spectra in both negative and positive mode, you should filter out one specific type for mass detection and chromatogram building.

![image](https://user-images.githubusercontent.com/10366914/37704100-2cd751b4-2cf8-11e8-8c55-f8d12cd37a6c.png)

**Comment by Angelahoerdum** [comment]
Thank you Robin!

 - Yes they are centroid  and the noise leve are set to 50. This was done because I was loosing some compounds that i found using QQQ targeted detection. So I tried to lower the noise level.

 Mass detection 
![image](https://user-images.githubusercontent.com/35375992/37705197-840e42be-2cfb-11e8-991d-76f824babe17.png)

Chromatogram builder
![image](https://user-images.githubusercontent.com/35375992/37705273-c200c07e-2cfb-11e8-9c73-e44136515cee.png)

 - I keep saving with the same name  (if that is what you mean) I dont know if this is relevant, but i did a base line correction before i started the mass detection. 
![image](https://user-images.githubusercontent.com/35375992/37705391-24dc90a6-2cfc-11e8-843c-9bd4bf907cd4.png)

 - My data includes both MS1 and MS2 data, but only in positive mode. Should i somehow only use one of the two?

 - Angela

**Comment by Annexhc** [comment]
Try a higher value for "Min time span (min)" in the chromatogram builder. I dont know if you have used GC or UHPLC, but for standard HPLC a value of 0.1 min could be alright. Anyway you should just try it to check if that value is causing your long processing times.

**Comment by robinschmid** [comment]
Hey Angela,

You are already using a MS1 filter in the Chromatogram builder. That is good. You should specify a Min time span in this module. You can basically take the mean difference between two MS1 scans and multiply with a minimum number of data points you would like to have in a chromatogram.
For example, if you acquire an MS1 scan every 0.02 minutes and you want at least 4 data points you could set your minimum time span to 3.5x0.02 min = 0.07 min.

Your data is from a Q-TOF right?
The m/z tolerance seems to be too high, regarding that it does not describe the tolerated difference between the calculated  exact mass and measured accurate mass. This tolerance describes the changing centroid m/z values of the "same" signal across all MS1 scans. Open an MS1 scan, zoom into some signals and see how the m/z value changes in MS1 scans.
Depending on the resolving power of your MS instrument and the m/z range of your experiments, you might have a chance with values around 0.003 (as absolute) and 5 ppm

**Comment by Angelahoerdum** [comment]
Robin! I changed the Noise level to 5000 and it made a huge difference! Thank you very much for the advice! I am not sure what what level will fit my data, but I am showing my data to a routined mzmine User on friday and this will be discussed.

Again Thank you!

**Comment by Angelahoerdum** [comment]
Hi Annexhc,

I am workign with HPLC data. And i just changed the "Min time span (min)" to 0.1 while keeping the Noise level at 50 and it really does make a difference. 

Can I ask why the "Min time span (min)" can be 0.1 for HPLC an not for GC?

 - Angela

**Comment by robinschmid** [comment]
You are welcome. 

No difference for HPLC or GC. The procedure is the same: You have to look into your dataset to have the acquisition rate of your MS1 scans and it is good to know the minimum peak width, which is dependent on your chromatographic system. 

What is your m/z range?
Based on m/z 1000 and this small subset of data points, 0.009 and 9 ppm should work fine. 
9 ppm would only apply to m/z>1000

**Comment by Annexhc** [comment]
Using GC often results in very narrow peaks, approximately a few seconds in width. HPLC peaks are in most cases much wider. But of course theire is no rule, it always depends on your specific dataset.

**Comment by Angelahoerdum** [comment]
Hi Robin,
My m/z range is 99 to 1699 (says the auto range) I am very intrested in comopunds below m/z 1000. 

I am also not sure if this i relevant, but i have a shift in retention time inbetween my peaks and i fix that later with RANSAC aligner.

**Comment by robinschmid** [comment]
RANSAC is your best choice then. The retention time shift makes no difference for the first processing steps.
I hope the proposed parameters solve the problem and yield reliable results.
Cheers,
Robin

**Comment by Annexhc** [comment]
I think we can close this
