### ISSUE TITLE
Problem MZmine !!! : files .cdf from bruker can't be processed

### ISSUE THREAD

**Issue by djawedb** [mzmine/mzmine2#424]
Hi everyone,
I am currently using a Q-TOF to perform a metabolomic analysis, the files generated at the end are .cdf (converted from .d using the bruker script). When I try to import those files to MZMine (version: 2.30) for the data processing and when I open every file by clicking on the + signe to check the scans, they are displayed with the sign "?" (see the picture below).
![image](https://user-images.githubusercontent.com/36295211/38604651-4e997c80-3d71-11e8-9dc2-f586ab164ed2.png)

At this point I  thought it was just a viewing problem. But when performing the mass detection nothing seems to happen (there is no masse list generated). This problem accurs also with previous versions such as 2.30,  2.26 and even with the last version 2.32. However the problem doesn't accur with the version 2.9 which can perform the data processing until a certain point where it just blocks (especially if I have more than 50 files). So please do you have any solution for this problem? is there another way to convert the .d files generated from the Q-TOF  into .cdf that can be processed withe the last version; 2.32 (I've already tried to convert them into mzXML but it doesn't seem to work correctly).   

Djawed.

**Comment by tomas-pluskal** [comment]
Hi,
The "?" sign just indicates unknown polarity. It is not a problem at all.

**Comment by djawedb** [comment]
Thank you so much for your answer. The reason why I thought it was a problem is because my data were analysed in positive mode and when I tried to perform the data processing, I choosed the positive sign on mass detection, and it told me that there were no scans detected so I thought I had a problem with the cdf conversion. but now I just put any instead of + or - and it works very well.
Thank you again for your answer!

Djawed

**Comment by tomas-pluskal** [comment]
You are welcome.

**Comment by li-chin** [comment]
Hi, I am facing an issue related to this topic. I am using Bruker .d file converted using msConvert to mzml onto mzMine3. After mass detections and ADAP, I can see the filtered feature list, but the scan number for most of the spectra turns 0 (As shown in attached Figure). Eventually it becomes a problem when I export to mgf after isotope grouping, gap filling and alignment steps - the features with zero scan number was not being exported.
![mzmine3 1_zeroscannumber](https://user-images.githubusercontent.com/96451969/190935921-71a8c75f-aa56-4152-bedc-f2e28c50c78d.png)
May I get your advice on this? Thank you.

**Comment by tomas-pluskal** [comment]
@li-chin Your issue is not related, please file a new issue for your problem

**Comment by li-chin** [comment]
> @li-chin Your issue is not related, please file a new issue for your problem

Noted. Sorry for that, I have filed a new issue here https://github.com/mzmine/mzmine3/issues/915. Thank you.
