### ISSUE TITLE
JavaFX initialization error on Linux.

### ISSUE THREAD

**Issue by bjonnh** [mzmine/mzmine2#425]
### Setup

I am reporting a problem with MZmine 2 version >2.33 (latest commit, bissected to the commit 089afd4b9db3083c6ebef43fc70c55d9bc3171c0). 
My operating system is ArchLinux, OpenJDK8, 64bits.

Below I pasted the exact output of the following commands:
```
java -version

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
```

### Expected behavior

Correct start of the application (2.32 works)

### Actual behavior

exits without opening a window with:
[12:19:34|FINE|MZmineCore]: Initializing GUI
[12:19:34|FINEST|DesktopSetup]: Initializing the JavaFX subsystem by creating a JFXPanel instance
[12:19:34|SEVERE|MZmineCore]: Could not initialize GUI(java.lang.reflect.InvocationTargetException@java.awt.EventQueue.invokeAndWait(EventQueue.java:1349))

**Comment by bjonnh** [comment]
Doesn't work either on Ubuntu 18.04 (testing) with openjdk8 too (with jfx installed).

**Comment by tomas-pluskal** [comment]
Thanks for the report, I'll look into it. 
Have you tried running any JavaFX-based app, or could you try running some?
http://www.oracle.com/technetwork/java/javase/overview/javafx-samples-2158687.html

**Comment by bjonnh** [comment]
Yes I tried that, they work well (all of them, even the 3D etc).

**Comment by tomas-pluskal** [comment]
Try now, should be fixed.

**Comment by bjonnh** [comment]
Excellent, this works beautifully now.  

Thanks!
