### ISSUE TITLE
problem in connecting with online database and other libraries for peak identification....please somebody help

### ISSUE THREAD

**Issue by shweta-talreja** [mzmine/mzmine2#433]
I am reporting a problem with MZmine 2 version (2.32). 
My operating system is (windows 10 64-bit).
Java 9 (JDK)
I have tried with java 8, but since it didn't work I tried java 9. with the latter, every time it completes the task (peak identification) till 25-28% then shows the error.
below is the screen shot of the same.

![screenshot 2018-05-14 14 58 36](https://user-images.githubusercontent.com/39258874/40109965-65cacef6-591c-11e8-8d36-895b493e7724.png)
 
Can someone help me please.....

Thank you
Shweta

**Comment by shweta-talreja** [comment]
#433  @zeehio @kaibioinfo @cpudney @tomas-pluskal   @OvenO 

Can anyone please help me......why am I not able to connect with the online database??????

Is there some bug with this software......:(

Atleast someone reply

**Comment by Annexhc** [comment]
Hi,
does the problem appear with EVERY database, or which one are you talking about? Did you got any identifications for the first quarter of your list? Have you tried using an other peak list? You are using an aligned peak list with only one raw file...
Best wishes

**Comment by shweta-talreja** [comment]
Hi,

I have tried with pubchem online database. I processing/rifined the raw
data file and after aligning the peaks I go for peak identification. I have
tried only pubchem as of now.

Also, I converted my raw data to MZXML using some online software as the
one exported from LCMS machine is not recognized by the MZmine software.
So, after importing the data, i get a folder which has many files. And when
i click on one file and try to see its TIC is shows the whole chromatograms
(i.e. peaks for RT 0.0 to 30 mins). I hope I have answered your question.

Kindly find the error that pop up while running it for peak identification.
And after error it stops completely and does not show any results (even the
first quarter of the list).

Thank you for your efforts.

Regards,
Shweta

**Comment by Annexhc** [comment]
I suggest to try different databases to check if there is a problem with your aligned peaks list or the database search module. Also try the database search on a non aligned feature list to check if there is a problem.

"Also, I converted my raw data to MZXML using some online software as the
one exported from LCMS machine is not recognized by the MZmine software."
 
Which software did you use? You may try something like MSConvert. You can also try to convert your data to mzML, redo your workflow in MZmine and try the database search again.
