### ISSUE TITLE
Calculate RI Values

### ISSUE THREAD

**Issue by Nexater** [mzmine/mzmine2#436]
Hey I like the idea of this tool. Until now I am using AMDIS to check my GC/MS runs for metabolites. As I am aware mzmime is using RT values for database search? It would be good to calculate RI (retention index) values, because RT will change with the Ramp the GC is using or with the column you are using. When I did the NIST Database search non of the compounds is right, not even stuff like Phenylethylalcohol...Or am I doing somethong wrong?

**Comment by robinschmid** [comment]
Duplicate to #691 
Should be closed
