### ISSUE TITLE
Mass list not created after running mass detection

### ISSUE THREAD

**Issue by rasikaphansalkar** [mzmine/mzmine2#437]
### Setup

I am reporting a problem with MZmine 2 version 2.32
My operating system is Windows 7, 64-bit

When I perform mass detection, the "task in progress" bar says status finished.
But there is no green check mark and no mass list is being created. I am working with raw .mzxml files

Not sure what I am doing wrong.

**Comment by amariagallego** [comment]
I got the same issue. Im working with windows 10 64-bit and mzxml files.
I run mass detection 4 hours and nothing happend. The green tick does not appear.

Thanks for your help!

Adriana

**Comment by amariagallego** [comment]
I solve it. When you go to
- Raw data methods/peak detection/mass detection
-  Click set filters, then 
- Click spectrum type, choose profile

Then, the program will show a pop up, you say ok and then the green tick appear

Regards

Adriana

**Comment by ejm339** [comment]
Hi Adriana, thank you for your suggestions. I'm also having the same problem with only some of my samples - 2 out of 8 samples do not finish mass detection with a green check and no mass list is created. I tried your suggestion but this did not help me (probably because before the spectrum type was set to 'any', so it didn't matter). Do you have any other ideas?

**Comment by tomas-pluskal** [comment]
https://mzmine.github.io/support.html#Issues

**Comment by arm47** [comment]
Hello,
I have the same problem when running marine 2 in a Mac, with netcdf files. Someone already solve the problem?

**Comment by lottaHO** [comment]
Hello,
I´m having the same problem for some files as described above.  The suggestion by Adriana did not work :( Did anyone solved this problem?

**Comment by tomas-pluskal** [comment]
There is no problem to be solved here. 
If you need help with using the software, follow the instructions: https://mzmine.github.io/support.html#Issues
