### ISSUE TITLE
Unable to export as .MGF file

### ISSUE THREAD

**Issue by Neelutpal** [mzmine/mzmine2#440]
I am unable to export the spectral data as .MGF format. Although it is created in the destination folder, but the file size is 0 kb. What might be the problem?

**Comment by lfnothias** [comment]
Are you trying to get MS2 spectra from your data ?

**Comment by Neelutpal** [comment]
Ya.....I have tried both, LC-MS and LC-MS/MS data...

**Comment by asmirn1** [comment]
It seems that there are currently two functions for exporting into .MGF: one is _Export to MGF file_ and another _Export for GNPS_. Have you tried them both? 

If none of them works, could you provide your .mzmine project file for testing?

**Comment by Neelutpal** [comment]
Ok, I will try with both function once more, if again problem arise, i will give you my file.

**Comment by Neelutpal** [comment]
I am able to export as .MGF file for MS/MS data in GNPS format. I but regarding MS data I am not able to do the same? So these function will work only for MS/MS data not for MS data. Am I right? Or there is any way to export MS processing data in .MGF format?

**Comment by lfnothias** [comment]
Yes that’s right. GNPS export works on the MS/MS level.
I am not sure if there is a way to batch export MS1 spectrum from a peaklist.
