### ISSUE TITLE
Unable to import .RAW files

### ISSUE THREAD

**Issue by selffi** [mzmine/mzmine2#445]
### Setup

I am reporting a problem with MZmine 2 version. I could not import .RAW files in MZmine. 
My operating system is Linux 16 with 64 bit 
When I try to upload my .RAW files, I got the following error:
"java.lang.Exception: No scans found (NativeFileReadEr.java.149)

Is there any problem with my .raw files?

**Comment by Annexhc** [comment]
Hi selffi,
.raw does not work under Linux, because .raw needs Thermo libraries only supported on windows. You can use MSConvert to convert .raw in .mzML on a windows machine. The .mzML format will work on a Linux system.
