### ISSUE TITLE
cannot import thermo raw data in window 7 (64 bit)

### ISSUE THREAD

**Issue by mamn123** [mzmine/mzmine2#447]
### Setup

I am reporting a problem with MZmine 2 version (MZmine-2.33). 
My operating system is (window 7, 64-bit ).
R-3.5.1
JAVA 8 Update 171 (64-bit)

Below I pasted the exact output of the following commands:
![image](https://user-images.githubusercontent.com/37838467/42647191-ceb85df2-8635-11e8-9549-d1b0f595ffe0.png)
![image](https://user-images.githubusercontent.com/37838467/42647197-d3a254bc-8635-11e8-964c-9cee8febf6c8.png)

j
![image](https://user-images.githubusercontent.com/37838467/42647131-a7b0c7c6-8635-11e8-857f-0a3093aab26e.png)

### Steps to reproduce the problem

(*Please fill this in *)

**Comment by tomas-pluskal** [comment]
Try to avoid spaces in filenames - move mzmine out of the “installed software” folder or rename it.

**Comment by mamn123** [comment]
@tomas-pluskal 
oh, I am sorry, it seems like that this action is not useful for this issue.

![wechatimg40](https://user-images.githubusercontent.com/37838467/42671074-d8b40c2e-8690-11e8-8723-a01ca9a1c9f2.jpeg)

**Comment by tomas-pluskal** [comment]
Does the thermorawdump.exe program exist in that folder? Try running it in the windows command line and see what happens.

**Comment by mamn123** [comment]
@tomas-pluskal 
Nope, there is no folder in that pathway:

![wechatimg42](https://user-images.githubusercontent.com/37838467/42671294-e9b21e2a-8691-11e8-8efe-cc567e763989.jpeg)

**Comment by tomas-pluskal** [comment]
No wonder it doesn’t work for you. Try downloading MZmine again and make sure you extract all files including the vendor_lib folder.

**Comment by mamn123** [comment]
Yes! It worked well. Thank you very much. Cause it almost make my crazy during these days.
Thank you a bunch, again!

Best wishes,
Mengna


在 2018年7月13日，上午11:47，Tomáš Pluskal <notifications@github.com<mailto:notifications@github.com>> 写道：


No wonder it doesn’t work for you. Try downloading MZmine again and make sure you extract all files including the vendor_lib folder.
