### ISSUE TITLE
Error while executing MZmine 2.33 on cluster

### ISSUE THREAD

**Issue by bioinforider** [mzmine/mzmine2#448]
### Setup
I cloned the github environment on the cluster
I am receiving the error as below with MZmine 2 version (2.33). 
My operating system is (* 64-bit *).

Processors | Intel Xeon E5-2670 (Sandy Bridge) 2.6 GHz (2.7 with turbo); 8 cores
-- | --
Memory | 128GB DDR3 1600 MHz (8 GB/cores)
Storage | 2×300 GB SAS 15krpm (RAID 1)

Below I pasted the exact output of the following commands:
```
jFound 128576 MB memory
Java maximum heap size set to 130000 MB
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (IcedTea 3.6.0) (build 1.8.0_151-b12 suse-27.8.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

Error: Could not find or load main class net.sf.mzmine.main.MZmineCore
```

**Comment by tomas-pluskal** [comment]
Don't clone the github repo, try downloading the latest release instead.
