### ISSUE TITLE
 Failed opening project

### ISSUE THREAD

**Issue by Messahra** [mzmine/mzmine2#451]
### Setup

I am reporting a problem with MZmine 2 version (*2.29*). 
My operating system is (*windows 10 64-bit *).

Below I pasted the exact output of the following commands:
```
java -Version 8 Update 181

 Failed opening project: java.util.zip.ZipException: invalid code lengths set (null:-1)
```

### Expected behavior

I use mzmine at windows 8.1 . windows 8 does not arrise any trouble.

### Actual behavior

Windows 10 PC note (32gb memory interl i-7)  does not work on mzmine2. file does not open .

### Steps to reproduce the problem

I redownroad JAVA again.
I redownroad mzmine 2.29 2.32 again.
I restarted windows.
My IE says JAVA is working.

I want to run mzmine by my PC(notebook) also..

**Comment by tomas-pluskal** [comment]
Try downloading the sample project from MZmine website. Does that one open correctly?
