### ISSUE TITLE
Chromatogram Builder Yields Empty Peak List

### ISSUE THREAD

**Issue by atostengard** [mzmine/mzmine2#452]
### Setup

I am reporting a problem with MZmine 2 version 2.33. 
My operating system is Windows 10, 64-bit.

```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

After importing an .mzML file and successfully using mass detection, I tried to use the chromatogram builder. The message says it was successfully completed and there were no error messages, but when I click on the peak list, it's empty. The .mzML is too large to attach here but I can provide it if needed.

Thanks!

**Comment by tomas-pluskal** [comment]
Without seeing the mzML file **and** the exact parameter values you used in each step, how could we possibly give you any advice?
