### ISSUE TITLE
"Cannot read batch file..."

### ISSUE THREAD

**Issue by Kevin-Murray** [mzmine/mzmine2#461]
### Setup
I am reporting a problem with MZmine 2 version 2.33. 

### Issue
I am encountering an issue when attempting to run MZmine 2.33 in batch mode on the command line. I created a simple test XML file to ensure that the software operated properly on the command line, created using the 'Batch mode' tool under the Project menu. On every attempt to run this file, I receive an error indicating the the batch file cannot be read. I have tried using multiple OS, new batch XML/txt files, and a different version of MZmine (2.32). It is unclear from the documentation if Batch mode must be set-up or initialized prior to use. I would greatly appreciate some advice on this issue.

My command line operation: "./MZmine-2.33/startMZmine_MacOSX.command test.xml"

My Batch XML is:
```
<?xml version="1.0" encoding="UTF-8"?>
<batch>
    <batchstep method="net.sf.mzmine.modules.rawdatamethods.rawdataimport.RawDataImportModule">
        <parameter name="Raw data file names">
            <file>/USERS/murra668/Desktop/mccu0173_murra668_20170929_16488_RPC18_POS_pooled_11.mzML</file>
        </parameter>
    </batchstep>
    <batchstep method="net.sf.mzmine.modules.rawdatamethods.peakpicking.massdetection.MassDetectionModule">
        <parameter name="Raw data files" type="BATCH_LAST_FILES"/>
        <parameter name="Scans">
            <ms_level>1</ms_level>
            <scan_definition/>
        </parameter>
        <parameter name="Mass detector" selected="Centroid">
            <module name="Centroid">
                <parameter name="Noise level">1.0</parameter>
            </module>
            <module name="Exact mass">
                <parameter name="Noise level"/>
            </module>
            <module name="Local maxima">
                <parameter name="Noise level"/>
            </module>
            <module name="Recursive threshold">
                <parameter name="Noise level"/>
                <parameter name="Min m/z peak width"/>
                <parameter name="Max m/z peak width"/>
            </module>
            <module name="Wavelet transform">
                <parameter name="Noise level"/>
                <parameter name="Scale level"/>
                <parameter name="Wavelet window size (%)"/>
            </module>
        </parameter>
        <parameter name="Mass list name">masses</parameter>
        <parameter name="CDF Filename (optional)" selected="false"/>
    </batchstep>
</batch>
```

### Error Message 

[21:25:40|SEVERE|MZmineCore]: Cannot read batch file test.xml

### OS
My operating system is MacOSX 10.11.6 (I have also tried using Windows 10 Home and Linux 2.6.32).

### Java and R Version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

R version 3.4.3

**Comment by tomas-pluskal** [comment]
This is probably caused by the fact that you are starting MZmine from a different folder than the actual MZmine folder. One these two should help
1. Use an absolute path for your text.xml
2. Start MZmine from the MZmine-2.33 folder:
```
cd ./MZmine-2.33
./startMZmine_MacOSX.command ../test.xml
```

**Comment by Kevin-Murray** [comment]
Thank you very much. That solved the issue.
