### ISSUE TITLE
Error with centroid data mass list generation

### ISSUE THREAD

**Issue by MuyMal** [mzmine/mzmine2#483]
Hello,

I am reporting a problem with MZmine 2 version 2.34 (tried on 2.3 as well and also did not work). 
My operating system is Windows 10 (Version 1709, build 16299.665) 64-bit.

java -8.0.1810.13
R --R x64 3.4.1

When I went to generate mass lists using the following menus and commands:

Raw Data, Peak Detection, Mass Detection
Filters: MS level 1 (tried 2 as well), Polarity +, Spectrum type centroided (tried "Any" as well, and while that fixed the problem it *significantly* increased the amount of time it took for the module to finish)
Mass detector = centroid (data was collected in centroid mode), when I show preview, it correctly shows red and blue peaks indicating the ones that will not be included in the mass list because they fall below the noise level.

However, when I click OK on everything to actually run the module, it gives me the following error:

"None one of the selected files contain centroided data points. The selected mass detector could give unexpected results."

![image](https://user-images.githubusercontent.com/29641179/45891743-57c2e500-bd94-11e8-9dce-9d0a6bd21671.png)

The mass list it generates is indeed erroneous, as it includes every peak, and doesn't filter the ones that fell below the noise limit.

Please let me know if you'd like to see/use one of the files I've been working with. I haven't seen this error before with Orbi Velos Pro data, but since switching to the Q-Exactive instrument, all of those files give the same error. 

Is there any additional information you need?

Thank you for your time,

Mallory

**Comment by Annexhc** [comment]
Do you use .raw files or .mzML? You should try to use profile data and exact mass detector. I than get good peak picking results with q exactive data.

**Comment by MuyMal** [comment]
Well folks, I changed a whole lot of things, including downloading a new R/Java, re-importing the files, and playing with a few of the parameters (including the ones Annexhc recommended, thanks!), and it does seem to be working now. Not sure which of the things fixed the issue though.
