### ISSUE TITLE
Possible to bulk label peak rows in aligned peak list?

### ISSUE THREAD

**Issue by chemnerd1** [mzmine/mzmine2#487]
Is it possible to assign labels/IDs to rows in an aligned peak list without using one of the Database Search modules? For instance is it possible to export a peak list using Export to CSV, then we can add labels to the "ID" column, and then import that list back into Mzmine?

**Comment by tomas-pluskal** [comment]
Yes. Check the Peak list methods / Identification / Custom database search module.
