### ISSUE TITLE
Export to csv. missing data

### ISSUE THREAD

**Issue by NicoleBale** [mzmine/mzmine2#488]
### Setup

I am reporting a problem with MZmine 2 version 2.31. 
My operating system is Windows 10, 64-bit

### Expected behavior

Created "Aligned peak list filtered gap-filled" from a series of mzXML files.
Then wanted to export the peak list table to a .csv file (Peak list methods, Export/Import, Export to csv.)
Expect ~400,000 features (as per peak list table)

### Actual behavior

After export to csv. the file only contains the first ~2500 features (of ~400,000)

**Comment by tomas-pluskal** [comment]
Strange thing. Could you upload somewhere (e.g., Dropbox) the .mzmine project file and the CSV file that you obtained?

**Comment by NicoleBale** [comment]
Thank you for your quick reply. I was having another look at the issue this morning and it seems to be working fine now. I will come back if I see such an issue again. Many thanks.
