### ISSUE TITLE
Limit number of threads during batch?

### ISSUE THREAD

**Issue by RachelGregor** [mzmine/mzmine2#491]
Hello,

I want to run a batch from the command line on my lab server, but I need to limit the number of threads it will use to 25. 

I'm running MZmine v 2.34, our OS is Ubuntu 14.04.5 LTS (GNU/Linux 3.19.0-80-generic x86_64).

When I work in the GUI, I set the number of cores through the preferences, but it doesn't seem to save this.

The command I was planning to run is:
nohup sh ./startMZmine_Linux.sh batch.xml  > out 2> err &

Is there an environment variable I can add, or make a permanent edit in the config file?

I see the previous issue that was opened around this: https://github.com/mzmine/mzmine2/issues/294
If I understand correctly, limiting the heap size will not limit the number of threads I am using though, correct?

Thank you!

Rachel

**Comment by Annexhc** [comment]
Haven't used nohup myself, but i think it would be easier to limit the number of tasks there. You could use something like a taskset. 
Maybe this post helps:
https://unix.stackexchange.com/questions/319164/does-nohup-place-each-process-on-one-core-specifically

**Comment by tomas-pluskal** [comment]
Hi Rachel,

The number of parallel tasks that you set in the Preferences **is** saved into the configuration file (conf/config.xml) and should be respected when the batch is executed. You can just use the same config file for your batch setup, or you can also edit the config file in a text editor.

Tomas

**Comment by RachelGregor** [comment]
Great, thanks to both of you for the quick responses!

So just to double check, this is the current line in the config file, after I have set the concurrently running tasks to 25 using the GUI:

<parameter isautomatic="false" name="Number of concurrently running tasks">25</parameter>

Should that be set to "true", or is it good like this?

Thanks again!

Rachel

**Comment by tomas-pluskal** [comment]
Looks correct to me.
