### ISSUE TITLE
How to run batch using command line

### ISSUE THREAD

**Issue by user98365** [mzmine/mzmine2#499]
The MZmine manual states: "If the startMZmine... script is supplied with a command line parameter, this parameter is treated as a batch queue file (see Batch mode). In such case MZmine is started as a command-line application and the batch file is loaded into the batch mode module and executed."

Does this mean that MZmine batches can be run using only the command line? This would be helpful for doing analyses on a remote server that I can only access through ssh (i.e. no GUI support).

If so, what would the command line look like in the batch file? I'm still very new when it comes to using command line interface.

Thank you Dr. Pluskal!

**Comment by tomas-pluskal** [comment]
Hi, 
yes MZmine batches can be run using command line. Just create a batch, save it as a .xml file and run the startMZmine script with the xml file name as a parameter.
