### ISSUE TITLE
ADAP Chromatogram construction fails

### ISSUE THREAD

**Issue by nareshibt** [mzmine/mzmine2#501]
### Setup

I am reporting a problem with MZmine 2 version (2.34). 
My operating system is (Windows 7 64-bit).

I tried using both RAW file, converted it to MzXml format, the error appears on both instances.

[2:30:51|SEVERE|WorkerThread]: Unhandled exception java.lang.IllegalArgumentExce
ption: Invalid range: (305.1788330078125..305.1788330078125) while processing ta
sk Detecting chromatograms in D2_cells_alone.mzXML(java.lang.IllegalArgumentExce
ption: Invalid range: (305.1788330078125..305.1788330078125)@com.google.common.c
ollect.Range.<init>(Range.java:352))
java.lang.IllegalArgumentException: Invalid range: (305.1788330078125..305.17883
30078125)
        at com.google.common.collect.Range.<init>(Range.java:352)
        at com.google.common.collect.Range.create(Range.java:155)
        at com.google.common.collect.Range.open(Range.java:167)
        at net.sf.mzmine.modules.masslistmethods.ADAPchromatogrambuilder.ADAPChr
omatogramBuilderTask.run(ADAPChromatogramBuilderTask.java:312)
        at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:58)java -version

**Comment by nareshibt** [comment]
I found a way around, I performed peak picking using msconvert (centroided the peaks). That solved the problem in this particular file (D2_cells_alone.mzXML).

But centroiding all my files is not helping. Because centroiding gives the same error on other files, which doesn't have the problem when used as mzxml file.

In this case I am using two different algorithms for mass detection based on the input file format

For RAW and mzxml files I will be using local maxima 
For centroided files (saved as mzxml file) I will be using centroided algorithm

But I am using ADAP chromatogram builder after mass detection on all my input files. 

Is this a right approach ?

**Comment by asmirn1** [comment]
Hi @nareshibt could you share one of mzXML files you are using?

Your steps (mass detection and then chromatogram building) seems right to me. Let me try to process your files myself and see what causes the error.

**Comment by nareshibt** [comment]
Hello @tomas-pluskal @asmirn1 and @duxiuxia thank you so much for taking your time to help me.

I have put two files in dropbox
https://www.dropbox.com/sh/91fdvl544olwfu1/AADnqyjvkYaBtO1rIv2EALLLa?dl=0

The blank.RAW and D2_cells_alone.mzXml gives error while using ADAP chromatogram builder. The chromatogram construction works fine for positive polarity. But it doesn't work for negative polarity.

I have also updated the screenshots of the parameters I used in the powerpoint file.

The blank file when converted to mzXml format using MSconvert, doesn't give rise to any errors. Interestingly, the D2_cells_alone doesn't show any error when used as RAW file.

I am not a veteran in programming, I am really looking forward for your comments and suggestions.

Thanks for all your help.

-Naresh

**Comment by asmirn1** [comment]
Hi, I think I have fixed this bug. @nareshibt you can download the updated version of MZmine 2 with this bug fixed, using this [link](https://github.com/mzmine/mzmine2/tree/master). Is that right, @tomas-pluskal?

Let me know if you are still experiencing this error.

Alex

**Comment by tomas-pluskal** [comment]
@asmirn1 , just downloading the master branch won't work, unless the user builds MZmine by himself/herself. You need to run 'mvn package' to prepare a release for them. I also recommend to update the version number in the pom.xml (e.g. 2.35.1).

**Comment by asmirn1** [comment]
@nareshibt Could you tell us how you download, install and run MZmine 2, and then we'll be able to help you update your version of MZmine.

**Comment by nareshibt** [comment]
I download the .zip file, extract and run the startMZmine_Windows.bat

**Comment by asmirn1** [comment]
@nareshibt Here is a link to a new version of mzmine with that bug fixed:
https://drive.google.com/file/d/1nQ3SGmVkzw6Xqtnxt2Z-p3UV0HAYQSbF/view?usp=sharing

Could you try to use this version and see if it works for you?

**Comment by nareshibt** [comment]
@asmirn1 it works, this is really awesome.

Thank you all for your help.

Best regards,
Naresh

**Comment by asmirn1** [comment]
@nareshibt You are welcome! Let us know if you have any other problems with ADAP Chromatogram Builder.
