### ISSUE TITLE
Issue wuth exporting as mzTab

### ISSUE THREAD

**Issue by YasinEl** [mzmine/mzmine2#508]
When exporting an aligned peak list as mzTab (30 samples) only 20 of them show up in the exportet mzTab. Exporting as csv works fine.

[blood30_dataset_mzMine_4.txt](https://github.com/mzmine/mzmine2/files/2576356/blood30_dataset_mzMine_4.txt)

Would be great if someone could help me out with that. Thanks for your time and effort.

**Comment by tomas-pluskal** [comment]
Hi,
Could you upload your .mzmine project file somewhere and specify the exact parameter values that you used for export?

**Comment by YasinEl** [comment]
Thank you for the quick response.

https://my.pcloud.com/publink/show?code=kZOKzT7ZTEhlttTb0LHkOFIHbJwWLXLH5iOV

I chose "aligned peak list" for export as mzTab file and checked the "include all peaks" box. There are no other parameters available as far as I can see.

**Comment by YasinEl** [comment]
Should I load it up somewhere else or is it alright like that?

**Comment by tomas-pluskal** [comment]
It's alright. Give me some time.

**Comment by YasinEl** [comment]
Sure, thank you a lot for you effort!

**Comment by tomas-pluskal** [comment]
This seems to be a problem in the underlying jmzTab library. I filed an issue there: https://github.com/PRIDE-Utilities/jmzTab/issues/11

**Comment by YasinEl** [comment]
Great, thanks a lot!
