### ISSUE TITLE
WARNING|MzMLElement

### ISSUE THREAD

**Issue by metabolon1** [mzmine/mzmine2#512]
### Setup

I am reporting a problem with MZmine 2 version 2.36. 
My operating system is Linux version 2.6.32-642.13.1.el6.x86_64 (mockbuild@c1bm.rdu2.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Wed Jan 11 20:56:24 UTC 2017.

Below I pasted the exact output of the following commands:
```
java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

R --version
-bash: R: command not found

```

### Expected behavior

Batch runs as expected.

### Actual behavior
Shortly after starting the batch--during raw file import--I get the following message and then no further progress.
```
[15:06:36|WARNING|MzMLElement]: MzIdentML Configuration file: jar:file:/scratch/user/MZmine-2.36/lib/jmzml-1.7.10.jar!/defaultMzMLElement.cfg.xml

```
### Steps to reproduce the problem
Start a batch run using the command line.

**Comment by tomas-pluskal** [comment]
This warning is normal, doesn't indicate any problem.

**Comment by tomas-pluskal** [comment]
Closing this issue for now, unless more information is provided.
