### ISSUE TITLE
problem generating mgf (error java:326)

### ISSUE THREAD

**Issue by eligaro** [mzmine/mzmine2#514]
### Setup

I am reporting a problem with MZmine 2 version (*2.34*). 
My operating system is (*MacBookPro(Retina, 2.3 GHz intel core i7 *).

Below I pasted the exact output of the following commands:
```
java -version
R --version
(*Please copy-and-paste the output here*)
```

### Expected behavior

(*Please fill this in*)

### Actual behavior

(*I wanted to export to mgf and got the mzmine error message: error while exporting to SIRIUS: java.lang.NUllPointerException (SiriusExportTaks.java:326*)

### Steps to reproduce the problem

(*Please fill this in *)

**Comment by tomas-pluskal** [comment]
Can you upload a project file that demonstrates this issue?

**Comment by eligaro** [comment]
Sorry, I am new to this. My file is 26MB and doesn’t want to be uploaded

**Comment by tomas-pluskal** [comment]
Use DropBox?

**Comment by robinschmid** [comment]
Did you run mass detection on all MS2 scans or did you use a scan filter?
(Or do you have MS3 scans?)

**Comment by eligaro** [comment]
https://www.dropbox.com/s/vq31ht79xqqbafo/A_Argyi_EtOAC.mzmine?dl=0

**Comment by eligaro** [comment]
Thanks for your advises. I am out of office today. I will try as soon as I am in again.

**Comment by eligaro** [comment]
[cid:image001.png@01D48AEB.2CBCDEF0]

**Comment by eligaro** [comment]
Sorry for the late answer. You are right. I indeed forgot the MS2 mass detection.
Thanks a lot for your help,
Have a nice day,
Eliane
