### ISSUE TITLE
Bruker files converted by Proteowizard (MSConvert) to mzML - fails to get load 

### ISSUE THREAD

**Issue by AndreasBergmannWerben** [mzmine/mzmine2#520]
Dear Thomas,

I have tried to use MZmine on Bruker .d-files (impact QToF) which I have converted into MZmL format. When I want to import these MZmL-files into MZMine, I got the following error-message (see screenshots). The version of MZMine is the 2.37 that has been released recently. Also the the ProteoWizard is up to date. 
Partho Sen has said that you might have a clue how to proceed in this case.

Thank you very much for any suggestion in advance.
Best wishes,
Andreas

![problem import](https://user-images.githubusercontent.com/45691131/49652060-a13cdb00-fa39-11e8-8dc7-0e04b5ee8669.PNG)
![problem import 2](https://user-images.githubusercontent.com/45691131/49652061-a13cdb00-fa39-11e8-90be-e3f2a520c611.PNG)

**Comment by tomas-pluskal** [comment]
Hi,
I don't see any error in the console output.

**Comment by AndreasBergmannWerben** [comment]
Hi Tomas,

sorry for my late response. Finally, the import works with files that I have converted to MZxmL format. Maybe something went wrong in the conversion to MZmL-format before. 
I will try processing now and let you know, if there are further problems.

Thanks so far, already,
Andreas

**Comment by sapnatars** [comment]
I am trying to import a batch of files in .mzXML format into mzmine 2. it shows the following javascript error:
java.lang.NumberFormatException: For input string""
(NumberFormatException.java:68)

**Comment by sapnatars** [comment]
please suggest if you have any ideas for resolving this

**Comment by tomas-pluskal** [comment]
Open a new issue for this and upload the file so we can take a look at it

**Comment by sapnatars** [comment]
Thanks Tomas. Ill do that rightaway
