### ISSUE TITLE
Is there anyway that CSV file format can be imported as data?

### ISSUE THREAD

**Issue by Rennepink** [mzmine/mzmine2#525]
### Setup

I am reporting a problem with MZmine 2 version (*Please fill this in*). 
My operating system is (*Please fill this in, including version number and 32-bit or 64-bit *).

Below I pasted the exact output of the following commands:
```
java -version
R --version
(*Please copy-and-paste the output here*)
```

### Expected behavior

(*Please fill this in*)

### Actual behavior
Hi,

My data file is in csv format. I tried it import it , but I get "Unspecified error".
Is csv file supported by mzmine?

Thanks,
Nasim

**Comment by tomas-pluskal** [comment]
CSV stands for "comma-separated values". I think you need to provide more details.

**Comment by Rennepink** [comment]
Yes, my data is in "comma-separated values" format, Which is an ASCII text format with each field delimited by commas. It contains peaks and abundance, and dummy values for retention time.

**Comment by tomas-pluskal** [comment]
So, is the file format defined anywhere?

**Comment by Rennepink** [comment]
Sorry I am not sure if I follow, but maybe this wikipedia helps? 
https://en.wikipedia.org/wiki/Comma-separated_values

**Comment by photocyte** [comment]
The point is that CSV is not a well defined data structure, and can be quite variable from different sources.  It almost certainly doesn't make sense for MZmine2 to implement importing of one specific CSV format.  Both ProteoWizard msConvert and OpenMS may have a tool to convert a CSV (if it is a generalized format that those developers have come across before) into a more well defined LC/MS file format.  If not, you may be able to write a script to convert it to an existing format.

**Comment by Rennepink** [comment]
Thanks for your comments! I did try MSconver from ProteoWizard, there is no csv import there also. I try to write a code to convert my csv to convertable format then! Thanks
