### ISSUE TITLE
export in GNPS

### ISSUE THREAD

**Issue by eligaro** [mzmine/mzmine2#527]
Hello,

My export for GNPS is not working properly. I am working with MzMine version 2.37 on a mac MacbookPro. 

I did select the Peak list filtered, then select in Peak List Method, Import/Export then Export for GNPS.
The process starts, there are three different tasks in the task window, but then nothing happen. The status of the processing bar say to zero and it doesn't move.

It did work last month though, and now not anymore.
Any idea why its not working? 

you can find my files:
https://www.dropbox.com/s/3iar965as27ct4w/A_Argyi_GE_EtOAC_FragDNP.mzmine?dl=0

Thanks a lot for your support,
Eliane

(*Please fill this in, and paste any relevant exceptions, log messages, and screenshots*)

**Comment by tomas-pluskal** [comment]
@robinschmid Could you take a look at this issue?

**Comment by tomas-pluskal** [comment]
@eligaro Please specify the exact parameter values you used to run the GNPS export module.

**Comment by robinschmid** [comment]
Hey, 
I am going to try it. What are the exact parameters?
Did you use the new submit function?

**Comment by robinschmid** [comment]
I think I figured out your problem. Go to Project/Set preferences 
Is your Number of Tasks set to 1? This would stop it as one task is waiting for the other ones to finish. 
Just set it to automatic. 

Tomas, I know that many people do not even know of this feature. Maybe we should show a message if this setting is way below the maximum.

![image](https://user-images.githubusercontent.com/10366914/50048220-1718f600-007b-11e9-9860-108df43d5f25.png)

**Comment by eligaro** [comment]
Thanks a lot Robin.
That’s great. I indeed had this parameter set manually to 1. I modified it as suggested and export to GNPS and it seems to be partially working. The soft is still stuck on Task 1. I did export without submit to GNPS, because I want to do it offline first to make sure it works. When I click on OK, it quickly performs the task 2 and 3, but task 1 is still on processing and stay like that? Is this normal?
I then obtain two files: one name_quant.csv and another one name.mgf. what is the difference? Do I need to upload both into GNPS?
Thanks a lot
[cid:image001.png@01D495EB.4AFA0720]

**Comment by robinschmid** [comment]
I have fixed this issue in PR #528 

Yeah there was a little bug that you needed to select at least one of the two options: open folder or submit to GNPS.

We are going to prepare a video on GNPS job submission. However, the submit function is a very fast and easy way to run a GNPS job. Just use the website that pops up, log-in and click on clone job. This allows you to specify more parameters and to clone the job into your local account.

You can also go to 
http://mingwangbeta.ucsd.edu:5050/featurebasednetworking

and drop the files in the correct boxes. The mgf holds all fragmentation spectra and the csv quant table is the mzmine table.

Cheers,
Robin

**Comment by robinschmid** [comment]
Yeah we should definitely link it. There is also more MZmine related material on the GNPS documentations website. @mwang87 what do you think?

**Comment by mwang87** [comment]
@robinschmid @tomas-pluskal 

Definitely, we'd be happy to include the documentation over there. The other tutorial videos we've created are:

MZMine2 Feature Detection   - https://www.youtube.com/watch?v=5jjMllbwD-U
MZMine2 -> GNPS Basic Feature Based Molecular Networking - https://www.youtube.com/watch?v=NTkQ0fS1aug

We're making a few new updates to the GNPS documentation for MZmine2 output, but our guide for MZmine2 interacting with GNPS are available in writing here:

https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking/#feature-based-molecular-networking-in-gnps

This is all written in markdown so if you would like to transplant hopefully it will be easy.

Happy to help!

Ming

**Comment by robinschmid** [comment]
This should be resolved
