### ISSUE TITLE
Appropriate Parameter Range for Wavelet Transform

### ISSUE THREAD

**Issue by atostengard** [mzmine/mzmine2#530]
I am running a big evaluation of segmentation algorithms, and am using a grid search of parameters to test a range for each. I have seen others use values for scale level of 1-10, but would highly value any input on what the best range of reasonable values for this parameter would be.

Thank you!

**Comment by tomas-pluskal** [comment]
Which module are you referring to, specifically?

**Comment by atostengard** [comment]
The scale level for wavelet transform.

**Comment by tomas-pluskal** [comment]
Argh. Which module are you referring to, specifically?

**Comment by atostengard** [comment]
Sorry, I'm talking about the mass detection module under peak detection, and then about the scale level parameter for the wavelet transform algorithm.

Thank you for your time!

**Comment by tomas-pluskal** [comment]
I'd say 1-10 is a reasonable range. This module was developed a long time ago, but it has never really been thoroughly evaluated.

**Comment by atostengard** [comment]
Thank you so much!
