### ISSUE TITLE
Mzmine 2.30 and 2.33/2.36 somethings changed with export to csv?

### ISSUE THREAD

**Issue by lemberger** [mzmine/mzmine2#535]
My operating system is Windows 10 Education, 64 bit

Hello everyone, 

I have a strange little problem. We use a Matlab Script to do the background subtraction after we run mzmine. The data from mzmine is exported to a csv sheet and from there imported into Matlab. If process data with Mzmine 2.30 and then export into csv and from there into Matlab everything runs perfectly fine. 
Problem: If I process data with newer versions mzmine 2.33 or 2.36 (same data, same computer, everything exactly the same, all the settings for exporting the csv same) the Matlab script produces an error (importing the csv file works and also some pre-processing but somewhen in the script I get errors). I'm not really experienced and I'm only using the Matlab script, I didn't write it. But as there is no problem with data from older mzmine versions and nothing else changed it doesn't seem that the problem is with the Matlab script.
Also if I load mzmine projects which I processed with mzmine 2.36 into mzmine 2.30 and export from there to csv, the Matlab script produces an error. I asked a colleague to send me his csv sheet from mzmine 2.30, so processed and exported on a different computer, it worked in the Matlab script. But not from newer versions. 
I looked at the data from old and new versions in excel, everything seems to be alright and looks the same (no problem with the seperators or the data etc)

Can anyone imagine any change in mzmine after version 2.30 which leads to problems with csv data? Again I'm not experienced so sorry if that's a kind of a stupid question but I didn't find a solution and I would like to always use the newest mzmine version. Thanks in advance for looking at the problem :)

**Comment by tomas-pluskal** [comment]
That's not enough information. Please attach the CSV files exported by both versions. Please specify what error exactly are you getting.

**Comment by lemberger** [comment]
Yes csv file are exactly the same, same order, same everything, as I did everything with the same batch mode. I deleted both mzmine versions and Java and reinstalled everything, now it works again, with mzmine 2.30 and 2.36.
