### ISSUE TITLE
MassBank search

### ISSUE THREAD

**Issue by tsufz** [mzmine/mzmine2#536]
MassBank.jp will be down until April 2019 and thus the search should be removed as long it is not available again. The new server software uses a different URL scheme. Needs to be updated. @meier-rene and @tomas-pluskal, we may also think about to improve search by using our new RESTful API (still in development).

**Comment by tsufz** [comment]
I will fix the URL issue

**Comment by tomas-pluskal** [comment]
@tsufz Is there a specification of the API?

**Comment by tsufz** [comment]
@tomas-pluskal, the API is very basic so far. @meier-rene can help with it.
