### ISSUE TITLE
GUI Font too small and did not scale

### ISSUE THREAD

**Issue by fdiversion** [mzmine/mzmine2#537]
On Windows 10 as well as Linux (Ubuntu 18.10 and Manjaro) and diffenent Java versions the GUI fontsize (menue, dialog boxes) is very small on higher res displays (i.e. FullHD on 14" laptop).
It even don't scall with the OS settings.

I have no exerience with java and the GUI frameworks used there (JavaFX?), is there any default option that can be changed?

For me, it is nearly unusable on my laptops.

regards 
Frank

**Comment by fdiversion** [comment]
Yes 1920x1080.
Java 8 on Win10 and up to 11 on Linux.
I've attached a Screenshot with Win10 Scaling of 150%
If you change this Windows scaling, there is no change in mzMine. 
I need to use a lower screen resolution like 1366x768.
![Uploading mzmine.jpg…]()

**Comment by fdiversion** [comment]
Yes, 1920x1080.
Java 8 on Win10, OpenJDK 8 to 11 on Linux.
Windows Scaling has no effect, I need to reduce the screen resolution.

**Comment by fdiversion** [comment]
Yes, 1920x1080.
Java 8 on Win10, OpenJDK 8 to 11 on Linux.
Windows Scaling has no effect, I need to reduce the screen resolution.

**Comment by fdiversion** [comment]
OK, solved.
By manually adding Openjdk 11 to Win10 it works.

**Comment by robinschmid** [comment]
Yeah this is also my suggestion. Automatic scaling of swing components was added in java 9, if I am not mistaken. JRE10 should also work. Or openjdk
