### ISSUE TITLE
Error using MZMine 2.37 with LipidMatch Flow

### ISSUE THREAD

**Issue by jkmunk** [mzmine/mzmine2#540]
### Setup

I am reporting a problem with MZmine 2 version 2.37. 
My operating system is Windows 7 64-bit.

Below I pasted the exact output of the following commands:
```
java -version 10.0.2 64-bit
R --version 3.3.3 (comes with LipidMatch Flow

```

### Expected behavior

Not sure - MZMine is embedded in LipidMatch Flow - contacting you was a suggestion of the LipidMatch Flow author, Jeremy Koelmel.

### Actual behavior

[10:36:33|INFO|BatchTask]: Starting step # 7
[10:36:33|SEVERE|BatchModeModule]: Error while running batch(java.lang.NullPointerException@net.sf.mzmine.modules.peaklistmethods.gapfilling.peakfinder.PeakFinderTask.<init>(PeakFinderTask.java:75))
java.lang.NullPointerException
	at net.sf.mzmine.modules.peaklistmethods.gapfilling.peakfinder.PeakFinderTask.<init>(PeakFinderTask.java:75)
	at net.sf.mzmine.modules.peaklistmethods.gapfilling.peakfinder.PeakFinderModule.runModule(PeakFinderModule.java:58)
	at net.sf.mzmine.modules.batchmode.BatchTask.processQueueStep(BatchTask.java:168)
	at net.sf.mzmine.modules.batchmode.BatchTask.run(BatchTask.java:89)
	at net.sf.mzmine.modules.batchmode.BatchModeModule.runBatch(BatchModeModule.java:96)
	at net.sf.mzmine.main.MZmineCore.main(MZmineCore.java:239)
Press any key to continue . . . 

### Steps to reproduce the problem

Using MZMine 2.37 with LipidMatch Flow 0.0.2

**Comment by jeremykoelmel** [comment]
LipidMatch Flow only works with MZMine 2.26, which comes with the software.

**Comment by tomas-pluskal** [comment]
@jeremykoelmel So you’re distributing a software that embeds an outdated version of MZmine? How is that sustainable/maintainable in the long term?? Wouldn’t it make more sense to contribute your code to the main MZmine development branch?

**Comment by jeremykoelmel** [comment]
It would of course be ideal to be integrated in MZMine, we would get more interest and it would promote lipid users to come to MZMine (MZMine is amazing, and is my favorite peak picking software for most applications). 

That being said...
We lost the main engineer who actualized LipidMatch Flow from my R scripts. I am currently to busy and don't have anyone to do the integration. It currently is not published, so if it was integrated it would stand as a great publication. If anyone here is interested feel free to contact me: jeremykoelmel@gmail.com. 

But the 2.26 version of MZMine works very well for what we are doing!
Of course the increase in speed, etc. would be useful, but there are errors in the new MZMine versions, so we have left that aside.

**Comment by Annexhc** [comment]
Hey jkmunk,
I have added MS/MS rules from the LipitMatch project to the MZmine Lipid Search module. You can try that as well. If you need any other lipid class just let me know, I can quickly add it to the database. 
best wishes,
Ansgar

**Comment by jeremykoelmel** [comment]
Thank you Ansgar, in collaboration with Hiroshi we should be doubling further the database soon! I'll keep you updated when we add libraries and rules. I assume you added oxidized lipids we have as well? Looking forward to the release with the new rules embedded. 

The only difference (theoretically) between Lipid Search and the LipidMatch Standalone will be:
1) LipidMatch ranks hits for mixed spectra (co-eluting lipids with the same exact mass which happen frequently)
2) LipidMatch has a unique algorithm for deconvolution and ID from AIF data (thermo)
3) Alignment of MS/MS spectra, parameters, and a few other minor differences may lead to different results
