### ISSUE TITLE
MZmine 2.38 issue with Java at startup 

### ISSUE THREAD

**Issue by KiroVandenBerg** [mzmine/mzmine2#543]
Dear all, 
when I am trying to start mzmine with "startMZmine_Windows.bat" (windows 64 bit ) i got the error message attached.
The file "adap-3.3.1.jar" is contained in the lib folder

![grafik](https://user-images.githubusercontent.com/47632742/52787637-c6b01b80-305e-11e9-923c-3bf75ed152b4.png)

Thanks for help!

**Comment by tomas-pluskal** [comment]
Java 6 is not supported anymore. Try downloading the latest JDK from here: https://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by KiroVandenBerg** [comment]
Dear Tomas,

thanks for your fast response!
I had two Java versions installed and overlooked that the old version was used by mzmine, actually the new version was not installed correctly.

Issue solved ;)
