### ISSUE TITLE
MzMine2 MS1 - MS2 association issue in chromatogram building step

### ISSUE THREAD

**Issue by mzdouc** [mzmine/mzmine2#548]
### Setup

I am reporting a problem with MZmine 2 version 2.38 and would like to ask for help with this issue.
I first encountered the problem using Ubuntu 16.04. 64bit Linux, but it occurs also while using Windows 10 64bit.

Linux:
```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
R-version:  3.4.4 
```

### Problem description

Following the youtube tutorial on feature based molecular networking, I have created a minimal working example, using 12 samples which have been investigated before using normal MN. Upon inspection of the network, I noticed that several important families were missing. The job in question can be found here: ID=529bf66e69f842c3a7d2428772543381

Back-tracking the issue, I found that some features present in MS1 lacked MS2-data and were therefore not exported for the GNPS-analysis. This problem seemed to present itself while running the chromatogram builder module. Looking at the raw, imported data, MS2-information is present, but it vanishes when creating the peak lists using the chromatogram builder module. Interestingly, the issue was file-specific. 

Thus, I created a MWE using only two files:
    -5440_5439.mzXML (no problems)
    -6132_6136.mzXML (lacking MS2-data after chromatogram building).

As you can see looking at the following screenshots, both files had MS2 scans in the raw data, but only 5440_5439.mzXML had a correct association of MS1 and MS2 scans after the chromatogram building step:

6132_6136.mzXML - missing MS2 data in peak list:

![1](https://user-images.githubusercontent.com/48592875/54446337-fbd78880-4746-11e9-8556-8160485f360a.png)

6132_6136.mzXML - MS2 data present in raw data:

![2](https://user-images.githubusercontent.com/48592875/54446359-098d0e00-4747-11e9-8fc8-126dc1628f08.png)

-5440_5439.mzXML - MS2 data present in peak list:

![3](https://user-images.githubusercontent.com/48592875/54446369-0d209500-4747-11e9-952f-ffbe2dcb17d7.png)

-5440_5439.mzXML - MS2 data present in raw data:

![4](https://user-images.githubusercontent.com/48592875/54446374-11e54900-4747-11e9-95bf-fb52f8149d49.png)

It seems to me that there is a problem while associating MS1- with MS2-data. This behaviour is unacceptable in my analysis, as it leads to unforseeable bias. 
All other steps of the workflow seem to run flawlessly.

The parameters I used for the processing are as follows:
1)Mass detection:
MS level - 1
Centroid / detection threshold - 1.0E3
MS level - 2
Centroid / detection threshold - 0

2)Chromatogram builder
MS level - 1
Min time span - 0.05 [analysis runtime: 30min]
Min height - 3E3 [3xdetection threshold as recommended in the tutorial]
Mass tolerance - 20 ppm

We are using a Bruker qTOF with a 30min isocratic gradient.

I have omitted further steps of the analysis since the problems seems to occure at the very beginning of the workflow. 

The mzMine session file can be found here: [https://www.dropbox.com/s/4eni3yjieurvwuv/mwe-mzdouc.mzmine?dl=0](url)

The mzXML- and original Bruker-files in question can be accessed on request. 

I would appreciate any help regarding this issue. Feature based molecular networking seems a highly promising analysis technique, but I cannot do a reliable analysis as long as the present issue persist. Do you have any recommendations on the parameters chosen? Do you see any obvious flaws? Is there any way to sidestep this problem, for example by using a different chromatogram builder? 

Thank you for you effort! 

Yours sincerely, 

Mitja Zdouc

**Comment by Annexhc** [comment]
Hi,
I think the MS2 scans are added to the features after chromatogram deconvolution. Add this step to your workflow and let me know if it works.
best,
Ansgar

**Comment by mzdouc** [comment]
Hi Ansgar, 

thank you for your quick answer! 

Unfortunately, the chromatogram deconvolution did not yield the desired result - the MS2 data is still missing. 

The parameters used were: 
Min peak height - 1E3
Peak duration - 0.05 - 10 min
Base Peak Level - 1E2
m/z range MS2 pairing: 0.02 Da
RT range MS2 pairing: 0.2 min

Example feature after deconvolution:

![5](https://user-images.githubusercontent.com/48592875/54449069-8b803580-474d-11e9-8367-02fb02a400fa.png)

The session-file can be provided upon request.

**Comment by tomas-pluskal** [comment]
Hi @mzdouc 
It seems your files contain incorrect precursor m/z values. For your 913 m/z peak the m/z values in MS1 scans fluctuate between 913.512 and 913.523 m/z, which is indeed within 20 ppm mass accuracy:

<img width="854" alt="Screen Shot 2019-03-15 at 18 42 24" src="https://user-images.githubusercontent.com/1796692/54451215-99848500-4752-11e9-97e4-af6a6ed6683d.png">

However, the precursor m/z values for your MS2 scans are way off:

<img width="890" alt="Screen Shot 2019-03-15 at 18 46 49" src="https://user-images.githubusercontent.com/1796692/54451292-d6507c00-4752-11e9-9b07-ea4875e66181.png">

That's why your MS2 scans are not associated with your MS1 scans.

You should double check how the precursor m/z values look in your original raw data files and check if the error was introduced during the conversion process to mzXML.

**Comment by mzdouc** [comment]
Dear @tomas-pluskal 

thank you for your effort and your suggestion. Indeed it seems like something went wrong with the calibration of the values. The accuracy of the MS2 precursor ion in file 6132_6136.mzXML is five-fold lower than the one in file 5440_5439.mzXML: 

![9](https://user-images.githubusercontent.com/48592875/54480544-10d91800-482a-11e9-839c-e6ac26494de4.png)

I will try to re-calibrate the values in the original data. If this is not successful, I will set the mass-accuracy to a lower value. 

I am happy that the issue lies with my data and not the MzMine-program!

I will try to solve the problem and, if successful, close this thread in the following week. 

Thanks a lot again!

**Comment by tomas-pluskal** [comment]
No problem.

I think MSConvert from the ProteoWizard package has an option to recalibrate the precursor m/z values, so you can try using that.

**Comment by lfnothias** [comment]
Hi @mzdouc, 
Did you use the CompassXport software for bruker data conversion to open format ?

**Comment by mzdouc** [comment]
@lfnothias 
Yes, I used the generic Export-function in Bruker's DataAnalysis to convert to open format. 

@tomas-pluskal 
Checking the original data, everything seemed to be alright. The MS2-precursor corresponds to the MS1-m/z as can be seen here:

![ms2-bruker PNG](https://user-images.githubusercontent.com/48592875/54540778-e35eac80-4998-11e9-97ac-a5211c590ca6.png)

I tried to convert the files using ProteoWizard's MSConvert package, first by using just the generic "Peak-Picking by Vendor" filter and second by adding the "Lockmass Refiner" filter, setting the reference m/z to 943.52627 and the m/z tolerance to 0.03. Alas, it did not correct for the inaccuracy in either case, i.e. the output was exactly the same as with the built-in export function in Bruker's Data Analysis. 

I am puzzeled by this behaviour. It appears as if the MS2-precursor m/z is distorted during the export, leaving the MS1-spectrum and the MS2-spectrum unaffected.

Here a comparision of the MS2 spectra of a single MS scan in both Bruker Data Analysis and MzMine2. The only difference lies in the precursor m/z:

![comp-bruker-mzmine](https://user-images.githubusercontent.com/48592875/54542507-30904d80-499c-11e9-8078-19a9661c053b.PNG)


Do you have any suggestion on how to solve this issue? I know that it is not part of MzMine, but I have no idea how to deal with this problem. Re-calibrating the precursor m/z in Bruker's Data Analysis does not seem to be promising, since the original data seems to be okay. 

Thanks a lot in advance!

**Comment by mzdouc** [comment]
@tomas-pluskal 

Of course! I have sent you the link via E-mail.

**Comment by tomas-pluskal** [comment]
So, I looked at your file, and I can confirm I see the same problem.

I tried running the command line version of msconvert to add the **precursorRecalculation** filter. But it refused to use this filter on your data:
````
C:\Users\plusik\AppData\Local\Apps\ProteoWizard 3.0.18353 64-bit>msconvert.exe z
:\tmp\6132_6136_BD3_01_31134.d --filter "precursorRecalculation"
format: mzML
    m/z: Compression-None, 64-bit
    intensity: Compression-None, 32-bit
    rt: Compression-None, 64-bit
ByteOrder_LittleEndian
 indexed="true"
outputPath: .
extension: .mzML
contactFilename:
runIndexSet:

spectrum list filters:
  precursorRecalculation

chromatogram list filters:

filenames:
  z:\tmp\6132_6136_BD3_01_31134.d

processing file: z:\tmp\6132_6136_BD3_01_31134.d
calculating source file checksums... Error writing run 1 in "6132_6136_BD3_01_31
134.d":
[SpectrumList_PrecursorRecalculator] Mass analyzer not supported: time-of-flight
````

I don't really know how you can fix this problem, but I suggest the following:
- contact the Proteowizard people and ask them why it is not possible to use the PrecursorRecalculator on your Bruker TOF data, and if they have any suggestion how to fix your precursor m/z values
- contact Bruker and ask them if they have any experience with this problem

**Comment by tomas-pluskal** [comment]
By the way, I think I understand where your precursor values are coming from: it is the center of the isolation window. See the isolation window here:

<img width="1508" alt="Screen Shot 2019-03-18 at 12 33 48" src="https://user-images.githubusercontent.com/1796692/54546487-1f364980-497a-11e9-890f-06f13ff105a9.png">

**Comment by lfnothias** [comment]
@mzdouc, 
I am not sure what you mean by "Generic export". For Bruker files, we used CompassXport in Bruker, and in our experience it is very robust. See the following doc https://bix-lab.ucsd.edu/display/Public/Data+Conversion+to+GNPS+Compatible+Formats+-+.mzXML+and+.mzML#DataConversiontoGNPSCompatibleFormats-.mzXMLand.mzML-ConversionofBrukerData
Make sure to use the last version, as a bug was corrected in the latest version, where the conversion was not applied correctly if spectra were not collected/saved in the first period on the acquisition.
You can download it here: https://www.bruker.com/service/support-upgrades/software-downloads/mass-spectrometry.html

**Comment by mzdouc** [comment]
@tomas-pluskal 
Thanks a lot for helping me out! I will follow your recommendations and will come back to you with my findings. 

@lfnothias 
Sorry for my lack in clarity. I converted the files as described in the document you linked. Since it is built into Bruker Data Analysis, I referred to it as "generic". 
We are using Data Analysis 4.2, and I guess it's already an older version. I will try to get access to the new version. Thanks for pointing out that possibility.

**Comment by lfnothias** [comment]
@mzdouc Sounds good. Yeah the same bug might be involved as it looks from the TIC that there is no scans at the beginning. Note that in our case, the bug was manifested with an output file no having the lockmass not applied neither on MS1 and MS2 levels.

**Comment by mzdouc** [comment]
Dear @Annexhc @tomas-pluskal @lfnothias 

I have found a way to walk around the MS2 precursor-inaccuracy that occured when exporting Bruker raw data using Bruker Compass Export. I will describe my workflow below (###).

First, following the recommendations of @tomas-pluskal I contacted the ProteoWizard crew but they could not really help me; the PrecursorRecalculator option is not suitable for TOF data and the precursor inaccuracy was somehow stored in the raw data, making it impossible for MsConvert to retrieve the correct values. 
After updating CompassXport as recommended by @lfnothias did not yield improvements, I also contacted Bruker's ESITof Support but their only recommendation was to try to export the files on a Win7 32bit machine, since DataAnalysis 4.2 is not compatible with Win10. Such a machine was not available to test for the reproducability of the issue. 

(###)

While testing different export-options in DataAnalysis, I found that it is possible to export the spectra detected by Find -> Compounds AutoMS(n) as .mgf-file. This file contained the correct precursor MS2:

```
###FS:    #m/z: 943.52279 #charge-128
###MaxRes:#m/z:  0.00000 #charge-128
###MS: 2169
###MSMS: 2170
BEGIN IONS
TITLE=Cmpd 466, +MS2(943.5228), 38.9-62.2eV, 12.4 min #2170
RTINSECONDS=745.735
SCANS=MS: 2169 MSMS: 2170
PEPMASS=943.52279	17533

161.13146	178	
175.14012	139	
...
END IONS
```

I figured out that the wrong MS2-precursor was saved as plain text in the .mzXML file. The binary spectrum-data seemed to be ok (the same values in both DataAnalysis and MzMine/SeeMS)

```
...
<scan num="2170" centroided="1" retentionTime="PT745.90800000S" polarity="+" msLevel="2" collisionEnergy="38" peaksCount="328" lowMz="111.06203382" highMz="1199.21356621" basePeakMz="423.35906745" basePeakIntensity="3002.00000000" totIonCurrent="24603.00000000">
<precursorMz precursorIntensity="17533">943.49914551</precursorMz>
...
```

I decided that my best chance to solve this issue was to correct the wrong precursor values in the .mzXML-file, using the values from the .mgf-file and leaving everything else untouched. 

I checked my hypothesis by manually correcting the precursor value in the .mzXML-file and importing into MzMine. This time, in worked - the MS2 spectrum was attributed to the MS1. 

Therefore, I came up with a Perl-script that reads the mgf-file, extracts the correct precursor m/z (keeping specificity by using the scan number) and corrects the corresponding mzXML-file for these values. 

```
#!/usr/bin/env perl

use strict;
use warnings;
use autodie;
use feature qw(say);

my %hash;

#mgf-file
open my $fhh, "<", "$ARGV[1]";

my $key = 0;
my $val = 0;
my $tag = 0;

#checks each line of input for the scan id and assigns it to variable $key.
#sets a tag for the next loop to initiate that checks the (next) line
#for the precursor m/z which gets subsequently stored in $val. 
#The next if clause evaluates as true if $val was assigned and the key and value
#are assigned to the hash. All flags are set to 0 again to prevent the assignment 
#of the wrong precursor to the key. 
while (my $input = <$fhh>){
	chomp $input;
	if ( $input =~ m/\ASCANS=MS:\ [\d]+\ MSMS:\ ([\d]+)/ ) {
		$key = $1 if $input =~ m/\ASCANS=MS:\ [\d]+\ MSMS:\ ([\d]+)/;
		$tag = 1;
	}
	if ( $tag ) {
		$val = $1 if $input =~ m/\APEPMASS=([\d]+\.[\d]+)/;
		if ( $val ){
			$hash{$key} = $val; 
			$key = 0;
			$val = 0;
			$tag = 0;
		}
	}
}
close $fhh;


#standard mzXML file
open my $fh, "<", "$ARGV[0]"; 

###Uses tag to check if the id was found in the previous line
my $flag = 0;
my $id = 0;

#Here, every line of the mzXML-file is checked if it contains the 
#"marker" msLevel="2"; if yes, the foreach loop checks all hash keys for 
#identity with the scan number that can be found at the beginning of the 
#line (see regex line 41) and only if there is a fit, it assigns the id to 
#$id and sets the flag $flag to 1. If there is no fit, it jumps out of the
#loop with next and last. 
while (my $line = <$fh>) {
	chomp $line; 
		if ( $line =~ m`msLevel=\"2\"` ) {
			foreach my $i (keys %hash) {
			next unless $line =~ m`\A(<scan\ num=\"$i\")`;
			$id = $i;
			$flag = 1;
			last; 
			}
	}

#if flag was set previously and if the line starts with the right string
#substitute the precursor-mz with the value of the hash-key that was set previously.
#After the substitution, $id and $flag are unset again to prevent the erroreous 
#substitution of values.
#Specifity is given because the lines of scan id and the precursor value
#follow one after another. 
	if ( $flag ) {
		if ( $line =~ m`\A<precursorMz\ precursorIntensity=` ) {
			$line =~ s`[\d]+\.[\d]+(</precursorMz>)`$hash{$id}$1`;
			$id = 0; 
			$flag = 0;                          
		}
	}
print "$line\n"; #prints all lines; can be used instead of in-place-substitution of values
}
close $fh
```

The files can be fed into the program by something like this:
```
$ for i in *.mzXML ; do j=${i%.mzXML}; ./perl-script.pl "$i" "$j".mgf > "$j"_mod.mzXML ; done
```

The code works quite efficiently (ca 5sec per 80mb text file) but I am sure that it can be optimised - I haven't used Perl before working on this problem. 

For my purpose, I have solved my problem by using this method. I can further process my files by MzMine and that is all I wanted. The underlaying problem lies with Bruker's DataAnalysis however. 

Thanks to all for your help!

Best,

Mitja

**Comment by tomas-pluskal** [comment]
Hi @mzdouc 
I am glad you found a workaround for the problem, however it is still a workaround and not a solution. I would recommend to file a bug report with Bruker to make sure they are aware of the problem and can fix it in future versions. I guess talking to the support people won't help, because this is not a support issue.

Best,

Tomas
