### ISSUE TITLE
Isotope peak scanner issues

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#552]
The isotope peak scanner module executed with these parameters:

<img width="739" alt="Screen Shot 2019-03-28 at 11 38 24" src="https://user-images.githubusercontent.com/1796692/55171342-87411880-514e-11e9-9a24-edeb6af7cd2b.png">

produces this error:

<img width="689" alt="Screen Shot 2019-03-28 at 11 38 36" src="https://user-images.githubusercontent.com/1796692/55171353-8c9e6300-514e-11e9-9f55-587fa4936f07.png">

Also, in the task progress window, it shows as "Got parameters" with status CANCELED (should be ERROR).

<img width="1165" alt="Screen Shot 2019-03-28 at 11 42 53" src="https://user-images.githubusercontent.com/1796692/55171425-b6f02080-514e-11e9-8171-73e0cd3841e6.png">

**Comment by tomas-pluskal** [comment]
@robinschmid Could you please take a look at this?

**Comment by robinschmid** [comment]
Yeah will do.
