### ISSUE TITLE
javafx build problem

### ISSUE THREAD

**Issue by rgentz** [mzmine/mzmine2#564]
### Setup

I am reporting a problem with MZmine 2 version 2.38. 
My operating system is Ubuntu 18.04 lts).

Below I pasted the exact output of the following commands:
```
java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

 R --version
R version 3.5.3 (2019-03-11) -- "Great Truth"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

### Expected behavior
'''
mvn clean package 
'''
builds the package
### Actual behavior
mvn clean build fails with the following log

mvn clean package
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building MZmine 2.39
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.rsc.chemspider:chemspider-api:jar:1.0.0 is missing, no dependency information available
[WARNING] The POM for mzmine:macspecificsetup:jar:2.7 is missing, no dependency information available
[WARNING] The POM for mzmine:jmprojection:jar:1.0 is missing, no dependency information available
[WARNING] The POM for mzmine:gslibml:jar:0.0.1 is missing, no dependency information available
[WARNING] The POM for mzmine:visad:jar:20131024 is missing, no dependency information available
[WARNING] The POM for java3d:j3dcore:jar:1.6.0 is missing, no dependency information available
[WARNING] The POM for java3d:j3dutils:jar:1.6.0 is missing, no dependency information available
[WARNING] The POM for java3d:vecmath:jar:1.6.0 is missing, no dependency information available
[WARNING] The POM for de.unijena.bioinf.ms:chemistry_base:jar:3.1.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for de.unijena.bioinf:java-utilities:jar:1.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for gurobi:gurobi-linux64:jar:7.5.2 is missing, no dependency information available
[WARNING] The POM for cplex:cplex:jar:12.8 is missing, no dependency information available
[WARNING] The POM for de.unijena.bioinf.ms:chemical_db_oss:jar:1.1.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ mzmine2 ---
[INFO] Deleting /home/rgentz/git/mzmine2/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mzmine2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1459 resources
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ mzmine2 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1142 source files to /home/rgentz/git/mzmine2/target/classes
[INFO] /home/rgentz/git/mzmine2/src/main/java/net/sf/mzmine/modules/peaklistmethods/dataanalysis/clustering/ClusteringTask.java: Some input files use or override a deprecated API.
[INFO] /home/rgentz/git/mzmine2/src/main/java/net/sf/mzmine/modules/peaklistmethods/dataanalysis/clustering/ClusteringTask.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/rgentz/git/mzmine2/src/main/java/net/sf/mzmine/modules/visualization/twod/TwoDDataSet.java: Some input files use unchecked or unsafe operations.
[INFO] /home/rgentz/git/mzmine2/src/main/java/net/sf/mzmine/modules/visualization/twod/TwoDDataSet.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/rgentz/git/mzmine2/src/main/java/net/sf/mzmine/desktop/impl/DesktopSetup.java:[31,26] package javafx.embed.swing does not exist
[ERROR] /home/rgentz/git/mzmine2/src/main/java/net/sf/mzmine/desktop/impl/DesktopSetup.java:[107,7] cannot find symbol
  symbol:   class JFXPanel
  location: class net.sf.mzmine.desktop.impl.DesktopSetup
[ERROR] /home/rgentz/git/mzmine2/src/main/java/net/sf/mzmine/desktop/impl/DesktopSetup.java:[107,33] cannot find symbol
  symbol:   class JFXPanel
  location: class net.sf.mzmine.desktop.impl.DesktopSetup
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.422 s
[INFO] Finished at: 2019-04-15T11:38:25-07:00
[INFO] Final Memory: 49M/174M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project mzmine2: Compilation failure: Compilation failure: 
[ERROR] /home/rgentz/git/mzmine2/src/main/java/net/sf/mzmine/desktop/impl/DesktopSetup.java:[31,26] package javafx.embed.swing does not exist
[ERROR] /home/rgentz/git/mzmine2/src/main/java/net/sf/mzmine/desktop/impl/DesktopSetup.java:[107,7] cannot find symbol
[ERROR]   symbol:   class JFXPanel
[ERROR]   location: class net.sf.mzmine.desktop.impl.DesktopSetup
[ERROR] /home/rgentz/git/mzmine2/src/main/java/net/sf/mzmine/desktop/impl/DesktopSetup.java:[107,33] cannot find symbol
[ERROR]   symbol:   class JFXPanel
[ERROR]   location: class net.sf.mzmine.desktop.impl.DesktopSetup
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
### Steps to reproduce the problem

followed the eclipse tutorial and it does build in eclise if I specify building it with JAVA 8. However when compiling it with the default java 10 implementation i get the above error. Any hints how to make this build?

**Comment by tomas-pluskal** [comment]
Hi,

It seems the openJDK builds do not contain the JavaFX libraries. If you download the Oracle JDK version 8, 9, or 10, it should fix the problem: https://www.oracle.com/technetwork/java/javase/downloads/index.html

Note that JavaFX was completely removed from JDK version 11 and newer. I will need to make some updates in MZmine to account for that.

**Comment by tomas-pluskal** [comment]
I believe this should be fixed now.
