### ISSUE TITLE
Java out of memory

### ISSUE THREAD

**Issue by Frederik-Det** [mzmine/mzmine2#565]
### Setup

I am reporting a problem with MZmine 2 version (*Please fill this in*). 
My operating system is (*Please fill this in, including version number and 32-bit or 64-bit *).

Below I pasted the exact output of the following commands:
```
java -version
R --version
(*Please copy-and-paste the output here*)
```

### Expected behavior

(*Please fill this in*)

### Actual behavior

(*Please fill this in, and paste any relevant exceptions, log messages, and screenshots*)

### Steps to reproduce the problem

(*Please fill this in *)

**Comment by Frederik-Det** [comment]
Hi,

MZmine 2.35 is crashing ..java is out of memory.. than the GUI closes
I recently got a memory extension from 16GB to 32GB, Win 7 Pro 64Bit.
Java 8 build 1.8.0_121-b13

The Software runs smooth with 16GB but with 32 GB I can see in the Task Manager RAM is occupied till 20GB than the error message appears and MZmine GUI closes.

Unfortunately I cannot reproduce the error as our inhouse IT removed the additional RAM already.

It is not a specific step. Only when the memory has reached a certain threshold.

Thank you

**Comment by robinschmid** [comment]
Hey

did you try the latest MZmine version?
Do you use profile data or centroid data (mzML) files?
How many files/GB of data?

Cheers
Robin

**Comment by Frederik-Det** [comment]
Hi Robin,

I have not jet tried the new version.
I use mzXML files, around 20 files each 90MB.
As I said there is no problem with 16GB of RAM. Task Manager shows memory filled around 15.8 GB and it stays constant during the processing.

Best, Frederik

**Comment by robinschmid** [comment]
This is weird.
However, 15.8 GB RAM usage for 20 small files is quite high. Are you setting the noise levels high enough? (for mass detection and chromatogramm building)

**Comment by Frederik-Det** [comment]
No, noiselevels are low ..searching for the tiny ones in the grass ;)
It takes a while to process but there are no problems.

**Comment by tomas-pluskal** [comment]
You probably just need to set the noise level higher. In any case, your report does not give any details on what modules you are running, with what parameter values, and what kind of data you are dealing with (which instrument, centroid or profile, etc.). Try again.

**Comment by Frederik-Det** [comment]
Thank you for your suggestions.
I run centroided data from a HR TOF MS.
It is the Mass Detection module.

Still I think it is a general issue: with 16 GB RAM it runs smooth, with 32GB RAM I get the error. I did not change anything except of the RAM.
RAM was tested by the IT and it is fine.

32 GB RAM should not be a problem for MZmine, or?

I am happy for any suggestions.

Best, Frederik

Am 18.04.2019 20:07 schrieb Tomáš Pluskal <notifications@github.com>:

You probably just need to set the noise level higher. In any case, your report does not give any details on what modules you are running, with what parameter values, and what kind of data you are dealing with (which instrument, centroid or profile, etc.). Try again.

**Comment by tomas-pluskal** [comment]
32 GB RAM is not a problem for MZmine. If you want to get a better advice, you need to provide all the relevant details.
