### ISSUE TITLE
Raw data import

### ISSUE THREAD

**Issue by gampenora** [mzmine/mzmine2#571]
I am reporting a problem with MZmine 2.39 version 
My operating system is Windows 7 64-bit.

I tried to import a converted mzdata.xml datafile originated from an Agilent .d file, but I got the error message of the following:
![image](https://user-images.githubusercontent.com/39517442/57139380-6b680c80-6db5-11e9-9071-58ebcdf1a7f5.png)
The converted file is available here:
https://1drv.ms/u/s!AiSWU1JT2D7_0w-m4SryDc5cOH47
Thank you very much for your help!

**Comment by tomas-pluskal** [comment]
Hmm, mzData is a very outdated format. You should try using mzML or mzXML instead. How did you convert the file?

**Comment by gampenora** [comment]
I use Agilent MassHunter for conversion. As output, it can produce ASR, CEF, CSV, MGF, mzData and MS/MS inclusion list options.

**Comment by tomas-pluskal** [comment]
Try using MSconvert from the ProteoWizard package instead.

**Comment by gampenora** [comment]
It solved the problem :) Thank you for your fast replies and help!!!!
