### ISSUE TITLE
Duplicate peak filter for rows with MS2 spectra?

### ISSUE THREAD

**Issue by RachelGregor** [mzmine/mzmine2#581]
Hello, 

I would like to use the duplicate peak filter function (as part of data clean-up for the GNPS workflow), but I wanted to first ask what happens when two rows that each have associated MS2 data are merged? One is saved and the other discarded?

Thank you!
Rachel

**Comment by robinschmid** [comment]
Hey Rachel,

I would definitely run the duplicate filter. Especially if you use GAP-filling, use the duplicate filter afterwards. The old average option just deletes duplicate rows. The new average or single feature option will merge duplicate rows. All detected peaks are going to be merged into one row. The MS/MS scans are then kept for the selected feature. You can also run a new module on any feature list to make sure all MS/MS scans are assigned correctly (see link below).

Are you using the latest version of mzmine 2? The new direct submission module now allows you to submit with your GNPS username and password to create a new GNPS job in your account.

If your project was created with MZmine 2.37 or earlier - watch this video (sorry for my slow pace) and use the new module to assign all MS/MS scans to all features.
https://www.youtube.com/watch?v=EL5pmFvpTFE&t=57s

Cheers
Robin

**Comment by RachelGregor** [comment]
Hi Robin, 

That's perfect, thank you. This is indeed a job created with an older version of MZmine. 

The video is very helpful-- Just to be clear, I should run the group MS2 scans module on the aligned peak list, or on all the chromatograms separately, or either? 

Thanks again!

Best, 
Rachel

**Comment by robinschmid** [comment]
You can either run it on feature lists of a single sample or on the aligned lists. 
No difference. I think this module and the mz/rt tolerances are more straight forward and they also allow to change the assignment of MS2 later.

Cheers,
Robin

**Comment by RachelGregor** [comment]
Great, thanks again!!

Best, 
Rachel

**Comment by tomas-pluskal** [comment]
Hey @robinschmid 
Perhaps we should add a warning message to the project loading module when people are opening an older project file (<2.37).

**Comment by robinschmid** [comment]
We could do that. This is not important for every purpose - however, more and more projects are going to use the new MS/MS data structure.
