### ISSUE TITLE
Valley Detection

### ISSUE THREAD

**Issue by grfxmunkey** [mzmine/mzmine2#584]
I'm attempting to use MZmine for data that has no real chromatography.  The data files include a chromatogram over the acquisition time, but it should be relatively flat.  Is there a way to control valley detection in the chromatographic peak picking so that if there is a short drop out in signal, the algorithm doesn't assume a new peak unless the drop is longer than a set amount of time?

![image](https://user-images.githubusercontent.com/21205573/57704730-7e3dd500-7630-11e9-96f2-9dba9f160efe.png)

**Comment by tomas-pluskal** [comment]
Hi, please describe your workflow - which MZmine modules you used, including parameter values.

**Comment by grfxmunkey** [comment]
I'm using 2.33 with .mzXML files with these modules in this order:
![image](https://user-images.githubusercontent.com/21205573/57705687-4f286300-7632-11e9-81ba-a4219ec18939.png)

Parameters:
Mass Detection
![image](https://user-images.githubusercontent.com/21205573/57705399-d1fcee00-7631-11e9-8914-5f114df5db7e.png)

Chromatogram builder
![image](https://user-images.githubusercontent.com/21205573/57705446-f062e980-7631-11e9-9336-a84da2b977dd.png)

Smoothing - 5 point filter width

Isotopic peaks grouper
![image](https://user-images.githubusercontent.com/21205573/57705782-7b43e400-7632-11e9-9878-3fbb6fd34143.png)

Join aligner
![image](https://user-images.githubusercontent.com/21205573/57705805-872fa600-7632-11e9-9e8a-bfce4c93b756.png)

Peak list rows filter
RT 0.15 - 0.65 min

Peak finder
![image](https://user-images.githubusercontent.com/21205573/57705921-b80fdb00-7632-11e9-9008-9f7659b1226f.png)

Duplicate peak filter
![image](https://user-images.githubusercontent.com/21205573/57705961-ca8a1480-7632-11e9-8e5b-9c1bd6c8e297.png)

**Comment by tomas-pluskal** [comment]
Awesome. Can you also upload one of your mzXML files for testing?

**Comment by grfxmunkey** [comment]
Test file.  Thanks.
[test.zip](https://github.com/mzmine/mzmine2/files/3178308/test.zip)

**Comment by tomas-pluskal** [comment]
Awesome. I tried to run the Chromatogram builder on your file and I don't see any features being split. Can you point to a specific feature (mass) that shows this problem?

**Comment by grfxmunkey** [comment]
I just played around with it.  It doesn't seem to be in Chromatogram Builder, but maybe in the Join Aligner or Gap filling.  I increased the aligner to a RT tolerance of 0.3 min in a dummy dataset including the file below and removed the duplicate peak filter to see any duplicated features.  m/z 70.0657 came up twice in the peak list after filling with two different times, so maybe an integration issue?

![image](https://user-images.githubusercontent.com/21205573/57711434-b3e8bb00-763c-11e9-8816-b93aa330dd05.png)
![image](https://user-images.githubusercontent.com/21205573/57711438-b77c4200-763c-11e9-8746-c486ac008d96.png)

[5 glitch.zip](https://github.com/mzmine/mzmine2/files/3178613/5.glitch.zip)

**Comment by tomas-pluskal** [comment]
It's just about setting the parameters right. Since you don't have chromatographic peaks, the retention time of your signals (which is defined by the highest point in the chromatogram) can be all over the place, quite randomly. So you should set the RT tolerance to a very high value like 10000 min. That will solve your problem, I guess.

**Comment by grfxmunkey** [comment]
I think I actually got it to work.  Thanks for the help.

**Comment by tomas-pluskal** [comment]
Please explain how you got it to work and what the problem was, otherwise this issue is not helpful to anyone.
