### ISSUE TITLE
Open last project

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#601]
<img width="498" alt="Screen Shot 2019-05-27 at 12 43 42" src="https://user-images.githubusercontent.com/1796692/58431713-1d28ef00-807d-11e9-89aa-39e94d015bcd.png">

How about making the Open last project menu disabled if it's empty?

**Comment by robinschmid** [comment]
Sounds good

**Comment by robinschmid** [comment]
Resolved
