### ISSUE TITLE
ADAP chromatogram deconvolution hangs

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#615]
It seems setting the "RT wavelet range" parameter to a range with the same min and max (like 0.1 - 0.1) causes the method to hang with high CPU use. 

@du-lab @asmirn1 Could you take a look at that?

**Comment by asmirn1** [comment]
Sure, I'll fix it.

**Comment by asmirn1** [comment]
Hi Tomas,

I've pulled the latest version of MZmine 2, and now it doesn't compile for me. I'm using Java 8. Here is the output:
```shell
mvn clean install
```

[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< io.github.mzmine:mzmine2 >----------------------
[INFO] Building MZmine 2.40.1
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.rsc.chemspider:chemspider-api:jar:1.0.0 is missing, no dependency information available
[WARNING] The POM for mzmine:macspecificsetup:jar:2.7 is missing, no dependency information available
[WARNING] The POM for mzmine:jmprojection:jar:1.0 is missing, no dependency information available
[WARNING] The POM for mzmine:gslibml:jar:0.0.1 is missing, no dependency information available
[WARNING] The POM for mzmine:visad:jar:20131024 is missing, no dependency information available
[WARNING] The POM for java3d:j3dcore:jar:1.6.2 is missing, no dependency information available
[WARNING] The POM for java3d:j3dutils:jar:1.6.2 is missing, no dependency information available
[WARNING] The POM for java3d:vecmath:jar:1.6.2 is missing, no dependency information available
[WARNING] The POM for de.unijena.bioinf.ms:chemistry_base:jar:3.1.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for de.unijena.bioinf:java-utilities:jar:1.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for gurobi:gurobi-linux64:jar:7.5.2 is missing, no dependency information available
[WARNING] The POM for cplex:cplex:jar:12.8 is missing, no dependency information available
[WARNING] The POM for de.unijena.bioinf.ms:chemical_db_oss:jar:1.1.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ mzmine2 ---
[INFO] Deleting /Users/aleksandrsmirnov/Projects/mzmine/mzmine2/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mzmine2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1600 resources
[INFO] Copying 11 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ mzmine2 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1262 source files to /Users/aleksandrsmirnov/Projects/mzmine/mzmine2/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.461 s
[INFO] Finished at: 2019-06-12T09:49:20-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project mzmine2: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

I've checked the version v2.40 and that version compiles fine.

**Comment by asmirn1** [comment]
It seems that Java 8 (or maven) doesn't understand the line `<release>8</release>` in the pom.xml. If I remove that line, then the compiler works fine.

**Comment by tomas-pluskal** [comment]
You are right. However, that line is required for building MZmine with newer versions of Java. 

Do you actually need to build MZmine using maven? If you are using Eclipse, you can run it directly from Eclipse just using the in-built Eclipse java compiler.

**Comment by asmirn1** [comment]
I didn't try compiling it with Eclipse. I can try it.



I wonder if it's possible to have pom.xml file that would work with both Java 8 and Java 9. What if we specify the source/target/release in the __properties__ section instead of __plugin__. Something like this:

```
<properties>
		<maven.compiler.source>8</maven.compiler.source>
		<maven.compiler.target>8</maven.compiler.target>
		<maven.compiler.release>8</maven.compiler.release>
		...
```

It works with Java 8. Would it work with Java 9?

I'm attaching a new pom.xml here
[pom.xml.txt](https://github.com/mzmine/mzmine2/files/3283030/pom.xml.txt)

**Comment by tomas-pluskal** [comment]
It is much better if you run MZmine directly from Eclipse, because then you can update the code while MZmine is running, and it will immediately reflect the changes.

See section 6 here: https://mzmine.github.io/eclipse_tutorial.html

**Comment by tomas-pluskal** [comment]
As an alternative solution, just install a newer JDK. I haven't tried your pom.xml but I don't believe changing it to properties is going to help.

**Comment by asmirn1** [comment]
Well, okay. I might try Eclipse.

**Comment by asmirn1** [comment]
Actually, setting up source/target/release in __properties__ instead of __plugin__ and running `mvn clean install` works with both Java 8 and Java 11. I've just checked it. 

I couldn't download Java 9 (its support is ended and it's not available on the Oracle website), but I assume it might work with Java 9 as well.

It's possible that maven handles its properties (<maven.compiler.source>, etc.) more gracefully than plugin options.

**Comment by asmirn1** [comment]
I don't mind using JDK 9. It just seams strange having source and target set to 8, but not being able to compile it with Java 8.

**Comment by tomas-pluskal** [comment]
If you remove the ```<release>8</release>``` line, it will still compile with Java 9+. But you will run into serious compatibility issues in runtime - for example, loading a project won't work. Try and see for yourself.

The only reason we stick to Java 8 (which is not supported anymore by Oracle, by the way) is the old 3D visualizer, which does not work with Java 9+. But we have a student currently working on a new 3D visualizer based on JavaFX, so as soon as that is finished, I am planning to move MZmine to the most recent Java 12, discard all the code that has been maintained just for Java 8 compatibility, and also switch the build tool from maven to gradle.

You can track the development of the new 3D plot here: https://github.com/Akshaj5/mzmine2/tree/new3d/src/main/java/net/sf/mzmine/modules/visualization/fx3d

**Comment by asmirn1** [comment]
Okay, I see now.
