### ISSUE TITLE
Spectral search for single peak list row?

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#616]
@robinschmid Wouldn't it be useful to have the option to search spectral database for a single peak list row, similarly to other search functions that we have?

<img width="1163" alt="Screen Shot 2019-06-11 at 22 19 10" src="https://user-images.githubusercontent.com/1796692/59318999-1ca47100-8c97-11e9-92c7-fa93c06933ae.png">

**Comment by Annexhc** [comment]
hey Tomas, that is a good idea. I can handle this.

**Comment by robinschmid** [comment]
I have planned to do this. But somehow I forgot to implement it 
;)
I could also do it. 
We should rund it on all selected peaklist rows and keep it similar to the peaklist module

**Comment by robinschmid** [comment]
Thanks for the implementation Ansgar. 
Works fine on single and multiple rows at a time.
This issue should be resolved.

**Comment by tomas-pluskal** [comment]
Thanks you all!
