### ISSUE TITLE
Help With Appropriate Modules for UPS2 Dataset

### ISSUE THREAD

**Issue by atostengard** [mzmine/mzmine2#617]
Hi, I spoke to you at ASMS about our evaluation of XIC extraction algorithms (in Rob Smith's lab), and you directed me here for assistance. The dataset we would like to run can be found here: https://www.ebi.ac.uk/pride/archive/projects/PXD001587.

As it is a centroided dataset, I assume that I will want to use the centroid mass detector. Beyond that, I am looking for suggestions on other modules to run. From reading the workflow in the manual, I see that I will want to use any modules that are not listed as optional. Would you suggest using the FTMS shoulder peaks filter or the smoothing module? Would I want to use other optional modules such as normalization or gap filling? As for R/T alignment, would you suggest the Join or RANSAC aligner?

Please let me know if you need more information, and thank you so much for your time!

**Comment by tomas-pluskal** [comment]
Hi Annika,

In order to give you a good advice, I need to know what and how you are actually going to evaluate.

**Comment by atostengard** [comment]
Hi Tomas,

Thank you so much for your quick response! This evaluation is on the XIC-level only; essentially we look at each XIC found in the ground truth, and find the corresponding XIC by matching the m/z and r/t values for each point. Then we look at which points were assigned by the algorithm, and if at least 50% of the same points were clustered by both the ground truth and algorithm, then it's considered "correctly extracted". I exported the original results I got just from running the mass detection using the CSV exporter within MZMine2, which is exactly the format I need to run through the code that we are using.

Hopefully this is the answer you need; let me know if not. I really appreciate your time and help.

**Comment by tomas-pluskal** [comment]
Hi Annika,

I still need more details, because some of the terms you are using can mean different things to different people (like “XIC” or “points”). Can you upload an example of the data format how your ground truth data looks like?

Also, the centroid mass detector in MZmine does not output XICs, and the results of the centroid mass detector cannot be directly exported to CSV, so I am a bit confused about how you used MZmine. Could you list the exact sequence of modules that you used and their parameter values?

Best,

Tomas

**Comment by atostengard** [comment]
Hi Tomas,

Here are the first few hundred lines of the ground truth file that we are using: 
[ups2GroundTruthSample.xlsx](https://github.com/mzmine/mzmine2/files/3298781/ups2GroundTruthSample.xlsx)
Each line represents a point, and a traceID or envelopeID of 0 indicates that the point was unassigned (trace here meaning XIC or peak). Any other number in those columns indicates that point was assigned to a peak/envelope.

I used the centroid mass detector as well as the chromatogram builder:
We did three runs, with noise levels of 5, 10, and 100 for the mass detector.
As for the chromatogram builder, I used 0.01 for both the min time span and the m/z tolerance, and matched the noise level from the mass detector for the min height (so if I used five as the noise level for the mass detector, I used 5 for the min height in the chromatogram builder). Then once I had the peak lists from running the chromatogram builder, I was able to use the csv exporter.

Thank you!
Annika

**Comment by tomas-pluskal** [comment]
What is your definition of "point"? Does that mean every single ion (centroid) in each scan? 
In other words, does your "ground truth" file contain ALL spectral data points that are found in the original raw file? 

A second question: In your ground truth file I see this:
```
431.2234 | 0.249 | 85.87877 | 3610 | 490
431.2329 | 0.585 | 1.792474 | 0 | 0
431.2619 | 0.585 | 390.6571 | 3610 | 490
431.2626 | 0.249 | 244.0974 | 3610 | 490
```
How is it possible that XIC trace 3610 contains both masses 431.2234 and 431.2626 at the same retention time 0.249? That makes no sense to me.

**Comment by tomas-pluskal** [comment]
By the way, a while ago I made these slides about evaluating feature detection. 
I recommend to take a very close look at the papers listed in these slides:

[20190618 evaluating feature detection.pptx](https://github.com/mzmine/mzmine2/files/3300489/20190618.evaluating.feature.detection.pptx)

**Comment by atostengard** [comment]
Hi Tomas,

Yes, point being every single centroid in each scan; although we didn't include any centroids with an intensity lower than 2.

Also I think I may have the old, unvalidated version of the file on my local machine, which is what I sent to you. The validated file is a version where one person reviewed each trace/envelope with the goal of fixing mistakes. Using the validated file and our visualization software, here is a screenshot of the area containing trace 3610 (x-axis is m/z and y-axis is r/t):
![ups2Trace3610](https://user-images.githubusercontent.com/27148862/59721629-f4f56180-91de-11e9-8ddc-1255a4a8baa7.png)

So it looks like the exact point in question you are asking about was removed from that trace in the validated version; however, there is still an extra point included in that trace that shouldn't be there at the very bottom, around r/t 0.149. The file is definitely not perfect (and as you noted in your slides, the process is subjective) and this is partly why we require that only 50% of the points from the ground truth traces also be clustered by the algorithms.

Also, thank you very much for sharing the slides; I am reading through the publications now and they are very helpful.

Thanks!
Annika

**Comment by tomas-pluskal** [comment]
Okay, now I understand what you are trying to do.

However, the CSV export module in MZmine does not export such data. It only exports one chromatogram per line, with its "average" m/z value (calculated from all the points of the whole chromatogram) and its RT value (at the apex). If you want to extract all individual points of all detected chromatograms from MZmine, you will have to implement a new export module.

**Comment by atostengard** [comment]
Hi Tomas,

Ah that's right, it's been a couple months so I had forgotten some of the exact details. What I did was export the row ID, peak RT start, peak RT end, peak m/z max, and peak m/z min. Then I have a script that iterates through the points in the ground truth file, and assigns them the corresponding row ID based on  whether they fit within the m/z and r/t range reported in the exported CSV file. Hopefully that makes sense.

Does that seem sufficient to you or is that incorrect?

Thanks!
Annika

**Comment by tomas-pluskal** [comment]
Okay, I understand. In that case you will probably end up with more points reported for MZmine than what MZmine actually detects in the XIC. So your "precision" will be fine but your "recall" may be biased, depending on how you are calculating the final score.

My main concern is that in your ASMS poster you showed very poor results using MZmine, which to me suggests that there is some problem in your calculation (although the workflow you described above seems okay). I think you should investigate specific examples of XICs that were not correctly reported by MZmine and then we can discuss those together.

**Comment by atostengard** [comment]
Hi Tomas,

I'm sorry it's taken me so long to respond - I was ill and there was a holiday here and also we made some changes to how the metrics work - the primary change being that an XIC is now considered a true positive if an algorithm's XIC has at least 50% of the intensity of the "ground truth" XIC's intensity - hopefully the way I worded that makes sense.

I included a screenshot of the entire chromatogram, because up until now I never noticed what must be really skewing the results - the R/T dimension only goes up to ~120 r/t in the results from MZMine2. Any ideas on why this would be happening?
Here's the one from our file:
![fullChromatogramGTUnsegmented](https://user-images.githubusercontent.com/27148862/60925858-0c65be80-a262-11e9-80d9-28f33b1e7296.png)

And then here are the MZMine2 results:
![fullChromatogramMzMine2Unsegmented](https://user-images.githubusercontent.com/27148862/60925860-0d96eb80-a262-11e9-9a97-f15f44a25ee0.png)

Thank you!

**Comment by tomas-pluskal** [comment]
I guess MZmine reports retention time in minutes, while your other software reports it in seconds?

**Comment by atostengard** [comment]
Hi Tomas,

Took me awhile to find an answer but yes, that is where the difference in retention time values came from. Also, that impacted the way I was assigning points to the windows reported by MZMine2, so taking that into account and re-running the results, I'm now getting ~34,000 correct XIC from MZMine2, so that appears to have solved the problem. Thank you so much for your help!

Annika

**Comment by tomas-pluskal** [comment]
Hi Annika,
In any case, you should always investigate the **causes** of the different results provided by different softwares, not just report the numbers. Numbers without explanation are useless, anyone can produce a ton of those.. Just my 5c.
Best,
Tomas
