### ISSUE TITLE
i am getting error message in mac

### ISSUE THREAD

**Issue by sudhashanmugam-sudo** [mzmine/mzmine2#629]
<img width="607" alt="Screen Shot 2019-06-29 at 10 01 58 AM" src="https://user-images.githubusercontent.com/52352091/60385991-896c8900-9a55-11e9-93b6-8c64fda93753.png">
### Setup

I am reporting a problem with MZmine 2 version (*Please fill this in*). 
My operating system is (*Please fill this in, including version number and 32-bit or 64-bit *).

Below I pasted the exact output of the following commands:
```
java -version
R --version
(*Please copy-and-paste the output here*)
```

### Expected behavior

(*Please fill this in*)

### Actual behavior

(*Please fill this in, and paste any relevant exceptions, log messages, and screenshots*)

### Steps to reproduce the problem

(*Please fill this in *)

**Comment by Annexhc** [comment]
Okay, we need more information on what you have tried.

**Comment by sudhashanmugam-sudo** [comment]
Hello
I have dowloaded mzmine 2 and java 8 in my mac pro. But when I am trying to
import data  i am getting error message as I have attached. Please help.


Thanks

**Comment by Annexhc** [comment]
What type of raw data? Thermo, Waters...?

**Comment by Annexhc** [comment]
Anyway, if you use mac, you have to convert your raw files to an open format such as mzML. For that you can use MSConvert. Native raw data files are only supported on windows. For more information please check the MZmine documentaton (http://mzmine.github.io/documentation.html).

**Comment by tomas-pluskal** [comment]
Thanks @Annexhc
