### ISSUE TITLE
Downloadpage - bioconductor R code update

### ISSUE THREAD

**Issue by dschief001** [mzmine/mzmine2#641]
Hello!

On the http://mzmine.github.io/download.html page
the:  **(Optional) Install the required R packages using the following commands in the R console:** 
the code should be updated to:
```{r}
install.packages(c("Rserve", "ptw", "gplots", "baseline", "hyperSpec", "ggplot2","boot"))
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install() # not sure if necessary, but allows update of older packages
BiocManager::install(c("xcms", "CAMERA","PROcess"))
```
I would ask for the change, because the old source(... bioclite.R) is not working anymore I think...
Unless this installation is required as stated to allow full functionality and updating to newer bioconductor packages causes problems, then consider this issue resolved.

Thanks in advance!

**Comment by tomas-pluskal** [comment]
Updated, thanks for letting us know!
