### ISSUE TITLE
Problems with exporting data to GNPS

### ISSUE THREAD

**Issue by Angelahoerdum** [mzmine/mzmine2#660]
### Setup

I am reporting a problem with MZmine 2 version (2.39). 
My operating system is (64-bit ).

```
java 8 -version
Rx64 3.5.0 --version
(*Please copy-and-paste the output here*)
```
I wanted to export/submit to GNPS
I used the following settings:
![image](https://user-images.githubusercontent.com/35375992/61629573-9875de00-ac85-11e9-808e-f9751fc83ae3.png)
I made sure to use the correct mass list.

The output was as following:
](https://user-images.githubusercontent.com/35375992/61533789-26f02280-aa2e-11e9-90fc-e09837bcdbab.png)
Error text: Unhandled exception in task Exporting files GNPS feature based molecular networking job: java.lang.NullPointerException (FileAnd PathUtil.java:192)

I have filezilla installed, if that is any help?

I hope some one can help me.

**Comment by robinschmid** [comment]
Hey

Did you try to specify a full path? Right now you are only setting a file name without the directory.
Just click on the ... button to choose the file path.

And you might want to check out the latest MZmine version 2.40.1 with some updates to the GNPS export.
http://mzmine.github.io/changelog.html

Please tell me if the error still exists after trying the full path or the latest version.

Cheers
Robin

**Comment by Angelahoerdum** [comment]
Thank you very much Robin. I will try that.
Btw I just want to let you know that the GNPS platform is really making a diffrence! Thank you so much for that! and the resent youtube videos ;)

**Comment by Angelahoerdum** [comment]
Well, that worked! thak you. Would you still recomend me to use the latest mzmine version or just continue with this. Sorry for the silly quesion before!

**Comment by robinschmid** [comment]
Thanks for the nice feedback. I think GNPS is a great hub that brings different tools together. 
I think the latest version is always the best version. 

@kaibioinfo introduced a merging function to the GNPS export. It is still very new (even to me) but @lfnothias is testing it and it seems to perform well and to produce a better output for GNPS.

Cheers
Robin

**Comment by robinschmid** [comment]
Can be closed

**Comment by Angelahoerdum** [comment]
Thank you very much!
