### ISSUE TITLE
MS2 scans grouping/merging

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine2#661]
Hi,

I have a question regarding the (un-)compatibility and priority of the different modules allowing MS/MS association / merging.

As an old user, what I did was always associating my MS2 scans during the deconvolution step.

As an example: 
ADAP deconvolution, 
0.02Da tolerance _m/z_ ,
0.1min tolerance RT 

I then obtained a peaklist, filtered MS2 only and exported for further exploration (GNPS, et cætera.)

With your recent improvement (I think Robin), there is a new filter "Group MS2 scans with feature", with similar parameters. Has this module priority over the previous one?
If after my deconvolution, I perform this module with larger parameters, will I obtain some additional MS2 scans associated? 
On the contrary, if I run it with more restrictive parameters, will some lines loose their (or some of their) MS2?

And finally, regarding the final merging at the export step:
- Does the "merge across samples" option also includes the merging across each sample?
If the row 323 of my column 1 has 3 MS2 associated, my column 2 has no MS2 associated, my column 3 2 MS associated, is the algorithm primarily merging the 3 (consensus) of column 1 and then merging the 2 (consensus) of column 3 to give an overall consensus, or merging all of them 5 together? Only the most instense of each column?
It has of course then high impact on the % threshold of "X% of merged spectra". If meaning already column merged spectra or possibly way more.

My apologies for those annoying questions but I noticed huge differences with only "small" changes and therefore would like to know a bit more. :)

**Comment by robinschmid** [comment]
Maybe you can answer some of the questions and consider them in the help file. 
@kaibioinfo @lfnothias 

The merging always follows this direction (ending at the point that you specify):
- merge all consecutive scans
- merge all of the same sample
- merge all of all samples

Personally, I think the grouping at the deconvolution step is a good way to assure that most people group the MS2 with the features. The new module was developed for a few reasons:
- the MS/MS data structure was changed and this module allows to assign all MS/MS scans in older projects
- the use of the tolerances parameters is more straight forward
- you can change the tolerances - this is going to remove all MS/MS scans from all features and regroup them with the features
