### ISSUE TITLE
Features lists not saved within the project

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine2#668]
Hey guys,

Could it be that because of the switch peak -> feature the features lists are not saving properly within the project? They are all written in the /tmp folder but then no way to get them back...

EDIT: Tested in on Mac OS, no problem, only on Linux platform

**Comment by tomas-pluskal** [comment]
This was a bug in version 2.41, fixed in version 2.41.1 - see https://mzmine.github.io/changelog.html
