### ISSUE TITLE
Show preview doesn't work on mass detection-centroid.-....

### ISSUE THREAD

**Issue by Biljana-ruc** [mzmine/mzmine2#679]
### Setup

I am reporting a problem with MZmine 2 version (*2.41.2*). 
My operating system is (* 64-bit *).

Below I pasted the exact output of the following commands:
```
java -version
R --version
(*Please copy-and-paste the output here*)
```

### Expected behavior

(*Please fill this in*)

### Actual behavior

(*Please fill this in, and paste any relevant exceptions, log messages, and screenshots*)

### Steps to reproduce the problem

(*Please fill this in *)

**Comment by tomas-pluskal** [comment]
Closing incomplete report, will reopen if more information is provided

**Comment by Biljana-ruc** [comment]
Hi Tomas,

I couldn’t figure out how to import all the expected behavior but I have added a new issue and have put all the data in a word file so one can see all the steps and help me out in some if possible.

Thanks for your time


Kind regards,

Biljana Mojsoska, Ph.D.
Assistant Professor / Adjunkt
Chemistry
[ruc_logo_download_0]

Roskilde University
Department of Science and Environment/ Chemistry
Universitetsvej 1
DK-4000 Roskilde
Telephone: +4546743645

ruc.dk
facebook.com/ruc.dk
twitter.com/roskildeuni
instagram.com/roskildeuniversitet
