### ISSUE TITLE
Centroid scans being confused as profie

### ISSUE THREAD

**Issue by fernie0341** [mzmine/mzmine2#683]
### Setup

I am reporting a problem with MZmine 2 version (2.41.2). 
My operating system is (64-bit).

Below I pasted the exact output of the following commands:
```
java -version
R --version
(*R version 3.6.0 and java version 1.8.0_201*)
```

### Expected behavior

(*I am trying to perform MS1 and MS2 mass detection on my dataset. The files were generated using a Q-Exactive and converted to mzXML format using the msconvert gui. My MS1 noise level is 2.0E5 and my MS2 noise levels is 2.0E2*)

### Actual behavior

(*I keep on getting an error on both ms1 and ms2 match detection that says my data is profile when it is in fact centroid 

![error](https://user-images.githubusercontent.com/42684038/63538542-f2f49b00-c4cc-11e9-822c-19d0836e30c8.PNG)

![error2](https://user-images.githubusercontent.com/42684038/63538852-9ba2fa80-c4cd-11e9-9cfb-912947470304.PNG)

![error3](https://user-images.githubusercontent.com/42684038/63539068-1f5ce700-c4ce-11e9-948c-65c56e10a00d.PNG)

 I am still able to continue with the mzmine job and use the "output to gnps" for FBMN but this is an error I didn't have before using an older version of mzmine *)

### Steps to reproduce the problem

(*I have tried converting my .raw into mzML instead of mzxml and I still get the same error *)

**Comment by tomas-pluskal** [comment]
Thanks for the report, I just fixed this problem. The fix will be included in the next MZmine release.

**Comment by tomas-pluskal** [comment]
Try using just-released MZmine 2.42.

**Comment by fernie0341** [comment]
I will give it a try. Thanks for the quick response

**Comment by fernie0341** [comment]
I just tested it and I am no longer getting the error. Thanks for the help
