### ISSUE TITLE
Issue with Isotopic peaks grouper

### ISSUE THREAD

**Issue by Chemistophe** [mzmine/mzmine2#685]
Hello,

I don't understand why after the isotopic peaks grouping function set up with with these parameters:

<img width="682" alt="Capture d’écran 2019-08-24 à 10 10 14" src="https://user-images.githubusercontent.com/54418294/63638529-70e4ad80-c657-11e9-9762-ed7d2ed023d4.png">

I still have many way too isotopic peaks, in fact my peak list decreases only from 7353 to 7350?!? 

<img width="1394" alt="Capture d’écran 2019-08-24 à 10 13 33" src="https://user-images.githubusercontent.com/54418294/63638578-27489280-c658-11e9-8570-10cd39abba77.png">

Can anyone know what's wrong?
Many thanks in advance

**Comment by tomas-pluskal** [comment]
Hi @Chemistophe 
The peaks that you show have identical m/z value. Therefore, they are not isotopes, but rather results of incorrect feature detection. The isotope peak grouper module will only group peaks that are part of an isotope distribution (increasing number of neutrons).

You probably need to fix the parameters of your feature detection workflow.

**Comment by Chemistophe** [comment]
Thanks for your very helpful answer!
Also I found useful the Duplicate peak filter function to deal with my issue.
