### ISSUE TITLE
Cannot compile with Gradle

### ISSUE THREAD

**Issue by asmirn1** [mzmine/mzmine2#689]
### Basic information

* My operating system: Mac
* My MZmine version: devel

### What happened

Cannot compile the project. Here is the output:

> [aleksandrsmirnov@CCI16KJV40AWS:~/Projects/mzmine2]$ ./gradlew
> 
> > Configure project :
> OS detected as mac
> 
> > Task :compileJava
> /Users/aleksandrsmirnov/Projects/mzmine2/src/main/java/net/sf/mzmine/util/scans/ScanUtils.java:985: error: cannot find symbol
>         sortedScans.stream().limit(topN).collect(ImmutableList.toImmutableList());
>                                                               ^
>   symbol:   method toImmutableList()
>   location: class ImmutableList
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 1 error
> 
> > Task :compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileJava'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s
> 1 actionable task: 1 executed

It says that class `ImmutableList` from Guava doesn't have method `toImmutableList()`. It seems that Maven uses Guava version 20, while Gradle uses the latest Guava, version 28. Maybe that's the problem.

**Comment by tomas-pluskal** [comment]
Hi Alex,

That's strange. What does your `java -version` say?

Tomas

**Comment by tomas-pluskal** [comment]
The `toImmutableList()` function has been in Guava since version 21: https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/ImmutableList.html#toImmutableList--

You can also try running `./gradlew --scan` and when that's done, send me the link to the build scan website.

**Comment by asmirn1** [comment]
I'm using OpenJDK 12. 

> [aleksandrsmirnov@CCI16KJV40AWS:~/Projects/mzmine2]$ java -version
> openjdk version "12.0.2" 2019-07-16
> OpenJDK Runtime Environment (build 12.0.2+10)
> OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

Here a link to the scan: https://scans.gradle.com/s/gknuwstha2tx2

**Comment by asmirn1** [comment]
Maybe, I'm using the old version of Guava somehow. I'm trying to figure out why.

**Comment by tomas-pluskal** [comment]
Check your `/Library/Java/Extensions` and `~/Library/Java/Extensions` folders.

**Comment by tomas-pluskal** [comment]
Can also try running `./gradlew --refresh-dependencies`

**Comment by asmirn1** [comment]
`/Library/Java/Extensions` is empty. `~/Library/Java/Extentions` doesn't exist.

This is a new build scan: https://scans.gradle.com/s/ugz5jtzl74bek

It shows something interesting, but I'm not sure what it means.
<img width="882" alt="Screen Shot 2019-08-29 at 10 24 35 AM" src="https://user-images.githubusercontent.com/13631120/63948814-56d81000-ca47-11e9-8a61-4bc448ca184c.png">

**Comment by tomas-pluskal** [comment]
The second build scan looks correct to me - some of the dependencies declare transitive dependencies on older versions of guava, but those are all overridden by version 28-jre, which is correct.

**Comment by asmirn1** [comment]
`./gradlew --refresh-dependencies` didn't help. Same error.

**Comment by asmirn1** [comment]
I'll try to google more about this issue.

**Comment by tomas-pluskal** [comment]
Try removing the `mavenLocal()` repository from the `build.gradle` file and see if that changes anything.

**Comment by tomas-pluskal** [comment]
Also you can try running `./gradlew clean` first.

**Comment by asmirn1** [comment]
Removing `mavenLocal()` and running `gradlew --refresh-dependencies` helped! It compiles for me now.

**Comment by asmirn1** [comment]
I guess, Gradle was using the old version of Guava for some reason.

Thank you for helping me!
