### ISSUE TITLE
Issue with local DB search

### ISSUE THREAD

**Issue by minzaroma** [mzmine/mzmine2#690]
* My operating system: Windows Server 2012 R2 Standard
* My MZmine version: 2.41

Thanks for all the cool new functions in the recent update!
I encountered one issue and have another feature request.

1) Issue: I tried to use the new function to run a local DB search for a specific peak in the results table. Unfortunately, this caused the program to crash completely so that all previous work is gone.
I could not find any info what caused it, the program only became completely unresponsive and did not show any further processes in the command window.

2) Request: NIST and many other databases denote the Kovats retention index (RI) for each analyte to assist in compound identification. As it was already requested by another user [here](https://github.com/mzmine/mzmine2/issues/436), I'll just describe it quickly in case it is unknown:
RI is a very established method which uses a compound's position relative to an alkane ladder.
Whenever any settings are changed for a new sequence, an alkane mix is simply run along with the other samples. A compound with RI=1300 always comes somewhere between C12 (RI=1200) and C14 (RI=1400), so it is much more universal and independent indicator than RT.
Many other programs such as MSDIAL and AMDIS utilize the Kovats index, as it is a really useful validation tool. It would be really cool if this feature could be included into MZmine in the future!

Again, as a non-programmer I can only leave a suggestion and thank you for your efforts!

**Comment by Annexhc** [comment]
Hey minzaroma,
glad you like the additions. Does the database matching worked with one of the other modules, using similar settings (Feature list or in the scan visualizer)? I am asking because we need to find out what the problem is, your settings, the database file, or the feature list row module. Can you also send a screenshot of your settings?
Regarding your feature request: It would be better to have an other issue to discuss it, or add your request to issue #436

**Comment by minzaroma** [comment]
Ok, now I tried it again and this time it worked, so maybe it was only bad luck, otherwise I'll try to get some more info next time it happens. ;o)
I put the other issue in a new thread.

**Comment by Annexhc** [comment]
Very good, this one can be closed.
