### ISSUE TITLE
Issue for data export

### ISSUE THREAD

**Issue by rendabing425** [mzmine/mzmine2#694]
[Issue for data export.docx](https://github.com/mzmine/mzmine2/files/3567817/Issue.for.data.export.docx)
### Basic information

* My operating system: windows 10
* My MZmine version:  2.42

### What happened

After data processing, an error was reported when I try to exported the aligned data by using Export for SIRIUS, the error is as following. Can someone help me to handle this problem?

**Comment by robinschmid** [comment]
It is a problem inside the MS/MS merging function.
Can you also send a snap of these settings? (press Setup button)
MZmine 2.50 was released - you could check with this version, although I do not think that the SIRIUS export was changed.

![image](https://user-images.githubusercontent.com/10366914/64170657-f3881c80-ce50-11e9-849a-68d5e6f4d746.png)

**Comment by tomas-pluskal** [comment]
Please try using MZmine version 2.51, which I just released. 

If the problem persists, please provide more information as @robinschmid asked, and also upload your MZmine project file so we can test it.

**Comment by rendabing425** [comment]
@robinschmid @tomas-pluskal  As you suggested, MZmine 2.51 has been tried. However, the problem is sitll existed. 
![TR5KO{@WR1{%{PHY328OT(L](https://user-images.githubusercontent.com/54423944/64219443-1d484e80-cef8-11e9-8064-70978f843b9a.png)

**Comment by tomas-pluskal** [comment]
Please upload a project file that demonstrates the issue

**Comment by rendabing425** [comment]
OK. The attched zip file is my project.

**Comment by rendabing425** [comment]
@tomas-pluskal  Since the poject cannot be successfully uploaded, I sended it to you by email (plusik@gmail.com). Thank you for your kind help.

**Comment by tomas-pluskal** [comment]
The problem in your project is that you have mixed polarity (positive and negative) scans, while you performed the mass detection only on your negative scans. MZmine is currently not very smart when it comes to handling datasets that have mixed polarity. My recommendation is to first use the Crop filter (Raw data methods -> Filtering -> Crop filter and select only negative scans, that will create a new file that will have only negative polarity scans, and you can then run the processing on that reduced file. It will make your life easier and avoid this kind of errors.

**Comment by rendabing425** [comment]
@tomas-pluskal Thank you for your helpful suggestion.
