### ISSUE TITLE
Error when importing Waters raw files

### ISSUE THREAD

**Issue by TilimoNED** [mzmine/mzmine2#695]
### Basic information

* My operating system: Windows 10
* My MZmine version: Version 2.50

### What happened

I tried to import multiple raw files created by a Waters Q-Tof. But as soon as I started the import process I got the following message:

"java.io.IOException: Cannot run program
D:\MZmine-2.50-Windows\MZmin-2.50-Windows\lib\vendor_lib\waters\WatersRawDump.exe
CreateProcess error=2, System can find the chosen file
(ProcessBuilder.java:1228)

And the command window gave the following:
[14:05:51|SEVERE|net.sf.mzmine.taskcontrol.impl.WorkerThread]: Error of task Opening file D:\TimV_20190827_NSE_digestion_blank_1h_1to10_5inj_1.raw: java.io.IOException: Cannot run program "D:\MZmine-2.50-Windows\MZmine-2.50-Windows\lib\vendor_lib\waters\WatersRawDump.exe": CreateProcess error=2, Het systeem kan het opgegeven bestand niet vinden (ProcessBuilder.java:1128)
![Waters raw import fail](https://user-images.githubusercontent.com/54846559/64172112-824a6880-ce54-11e9-96fb-9f8162ba1253.png)

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by tomas-pluskal** [comment]
Oops, it seems I forgot to include the vendor libraries in the new build system.

Try with this updated build:
https://www.dropbox.com/s/p4r2msm1v7dbkuq/MZmine-2.50.1-Windows.zip?dl=0

**Comment by TilimoNED** [comment]
Hi Tomas,

Unfortunately I still get the same message. However, I haven’t deleted the older version, so I will try that as well and see what happens. Thank you for helping.

**Comment by tomas-pluskal** [comment]
Sorry, that was my bad (not enough sleep). Second attempt:
https://www.dropbox.com/s/7dau36pyh61avzh/MZmine-2.50.2-Windows.zip?dl=0

**Comment by TilimoNED** [comment]
It worked! Thank you for the quick response and solution

**Comment by tomas-pluskal** [comment]
Fixed in version 2.51

**Comment by CapriniEvaristo** [comment]
Hi Tomas, I am trying to import the Thermo raw data, using the latest version of MZMine2 (2.51) and I am having the same problem reported above. Could you helpme?

**Comment by Annexhc** [comment]
Quick work around: Download MSConvert and convert to mzML.

**Comment by CapriniEvaristo** [comment]
But the site says that it accepts raw data from thermo...

**Comment by Annexhc** [comment]
Yes, and it will work again. If you really need to analyze Thermo raw files without conversion to mzML you can try an older version, 2.42 should work. We are optimizing the back end of MZmine at the moment, sorry for the error.

**Comment by tomas-pluskal** [comment]
@CapriniEvaristo I think you are probably experiencing a different problem. The problem that was described in this issue has been fixed in version 2.51. Please file a new issue, include all the relevant error messages and log files, and double-check whether the raw file import works for you using older versions of MZmine.
