### ISSUE TITLE
feature finding error using Waters DDA data

### ISSUE THREAD

**Issue by katherinemaloney** [mzmine/mzmine2#696]
### Basic information

* My operating system: Windows
* My MZmine version: 2.41.2

### What happened

* I'm trying to do use MZmine2 to generate a feature quantification table for use to do [feature-based molecular networking](https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking-with-mzmine2/). I'm able to do the mass detection step, but when I try to use the ADAP chromatogram builder, I get the following error (for each of my mzML files): "Retention time of scan #47 is smaller then the retention time of the previous scan. Please make sure you only use scans with increasing retention times. You can restrict the scan numbers in the parameters, or you can use the Crop filter module"

As I look through the scans in each file, I notice a similar pattern:
The first scan is always an MS2 scan.
Scans 2 through ~45 are MS1 scans spaced ~every 0.1 minute apart.
Scans ~46 through ~260 are MS1 scans spaced ~every 0.03 minutes apart
The remaining scans are MS2 scans, roughly - but not exactly - in retention time order.

![image](https://user-images.githubusercontent.com/54910364/64281931-1ece4280-cf09-11e9-80c4-9fefd8ecee67.png)

I was going to try and use the crop filter to select a set of in-order scans, but I'm not sure (a) which set of scans I should be using for the chromatogram builder - presumably the second set since they are spaced closer together? or (b) how to set up the crop filter given that the exact scan number where the retention times restart varies slightly from sample to sample (MS1 restarts at scan# 45-47, switches to MS2 at scan# 250-262).

Or is it a problem with the raw file conversion to mzML?

I was hoping to upload the project file here, but now it seems that the program has frozen and I can't save it. :/

**Comment by asmirn1** [comment]
Hi,

Could you upload and share an mzML data file? 

First, we probably should understand why your data has two sets of MS1 scans.

**Comment by katherinemaloney** [comment]
Hmm. I'd like to but I can't quite figure out how... Tried creating a repository, but it said the file was too big. Is there another way to share it?

**Comment by asmirn1** [comment]
You can upload file on Google Drive or Dropbox and post a link here

**Comment by katherinemaloney** [comment]
Thanks for the speedy reply. Here goes: https://drive.google.com/file/d/14zec5OsCVI7ba73ErpKsFlWux9oZ-M61/view?usp=sharing

**Comment by asmirn1** [comment]
I've looked into your file, and the order of scans in the file is different from their order in MZmine.

Scans in the file go:
1. MS1 at 0.020316666 min,
2. MS1 at 0.026316667 min,
3. MSn at 0.0292333327 min,
4. MSn at 0.0317333341 min,
...

So, my guess is that MZmine doesn't read your file correctly. What tool did you use to convert your raw data into mzML? Also, could you try to convert your raw data into mzXML or CDF instead?

**Comment by asmirn1** [comment]
@tomas-pluskal 
I saw some other recent issues with importing raw data files. Can this be related to those issues?

**Comment by tomas-pluskal** [comment]
@asmirn1 Not sure which issues you are referring to.

This could be a bug in the jmzml library. We need to do some testing to find out where it comes from.

**Comment by asmirn1** [comment]
Sure, I'll test it.

**Comment by katherinemaloney** [comment]
Thank you for checking that. I've asked my collaborator to send me the raw data files. I'll try converting again from those.

**Comment by asmirn1** [comment]
@tomas-pluskal 

I've found a problem with the mzML file. Its scan numbers are not unique.

This file contains 1660 scans. Each scan has an id-attribute. The first few ids are:
- Scan with id="function=5 process=0 scan=1"
- Scan with id="function=1 process=0 scan=1"
- Scan with id="function=2 process=0 scan=1"
- Scan with id="function=3 process=0 scan=1"
...
- Scan with id="function=3 process=0 scan=2"
...

The `jmzml` package reads all the scans correctly. However, the code retrieves the scan number from the id-attribute (see method `MzMLReadTask.convertScanIdToScanNumber()`), so the first four scans will have the same scan number (scan# = 1). Then, this scan number is used to store all the scans in `Hashtable<<Integer, StorableScan>>` in class `RawDataFileImpl`. Thus, many scans are overwritten in the hash table, and only 470 scans are displayed in MZmine. 

I guess, we could add the following code to `MzMLReadTask`:
1. Check if the scan numbers are unique
2. If they are not unique, ignore them and generate new scan numbers: 1, 2, 3, ...

What do you think?

**Comment by tomas-pluskal** [comment]
Thanks for looking into this, Alex!

Yes, I agree with the solution you propose.

**Comment by asmirn1** [comment]
Okay, I'll implement these changes.

**Comment by katherinemaloney** [comment]
Just revealing my ignorance here, but does this mean there is something I can still do with my existing files? Or do you still recommend I try reconverting the raw files? (Wondering in part because I haven't yet received the raw files from my collaborator...)

**Comment by asmirn1** [comment]
The fix for this bug will be included in the next official release of MZmine. For now, I can give you a developer version of MZmine. 

Are you running MZmine on Windows or MacOS (Linux)?

**Comment by katherinemaloney** [comment]
Windows. Thank you!

**Comment by asmirn1** [comment]
@katherinemaloney 
Try using this MZmine: https://drive.google.com/file/d/1mK9sGaDyl4qeOcK7OffPT75LmluLPsoA/view?usp=sharing

It should be able to read your files.

**Comment by akoladeace** [comment]
**Basic information**
My operating system: Windows
My MZmine version: 2.51

**What happened**
I'm trying to use MZmine2 to generate a feature quantification table for use to do feature-based molecular networking. I'm able to do the mass detection step, but when I try to use the ADAP chromatogram builder, I get the following error (for each of my mzML files): "Retention time of scan #1927 is smaller then the retention time of the previous scan. Please make sure you only use scans with increasing retention times. You can restrict the scan numbers in the parameters, or you can use the Crop filter module"

Please, how could I resolve this
