### ISSUE TITLE
Unhandled exception in Predict Molecular Formula

### ISSUE THREAD

**Issue by pvervliet** [mzmine/mzmine2#698]
### Basic information

* My operating system: Windows 10 Enterprise - Version 1903 - OS build 18362.113
* My MZmine version: 2.51

### What happened

After I have done all my preprocessing (deconvolution, deisotoping, alignment, gap-filling and filtering) I wanted to predict a molecular formula for some of the features in my final feature list.

The parameters for the feature I want to generate a formula for: 
m/z: 193.0507   charge: 1
Ionization type: [M-H]-
Calculated mass: 194.0580

m/z tolerance: 0.02 m/z or 10 ppm
Elements: C (0-100), H (0-100), O (0-50)

No other criteria were selected.

The error I receive: 
"Unhandled exception in task Formula prediction for 194.0580:
java.lang.NullPointerException (SingleRowPredictionTask.java:214)

![Screenshot 2019-09-05 at 09 33 52](https://user-images.githubusercontent.com/38757650/64321175-521fd880-cfc0-11e9-8173-92d70bc52614.png)

I have also tried other criteria and features but the error persists.

**Comment by tomas-pluskal** [comment]
Does this happen with all peaks or only some?

**Comment by tomas-pluskal** [comment]
I have not been able to reproduce this bug with MZmine 2.51:

<img width="536" alt="Screen Shot 2019-09-09 at 09 17 33" src="https://user-images.githubusercontent.com/1796692/64534088-c4efc300-d2e2-11e9-8abe-8975dcefacf9.png">

Worked fine:

<img width="724" alt="Screen Shot 2019-09-09 at 09 17 46" src="https://user-images.githubusercontent.com/1796692/64534074-c0c3a580-d2e2-11e9-930c-8d4e7aa0ac17.png">

**Comment by cruzerswtich** [comment]
Hello,

I am new to MZmine, currently using its 2.53 version on a Window 10 Pro 64-bit operating system, to do formula prediction.

I am having the same error just as @pvervliet for all of the peaks, regardless of the parameter settings. I see that you @tomas-pluskal did the test on a mac system and it worked. Both @pvervliet and I are having the issue with Windows 10.

Is there any solution to solve this?

PS. I can do formula prediction for the whole feature list by doing: Feature list methods>Identification>Formula prediction. This will give formula identity in the feature list table. The error occurs when I want to predict selected features from the feature list table, just like how you have tested  @tomas-pluskal , which provides RDBE and other values that are necessary for my project.

Thank you in advance for looking into it.

**Comment by tomas-pluskal** [comment]
@cruzerswtich You should file a new issue and provide a link to your .mzmine project file as well as the exact parameter values that you used, otherwise it's impossible to investigate the issue.

**Comment by cruzerswtich** [comment]
> 

Thank you for the reply. Will do that.

**Comment by cheilarianti** [comment]
Hello, I have the same problem,
shall I file a new issue?
