### ISSUE TITLE
Error of task Detecting chromatograms in ,,,

### ISSUE THREAD

**Issue by AmmarTahir2019** [mzmine/mzmine2#701]
### Basic information

* My operating system: Win10
* My MZmine version: 2.5.1

### What happened

* Error of task Detecting chromatograms in CDF, RAW or MZXML (these extensions I have tried)
1) I do perform mass detection first and it is successful 
2) when i want to perform ADAP chromatogram builder I get the error message (below)

Any advice from your side? Thanks a lot for the efforts :-)

 
![image](https://user-images.githubusercontent.com/55129645/64593027-92f76300-d3ad-11e9-9505-61f0f307edba.png)

**Comment by AmmarTahir2019** [comment]
here are the parameters:

![image](https://user-images.githubusercontent.com/55129645/64593322-30eb2d80-d3ae-11e9-82e8-1c5bd7d8b594.png)

**Comment by asmirn1** [comment]
Could you share parameters for mass detection?

**Comment by tomas-pluskal** [comment]
@AmmarTahir2019 I think the error message that you are getting is quite self-explanatory, isn't it? 
**Scan HS2.mzxml number 1 does not have a mass list "masses 5"**

**Comment by AmmarTahir2019** [comment]
> Could you share parameters for mass detection?

Thank you for your reply! Here are the parameters, the original file is thermo RAW, but I could not open it with mzmine, so I converted it to mzxml using Proteowizard. 

![image](https://user-images.githubusercontent.com/55129645/64758866-fca27900-d535-11e9-91fe-afce05583df3.png)
![image](https://user-images.githubusercontent.com/55129645/64758880-0926d180-d536-11e9-86c2-54a28bf3b8c4.png)

![image](https://user-images.githubusercontent.com/55129645/64758898-1348d000-d536-11e9-814e-4965e4a40b77.png)

**Comment by AmmarTahir2019** [comment]
> @AmmarTahir2019 I think the error message that you are getting is quite self-explanatory, isn't it?
> **Scan HS2.mzxml number 1 does not have a mass list "masses 5"**

Thank you for your reply! Not really to me? I am using mzmine for the first time, I would be grateful if your could point out my mistake! Thank you in Advanced.

**Comment by tomas-pluskal** [comment]
@AmmarTahir2019 Like Alex said, the problem is most likely in your mass detection step. You can verify your generated mass lists by opening the scan tree in the main window's "Raw data files" section:

<img width="338" alt="Screen Shot 2019-09-13 at 15 21 10" src="https://user-images.githubusercontent.com/1796692/64888941-22b14180-d63a-11e9-8ba8-3fcab361df85.png">

(in this case, "citrusMS1" is the name of the mass list)

**Comment by AmmarTahir2019** [comment]
> @AmmarTahir2019 Like Alex said, the problem is most likely in your mass detection step. You can verify your generated mass lists by opening the scan tree in the main window's "Raw data files" section:
> 
> <img alt="Screen Shot 2019-09-13 at 15 21 10" width="338" src="https://user-images.githubusercontent.com/1796692/64888941-22b14180-d63a-11e9-8ba8-3fcab361df85.png">
> 
> (in this case, "citrusMS1" is the name of the mass list)

Thank you all for your support! without applying a filter the procedure works flawless! When I choose the polarity then issues start to arise. I guess it is a problem of my raw files! Anyhow , Thank you all for your replies and help!
