### ISSUE TITLE
How to process MS/MS data by MZmine? 

### ISSUE THREAD

**Issue by wzh244** [mzmine/mzmine2#704]
Hi,

My MZmine 2 version 2.40.1
My operating system is 64-bit.

I want to know how to process MS / MS data through MZmine? What are the general steps involved in batch mode? Any help is greatly appreciated.

Best,
wzh244

**Comment by Annexhc** [comment]
We need more information, what is your target?

**Comment by robinschmid** [comment]
Quick response from my vacation.

You can assign all MS/MS scans to the corresponding features during feature deconvolution or how I prefer it: select a feature list and use feature list methods/filters/group MS/MS scans with features (hope the name of the module is correct ;) )

The second way allows you to change the isolation width and retention time tolerance.

Now you can use many different MS/MS dependent methods:
- SIRIUS structure prediction or export
- GNPS feature based molecular networking (you can directly export and run a GNPS job from MZmine)
- create your own MS/MS spectral library
- download massbank of north america library and perform spectral library matching
- lipid identification
...

Cheers
Robin

**Comment by wzh244** [comment]
> We need more information, what is your target?

When processing  MS1 data, we use the following sequence as shown.

![QQ截图20190916202634](https://user-images.githubusercontent.com/55376549/64957934-982e4380-d8c0-11e9-9bb2-2aefb48c58e5.jpg)

What sequences are needed to process MS2 data with batch mode? My target is to find out which sequences are needed in batch mode to process MS2 data?

**Comment by tomas-pluskal** [comment]
@wzh244 "Process MS2 data" can mean many different things. If you don't explain clearly what is your goal, we cannot give you any advice.
