### ISSUE TITLE
Couldn't compile MZmine/MSDK

### ISSUE THREAD

**Issue by asmirn1** [mzmine/mzmine2#714]
### What happened

I couldn't compile MZmine on a new machine (OS Windows). Has anyone else had problems with compiling MZmine or MSDK recently?

This is the output:

> C:\Users\AleksandrSmirnov\Projects\mzmine2>gradlew.bat runtimeZip
> 
> > Configure project :
> OS detected as Windows
> 
> > Task :compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileJava'.
> > Could not resolve all files for configuration ':compileClasspath'.
>    > Could not resolve org.json:json:1.0.
>      Required by:
>          project : > io.github.msdk:msdk-id-sirius:0.0.27 > de.unijena.bioinf.ms:fingerprinter_oss:1.1.3
>       > Could not resolve org.json:json:1.0.
>          > Could not get resource 'https://jitpack.io/org/json/json/1.0/json-1.0.pom'.
>             > Could not HEAD 'https://jitpack.io/org/json/json/1.0/json-1.0.pom'. Received status code 522 from server: Origin Connection Time-out
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 35s
> 1 actionable task: 1 executed

**Comment by tomas-pluskal** [comment]
It says `Could not HEAD 'https://jitpack.io/org/json/json/1.0/json-1.0.pom'. Received status code 522 from server: Origin Connection Time-out` but my connection to https://jitpack.io/org/json/json/1.0/json-1.0.pom works fine (gives code 404 file not found which is okay).

**Comment by asmirn1** [comment]
When I follow https://jitpack.io/org/json/json/1.0/json-1.0.pom in my browser, I get code 404 as well. But why this is okay? It seems that the compiling stops because it cannot find `org.json:json:1.0`

**Comment by tomas-pluskal** [comment]
It is fine that the json artifact is not found in the jitpack repository. It should be found here:
https://bio.informatik.uni-jena.de/repository/libs-release-oss/org/json/json/1.0/json-1.0.jar

**Comment by asmirn1** [comment]
Okay, it seems that moving
```
maven {
        url = "https://bio.informatik.uni-jena.de/repository/libs-release-oss/"
    }
```
in front of jitpack.io has solved this issue.
