### ISSUE TITLE
How to redirect the TEMP directory?

### ISSUE THREAD

**Issue by wittetom** [mzmine/mzmine2#715]
### Basic information

* My operating system: Windows
* My MZmine version: 2.51

### What happened

I'm running MZMINE on windows on a computer with a storage drive (D:) that has much more free space than my C drive.  How do I direct MZMINE to use this storage drive as its temp directory?  I see from older posts that this used to be editable in the batch file for mzmine but this seems to have been removed. 

Thank you!  

Tom Witte

**Comment by tomas-pluskal** [comment]
Have you tried setting  the Windows TEMP environment variable? 
https://www.rapidee.com/en/environment-variables

**Comment by minzaroma** [comment]
I've got the same issue, unfortunately I don't know what to do with your suggestion. Do you mean to modify the paths within our system? I cannot do that because I'm working on a server.

The file in the pic is how it was beforehand - where would you set it in the new version?
![grafik](https://user-images.githubusercontent.com/52671757/69425529-5f30a600-0d2b-11ea-926f-bf75ffa238ce.png)

Thanks a lot!
Caro

**Comment by tomas-pluskal** [comment]
Hi @minzaroma 
If you cannot modify the environment variables, you can set the java.io.tmp property in the start script:

Change
````
set DEFAULT_JVM_OPTS="-showversion" "-XX:MaxHeapFreeRatio=100" "-XX:InitialRAMPercentage=30" "-XX:MinRAMPercentage=80" "-XX:MaxRAMPercentage=80" "-Djava.library.path=lib" "-Dapple.awt.application.name=MZmine 2.52" "-Dapple.laf.useScreenMenuBar=true"
````
to 
````
set DEFAULT_JVM_OPTS="-showversion" "-XX:MaxHeapFreeRatio=100" "-XX:InitialRAMPercentage=30" "-XX:MinRAMPercentage=80" "-XX:MaxRAMPercentage=80" "-Djava.library.path=lib" "-Dapple.awt.application.name=MZmine 2.52" "-Dapple.laf.useScreenMenuBar=true" "-Djava.io.tmpdir=F:\TEMP"
````
That should help.

**Comment by minzaroma** [comment]
Ok perfect, seems that's what I need!

**Comment by bjonnh** [comment]
Shouldn't we add that to the start scripts? Ability for the user to set the temp folders easily? (or better using an environment variable?)

**Comment by tomas-pluskal** [comment]
@bjonnh I agree :) Would you like to contribute?

**Comment by bjonnh** [comment]
Yes, I'm working on it, but I'll only be able to test that on Linux, and maybe Windows (but if someone wants to do that one go ahead).

**Comment by bjonnh** [comment]
The most feasible option I can think of would be to override all calls to our own function for determining temp directory, that would read from an environment variable and fallback to Java.io.tmpdir if it is not set or not valid. I would also add a line in the log that tell the user where tmp files are.

**Comment by tomas-pluskal** [comment]
Adding a line to the log is fine. 
But I don't like the idea of overriding a function within MZmine. The location of temporary files is set using the java.io.tmpdir property, so you can just design a clean way to set that property in the startup script. By the way, on Windows the default value of that property IS set using the environment variable TMP.

**Comment by bjonnh** [comment]
Yes but this is only valid for windows, and the application gradle plugin doesn't really allow for heavy tweaking of start files like that… We can also patch the startup file after creation, but that can be problematic as well if the gradle plugin change…

**Comment by bjonnh** [comment]
Is the tmp dir on Mac /tmp as well? In that case we can just add the redefinition of the var with -Djava.io.tmpdir=$TMPDIR  and make a custom script creator (we will just have to be careful if there are any breaking changes in the gradle application plugin)

**Comment by bjonnh** [comment]
I'll be working on it on this branch: https://github.com/bjonnh/mzmine2/tree/feature-tmpdir

**Comment by bjonnh** [comment]
It works by simply doing:
JAVA_OPTS=-Djava.io.tmpdir=/somewhere ./startMZmine-Linux

So maybe we can just keep it like that and put that in the documentation somewhere?

Can anybody check that this also works on Mac? (you can use my feature branch to see easily where the temporary directory is)

**Comment by tomas-pluskal** [comment]
It does work on Mac too.

I agree adding the documentation is sufficient. For any changes to the code, please make them in the mzmine3 repository, not the mzmine2.

**Comment by bjonnh** [comment]
Didn't know there was a 3… I'll switch both of today's branches.
