### ISSUE TITLE
Local Spectra database Search 

### ISSUE THREAD

**Issue by Mattesimone** [mzmine/mzmine2#727]
### Basic information

* My operating system: Windows 10 pro 64 bit VM in MacOS 10.14.6
* My MZmine version: 2.51

### What happened
Hello,

I'm trying to use the tool Feature list Method-- identification--Local Spectra database Search and it's seem to work not properly: I mean I have few identifications from my library less than expected.
Moreover I get multiple messages of errors that I am attaching.

Thank in advance

Matteo Simone 

![Screenshot 2019-10-22 at 10 46 55](https://user-images.githubusercontent.com/56867271/67270599-48432d80-f4b9-11e9-9187-bbc442abbb29.png)
![Screenshot 2019-10-22 at 10 48 16](https://user-images.githubusercontent.com/56867271/67270691-788acc00-f4b9-11e9-9ddf-5634f1a0c32a.png)

[library_example.txt](https://github.com/mzmine/mzmine2/files/3754475/library_example.txt)

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by robinschmid** [comment]
Hey Matteo,

where did you download/ how did you create this library? 
Is this supposed to be in msp format?

1. Did you run mass detection on all MS2 scans? It seems like some scans do not have the mass list *"Gneg3"* which you specified in the library matching parameters. Make sure to run mass detection on all MS-level 2 scans.

2. It is crucial that you pair MS2 scans with their corresponding features. This can be done in two ways:
    - During feature deconvolution (set MS2 pairing tolerances for retention time and m/z)
    - Use Feature list methods/filters/**Group MS2 scans with features**: You might want to try to use a wider m/z tolerance (as the isolation in the instrument is also wider)

![image](https://user-images.githubusercontent.com/10366914/67293022-21e6b780-f4e4-11e9-8a11-5f6a8e561f3b.png)

### msp format downloaded from MoNA (Mass bank of North America)
![image](https://user-images.githubusercontent.com/10366914/67292359-324a6280-f4e3-11e9-85e3-3a4301b640dc.png)

**Comment by robinschmid** [comment]
Are you applying this to low-res data? Otherwise, your tolerances are very high.

**Comment by Mattesimone** [comment]
Hey Robin,

Yes, I’m using low-res data.
Our library was created starting from .mgf files by using a python script that I'm attaching.
I run mass detection on all ms2 scans and I used feature deconvolution for pairing MS2 scans; so I tried the second way with wider m/z tolerance (m/z 1) : list methods/filters/Group MS2 scans with features but I obtained the same errors.

Best regards

Matteo Simone

**Comment by robinschmid** [comment]
It might be best if you directly answer on GitHub.

Can you verify that you ran mass detection on all MS2 scans? Sometimes users apply filters to mass detection (apart from MS Level=2) and then some of the MS2 scans have no mass list with the given name.

Otherwise, please copy your whole console into a txt and attach it here.

Your example follows a strange format... What format did you convert it to? (see below)
The mgf file itself was no library? Because the supported formats are: mgf, msp, json (MoNA and GNPS), jdx.

![image](https://user-images.githubusercontent.com/10366914/67376823-0c759a00-f585-11e9-87d7-022f3665bd37.png)

**Comment by Mattesimone** [comment]
Hey Robin,

you were right. I realized I had applied a filter on retention time to mass detection. I did a test by keeping RT autorange and then the identification tool worked well. Thank you so much.
All the best
Matteo Simone

**Comment by robinschmid** [comment]
Sounds good.
So the issue can be closed?

Cheers
RObin

**Comment by Mattesimone** [comment]
Hey Robin,

I would like to ask you one more question: when mass lists are generated for all MS level 1 scans, a green check mark will appear next to the raw data file icon. Analyzing another my data set after mass detection MS level 1 and 2 (no filtering), not all files have a green check. What does it mean? The features have been created for all the samples including those that do not have the green check but then I get the same error when I go to use the identification tool. If I consider only those with the green check I can use identification tool without errors.

Best regards

Matteo Simone

**Comment by robinschmid** [comment]
That's weird. 
Have you tried to remove the scan filter completely?
Can you find scans in the raw file that have no check/mass list?
@tomas-pluskal any idea?

**Comment by Annexhc** [comment]
Hey Matteo,
can you show us a screenshot of your mass detection settings? As Robin suggested, maybe there are still some scan filters enabled. I dont know your raw data, but if you want to consider every scan for mass detection you have to make sure that you also dont use the polarity and scan type filter (centroid, profile, thershold). Make sure they are set to "any".
best wishes,
Ansgar

**Comment by tomas-pluskal** [comment]
The green check mark probably won't appear if there are no MS1 scans in the file. If that is not the case, please provide more information (screenshots, project files, etc.).

**Comment by Mattesimone** [comment]
Hello,

Sorry but you're still right. I was still using the positive polarity filter and the scan centroid type. Using 'any' for polarity and scan type filters I got the green check on all the files and the identification was successful. However, I was still wondering if the fact of using mass detection both on positive scans and on negative scans can confuse the software, obtaining a mixture of both. thank you for your support and for your time.

Yours sincerely

Matteo

**Comment by Mattesimone** [comment]
Hello,

the mass analysis method I used to run my samples only provides positive mass fragmentation and for this reason I decided to remove intermediate negative polarity.

Matteo

**Comment by robinschmid** [comment]
Sometimes the scan type recognition fails and it switches between centroid and profile (although all scans are of the same type). 
I think the polarity filter should be fine. Otherwise, you could try to filter out one polarity as it is usually more convenient.

**Comment by robinschmid** [comment]
Rawdata methods/filtering/Crop filter
I think this one was the one to filter out specific scans
