### ISSUE TITLE
Spectral export check button

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#729]
It is unclear what this button actually does. Perhaps some tooltip would be useful?

<img width="1487" alt="Screen Shot 2019-10-22 at 11 23 02" src="https://user-images.githubusercontent.com/1796692/67302154-7414e200-f4be-11e9-9f05-50ad2473acf6.png">

**Comment by robinschmid** [comment]
Solved by PR #732 (?)

Button is removed when only one entry is submitted. 
Tooltips added to all buttons and text fields
