### ISSUE TITLE
Help files: All links are opened in the help dialog

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine2#730]
Hey all,

we should change the link outs in the help files. They open up in the help dialog and there is no return button.
1. We should redirect this to the default browser
2. if a video (youtube) is linked (see GNPS export help)- the audio and video keeps playing after the dialog is closed

![image](https://user-images.githubusercontent.com/10366914/67304538-45b1f980-f4f4-11e9-93e1-351f2df4b437.png)

**Comment by tomas-pluskal** [comment]
How about now, does it work for you?

**Comment by robinschmid** [comment]
Solved by #731
