### ISSUE TITLE
Correct usage of terminology

### ISSUE THREAD

**Issue by tsufz** [mzmine/mzmine2#735]
### Basic information
* My MZmine version: 2.51

### What happened

Somehow, the term feature was introducted in MZmine. In my opinion, this term is not used consequently correct.

As discussed in https://twitter.com/tsufz/status/1187625990253678592?s=20, a peak is a single peak in a sample defined by at least RT, m/z, area, height; a feature is a group of aligned peaks over single samples in my batch with averaged RT and m/z.

Hence, the naming of `RAW data methods | Feature Detection` is totally wrong. These methods work on single peaks in single samples and not over all samples in the batch.

Also the term `Feature list methods` is wrong and misleading following the definition above. The previous `peak list` (with non-aligned peaks) will get to a `feature list` first after `alignment`. If no `alignment` is used, the `peak list` stays a `peak list`.

Therefore I suggest to use the term `peak list` and not `feature list`.

Yours,
Tobias

**Comment by robinschmid** [comment]
To my understanding, a peak is a two-dimensional profile. We usually have two types: MS peaks in spectra and chromatographic peaks. For clarification, I use feature to describe a chromatographic peak with a specific m/z value. Single sample or aligned across multiple samples.

`peak list` can also (and it often does) refer to a signal list (centroids) which is extracted from a single spectrum or multiple spectra, e.g., for direct infusion analysis, imaging analysis, ...

**Comment by tomas-pluskal** [comment]
@tsufz Unfortunately the terminology is not standardized and different projects use it differently. For example, OpenMS uses 'feature' for a group of isotopes of a single peak.

See this paper (which makes things even worse):
http://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-16-S7-S2

I agree with Robin, our definition is the best :)

**Comment by tomas-pluskal** [comment]
<img width="1092" alt="Screen Shot 2019-10-25 at 08 04 14" src="https://user-images.githubusercontent.com/1796692/67569966-461de080-f6fe-11e9-94f2-51ef8f636dc7.png">
I made this slide a while ago to demonstrate the different terms that you can find in the literature

**Comment by tomas-pluskal** [comment]
Let's close this issue and continue the discussion on twitter, to avoid redundancy.
