### ISSUE TITLE
GNPS and MZmine2

### ISSUE THREAD

**Issue by naydja** [mzmine/mzmine2#745]
Hello guys!

I started working with metabolomics recently and I've got some difficulties with the MZmine2 software... Hope you can help me!

I'm currently using Windows 10 operating system and MZmine version 2.40.

Here's what's happening: First, I did a molecular networking (on GNPS website) with the LC-MS/MS data I got from various extracts from actinobacteria fermentation media. I found some interesting features in some of them and I need to compare and quantify these molecules among samples, besides preparing the data for statistical analysis. For this I intend to use MZmine2. It turns out that even after trying to use several different parameters in data processing, in the end I can't find any features in the lists generated by MZmine2 that have the same m/z values annotated by GNPS. The data were processed following these steps (with examples of parameters I used): mass detection (noise level set to 1.0E4), chromatogram builder (minimum time span of 0.05 min, m/z tolerance of 0.001 m/z and minimum height of 1.0E4), chromatogram deconvolution (search minimum in RT range 0.1 min, chromatographic threshold 90%, minimum relative height 1%, minimum absolute height 1.0E4, minimum ratio of peak top/edge 2 and peak duration range 0.05–3 min), deisotoping (isotopic peaks grouper, m/z tolerance 0.001 m/z and retention time tolerance 0.1 min), normalization (linear normalizer, total raw signal, peak area) and alignment (join aligner, m/z tolerance 0.001 m/z, m/z weight 20, retention time tolerance 0.1 min, and retention time weight 20).

Does anyone have any tips that could be helpful to me?

Thanks!!!

**Comment by robinschmid** [comment]
Hey naydja, welcome :)

It is always a good idea to update to the latest version (2.51). 

Your first approach was molecular networking on GNPS directly from the mzML files, right. And now you want to apply feature-based molecular networkng. (https://www.biorxiv.org/content/10.1101/812404v1)

I guess you have already checked out this video by Daniel: (It is in a playlist with more related MZmine/GNPS FBMN videos)
https://www.youtube.com/watch?v=5jjMllbwD-U&list=PL4L2Xw5k8ITzd9hx5XIP94vFPxj1sSafB&index=2&t=233s

**Comment by naydja** [comment]
Hello, robinschmid! Thanks for your answer!

Well, in fact the problem is that I cannot find the features annotated by GNPS in the MZmine lists. For example: GNPS indicated a node with m/z of 266.10, identificated as anisomycin. Searching for this specific m/z on the list, I cannot find anything.

I have no idea of what's wrong...

**Comment by robinschmid** [comment]
You can use MZmine to process the data and submit to GNPS FBMN and also export to do statistics in MetaboAnalyst.

The settings seem ok. However, you always need to change them in regards to your instrument, study design, and acquisition method.
Please tell me something about:
- Instrument
- Gradient length
- data points on the peak (MS1)
- data dependent acquisition? (Top n=?)
- did you convert the data to mzML?

Maybe provide a representative sample or mzmine project.

### Parameters
To set the noise level and minimum heights: Open some spectra zoom axis to see the noise and use arrow keys to check the noise across your sample. 

Use **ADAP chromatogram builder **instead:
- Minimum data points (process once and look at medium sized features)
- Next parameter is basically the noise level
- Higher m/z tolerance: 0.0015 + 5-10 ppm


**Deconvolution**
- minimum relative height **0%** (this parameter does not make any sense in my view - set to 0)

**Comment by robinschmid** [comment]
For statistics, consider using **Gap filling**, e.g., the Multithreaded Peak Finder. After Gap filling you might want to use the Peak Filter to filter out bad features.

Did you try to plot an EIC (or base peak plot) with this specific m/z?
Did you try to submit your MZmine aligned feature list to GNPS feature based molecular networking?

Feature detection can always fail. Both feature based and traditional MN have their own strengths and drawbacks.
However, you should be able to extract most features with the right settings. 

Sometimes you lose features in deconvolution:
- peak top/edge 2 can sometimes be too restrictive
- Chromatographic threshold 90% might be too high if an EIC is noisy or if you have plenty of isomers (my range is 80-90%)

**Comment by naydja** [comment]
Ok, let's go:

Instrument: **Acquity UPLC H Class - Xevo G2-XS Qtof (Waters)**
Gradient length: **10 min**
data dependent acquisition? (Top n=?): **no**
did you convert the data to mzML?: **I converted to mzXML format**

Parameters
To set the noise level and minimum heights: Open some spectra zoom axis to see the noise and use arrow keys to check the noise across your sample: **I did it.**

Use **ADAP chromatogram builder **instead: **Right, I'm gonna try it.**

Minimum data points (process once and look at medium sized features)
Next parameter is basically the noise level
Higher m/z tolerance: 0.0015 + 5-10 ppm
Deconvolution

minimum relative height 0% (this parameter does not make any sense in my view - set to 0): **I used 1%.

**

**Comment by naydja** [comment]
> For statistics, consider using **Gap filling**, e.g., the Multithreaded Peak Finder. After Gap filling you might want to use the Peak Filter to filter out bad features.
> 
> Did you try to plot an EIC (or base peak plot) with this specific m/z?: **I have searched for this m/z in the aligned peak list.** 
> Did you try to submit your MZmine aligned feature list to GNPS feature based molecular networking?: **Yes, I have. I used the option for upload the archives generated by mzmine directly to GNPS. The result was pretty different of the first network I created.** 
> 
> Feature detection can always fail. Both feature based and traditional MN have their own strengths and drawbacks.
> However, you should be able to extract most features with the right settings.
> 
> Sometimes you lose features in deconvolution:
> 
> * peak top/edge 2 can sometimes be too restrictive
> * Chromatographic threshold 90% might be too high if an EIC is noisy or if you have plenty of isomers (my range is 80-90%)

**Comment by robinschmid** [comment]
> data dependent acquisition? (Top n=?): no
How did you acquire the MS2 spectra?
For GNPS (or non-target in general) people usually use DDA.

The results are usually different yes. (FBMN and MN)

> minimum relative height 0% (this parameter does not make any sense in my view - set to 0): Iused 1%
I always go for the absolute height only and set this parameter to 0%
If you have to peaks in the same chromatogram one is 1E5 the other one 1.1E7 - both are real and should be considered.

**Comment by robinschmid** [comment]
Is this issue still active?

**Comment by naydja** [comment]
Hi! The problem has been solved, thanks!
