### ISSUE TITLE
exporting to JPG ot tif

### ISSUE THREAD

**Issue by mahmoudabbassaleh** [mzmine/mzmine2#746]
### Basic information

* My operating system:
* My MZmine version: 
how to export 3d graph to JPG or TIF
### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by tomas-pluskal** [comment]
The 3D plot has no export function, but you can take a screenshot.
