### ISSUE TITLE
Error in importing mzXML files into MZmine

### ISSUE THREAD

**Issue by sapnatars** [mzmine/mzmine2#747]
### Basic information

* My operating system:Windows 7 64 bit operating 
* My MZmine version: 2.51

### What happened
I selected a list of .mzXML files to import into mzmine via the raw data import tab and I have the following error 
![MZmine error](https://user-images.githubusercontent.com/57454731/68326290-1cb76a00-0099-11ea-91bd-5388db642177.jpg)
![MZmine error](https://user-images.githubusercontent.com/57454731/68326306-28a32c00-0099-11ea-92dc-aa8bcab50b4f.jpg)

please suggest any ideas you may have to resolve this.

**Comment by sapnatars** [comment]
Also, I am importing this list which contains files of both negative and positive mode of analysis

**Comment by tomas-pluskal** [comment]
Please provide the mzXML file that gives you the error. You can share it using dropbox, google drive, etc.

**Comment by sapnatars** [comment]
Thanks.
Here is the link: 
https://drive.google.com/file/d/1nbZcTsotQEUFpOt3M_BtP2zgv1XBD1bt/view?usp=sharing

**Comment by sapnatars** [comment]
These are only a couple files out of 110 sample data files, which are both in positive and negative mode.I look forward to your response. Thanks.

**Comment by robinschmid** [comment]
**Few questions**
- Which mass spectrometer?
- first mzML is newer than mzXML.
- please attach your conversion parameters in msconvert
- please also send a RAW file

**Comment by sapnatars** [comment]
Hi Robin thanks for your response. below is the info:
1. Which mass spectrometer?: ACQUITY UPLC-Synapt (Waters Corp., Milford, MA).  
2. first mzML is newer than mzXML.: could you please elaborate on this? I did not understand this point.
3. please attach your conversion parameters in msconvert: my collaborator did the conversion, and they mention that they did not input any specific parameters. 
4. please also send a RAW file: please see the link below
https://drive.google.com/drive/folders/1cy7Zyd3wLrfjHIUYyg40mYGkCZQpe6pB?usp=sharing

I appreciate all your help. Thanks.

**Comment by tomas-pluskal** [comment]
Your mzXML files are somewhat non-standard, because the msLevel attribute in the scans is empty. I added a workaround for that, so in the next version of MZmine you will be able to import your files.

**Comment by tomas-pluskal** [comment]
As to point 2., I think @robinschmid meant that mzML is a newer standard than mzXML (which is obsolete at this point). You should use the mzML format instead (supported by both MSConvert and MZmine).

**Comment by sapnatars** [comment]
So what steps should I take now? Can you please suggest? 
1. When you mention" I added a workaround for that, so in the next version of MZmine you will be able to import your files.": which version should I use then.
2. When you mention: Your mzXML files are somewhat non-standard, because the msLevel attribute in the scans is empty.: do you suggest I convert the raw files again to MzML? Any suggestions on parameters that I should input?
Thank you for all your help. I sincerely appreciate it.

**Comment by tomas-pluskal** [comment]
1. You can use the next version (2.52) after it is released. Hopefully soon.
2. I do think using mzML is a better choice for you, so try re-converting the file. I have no particular recommendation for the conversion parameters, read the MSConvert documentation for that purpose.

**Comment by sapnatars** [comment]
Thanks Tomas.I will give that a try and get back to you, if I come across any errors. Many thanks.

**Comment by kwebber3** [comment]
I had a similar error, so I am trying to import thermo raw files instead, but it is super slow. Is there an implicit conversion to mzML? if so it doesn't work very well.
