### ISSUE TITLE
cannot open MZmine 2.51 on Mac OS 10.15 (Catalina)

### ISSUE THREAD

**Issue by du-lab** [mzmine/mzmine2#752]
![image001](https://user-images.githubusercontent.com/13665067/68624101-16aff780-04a4-11ea-9989-1c43bb54be74.png)

**Comment by tomas-pluskal** [comment]
See https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave

**Comment by tomas-pluskal** [comment]
When jpackage (https://jdk.java.net/jpackage/) is finished (hopefully in Java 14 or 15), we can deploy native packages for each platform and that should finally resolve this issue.
