### ISSUE TITLE
About peak height

### ISSUE THREAD

**Issue by Fedemine19** [mzmine/mzmine2#753]
### Basic information

* My operating system: Windows 7
* My MZmine version: 2.51

### What happened
Hello people, maybe it's a basic question but I'm lost here. I performed the data mining steps according to tutorial and got my final table. In each row I see value of Height and Area next to a color light (green, yellow, red). The issue at hand is: What does this height value stand for? I need to filter peaks if their intensity is less than 1000. But this height value doesnt seem to match the BPC/TIC value for that ion in the chromatogram, is it maybe a peak height for the M-H ion instead of a chromatographic intensity??. Otherwise where can I find the BPC/TIC numeric value for each row (ID) of the table, so I can export it to Excel? 

Thank you so much in advance and I really hope you can help me

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by tomas-pluskal** [comment]
Peak height = peak intensity, it is the same thing.

If you have concerns about particular values that you see, please upload your project file so we can take a look at it.

**Comment by Fedemine19** [comment]
![Height1](https://user-images.githubusercontent.com/57727470/68797379-42151c80-0633-11ea-9d41-26ec4245881f.png)
![Height2](https://user-images.githubusercontent.com/57727470/68797380-42adb300-0633-11ea-81dd-6d8d3b832788.png)
Thank you for your kind answer, I couldnt upload my project, so I took screenshots for you in picture 1 you will see the color lights and the Height titles im talking about, and in picture 2 the chromatogram for the feature in row 1 where the intensity is 1,5E6, not matching the value of picture 1 (which is 4.5E4 for sample F1). I would need to see displayed the intensity for the real value, or to understand the 4.5E4 maybe.

Thank you so much!!

**Comment by tomas-pluskal** [comment]
The values should indeed be the same. But I cannot help if you if I cannot take a look at the project data. So again, please upload your project file first. You can use Google Drive, Dropbox, etc.

**Comment by Fedemine19** [comment]
I could upload the mzmine project to my onedrive. this is the shared link. Hope it works, if you need all the spectra to open it then It'll take more time uploading all the spectra.


https://1drv.ms/u/s!AiE3mhbJdBsDknl1D4w1-l5hO3e9?e=EuhMA9

**Comment by tomas-pluskal** [comment]
Awesome. And what is the ID of the peak that you mentioned above?

**Comment by tomas-pluskal** [comment]
I assume it's peak ID 65.

The peak height is correctly reported as 1.5E6 in the F1 sample, all the way up to your gap-filled peak list. The value changed after normalization, because it was normalized. After normalization, the values of peak height and peak area don't correspond to the raw data values anymore.

<img width="529" alt="Screen Shot 2019-11-13 at 15 42 44" src="https://user-images.githubusercontent.com/1796692/68802644-4b4ebb00-062c-11ea-98f1-2ad7983828ca.png">

**Comment by Fedemine19** [comment]
Thank you so much for everything! So I will filter first and then normalize the values.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
