### ISSUE TITLE
[Core] Change module directories

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine2#758]
Move all modules into two directories:
- visualization
- general

**Comment by tomas-pluskal** [comment]
"general" seems too general :)

How about 

- visualization
- io
- dataprocessing
- tools
- example

Things like the isotope pattern calculator made by Steffen or the Kovacs Index extractor can go to "tools". "example" can be for the current net.sf.mzmine.modules.peaklistmethods.basiclearner.LearnerModule, so it is easy to find.

What do you think?

**Comment by robinschmid** [comment]
Sounds good to me
