### ISSUE TITLE
"Error of task ADAP Peak decompositon"

### ISSUE THREAD

**Issue by minzaroma** [mzmine/mzmine2#762]
### Basic information

* My operating system: Windows 2012 Server R2 Standard
* My MZmine version: 2.52

### What happened

Hey all,

I was analyzing some GC-MS data using the new MZmine version (2.52). Unfortunately, the ADAP spectral deconvolution (hierarchical clustering) module failed with the following note: "cern/colt/matrix/DoubleMatrix1D".  Here's a screenshot:

![grafik](https://user-images.githubusercontent.com/52671757/69435268-84c7aa80-0d3f-11ea-94f3-783b04659dee.png)

Seems to be a new new issue as I never had it in earlier versions (2.4....).

Cheers, Caro

**Comment by tomas-pluskal** [comment]
Looks like a missing dependency or something... @asmirn1 ?

**Comment by tomas-pluskal** [comment]
@minzaroma Could you provide your project file so we can reproduce the issue?

**Comment by minzaroma** [comment]
Yes, but it's a bit big

**Comment by tomas-pluskal** [comment]
Use Dropbox, Google Drive, or something similar.

**Comment by minzaroma** [comment]
Ok, here it is: https://drive.google.com/open?id=1b7iONTTVTC9lIMk4VTeuBIR-GAwvYne2
Thanks for your fast response!

**Comment by asmirn1** [comment]
It does look like a dependency issue. 

Thank you for the project file. I'll try to reproduce the error.

**Comment by asmirn1** [comment]
Hi @minzaroma I've made some changes to the developer version of MZmine. Here is the updated version: https://drive.google.com/file/d/1dhQRkGCpbAT2xYC7yGoR4_r7FksqsXUF/view?usp=sharing

Could you try it and let me know if it works. If it does, we'll push these changes to the next release version of MZmine.

**Comment by minzaroma** [comment]
Thanks @asmirn1 I tried your version just now and it seems to be all fine again!

Cheers, Caro

**Comment by tomas-pluskal** [comment]
Should be fixed in version 2.53
