### ISSUE TITLE
cant build mzmine following the eclipse tutorial

### ISSUE THREAD

**Issue by rgentz** [mzmine/mzmine2#765]
### Basic information

* My operating system: MacOS Catalina
* My MZmine version: current git.

### What happened

* Please describe what happened and how it differs from what you expected to happen.
Followed the eclipse tutorial for MZmine.
Did not build.

Tried running mvn package from the command line

rgentz-mbp:mzmine2 RGentz$ mvn package
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< mzmine2rgentz:mzmine2rgentz >---------------------
[INFO] Building mzmine2rgentz 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.rsc.chemspider:chemspider-api:jar:1.0.0 is missing, no dependency information available
[WARNING] The POM for mzmine:macspecificsetup:jar:2.7 is missing, no dependency information available
[WARNING] The POM for mzmine:jmprojection:jar:1.0 is missing, no dependency information available
[WARNING] The POM for mzmine:gslibml:jar:0.0.1 is missing, no dependency information available
[WARNING] The POM for mzmine:visad:jar:20131024 is missing, no dependency information available
[WARNING] The POM for java3d:j3dcore:jar:1.6.2 is missing, no dependency information available
[WARNING] The POM for java3d:j3dutils:jar:1.6.2 is missing, no dependency information available
[WARNING] The POM for java3d:vecmath:jar:1.6.2 is missing, no dependency information available
[WARNING] The POM for de.unijena.bioinf.ms:chemistry_base:jar:3.1.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for de.unijena.bioinf:java-utilities:jar:1.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for gurobi:gurobi-linux64:jar:7.5.2 is missing, no dependency information available
[WARNING] The POM for cplex:cplex:jar:12.8 is missing, no dependency information available
[WARNING] The POM for de.unijena.bioinf.ms:chemical_db_oss:jar:1.1.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.767 s
[INFO] Finished at: 2019-11-25T23:18:18-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mzmine2rgentz: Could not resolve dependencies for project mzmine2rgentz:mzmine2rgentz:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: mzmine:macspecificsetup:jar:2.7, mzmine:visad:jar:20131024, java3d:j3dcore:jar:1.6.2, java3d:j3dutils:jar:1.6.2, java3d:vecmath:jar:1.6.2: Failure to find mzmine:macspecificsetup:jar:2.7 in https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of ebi-release-repo has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 

specifically went back to java 1.8 as otherwise I get thousands of errors.
java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)

Can you help update the eclipse tutorial or describe how I can get the project to compile? It would help me a lot Thank you

**Comment by Annexhc** [comment]
Hi,
MZmine is now using Gradle. Just use the import from git function in eclipse. Right click the project, select Configure -> Add Gradle Nature. 
Make sure you are using JDK 12 or newer.

**Comment by rgentz** [comment]
Thanks you Annexhc.

You hint was very valueable and I managed to compile and run it. Thanks a lot.  Expect a pull request with some enhancements to MZmine soon.

Thanks

**Comment by tomas-pluskal** [comment]
@rgentz If you are planning to implement new features for MZmine, I would strongly recommend to discuss and coordinate your effort with us first (what and *how* will be implemented).
