### ISSUE TITLE
[Windows 10] MZmine unexpectedly terminates bat file upon completion of batch

### ISSUE THREAD

**Issue by Kevin-Murray** [mzmine/mzmine2#779]
### Basic information

* My operating system: Windows 10
* My MZmine version: MZmine 2.53

### What happened

I am attempting to operate MZmine using the Windows command line as part of larger workflow. Upon the successful completion of the input MZmine XML batch file, the Windows console unexpectedly closes, failing to execute the remaining code in the bat file. I have confirmed that this issue is not dependent on the input MZmine batch XML file.  I have confirmed that this issues occurs in previous builds (I tested as far back as MZmine 2.42). This issue is Windows specific. If run using Linux shell script, MZmine will successfully complete the MZmine batch file and the remaining code will execute. 

Below is a simplified example:
`
:: Execute MZmine Batch Script
C:\MZmine\MZmine-2.53-Windows\startMZmine-Windows.bat test.xml

:: Successful completion of batch -> Unexpected termination occurs

ECHO "Hello World"

:: Expected termination
`

I have attempted to determine what in the startMZmine-Windows.bat file would be causing this behavior but nothing stands out. Is the expected behavior of the Windows distribution or is this a bug?

I have attached the Windows bat file, MZmine batch XML file, and logs for reproduction (as txt files). Would anyone be able to confirm the presence of this issue? 

Thank you very much for your assistance. 

[test_bat.txt](https://github.com/mzmine/mzmine2/files/4016262/test_bat.txt)
[test_log.txt](https://github.com/mzmine/mzmine2/files/4016263/test_log.txt)
[test_xml.txt](https://github.com/mzmine/mzmine2/files/4016264/test_xml.txt)

**Comment by tomas-pluskal** [comment]
Hi,

I guess this might be what you're looking for?

https://stackoverflow.com/questions/3585968/windows-batch-file-terminating-prematurely

**Comment by Kevin-Murray** [comment]
Hi Tomas,

Yes, that solved it exactly. 

Thank you for the help.
