### ISSUE TITLE
Heatmap module not working with RServe

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine2#78]
As reported by @dyrlund :

Can you get the heat map plot (under data analysis) to work with the new RServe integration in MZmine 2.15? On my system (Windows 7 64-bit, R v. 3.2.1), Rserve.exe stops working during the processing and crashes. I have attached the output from MZmine from the Sample-2.3 data set. The baseline correction module works fine so the Rserve and R integration seems to be working.

**Comment by golgauth** [comment]
Hi, Tomas,

Just come back from vacations. I'll have a look very soon!
Cheers

Gaut


On 08/09/2015 12:55 PM, Tomáš Pluskal wrote:
>
> As reported by Thomas:
>
> Can you get the heat map plot (under data analysis) to work with the 
> new RServe integration in MZmine 2.15? On my system (Windows 7 64-bit, 
> R v. 3.2.1), Rserve.exe stops working during the processing and 
> crashes. I have attached the output from MZmine from the Sample-2.3 
> data set. The baseline correction module works fine so the Rserve and 
> R integration seems to be working.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mzmine/mzmine2/issues/78>.
>


-- 
Gauthier BOAGLIO
CEFE - UMR 5175
1919 route de Mende
F-34293 Montpellier cedex 5

Tel: +33/0 4 67 61 32 15
Fax: +33/0 4 67 61 33 36

email: gauthier.boaglio@cefe.cnrs.fr
www:   http://www.cefe.cnrs.fr/en/evolutionary-ecology-and-epidemiology/gauthier-boaglio
        http://www.evolepid.org/people.php?name=boaglio

**Comment by BrandiWest** [comment]
Hello,

I'm just wondering if any progress has been made to fix the issue with the heat map plot.

Thanks,

Brandi

**Comment by tomas-pluskal** [comment]
This bug is now fixed. The fix will be included in MZmine 2.16.
