### ISSUE TITLE
Enhancement proposal: CliqueMS

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine2#780]
Hi beloved developers,

Since our ways are closely related, and many issues regarding CAMERA opened, are you planning to implement CliqueMS (https://doi.org/10.1093/bioinformatics/btz207) as an alternative to CAMERA in upcoming versions? 

Could be very nice!

Here is the Git in case: https://github.com/osenan/cliqueMS

Best wishes for 2020!

**Comment by robinschmid** [comment]
Hey,
we are currently restructuring the data model and representation of feature list rows. 
I have already implemented a similar approach to grouping and annotation in MZmine/Java. Still, with the new data model it would also be nice to implement CAMERA in a good way and other grouping algorithms. 
I think the main problem is that no one is really maintaining the CAMERA support in MZmine.

**Comment by tomas-pluskal** [comment]
@Adafede You can volunteer! :)

**Comment by Adafede** [comment]
@tomas-pluskal As already mentioned in another proposal I made, I would be really happy to! :)

Only limitation is my inexistant knowledge of Java. I can code in R, poorly in python but that's it. I'm full of ideas/articles but I do not have the brain (and background) to implement them in Java, sadly. 

That's why I sometimes annoy you asking if you are going to implement such tools. It is simply to try pushing needs from the community instead of everyone developing his own python/R/shell script to pre/post process part of the data in his own manner...

**Comment by tomas-pluskal** [comment]
I totally agree it is better for the community to coordinate the efforts on a few good tools instead of everyone writing their own scripts. And your requests are not annoying at all.

I don't completely agree with the "cannot do it myself" part. Implementing a module in MZmine is really not that difficult. Many people have learned Java from scratch, so why not you. There are many existing MZmine modules that you can copy and start modifying. And the MZmine developers community is lovely and always happy to help you.

**Comment by Adafede** [comment]
Just ran it on my own mzmine feature lists and works like a charm:

https://github.com/rendju/CROP

Again, in R and "only" applicable to metabolomic studies. Happy to collaborate as soon as the kindest R/Java module translation MZmine developer contacts me! :) 

[mzmine1_CROPped_ccth0.75_rtw+-0.05_correlation_network.pdf](https://github.com/mzmine/mzmine2/files/4064313/mzmine1_CROPped_ccth0.75_rtw%2B-0.05_correlation_network.pdf)

**Comment by Adafede** [comment]
Hi, closing given the time. Will repost on mzmine3 if needed.
