### ISSUE TITLE
Custom database information is not being applied to feature list

### ISSUE THREAD

**Issue by chandlerjd** [mzmine/mzmine2#797]
### Basic information

* My operating system: Windows 10 Pro
* My MZmine version: 2.53

### What happened

* Please describe what happened and how it differs from what you expected to happen.
I followed the Help instructions for the 'Feature list methods -> Identification -> Custom database search' dialog including use of our lab's compound list. However, whether I attempt this for an aligned feature list or for a single file chromatogram list, the Identity data (or anything else from the database) does not appear in the feature list when I inspect it. I made a fresh CSV with a small number of metabolites to make sure my CSV file was not the problem. I made sure the order of the columns was correct. No error messages are given and the operation appears to complete successfully. 

* Please include all parameter values for the MZmine modules you used. SEE BELOW
* Please upload screenshots of any errors and your log/mzmine.log file. 
![Capture_DatabaseCustom](https://user-images.githubusercontent.com/32556064/74768988-8d088680-5257-11ea-9224-986438972b1e.PNG)

![Capture_DatabaseCustom2](https://user-images.githubusercontent.com/32556064/74769017-998cdf00-5257-11ea-9c9a-c9c7dda382e7.PNG)

![Capture_DatabaseCustom3](https://user-images.githubusercontent.com/32556064/74769074-b88b7100-5257-11ea-8a8d-c7f45ee06749.PNG)

![Capture_DatabaseCustom4](https://user-images.githubusercontent.com/32556064/74769101-c17c4280-5257-11ea-8aa9-127afc69d44a.PNG)

* Please upload an MZmine project file that demonstrates the problem you are reporting.
Will do on request, not sure it is necessary to do this right now.

**Comment by tomas-pluskal** [comment]
When you run the custom DB search module, you have to specify the order of the fields in your CSV file (the "Field order" parameter). Change the order using mouse drag&drop to reflect the order of the fields in your database, which is ID, mz, RT, identity, formula.

**Comment by chandlerjd** [comment]
Thank you for your response. I reproduced the problem even with a perfectly aligned database. I am attaching pictures as proof. 

Selection of the feature list
![Capture_DatabaseCustom5](https://user-images.githubusercontent.com/32556064/74846764-0c9d6080-52ff-11ea-95de-549246effea4.PNG)

Parameters
![Capture_DatabaseCustom8](https://user-images.githubusercontent.com/32556064/74846797-1921b900-52ff-11ea-9280-8e01e1343130.PNG)

Database (I made one from scratch to ensure no file issues with original database)
![Capture_DatabaseCustom7](https://user-images.githubusercontent.com/32556064/74846813-22128a80-52ff-11ea-888c-5c1fd2dc271d.PNG)

The target feature list (Identity sorted in either direction)
![Capture_DatabaseCustom9](https://user-images.githubusercontent.com/32556064/74846886-3d7d9580-52ff-11ea-8967-550b8d924cbb.PNG)
![Capture_DatabaseCustom10](https://user-images.githubusercontent.com/32556064/74846892-3f475900-52ff-11ea-9d6c-863aa5e26d5d.PNG)

Note that I never ran CAMERA for this feature list but I have lots of "pseudospectrum" IDs. I am not sure why these are listed. Perhaps they are blocking the database search/overruling it?

**Comment by chandlerjd** [comment]
Thank you for your response. I reproduced the problem even with a perfectly aligned database. I am attaching pictures as proof. 

Selection of the feature list
![Capture_DatabaseCustom5](https://user-images.githubusercontent.com/32556064/74846764-0c9d6080-52ff-11ea-95de-549246effea4.PNG)

Parameters
![Capture_DatabaseCustom8](https://user-images.githubusercontent.com/32556064/74846797-1921b900-52ff-11ea-9280-8e01e1343130.PNG)

Database (I made one from scratch to ensure no file issues with original database)
![Capture_DatabaseCustom7](https://user-images.githubusercontent.com/32556064/74846813-22128a80-52ff-11ea-888c-5c1fd2dc271d.PNG)

The target feature list (Identity sorted in either direction)
![Capture_DatabaseCustom9](https://user-images.githubusercontent.com/32556064/74846886-3d7d9580-52ff-11ea-8967-550b8d924cbb.PNG)
![Capture_DatabaseCustom10](https://user-images.githubusercontent.com/32556064/74846892-3f475900-52ff-11ea-9d6c-863aa5e26d5d.PNG)

Note that I never ran CAMERA for this feature list but I have lots of "pseudospectrum" IDs. I am not sure why these are listed. Perhaps they are blocking the database search/overruling it?

**Comment by chandlerjd** [comment]
I was able to resolve the issue by repeating the workflow without ever using CAMERA. Apparently the CAMERA pseudospectrum IDs did not get overwritten by the custom DB search. I had used CAMERA on deconvoluted chromatograms. Is this ability of CAMERA to take precedence over the DB search a bug or a feature? I am closing the thread as resolved.

**Comment by tomas-pluskal** [comment]
The identifications are added, not replaced. So if you run the custom DB search first and then run CAMERA after, you will keep your DB IDs as the main ones.
