### ISSUE TITLE
How to create readable netCDF

### ISSUE THREAD

**Issue by MDolanGU** [mzmine/mzmine2#807]
### Basic information

* My operating system: MacOS 10.15.1
* My MZmine version: 2.53

### MZmine can't open my file because it could not find variable mass_values

*   We don't have proprietary software, so the output I get for data is a .csv with time and intensity (collected on SIM mode so I only have one mass). I created a netCDF using R from the csv with dimensions time and m/z with a single variable of intensity. This led to the error mentioned about no variable mass_values. Does anyone know if there is a template that I could use to create the netCDF that MZmine is expecting? If anyone knows an easier way to load this data into MZmine that would also help.

Thanks for any help/advice.

**Comment by tomas-pluskal** [comment]
Hmmm... I wonder what are you planning to do with such data in MZmine?

**Comment by MDolanGU** [comment]
I was planning on trying to utilize it's baseline removal, peak picking, and PCA functionality. I was also considering trying out some of the other analysis techniques.

**Comment by tomas-pluskal** [comment]
I see. MZmine has a simple PCA plot, but overall the software is not really designed for comprehensive statistical or multivariate data analyses. It is designed for raw data processing, and in that regard applying it to SIM data is probably possible but it feels a bit like killing a fly with a cannonball.

Regarding to your question, perhaps the best way to learn about the netCDF structure would be to analyze some existing netCDF files. Try this file for example: https://github.com/msdk/msdk/raw/master/msdk-io-netcdf/src/test/resources/wt15.CDF

**Comment by MDolanGU** [comment]
Thanks for the example. I think this should be enough to help me figure it out.
