### ISSUE TITLE
Best practices for comparing muropeptide abundances across samples?

### ISSUE THREAD

**Issue by kelvink91** [mzmine/mzmine2#818]
* My operating system: Windows 10
* My MZmine version:  2.53

I'm doing LC-MS on muropeptides (peptidoglycan) and being fairly new to LC-MS overall, I was hoping to get an idea on best practices and overall workflow for such an analysis on mzmine. The type of sample I'm working with is [well described here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4267204/pdf/srep07494.pdf). In essence, I'm looking at this core structure with variations such as pentapeptide stem truncations, glycine bridge truncations, sugar O-acetylation etc and even multimeric structures. 

![image](https://user-images.githubusercontent.com/63601442/79138839-31ec9f00-7d83-11ea-8b1b-7a25ecac7589.png)

The following is the TIC for 3 samples where I'm able to manually assign most of the major peaks. With these samples, I observe protonations and sodiations or a combination for multiply charged states of up to +3.

![temp](https://user-images.githubusercontent.com/63601442/79139587-91977a00-7d84-11ea-93cd-b10853d39821.jpg)

However, I want to compare the abundances of the various muropeptides species between samples. So far what I have done is the following:
1. Samples ran on ABSCIEX 5600 TripleTOF (if I'm not mistaken, ran by a core facility)
2. Converted .wiff files to mzXML using ProteoWizard
3. Imported mzXML files into MZmine 2.53
4. Following the ADAP user manual, performed mass detection, ADAP chromatogram builder, chromatogram deconvolution
5. Join aligner on all 3 samples
6. Based on initial peak assignments, I created a simple custom database (with Identity, m/z & RT and manually assigned adducts) and ran a custom database search

At this point I realized I have two problems. First, even though similar peaks are observed between samples, they are not detected across all samples with these settings. For example, ~505.75 m/z (XIC attached) was extracted at 4 different retention times but the ~20 min signal was detected only in 2/3 of the samples (partial aligned feature list attached). I'm guessing this is a setting issue; in my chromatogram deconvolution step, I initially set the "m/z center calculation" to "median" which filtered out a lot of peaks. "Auto" seemed to work better but some peaks were still filtered out.  

![image](https://user-images.githubusercontent.com/63601442/79143207-ceff0600-7d8a-11ea-97a2-b83c6dc34e6c.png)
![image](https://user-images.githubusercontent.com/63601442/79142990-6879e800-7d8a-11ea-8cc5-215dfbe812cc.png)

Second, the same muropeptides can be multiply charged by a combination of protonation and/or sodiation. Based on my understanding, at least the ones with similar retention times should be collapsed/combined before I can accurately compare the peak areas/abundance. However, I am at a loss of how to do this.

Ultimately, I want to compare the abundances of the different muropeptide species across the different samples. I'll greatly appreciate any advise and input in figuring this out.

**Comment by photocyte** [comment]
I don't have any experience in peptidoglycomics, but from your XICs in the 2nd to last image of your post, doesn't seem like they'd be too problematic (clean, well separated chromatograms). 

Two pieces of advice: 
(1) Maybe try the RANSAC aligner, which adjusts the RT of the features, and might be a little bit better for systematic RT drifts. 
(2) For chromatogram deconvolution, try the preview feature, to test out different parameters and w/ a set of your target features to see how they are performing. My expectation is these shouldn't be too hard to robustly separate - you might watch for any parameters that deal with absolute values, and whether you did mass detection at a low enough value (~1E3).  Typically, 1E3 is well into the noise on something like a Q-Exactive Orbitrap instrument, and your processing time will be greatly increased if that is the case on your instrument, but if not, you'll want to adjust thresholds to include those "low" signals.

**Comment by kelvink91** [comment]
Thank you for the suggestions! I still have to tweak the parameters more but following what you recommended, it worked a lot better than my previous attempts. The RANSAC aligner managed to account for the RT drifts and could group similar features together.

With that resolved, I do have two other questions:
1. Are the peak areas are now directly comparable between samples or is it necessary to perform some kind of normalization?
2. Is it best to combine the peak areas between different adducts of the same species (e.g. M+H, M+2H, M+Na) prior to abundance comparison? My features table is vastly simplified now so I could certainly do it manually though.

**Comment by photocyte** [comment]
1. Whether or not your peaks are directly comparable depends on how quantitative your sample preparation method was (does it have high variance or systematic error).  If it's on the more quantitative side, and you have good separation (so, reduced effect of 'matrix' effects), yes should be directly comparable. Otherwise, you can try to normalize, but if I usually try to with the former approach of having a more reliable sample input.  But, my LC/MS is usually only roughly quantitative.  Maybe somebody who is running the big comparative studies w/ 100s of samples would have a different opinion.

2. I usually pick the most abundant ion for a given molecule, and ignore the rest. My sense is that adding all the species, would increase the variability.

**Comment by kelvink91** [comment]
Understood. Thank you again for your help and advice!
