### ISSUE TITLE
No newline/indenting in exported mzML files

### ISSUE THREAD

**Issue by pamodeo-icb** [mzmine/mzmine2#820]
### Basic information
When exporting both processed and unprocessed raw data (imported both in raw and mzML format), both on Windows and on Linux platforms, the resulting mzML files appear as a unique line of text (also without final newline, since "wc -l" command under Linux results in 0 lines).
* My operating system:
Windows 10
Ubuntu 18.04 LTS
* My MZmine version: 
2.53
### What happened
Whenever a mzML file is exported (in batch or interactive mode) the issue described above occurs.
The resulting one-line file is read back in MZmine and processed (although the results of several protocols differ somewhat from those obtained with the original mzML file).
Because of the form of the exported file and the limitations of the machines that I can presently use for tests it is difficult at moment to perform a compared evaluation of the original vs the exported file.
Obviously I can provide any further info or file, but at present the problem seem quite systematic under any tested condition and environment.

**Comment by pamodeo-icb** [comment]
Although my Java programming skills are close to zero, I tried to identify the origin of the problem, which led me to a potential cause (and possible solution) in the lack of "javolution.xml.stream.lineSeparator"  and "javolution.xml.stream.indentation" instructions (possibly) in MzMLFileExportMethod.java from msdk library.

Because of the aforementioned skill limitations, any confirmation/hint would be welcome.

**Comment by tomas-pluskal** [comment]
The absence of whitespace in the exported mzML file is a conscious decision. Adding indentation to mzML massively increases the file size. Human readability is not so important for formats like mzML where files generally reach the size of hundreds of MBs - nobody is going to process such data by manually editing the file. If you need to do it for some reason, you can process the mzML file through a text filter that will add newlines and indentation to your liking.

**Comment by pamodeo-icb** [comment]
While I can easily live without indentation (though human readability can sometimes be useful when debugging or tracing problems or oddities in data or programs), the lack of newlines can result a little bit more problematic, since there are tools or libraries not at their ease with single records of hundreds of MBs. Compression typically helps a lot with mzML files. Anyway, since this choice is deliberate and text filtering can fix the problem whenever required, this issue can be closed.
Thank you for your explanation.

**Comment by tomas-pluskal** [comment]
Can you provide an example of a tool or a library that has a problem with parsing XML (or mzML) if it doesn't contain newlines? Just curious.

**Comment by pamodeo-icb** [comment]
The tools I had in mind are not specifically oriented to XML or mzML format. Since, in addition to python, I often use tools like awk and Fortran (and related libs, plus other file parsing commands and utils), record size limitations can be a particularly annoying problem, since they are strongly implementation-, OS- and version-dependent. Fortunately, on 64-bit machines and in recent OSes/versions these limits have grown to rather safe values (order of GB), but, since especially in this period, I have to used some hw/sw outdated machines for testing and development, it can still represent an issue. However, this is nothing that a proper preprocessing (or sw upgrading) can't get rid of.
Obviously, having the choice between human-readable and smaller files would be the best solution, but I understand that it requires additional work and introduces potential complexity.
