### ISSUE TITLE
Online compound ID: Neutral mass not calculating

### ISSUE THREAD

**Issue by rthuillier** [mzmine/mzmine2#827]
### Basic information

* My operating system: Windows 10/64
* My MZmine version:  MZmine 2
Java version: 1.8.0_241
R version: R-3.6.2

### What happened
When I attempt to perform an online search for compound identification, the neutral mass doesn't compute, whichever ionisation option I select, hence I get an error message

I checked if MZmine correctly connects to the internet (ie: is it my firewall) and MZmine checks for update without any issues, so I'm at a loss

![Diapositive1](https://user-images.githubusercontent.com/64971231/81306566-e8405d00-907f-11ea-8ed2-df1ab30f6c80.JPG)
![Diapositive2](https://user-images.githubusercontent.com/64971231/81306585-f0000180-907f-11ea-830e-5ce68d56b681.JPG)
![Diapositive3](https://user-images.githubusercontent.com/64971231/81306601-f4c4b580-907f-11ea-84b6-554d028d0833.JPG)
![Diapositive4](https://user-images.githubusercontent.com/64971231/81306611-f8583c80-907f-11ea-8b21-bf7b2c9eae34.JPG)

**Comment by tomas-pluskal** [comment]
That’s because the charge value is missing.

**Comment by rthuillier** [comment]
Damnit, I was puting '+' or '-' and not actual numbers... thanks for the help !

**Comment by tomas-pluskal** [comment]
You are welcome!
