### ISSUE TITLE
Online database search Pubchem error

### ISSUE THREAD

**Issue by AdrienFremont** [mzmine/mzmine2#830]
### Basic information

MZmine 2.53
java version "12.0.2" 2019-07-16
64-bits 
Windows 10 professional version 1903

### What happened

I would like to search pubchem for a rapid identification of my aligned and filtered list of features from MS1.
 
But I repeatedly get this error message, a few seconds after I launch the search:
"Error of task Identification of peaks in Aligned feature list filtered using PubChem
Could not search PubChem: java.io.lOException: java.io.lOException: Server returned HTTP response code: 429 for URL:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fc gi?usehistory=y&db=pccompound&sort= cida&retmax=20&term=333.18789279979296:333.19122469538047[MonoisotopicMass] (PubChemGateway.java:145)"

I tried several times with a range of search parameters but it is still returning the same error.
However, it works fine with KEGG online database search.

Do you know what could be the origin of the error?

Thanks a lot

**Comment by tomas-pluskal** [comment]
https://httpstatuses.com/429

Apparently, HTTP code 429 means too many requests to the server. I guess PubChem started blocking too many requests from a single IP address. Someone will have to rewrite the MZmine module accordingly..

**Comment by AdrienFremont** [comment]
Thanks a lot for your reply.
