### ISSUE TITLE
I can not open MZmine 2.53 in Linux (CentOS 8)

### ISSUE THREAD

**Issue by MToledoSilva** [mzmine/mzmine2#837]
### Basic information

* My operating system: CentOS 8 64bit
* My MZmine version: 2.53

$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

$R --version
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

### What happened

I have been using MZmine in Windows for two years. Recently I installed CentOS 8 in my computer, and am still getting used to it. So I downloaded MZmine 2.53 for Linux, to use in my new OS. However, after installing Java and R, I tried to start the MZmine software, but when I double click the "startMZmine-Linux" file, it always leads to the text editor, and do not start the software.

I have looked in internet, but I could not found the solution for this issue. I think it should be easy to address, but I really could not find any solutions.

Thanks in advance for the patience.

Regards.

**Comment by tomas-pluskal** [comment]
Try using the command line instead?
This is not an issue of MZmine, but rather how you use your OS.
