### ISSUE TITLE
The problem of peak picking.

### ISSUE THREAD

**Issue by YeanChoi** [mzmine/mzmine2#841]
### Basic information

* My operating system : window10 
* My MZmine version : 2.42

I don't know the problem that the peaks don't picked after 'filtering - feature list rows filter'.
So, I expect a problem with MS1-MS2 pairing. But I have no idea how to solve it.

I prepared a short video of processing, but it was not uploaded due to the file format, so I attached a link below.
If there is a problem with my process, please check and give me feedback.

https://youtu.be/40HrbhGGXEU

**Comment by SteffenHeu** [comment]
Could you provide more specific information on the expected behavior please? 
Do you expect more features to have MS2 scans?
Did you try to just filter for features with MS2 scans? How many are left there?

**Comment by YeanChoi** [comment]
> Could you provide more specific information on the expected behavior please?
If you watch the video clip in 4:33, you can see that 'filtering - feature list rows filter' rarely pick the feature.
![capture1](https://user-images.githubusercontent.com/48466178/88743822-9ee44300-d180-11ea-8461-dfe80e4336d1.JPG)
> Do you expect more features to have MS2 scans?
Of course. Because I have used this same sample data before. Only the MS equipment type was changed, but the same parameter values and format were used.
> Did you try to just filter for features with MS2 scans? How many are left there?
I tried and the result is like this. I have no idea why. Is my raw data a problem?
![capture2](https://user-images.githubusercontent.com/48466178/88748377-d5738b00-d18b-11ea-84fd-3ed44659846a.JPG)

**Comment by SteffenHeu** [comment]
Mhhh. 
Could you try a different deconvolution algorithm? Maybe local minimum instead of baseline cutoff?

**Comment by YeanChoi** [comment]
Thank you for your quick reply.
I tried using a different deconvolution as you advised, but the result was the same.

**Comment by YeanChoi** [comment]
> 
> 
> Mhhh.
> Could you try a different deconvolution algorithm? Maybe local minimum instead of baseline cutoff?

**Comment by tomas-pluskal** [comment]
> -> Of course. Because I have used this same sample data before. Only the MS equipment type was changed, but the same parameter values and format were used.

If you used different MS equipment, then obviously the old parameters may not work. You should upload your .mzmine project file, it is impossible to give a good advice without looking at the raw data.
