### ISSUE TITLE
Strange cropping when generating XICs

### ISSUE THREAD

**Issue by mhagar** [mzmine/mzmine2#844]
### Basic information

* My operating system: 64-bit Windows 10
* My MZmine version: 2.53

### What happened
I have .mzML files where, when I try to plot an XIC that does not contain the maximum m/z in the data, most of the chromatogram has an intensity of 0 even though it clearly should not. For example, in this dataset, trying to generate an XIC with anything that doesn't contain 800 m/z, (the highest mass recorded), results in most of the chromatogram being chopped out.

![image](https://user-images.githubusercontent.com/68135547/89105136-72743500-d3d3-11ea-86b2-437d4c88e597.png)

Here's an mzmine project file with some examples. Mzmine usually works great for me, but this data is from an Agilent instrument set up on their proprietary ChemStation software (".D" format). I converted it into .mzML by first opening it in OpenChrom, saving as an .mgf, then converting using MSConvert. This has worked well for me with this type of data in the past.
[second_batch_bad_XICs.zip](https://github.com/mzmine/mzmine2/files/5010879/second_batch_bad_XICs.zip)

I just thought I'd let you guys know!

**Comment by tomas-pluskal** [comment]
Hi, thanks for the report. I checked your files. The issue is that your .mzML files have their intensity arrays in decreasing m/z order, which is something that MZmine doesn't expect. I have never seen such files - generally the data is stored in increasing m/z order.

I added a fix for this type of data. It will be included in MZmine 3.

**Comment by mhagar** [comment]
> Hi, thanks for the report. I checked your files. The issue is that your .mzML files have their intensity arrays in decreasing m/z order, which is something that MZmine doesn't expect. I have never seen such files - generally the data is stored in increasing m/z order.
> 
> I added a fix for this type of data. It will be included in MZmine 3.

Ah, I see! I guess it's a weird quirk about how OpenChrom exports its data. In the meantime, I'll just reformat it to increasing m/z order.

Thanks a ton!
