### ISSUE TITLE
zero TIC for a mass window of .raw files that contains clear peaks when analyzed by Thermo software

### ISSUE THREAD

**Issue by avreavrea** [mzmine/mzmine2#845]
### Basic information

* My operating system: Windows 7
* My MZmine version: 2.5.3

### What happened

I opened .raw files on MZMine. When I look for common masses of E. coli lysate metabolites such as deprotonated ATP and deprotonated UDP of m/z 505.98792 and 402.99437, respectively, I get a zero value for a +/- 5 ppm window. On the Thermo software i can see a clear peak for both of these m/z windows. When I look at other .raw files of E. coli lysates expressing GFP on MZmine I see these peaks clearly so I suspect it has to do with how MZmine reads these specific .raw files (attached).

Highlight imported raw files  -> Show TIC -> From mass -> m/z 505.988, m/z tolerance 0.001, ppm 5.00

Please find the MZmine project file as well as the raw files attached in a dropbox link. 
I get the same problem when I'm running MZmine 2.5.3 on linux after converting the files to .mzml files by thermorawfileparser and also after converting the files to .mzml files by MSConvert. Usually I analyze files that do not have MS2 data in the scans. Perhaps the issue is related. 
https://www.dropbox.com/sh/l4ucv1penz3k83c/AAC0nDHTXnirOqXnMEJr3_bOa?dl=0
Thank you!

![image](https://user-images.githubusercontent.com/21956135/89527813-a5169700-d7f2-11ea-96ae-2621b48476f8.png)

**Comment by tomas-pluskal** [comment]
Can you show a screenshot from the Thermo software? I tried to open your .raw files in Qual Browser but I don't see any peak at 505.988 m/z.

**Comment by avreavrea** [comment]
![Picture1](https://user-images.githubusercontent.com/21956135/89531357-c7131800-d7f8-11ea-8f93-3267e6a719e0.png)
Yes, please find attached.

**Comment by tomas-pluskal** [comment]
The file that you are showing here (Polar_Sorek_C_GFP_1_030843.raw) is different from the file that you uploaded earlier (GFP_1.raw). Try opening the file that you uploaded.

**Comment by avreavrea** [comment]
It is the same file. I just changed the filename for clarity. I have the same problem with Polar_Sorek_C_GFP_1_030843.raw
![image](https://user-images.githubusercontent.com/21956135/89532686-dbf0ab00-d7fa-11ea-859b-2db359c2fb13.png)

**Comment by tomas-pluskal** [comment]
Well, I cannot comment on the file Polar_Sorek_C_GFP_1_030867.raw, because I have not seen that file. But I can see that your XIC window in MZmine is 505.9853-505.9905, while your window in Qual Browser is 505.98240-505.99454, so your window is considerably wider in Qual Browser. You are not comparing the same plots.

As for whether the two files are the same, I don't think so. The file Polar_Sorek_C_GFP_1_030867.raw that you show above contains **negative mode** scans, while the file GFP_1.raw that you uploaded contains **positive mode** scans.

**Comment by tomas-pluskal** [comment]
Also, by the way, your MZmine plot is shown using file Polar_Sorek_C_GFP_1_030867.raw, while your Qual Browser plot is shown using file Polar_Sorek_C_GFP_1_030843.raw. So again, you are **not** showing the same thing.

**Comment by avreavrea** [comment]
I added the Polar_Sorek_C_GFP_1_030867.raw file to the dropbox link. I have the same problem with a window of 505.98240-505.99454. It could be that the Qual Browser images were generated with different files of the same name. I am very sorry if this is the case. I will check now and follow up. 
![image](https://user-images.githubusercontent.com/21956135/89533803-a5b42b00-d7fc-11ea-87d9-a8667048ab61.png)

**Comment by avreavrea** [comment]
I am very very sorry. These were the wrong files indeed. 
Thank you

**Comment by avreavrea** [comment]
The other files Polar_Sorek_C_GFP_1_030843.raw are negative indeed and show no problem whatsoever.
