### ISSUE TITLE
MZmine/java saturation

### ISSUE THREAD

**Issue by tirolab** [mzmine/mzmine2#846]
Dear developers, 

Thank you very much for your work on MZmine, our lab uses it a lot.
We have encountered some issues while working with large numbers of samples (100 or more). Indeed, MZmine seems to stop working (or work very slowly) when tasks involve that many samples. The easiest way to solve the issue is to end all tasks, but when the MZmine seems too saturated, even this option is impossible and the only way to get MZmine to work again seems to be restarting it all together.. Is there some kind of command line we could use to end all current tasks without loosing the results of previous steps?

I did not mention an OS or MZmine version because this tends to happen with multiple operating systems and with multiple versions of MZmine. Our java version is 1.8. 

I thank you for your help, 

Best regards, 

David Chardin

**Comment by photocyte** [comment]
Hi there,

Almost certainly a RAM issue.  See #842 for tips.

If you want to have intermediate files from before a troublesome step, you could try saving a project file before whichever step is causing problems.
