### ISSUE TITLE
Cannot run MZMine2 at all

### ISSUE THREAD

**Issue by KMHoch** [mzmine/mzmine2#85]
I updated Java to most recent 1.8.0_60 and just downloaded the most current version of R.  I downloaded the most recent version of MZMine2.  I have a Windows 7 Professional with 64 bit.  When I go to open MZMine2 I get the following:
Checking physical memory size...
Found 8097 MB memory, 64-bit system
Java heap size set to 6049 MB
Invalid initial heap size: -Xms6049m
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to continue . . .
I cannot do anything further because the program closes.  What do I need to try next?  I have used MZMine in the past and would like to be able to use it again.  Thank you.

**Comment by tomas-pluskal** [comment]
Hi Kathleen,

You probably have 32-bit version of Java installed. Please uninstall Java and go to http://java.com/en/download/manual.jsp where you can download the 64-bit version.

Tomas

**Comment by KMHoch** [comment]
Thank you for your prompt response.  It was the version of Java that was causing the problem.
Kathleen Hoch
