### ISSUE TITLE
cdf with HDF-format

### ISSUE THREAD

**Issue by zdens** [mzmine/mzmine2#850]
### Basic information

* My operating system: kubuntu 20.04
* My MZmine version: 2.53

### What happened

Hello,
there is file type detection in the source code https://github.com/mzmine/mzmine2/blob/master/src/main/java/net/sf/mzmine/modules/rawdatamethods/rawdataimport/RawDataFileTypeDetector.java#L37.

I have a netCDF-file with "HDF" in its header.

If I understood correctly in case of using netCDF library from unidata.ucar, it is possible to work with both CDF and HDF formats of netCDF.

Is there any possibility to support HDF format in MZmine?

**Comment by tomas-pluskal** [comment]
Feel free to update the netCDF parser, this is open source.
