### ISSUE TITLE
Long computational times due to the use of only 1 CPU during some steps

### ISSUE THREAD

**Issue by MilouArts** [mzmine/mzmine2#851]
### Basic information

* My operating system: Windows/linux - use PuTTY with screen so I can disconnect from the server
* My MZmine version: MZmine 2.37.corr17.7_kai_merge2

### What happened

I'm running a job on our local shared server, with a batch file to eventually do Ion Identity networking.
I've set up a batch file to open a previously made empty save file so I can adjust the max number of cores it uses (java very much want to occupy all 144 cores/CPU).

now the problem:
some steps only use 1 core/CPU instead of the 30 or 50 cores I assign. I think the bottlenecks the gap-filling or join aligner (for one I use the multithreaded option), and the metacorrelate (it is currently making a row2row correlation since august 13th, and the job started on July 28th) So this seems to be a huge bottleneck and I and my bioinformatics/server colleague do not understand why it is only using 1 CPU during some steps.

Is there any way I can change something in this, or can this be improved in later versions? 
any other insights into why this problem occurs?

Cheers, Milou

ps.
more info on my data:
My data consists of 235 files, with lots of peaks because it is dissolved organic matter.  (previous workflows, 20.000 peaks), now I tried local minimum search algorithm instead of baseline cutoff algorithm and it now creates before gapfilling and filtering 900.000 peaks/features and after filtering I'm with 50.000 left. (I exported them before starting the metacorrelate step)
This is a lot more, and I don't know how much of it is real, but I have also issues with opening very big save files/projects, but I think I had a memory error which might be because the heap size has also been restricted

pps. programming is not my strong side, I'm already very happy I can get screen running, start a job with a batch file in command line and detach without stopping the job. =)

**Comment by photocyte** [comment]
Hi there,
Not all the tasks can be parallelized, or if they could be parallelized, were implemented in a parallelized way.  It is not so unexpected that some of the steps won't use all the CPUs. So, to answer your question, you probably can't change those steps, and although it might be improved in MZmine3, there is no guarantee or timeline. 

Trying to analyze all the peaks in 235 files with low thresholds, and running into computational / memory issues isn't surprising. Having up front data reduction steps like cropping & setting higher thresholds for peak detection would likely dramatically speed things up.
