### ISSUE TITLE
Can't open mzmine 2.53 bc can't open "java" bc the developer can't be verified.

### ISSUE THREAD

**Issue by Chemistophe** [mzmine/mzmine2#852]
Hi,

I'm on MacOS Catalina and I can't open mzmine 2.53 because:

"Cannot open "java" because the developer cannot be verified.
macOS cannot verify that this app contains malware."

I never had any problem with 2.52 :(

Thanks in advance for your help

**Comment by tomas-pluskal** [comment]
Check
https://support.apple.com/en-us/HT202491

**Comment by Chemistophe** [comment]
Thanks! I just updated to Catalina and was not aware of this new safety issue.
