### ISSUE TITLE
targeted feature detection not working

### ISSUE THREAD

**Issue by giorgiasapienza** [mzmine/mzmine2#853]
### Basic information

* My operating system: 64 bit
* My MZmine version: 2,53

### What happened

I tried to use the targeted feature detection with a home made database (only masses no retention time).
One week ago it worked perfectly, now it doesn't anymore, even though I am using exactly the same database and the same parameters.
It process the raw data in less than one second and the outcome is a peak list where there is no match ( all the ions have a red status)

Parameters: int tolerance 100%, noise level 50, mass tolerance 0.001 or 5 ppm, ret time tolerance 0.

PS even if i increase the mass tolerance is the same

Could you help me??

Thanks in advance!!

Giorgia

**Comment by tomas-pluskal** [comment]
Retention time tolerance 0?

**Comment by giorgiasapienza** [comment]
You are right. I don't know what told me that if I set ret time 0 in the excel file i had to set also ret time tolerance 0.
Sorry for bothering!!

Giorgia
