### ISSUE TITLE
Search --> SIRIUS Structure Prediction fails with error message

### ISSUE THREAD

**Issue by Althalis** [mzmine/mzmine2#870]
### Basic information

* My operating system: Windows 8 
* My MZmine version: 2.53

### What happened

I have followed the same steps as Tomas Pluskal in his workshop (23/10/2020) and got the same error as him it seems. You can see the video here: https://chalmersuniversity.app.box.com/s/orvgjfwb49z7jcxum77f9fzuqj51ok2e/file/734799178129
Look at 35 min 40 sec.

So basically I chose a feature in my aligned feature list and launched the search for SIRIUS Structure prediction.
I get this error (see screenshot)

"Unhandled exception io.github.msdk.MSDKRuntimeException: Cannot parse ion type No ionization while processing task Peak identification of 338.3416 using Sirius module(io.github.msdk.MSDKRuntimeException: Cannot parse ion type No ionization@io.github.msdk.util.IonTypeUtil.createIonType(IonTypeUtil.java:53))"

![2020-11-04_bug_SIRIUS](https://user-images.githubusercontent.com/5079495/98111863-8d0dec80-1ea1-11eb-8a36-578b06332d3a.PNG)

I am using the default parameters of the module.

I attach my log file: 
[mzmine.log](https://github.com/mzmine/mzmine2/files/5487750/mzmine.log)

Here is one .mgf example that doesn't work:
[ID3266.zip](https://github.com/mzmine/mzmine2/files/5487754/ID3266.zip)

Also, when I try to import the .mgf directly into SIRIUS 4.4.29, it also fails (both on Windows 10 and 8). So I suspect something is not working there.
See screenshot: 
![2020-11-04_bug_SIRIUS2](https://user-images.githubusercontent.com/5079495/98112473-93e92f00-1ea2-11eb-8b16-f26513a0e42f.PNG)

Thanks for your help!

**Comment by tomas-pluskal** [comment]
The error you are getting is different from the error in the video.

There is no such thing as "default parameters". You always need to set the parameters correctly and understand their meaning (read the Help).

Your error is clearly related to the incorrectly set ionization type (you set No ionization, really?).

**Comment by Althalis** [comment]
Hi, sorry I was obviously lacking sleep yesterday.
I apologize for the silly mistake and thank you for taking the time to reply anyway.
