### ISSUE TITLE
Preprocessing LC/MS Data 

### ISSUE THREAD

**Issue by lctoppen** [mzmine/mzmine2#872]
### Basic information

* My operating system: Windows 10
* My MZmine version: 2.53

### What happened
I am preprocessing .raw files of ESI- and ESI+ LC/MS data. I uploaded the data into MZmine fine but once I attempt to run the mass detector feature, I recieve an error of parameters saying the noise level was not set properly.
I do not know how to set the noise level or even find that parameter, any advice would be extremely helpful. 

![image](https://user-images.githubusercontent.com/72627769/98711659-44e44380-2353-11eb-91a9-8d903e1d9916.png)

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by SteffenHeu** [comment]
The three dots next to the "Centroid" mass detector will lead you to that menu.
