### ISSUE TITLE
MzMine problem during opening

### ISSUE THREAD

**Issue by VicentYusa** [mzmine/mzmine2#88]
![mzmine problem](https://cloud.githubusercontent.com/assets/13874594/9393776/6272c4f4-4784-11e5-87e2-3645272678d4.gif)
![mzmine problem](https://cloud.githubusercontent.com/assets/13874594/9393795/7e6e9e1c-4784-11e5-870d-e204442816e8.gif)

**Comment by tomas-pluskal** [comment]
Did you change anything in your Java installation?
This problem normally occurs when you install 32-bit Java on a 64-bit OS.
Try uninstalling Java and installing the 64-bit version again from http://java.com/en/download/manual.jsp

**Comment by VicentYusa** [comment]
Tomas, I have instaled Java again, 64 bits, and the program now opens correctly.
But when I upload a raw data, the error attached appeard. Do you recomend me any action?
Tanks again
Vicent


![new problem](https://cloud.githubusercontent.com/assets/13874594/9394494/11813eea-4789-11e5-84b6-4e4076836c71.gif)

**Comment by tomas-pluskal** [comment]
I have no idea, sorry.

**Comment by VicentYusa** [comment]
I have downloaded the version 2.14.2 and it works.

Thanks

Vicent

2015-08-20 22:20 GMT+02:00 Tomáš Pluskal <notifications@github.com>:

**Comment by dyrlund** [comment]
Vicent, you can try to copy your raw data file to your local c drive before importing to MZmine. The error seems to be related to problems with your file system - try googling it.

/Thomas

**Comment by VicentYusa** [comment]
Tomas, I have copied the raw data file in the local C drive, but the same error appears. On the other hand the MzMine 2.14.2, works well


Many thanks for your kind support

Vicent

*********************************************************************
Dr. Vicent Yusà
Cap de secció de laboratoris de salut pública
Centro Superior d´Investigació en Salut Pública (CSISP)
Direcció General de Salut Pública
Conselleria de Sanitat
Generalitat Valenciana
C/ Avenida Cataluña, 21   46020- Valencia (España)
Tel: 961925865
Email: yusa_vic@gva.es; Vicent.Yusa@uv.es
http://www.csisp.gva.es/web/csisp
https://www.researchgate.net/profile/Vicent_Yusa/?ev=hdr_xprf
***********************************************************************

**Comment by dyrlund** [comment]
Hi Vicent

Can you please upload the raw data file which you are experiencing problems with to Dropbox or some other online storage system so we can reproduce your steps.

Thanks.

**Comment by VicentYusa** [comment]
Hi Tomas,
I'm currently on holidays in France. Buy I try that my PhD student sent you the raw data file
Best wishes
Vicent

**Comment by tomas-pluskal** [comment]
Hi Vicent,

Please also try this with MZmine 2.16.

Tomas

**Comment by VicentYusa** [comment]
Hi Tomas,
I' m currently on holidays. But I'll work with MZmine 2.16 next week.
Thanks
Vicent

**Comment by dyrlund** [comment]
@VicentYusa please test if you still have issues with MZmine 2.17.

**Comment by dyrlund** [comment]
@VicentYusa, we haven't heard from you in more than a month and will therefore close the issue.
