### ISSUE TITLE
Can't find peak widths

### ISSUE THREAD

**Issue by kwebber3** [mzmine/mzmine2#891]
### Basic information

* My operating system:
* My MZmine version: 

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

I am trying to find peak widths. so I can access the quality of my separations. Is this a feature of mzmine2?

**Comment by robinschmid** [comment]
After performing at least these steps:
- Mass detection
- ADAP chromatogram builder
- Chromatogram deconvolution 

You can open the feature list on the right side with a double click and see all the feature list rows. In case the width is missing, there is a button on the right side of the feature table and you can add more columns: width, area, number of data points, tailing factor etc

**Comment by kwebber3** [comment]
Thank you! That worked. I just needed to add more columns.
