### ISSUE TITLE
I need some help on how to set up the "m/z tolerance"

### ISSUE THREAD

**Issue by mliu2011** [mzmine/mzmine2#892]
My mass accuracy in my raw data is definitely below 5ppm or even lower, which is confirmed on Xcalibur. However, when I set up the "m/z tolerance" in MZmine, even I put 10ppm, I still could not get good peak for the obvious compounds there. And those compounds have very nice peaks in Xcalibur using 5ppm cutoff. Can you please give me some instruction on how to set up "m/z tolerance", because you could either do "m/z" or "ppm". I think "ppm" is better, because the mass range is very different. 

Thank you,
Min Liu

**Comment by photocyte** [comment]
I believe the chromatogram builder algorithm is a bit naive.  I'd just set a larger PPM m/z range (20 PPM or so).

If this is the XIC visualizer, then I'm not sure why it shouldn't be showing.  Something to be aware of is even on Orbitraps, if you get very abundant ions eluting, that really changes the trap gain / fill & the m/z of all the other ions can shift by ~20 ppm for a few scans.

**Comment by tomas-pluskal** [comment]
The mass tolerance is calculated as maximum of the "m/z" and "ppm" values. That's because for small mass values, the ppm tolerance can become unrealistically strict. 

Regarding your specific problem, you need to show (or upload) the actual data otherwise we can only speculate.

**Comment by mliu2011** [comment]
How can I upload the chromatogram here? Thanks
