### ISSUE TITLE
Is there a tutorial on using Mzmine2 on Linux?

### ISSUE THREAD

**Issue by jeep3** [mzmine/mzmine2#893]
### Basic information

* My operating system: Linux 
* My MZmine version: MZmine 2.53

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.
* 
Hi, tomas, 
I plan to use a dataset with more than 800 samples, which seems not feasible on windows. Is there a tutorial on using Mzmine2 on Linux? Many thanks.
Huali

**Comment by tomas-pluskal** [comment]
There is no difference between linux and windows in terms of how many files can be processed.

**Comment by jeep3** [comment]
![image (6)](https://user-images.githubusercontent.com/28469054/105580438-b0ec1a80-5d8c-11eb-8cbf-1e32f7a69bcb.png)  
Do you mean that when MZmine2 is opened on the server, it still displays the visual window, instead of the command line way to process the data? Sorry, I have only used Mzmine2 on my laptop, but my laptop is not enough to run large sample data sets, so I want to run it on the server.But now I know very little about the Linux version.

**Comment by tomas-pluskal** [comment]
I think you need to ask some Linux expert for help. This is not a problem of MZmine. (hint: your file permissions are messed up)

**Comment by jeep3** [comment]
Thanks, now is work.
