### ISSUE TITLE
start-script is not usual as what I expected to see

### ISSUE THREAD

**Issue by lipidomicR** [mzmine/mzmine2#930]
### Basic information

* My operating system: window 10
* My MZmine version: 2.53

### What happened
How do I change heap size? the start-script does not look like to be readable.
Thank you. 
![mzmine](https://user-images.githubusercontent.com/90867578/133785906-8c4157d1-e6e6-4a8a-ab1f-5d99c433b1c2.jpg)

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by tomas-pluskal** [comment]
The heap size is now managed automatically. The heap is dynamically resized up to 80% of available RAM. You can change the maximum using the `"-XX:MaxRAMPercentage=80"` parameter on the set DEFAULT_JVM_OPTS line.

**Comment by lipidomicR** [comment]
Thank you for the quick response. Following this change by changing
MaxRAMPercentage to 100%, should I just close the text file and open
mzmine? Because I cannot save it.

Thanks again for your help.

**Comment by tomas-pluskal** [comment]
Not sure what you mean by "cannot save it".

**Comment by lipidomicR** [comment]
After I change it, I click "File" on the left top of the text file to save
the changes, but it does not allow me. It pop out this window and please
see the screenshot on the left below. Thank you.
[image: image.png]

**Comment by tomas-pluskal** [comment]
The screenshot was not uploaded. In any case, I don't know why you cannot save the file - that's not an MZmine issue so maybe try to consult your IT department.

**Comment by lipidomicR** [comment]
ok thank you.
