### ISSUE TITLE
CDF (and .D) files yielding different TIC in AMDIS and chemstation compared to MzMine

### ISSUE THREAD

**Issue by Chemecol** [mzmine/mzmine2#949]
### Basic information

* My operating system: Windows 10
* My MZmine version: MzMine 2 (2.53)

### What happened

I've had some issues with the total ion chromatogram (TIC) when importing CDF files into MzMine. When I open the CDF files from one of my GC-MS runs in MzMine the TIC looks different in MzMine compared to AMDIS and chemstation. First I thought that the issue might be the conversion from .D files to CDF. .D is the custom format I get when the samples have been run on our instrument and these files can be opened with chemstation. In order to open them with MzMine i need to convert them to CDF files. However, when I open the CDF file with AMDIS the chromatogram looks similar to that of chemstation. According to my knowledge, the CDF file should create a similar chromatogram out of the CDF file in both programs. But this is not the case for me as you can see in the attached pictures. The differences in the chromatogram are minor, if you take an overall look the chromatogram looks similar but when you look close there's differences. In the example pictures i have zoomed in on an example of this with coeluting peaks where one peak is larger than the other in AMDIS and chemstation while its the opposite in MzMine. Does anyone have an explanation for this output? 

I won't upload any parameter values since the TIC created from the CDF file is simply created directly after the CDF have been imported into the program by right clicking the raw data file and then choosing show TIC.

![image](https://user-images.githubusercontent.com/95356124/144239826-3d528ea7-b546-4e55-b7f2-2a09778f5133.png)
MzMine TIC (CDF file)- first peak smaller than the second peak

![image](https://user-images.githubusercontent.com/95356124/144240313-a345ee70-3bdb-4d07-8578-1e0839c41d5b.png)
Chemstation TIC (.D file) - same two peaks in chemstation, this time the second peak is somewhat smaller

![image](https://user-images.githubusercontent.com/95356124/144240485-f2a59f0e-2cbf-47fc-b7a5-a4ef1e065c3e.png)
AMDIS TIC (CDF file) - same two peaks in AMDIS, this output looks similar to that of chemstation

Thanks in advance,

Chemecol

**Comment by romchal** [comment]
Make sure you are looking at the same thing - Base peak (highest peak in that retention time) or TIC (all ions at that retention time summed up)

**Comment by tomas-pluskal** [comment]
Yeah it looks like the Chemstation and AMDIS plots are TIC, while the MZmine plot is BPC. Well spotted @romchal ;-)

**Comment by Chemecol** [comment]
![image](https://user-images.githubusercontent.com/95356124/144242707-79a561f7-c065-4143-8155-0c2484040748.png)

This seems to be the mistake on my side. Then this is not the reason why I get different data output from MzMine to chemstation. I guess I need to do some more digging in the parameters in order to fix this issue. Thanks a lot for the fast response!

/chemecol
