### ISSUE TITLE
About the scan number of original file

### ISSUE THREAD

**Issue by leinie85** [mzmine/mzmine2#95]
Dear MZmine developers,

I am now using MZmine2 (version 2.14.2) to process proteomics data. 
I want to get the original scan number of original file (mzxml) from the file exported by MZmine2 (for example, the alignment results, csv format) for further analysis. 

Is "row ID" in the exported file same as scan number of original file? Are there any ways to get the scan number of original file? How can I get that number?

I look forward to giving me some suggestions.

Many thanks!

Best wishes,

Lei Nie

**Comment by dyrlund** [comment]
The row ID in MZmine is specific for the software and therefore does not correspond to any values from the original raw data files.

A peak consists of data from multiple MS scans. Therefore, there will be many scan numbers associated to one peak. The number will be equal to the number of data points for the specific peak. Currently there are no ways of exporting the scan numbers of the original raw data files.

Can you please explain what further analysis you wish to do after exporting the data from Mzmine?

Best,

Thomas

**Comment by leinie85** [comment]
Sure. I want to align the proteomics data by MZmine2, and then match the peptide identified by MSGF to the alignment results via scan number. After matching, I can quantify the peptides. Can you give me some suggestions on how to match the peptide identification results to alignment results? 
Many thanks!
Best regards,
Lei

**Comment by dyrlund** [comment]
Currently you would have to align your peptide identification and peaks based on RT and m/z value. These values are available for each scan in your raw data file.

If you would like to help improve MZmine with the functionality that you need then please feel free to make the necessary changes to the code and commit them to the repository.
