### ISSUE TITLE
targeted feature detection

### ISSUE THREAD

**Issue by bobi5rova** [mzmine/mzmine2#956]
I am a newbie to mzMine. I am trying to implement targeted feature detection. Could you share a template for the Feature list csv file? I would like to use a custom made list with my known metabolites (m/z, RTs). thanks.

**Comment by tomas-pluskal** [comment]
Hi! If you open the Help dialog of the Targeted feature detection module, it describes the exact format of the CSV file. Is anything unclear there?

**Comment by bobi5rova** [comment]
Hi Tomáš,
excellent thanks! Pretty clear, just did not notice the help dialog before.

Bory
