### ISSUE TITLE
patching mzmine log4j vulnerability

### ISSUE THREAD

**Issue by anupshah14** [mzmine/mzmine2#957]
### Basic information

* My operating system: Windows server
* My MZmine version: 2.5.2

### What happened

* The University IT department has flagged mzmine for having log4j vulnerability 
*location `Software\MZmine-2.32\lib\log4j-1.2.14.jar`

I was wondering if replacing it with `log4j-core-2.17.1.jar` would fix the issue or it requires any further steps to resolve.

Thanks in advance.

**Comment by tomas-pluskal** [comment]
I think that should be sufficient.

**Comment by anupshah14** [comment]
Thanks for you prompt response. 
I will give it a go. 

Regards,
Anup

**Comment by anupshah14** [comment]
The patch worked. 

Thanks for your comments.
