### ISSUE TITLE
BaseLine correction MZmine 2.15

### ISSUE THREAD

**Issue by Rivas-Ubach** [mzmine/mzmine2#96]
Hi,

I just downloaded the last version of MZmine (2.15).
I usually need the BaseLine correction tool. This tool is not working if the used do not set several paths in the Batch file (startMZmine_Windows.bat) as R_Home, R_LIBS_USER, PATH and JRI_LIB_PATH to link R with MZmine.
I used to do the same process with the previous versions since 2.10. Now, all the information in the batch file changed and I cannot find which parameters I should change now.

Opening now the batch file I find the following:

@echo off

:: *****************************************
:: Optional values - Please modify as needed
:: *****************************************

:: Total amount of memory in MB available to MZmine 2.
:: AUTO = automatically determined
:: Default: AUTO
set HEAP_SIZE=AUTO

:: Location where temporary files will be stored.
:: Default: %TEMP%
set TMP_FILE_DIRECTORY=%TEMP%

:: It is usually not necessary to modify the JAVA_COMMAND parameter, but if you like to run
:: a specific Java Virtual Machine, you may set the path to the java.exe command of that JVM
set JAVA_COMMAND=java.exe

:: ********************************************
:: You don't need to modify anything below here
:: ********************************************

But nothing is related with R_Home and the other paths.

Does someone know how to solve this problem with the new version?

Thank you very much for your attention,
Best regards,

Albert.

**Comment by dyrlund** [comment]
Dear Albert

The integration with R was changed in version 2.15. You therefore don’t have to set the R paths (R_Home, R_LIBS_User …). Instead, MZmine will try to automatically detect where R is installed on your computer.

If the auto detection doesn’t work, then you can manually define the path to R under Project -> Set preferences.

If you are still unable to run the Baseline correction module then please send us an information about what error you are getting?

Best,

Thomas

**Comment by Rivas-Ubach** [comment]
Thank you Thomas for your quick response,

I tried to define manually the path to R as you described. Here, what
exactly I should select? Since do not only need to select the path to R but
a file is necessary. I tried diverse combinations selecting the path but
the base line correction still does not work.

This is the message that appears when I try to perform the correction of
base lines:
*"R computing error" during baseline correction.*
*Could not start Rserve (R> install.packages(c("Rserve"))). Please check if
R and Rserve are installed and, in case the path to the R installation
directory could not be detected automatically, if the "R executable path"
is properly set in the project's preferences. (Note: alternativerly, the
"R_HOME" environment variable can also be used).*


I have R and Rserve package installed.
It seems it is something about detecting the path but I cannot solve the
issue. Also, how could I use the R_HOME environment variable?

Thank you very much for your attention,

Albert.

On Wed, Aug 26, 2015 at 11:00 PM, Thomas F. Dyrlund <
notifications@github.com> wrote:

> Dear Albert
>
> The integration with R was changed in version 2.15. You therefore don’t
> have to set the R paths (R_Home, R_LIBS_User …). Instead, MZmine will try
> to automatically detect where R is installed on your computer.
>
> If the auto detection doesn’t work, then you can manually define the path
> to R under Project -> Set preferences.
>
> If you are still unable to run the Baseline correction module then please
> send us an information about what error you are getting?
>
> Best,
>
> Thomas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mzmine/mzmine2/issues/96#issuecomment-135302996>.
>



-- 
*Albert Rivas-Ubach*
Ph.D.

albert.rivas.ubach@gmail.com
Tel. +1 509 371 7319
3335 Innovation Boulevard, Richland, WA 99354 (USA)
http://www.emsl.pnl.gov/
Think in the environment before printing this e-mail.

**Comment by tomas-pluskal** [comment]
Hi Albert,

The "R executable path" should point to your R.exe file, if you're running on Windows. 

Could you please copy & paste here the complete output of your MZmine console? At some point there should be something like:

```
[22:12:56|FINEST|RSessionWrapper]: 'R_HOME' set to '/Library/Frameworks/R.framework/Resources/'
```

Also, just to make sure: did you install all required R packages, as described in the MZmine manual?

**Comment by Rivas-Ubach** [comment]
Hi Tomás,

The packages I have installed from R are: *: **"Rserve", **"ptw", "rJava",
“baseline”, “hyperSpec” and “PROcess”.*
Actually I am right now using the MZmine 2.14.2 and everything is running
well. Of course, I defined the R path in the .bat file.
Here I pasted the output from the console from the 2.15 version (R_HOME
does not appear here):

Checking physical memory size...
Found 16292 MB memory, 64-bit system
Java heap size set to 14244 MB
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

[13:30:35|INFO|MZmineCore]: Starting MZmine 2.15
[13:30:35|FINE|TmpFileCleanup]: Checking for old temporary files...
[13:30:35|FINE|MZmineCore]: Loading core classes..
[13:30:35|FINE|MZmineCore]: Initializing core classes..
[13:30:35|FINE|MZmineCore]: Loading modules
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.projectmethod
s.projectload.ProjectLoadModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.projectmethod
s.projectsave.ProjectSaveModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.projectmethod
s.projectsave.ProjectSaveAsModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.projectmethod
s.projectclose.ProjectCloseModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.batchmode.Bat
chModeModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.rawdatamethod
s.rawdataimport.RawDataImportModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.rawdatamethod
s.peakpicking.massdetection.MassDetectionModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.masslistmetho
ds.shoulderpeaksfilter.ShoulderPeaksFilterModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.masslistmetho
ds.chromatogrambuilder.ChromatogramBuilderModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.rawdatamethod
s.peakpicking.gridmass.GridMassModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.rawdatamethod
s.peakpicking.manual.ManualPeakPickerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.rawdatamethod
s.peakpicking.msms.MsMsPeakPickerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.rawdatamethod
s.filtering.scanfilters.ScanFiltersModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.rawdatamethod
s.filtering.cropper.CropFilterModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.rawdatamethod
s.filtering.baselinecorrection.BaselineCorrectionModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.rawdatamethod
s.filtering.alignscans.AlignScansModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.rawdatamethod
s.filtering.scansmoothing.ScanSmoothingModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.rawdatamethod
s.orderdatafiles.OrderDataFilesModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.orderpeaklists.OrderPeakListsModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.alignment.join.JoinAlignerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.alignment.ransac.RansacAlignerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.io.csvexport.CSVExportModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.io.metaboanalystexport.MetaboAnalystExportModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.io.mztabexport.MzTabExportModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.io.sqlexport.SQLExportModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.io.xmlexport.XMLExportModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.io.casmiimport.CasmiImportModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.io.mztabimport.MzTabImportModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.io.xmlimport.XMLImportModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.gapfilling.peakfinder.PeakFinderModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.gapfilling.samerange.SameRangeGapFillerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.isotopes.deisotoper.IsotopeGrouperModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.isotopes.isotopeprediction.IsotopePatternCalculator
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.peakpicking.smoothing.SmoothingModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.peakpicking.deconvolution.DeconvolutionModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.peakpicking.shapemodeler.ShapeModelerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.peakpicking.peakextender.PeakExtenderModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.rawdatamethod
s.peakpicking.targetedpeakdetection.TargetedPeakDetectionModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.filtering.duplicatefilter.DuplicateFilterModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.filtering.rowsfilter.RowsFilterModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.normalization.rtnormalizer.RTNormalizerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.normalization.linear.LinearNormalizerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.normalization.standardcompound.StandardCompoundNormalizerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.rtmzplots.cvplot.CVPlotModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.rtmzplots.logratioplot.LogratioPlotModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.projectionplots.PCAPlotModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.projectionplots.CDAPlotModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.projectionplots.SammonsPlotModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.clustering.ClusteringModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.dataanalysis.heatmaps.HeatMapModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.identification.customdbsearch.CustomDBSearchModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.identification.formulaprediction.FormulaPredictionModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.identification.fragmentsearch.FragmentSearchModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.identification.adductsearch.AdductSearchModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.identification.complexsearch.ComplexSearchModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.identification.onlinedbsearch.OnlineDBSearchModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.identification.glycerophospholipidsearch.GPLipidSearchModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.identification.camera.CameraSearchModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.identification.nist.NistMsSearchModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.peaklistmetho
ds.identification.formulapredictionpeaklist.FormulaPredictionPeakListModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.tic.TICVisualizerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.spectra.SpectraVisualizerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.ida.IDAVisualizerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.twod.TwoDVisualizerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.threed.ThreeDVisualizerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.neutralloss.NeutralLossVisualizerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.peaklisttable.PeakListTableModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.peaklisttable.export.IsotopePatternExportModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.peaklisttable.export.MSMSExportModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.scatterplot.ScatterPlotVisualizerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.histogram.HistogramVisualizerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.infovisualizer.InfoVisualizerModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.visualization
.intensityplot.IntensityPlotModule
[13:30:35|FINEST|MZmineCore]: Loading module
net.sf.mzmine.modules.tools.mzrange
calculator.MzRangeCalculatorModule
[13:30:35|FINE|MZmineCore]: Initializing GUI
[13:30:35|FINEST|MZmineConfigurationImpl]: Loading desktop configuration
[13:30:35|FINEST|MZmineConfigurationImpl]: Loading modules configuration
[13:30:35|INFO|MZmineConfigurationImpl]: Loaded configuration from file
conf\con
fig.xml
[13:30:35|INFO|MZmineCore]: Showing main window


Thank you very much for your attention,

Best regards,

Albert.

On Mon, Aug 31, 2015 at 1:20 PM, Tomáš Pluskal <notifications@github.com>
wrote:

> Hi Albert,
>
> The "R executable path" should point to your R.exe file, if you're running
> on Windows.
>
> Could you please copy & paste here the complete output of your MZmine
> console? At some point there should be something like:
>
> [22:12:56|FINEST|RSessionWrapper]: 'R_HOME' set to '/Library/Frameworks/R.framework/Resources/'
>
> Also, just to make sure: did you install all required R packages, as
> described in the MZmine manual?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mzmine/mzmine2/issues/96#issuecomment-136488139>.
>



-- 
*Albert Rivas-Ubach*
Ph.D.

albert.rivas.ubach@gmail.com
Tel. +1 509 371 7319
3335 Innovation Boulevard, Richland, WA 99354 (USA)
http://www.emsl.pnl.gov/
Think in the environment before printing this e-mail.

**Comment by tomas-pluskal** [comment]
The R_HOME line should appear in the console when you attempt to run the baseline correction module. Please try it.

**Comment by Rivas-Ubach** [comment]
This what I get with the 2.15 version trying the Rolling Ball Base Line
correction:


[13:44:21|FINEST|RSessionWrapper]: Windows: Query registry to find where R
is in

stalled ...

[13:44:21|SEVERE|RSessionWrapper]: ERROR: Unable to run REG to find the
location

 of R: java.io.IOException: Cannot run program "reg": CreateProcess
error=5, Acc

ess is denied

[13:44:21|SEVERE|WorkerThread]: Error of task Correcting baseline for
2.raw: 'R

computing error' during baseline correction.

Correct path to the R installation directory could not be detected

automatically. Please try setting manually the 'R executable path' in the

project's preferences. (Note: alternatively, the 'R_HOME' environment
variable

can also be used).



Thanks!

On Mon, Aug 31, 2015 at 1:41 PM, Tomáš Pluskal <notifications@github.com>
wrote:

> The R_HOME line should appear in the console when you attempt to run the
> baseline correction module. Please try it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mzmine/mzmine2/issues/96#issuecomment-136493194>.
>



-- 
*Albert Rivas-Ubach*
Ph.D.

albert.rivas.ubach@gmail.com
Tel. +1 509 371 7319
3335 Innovation Boulevard, Richland, WA 99354 (USA)
http://www.emsl.pnl.gov/
Think in the environment before printing this e-mail.

**Comment by tomas-pluskal** [comment]
Hi Albert,

As you can see yourself from the error description, MZmine cannot autodetect the R location, because it fails to execute the "reg" program for reading the Windows registry. Perhaps some restriction of user permissions on your computer?

Nevertheless, it should still work if you manually set the correct path to R.exe in the MZmine Preferences dialog. Did you try that?

**Comment by Rivas-Ubach** [comment]
Yes, I tried manually to set the correct path to R.exe but nothing changed:
C:\Program Files\R\R-3.1.2\bin\x64\R.exe

I do not know about the USER permissions of my computer. I work for the
Department of Energy in USA and all computers managed by the informatic
department and everything is extremely controlled. So.., perhaps there is a
problem there, I cannot tell you... but as I commented, everything runs
great with the 2.14.2. It is supposed that this version recognizes well the
"reg" program.

Thanks,

Albert.

On Mon, Aug 31, 2015 at 1:51 PM, Tomáš Pluskal <notifications@github.com>
wrote:

> Hi Albert,
>
> As you can see yourself from the error description, MZmine cannot
> autodetect the R location, because it fails to execute the "reg" program
> for reading the Windows registry. Perhaps some restriction of user
> permissions on your computer?
>
> Nevertheless, it should still work if you manually set the correct path to
> R.exe in the MZmine Preferences dialog. Did you try that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mzmine/mzmine2/issues/96#issuecomment-136495789>.
>



-- 
*Albert Rivas-Ubach*
Ph.D.

albert.rivas.ubach@gmail.com
Tel. +1 509 371 7319
3335 Innovation Boulevard, Richland, WA 99354 (USA)
http://www.emsl.pnl.gov/
Think in the environment before printing this e-mail.

**Comment by tomas-pluskal** [comment]
MZmine 2.14.2 did not use the reg program. But this program is only used to autodetect the R location - it is not mandatory.

If you set the path to the R.exe manually, it should work. But it might be necessary to stop MZmine and start it again. Let me know if that also does not help.

**Comment by tomas-pluskal** [comment]
Hi Albert,

Can you try once again with MZmine 2.16?

Tomas

**Comment by Rivas-Ubach** [comment]
Ok, I will try today.
Thank you very much for your help!

Albert

**Comment by Rivas-Ubach** [comment]
Hi again Tomas,

Now the base line correction worked well.
Even so, I had to set the R.exe path in the "Set preferences" menu. It
works great now.

Thanks fo much for your effort!
Have a great day!

Albert.

On Thu, Sep 3, 2015 at 11:51 AM, Tomáš Pluskal <notifications@github.com>
wrote:

> Hi Albert,
>
> Can you try once again with MZmine 2.16?
>
> Tomas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mzmine/mzmine2/issues/96#issuecomment-137540770>.
>



-- 
*Albert Rivas-Ubach*
Ph.D.

albert.rivas.ubach@gmail.com
Tel. +1 509 371 7319
3335 Innovation Boulevard, Richland, WA 99354 (USA)
http://www.emsl.pnl.gov/
Think in the environment before printing this e-mail.
