### ISSUE TITLE
Re: questions about some data processing parameters

### ISSUE THREAD

**Issue by JianFelixGuo** [mzmine/mzmine2#962]
### Basic information
* My operating system: Windows 10
* My MZmine version: MZmine 2 2.53

Dear developer,

I recently found MZmine 2 ADAP very useful and have been trying to process some data using MZmine2 ADAP specifically. But I have some questions about certain parameters.

1. Coefficient/area threshold: the default is 110. Could I use this value for all my data processing? How should I adjust this value based different datasets? 
2. RT wavelet range: default is 1-0.1. Are these values related to the peak duration range? How should I convert the peak duration range to RT wavelet range if they are related?

It would be greatly appreaciated if you could kindly enlighten me on these questions. Thank you!

Best,

Jian

**Comment by asmirn1** [comment]
Hi Jian,

I'm glad you like MZmine 2 ADAP. The best way to setup the parameters is to use the Preview within MZmine 2 and see how your changes affect the peak detection results.

1. In my personal experience, the Coefficient/area threshold doesn't affect the results too much. I'd say, you can leave the default value or set it to some small number, or even zero.
2. RT wavelet range does depend on the peak width/duration. You can set the upper range to about half of the peak width. The lower range affects the S/N estimator. If the S/N estimator is the Wavelet-based, then the lower range should be a small non-zero number (e.g., 0.001). If the S/N estimator is the Window Intensity-based, then the lower range can be zero.
3. I'd say, the most important parameters in ADAP Peak Detection are the S/N threshold and the RT wavelet range. For the S/N threshold, you can try different values from about 3 to 10. It will drastically vary the number of detected peaks.
 
Hopefully, this helps.

Alex

**Comment by JianFelixGuo** [comment]
Thank you very much for the quick reply. I will try using your recommended parameters.
