### ISSUE TITLE
New user: cannot open any Thermo raw files

### ISSUE THREAD

**Issue by agnilili** [mzmine/mzmine2#973]
* My operating system: macOS 12.0
* My MZmine version: MZmine 3.3.0

Problem:
* I can open the .mzML file in MZmine 3.3.0, but cannot open all the Thermo raw file. Should I convert all the files first in .mzML format? because I cannot install the MSConvertGUI in iOS.

<img width="1352" alt="Screen Shot 0005-02-08 at 16 10 53" src="https://user-images.githubusercontent.com/124765919/217460175-58d4dff2-7764-4b4b-898f-6321514363c0.png">

is there anything I can do to solve this? thank you in advance.

**Comment by tomas-pluskal** [comment]
Why did you close this issue?
