### ISSUE TITLE
Chromatogram builder failed

### ISSUE THREAD

**Issue by jbzhang1990** [mzmine/mzmine2#98]
Your MZmine version : 2.15
Your OS version - is it 32-bit or 64-bit? : 64-bit
The exact output of the following two commands:
Checking physical memory size...
Found 16296 MB memory, 64-bit system
Java heap size set to 14248 MB
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

[15:22:31|FINEST|MainMenu]: Setting parameters for module Chromatogram builder
[15:22:47|FINEST|MainMenu]: Starting module Chromatogram builder with parameters
 Raw data files: 20150813-64.raw, Mass list: masses, Min time span (min): 0.01,
Min height: 10000.0, m/z tolerance: 0.05 m/z or 50.0 ppm, Suffix: chromatograms
[15:22:47|FINEST|TaskQueue]: Adding task "Detecting chromatograms in 20150813-64
.raw" to the task controller queue
[15:22:47|INFO|WorkerThread]: Starting processing of task Detecting chromatogram
s in 20150813-64.raw
[15:22:47|INFO|ChromatogramBuilderTask]: Started chromatogram builder on 2015081
3-64.raw
[15:23:35|SEVERE|WorkerThread]: Unhandled exception java.lang.IllegalArgumentExc
eption: Invalid range: [11.9123‥11.9085] while processing task Detecting chroma
tograms in 20150813-64.raw(java.lang.IllegalArgumentException: Invalid range: [1
1.9123‥11.9085]@com.google.common.collect.Range.<init>(Range.java:363))
java.lang.IllegalArgumentException: Invalid range: [11.9123‥11.9085]
        at com.google.common.collect.Range.<init>(Range.java:363)
        at com.google.common.collect.Range.create(Range.java:153)
        at com.google.common.collect.Range.closed(Range.java:177)
        at net.sf.mzmine.modules.masslistmethods.chromatogrambuilder.Chromatogra
m.finishChromatogram(Chromatogram.java:280)
        at net.sf.mzmine.modules.masslistmethods.chromatogrambuilder.HighestData
PointConnector.finishChromatograms(HighestDataPointConnector.java:163)
        at net.sf.mzmine.modules.masslistmethods.chromatogrambuilder.Chromatogra
mBuilderTask.run(ChromatogramBuilderTask.java:157)
        at net.sf.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:61)

Screenshots of all the error messages or unexpected output
![Uploading QQ Photo20150829145432.jpg…]()

The exact steps you took until you encountered file, did the mass detection--> chromatogram builder, in the task in progress window, this error appeared when it reached 100%..

Please help me figure it out what's the problem. Thanks a lot!

**Comment by tomas-pluskal** [comment]
Hi!

Could you send your MZmine project file right before starting the Chromatogram builder? 
I will take a look at the cause of the error.

Tomas

**Comment by jbzhang1990** [comment]
Hi Tomas,

Thanks. I have emailed it to you. Please have a look on it.

Jianbo

**Comment by tomas-pluskal** [comment]
Hi, 

I have not received anything. My email address is plusik@gmail.com
If the file is big, please use DropSend or similar service.

Tomas

**Comment by tomas-pluskal** [comment]
Hi Jianbo,

The project file you sent somehow looks very strange. Could you please also send the original raw file, so I can check if the problem was in the raw file import or in the project saving process?
Thanks,
Tomas

**Comment by tomas-pluskal** [comment]
Hi Jianbo,

Basically, the problem with your data is that it contains multiple types of scans that MZmine could not distinguish. Please try again with MZmine 2.16 - there you can set the range of scans that are used for peak detection.

I also found another problem - your Waters RAW file shows some strange data points with random intensity when imported into MZmine. I cannot find where the problem is - my own Waters RAW files are always imported correctly. For now, I would suggest you to convert your data to mzML or mzXML using msconvert from ProteoWizard.

**Comment by jbzhang1990** [comment]
Hi Tomas,

I run the samples in positive and negative mode spontaneously, maybe that why you saw "multiple types of scans". I will try to run the samples in positive mode and to see if this is the reason. 

Also, I will also try mzXML idea. I will keep update once it's solved.

Thanks a lot!

Jianbo

**Comment by tomas-pluskal** [comment]
Hi Jianbo, you don't need to re-run your samples. In MZmine 2.16 you can select only positve or only negative scans when running Chromatogram builder.

**Comment by jbzhang1990** [comment]
Hi Tomas,

I tried MZmine 2.16 with same sample files, it works very well. 

Thank you very much,
Bob

**Comment by tomas-pluskal** [comment]
I found the bug in the Waters RAW import, the fix will be included in MZmine 2.17 (pull request #121)
